gpr banner & form
blockframes/blockframes pull request #3007
Opened 2020-06-08 14:43 UTC by pldespaigne

On going implementation of GDPR cookie banner & form
- cookie banner works but with a simple "accept" button
- cookie form is only html for now

2020-09-30 10:38 UTC, GrandSchtroumpf requested changes

2020-09-30 10:38 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/app.component.ts
> +  template: '<router-outlet></router-outlet><cookie-banner></cookie-banner><safari-banner><safari-banner>',
So we've got two banner ... ? @pldespaigne should we remove the safari banner now ?

2020-09-30 10:38 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/app.module.ts
> +    const googleCookieAccepted = localStorage.getItem('c8-gdpr-google-analytics');
localStorage is a slow process, don't use it several time. Store an object with the keys instead.
No need to specify "c8", localstorage is specific per page :
```typescript
const { googleAnalytics, intercom, } = localStorage.getItem('gdpr');
```
also use camelCase for the keys

2020-09-30 10:38 UTC, GrandSchtroumpf commented on libs/utils/src/lib/gdpr-cookie/cookie-banner/cookie-banner.component.html
> +    <button fxFlex="1 0 auto" mat-button (click)="changePreferences()">Change preferences</button>
no need to specify 1 0 auto. Just `fxFlex` works

2020-09-30 10:38 UTC, GrandSchtroumpf commented on libs/utils/src/lib/gdpr-cookie/cookie-banner/cookie-banner.component.ts
> +  public userAcceptedCookies() {
Rename to `acceptCookies`

2020-09-30 10:38 UTC, GrandSchtroumpf commented on libs/utils/src/lib/gdpr-cookie/cookie-banner/cookie-banner.component.ts
> +    this.dialog.open(PrivacyPolicyComponent, { maxHeight: '80vh' })
Also set a maxWidth

2020-09-30 10:38 UTC, GrandSchtroumpf commented on libs/utils/src/lib/gdpr-cookie/cookie-banner/cookie-banner.component.ts
> +    const cookieNames = cookies.map(cookie => cookie.split('=')[0].trim());
You might have a "cannot read trim of undefined" here if there is no first item.
Use `shift` instead: `cookies.map(cookie => cookie.split('=').shift()?.trim());`

2020-09-30 10:38 UTC, GrandSchtroumpf commented on libs/utils/src/lib/gdpr-cookie/cookie-banner/cookie-banner.component.ts
> +    this.hasAccepted = cookieNames.some(cookieName => cookieName === 'archipel');
Will this work for every app ? As media financiers doesn't seem to be an archipel app... I don't know.

2020-09-30 10:38 UTC, GrandSchtroumpf commented on libs/utils/src/lib/gdpr-cookie/cookie-banner/cookie-banner.component.ts
> +    this.document.cookie = 'archipel=';
Maybe use "blockframes" instead of archipel.

2020-09-30 10:38 UTC, GrandSchtroumpf commented on libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.html
> +      <mat-divider></mat-divider>
Put mat-divider between the section.

2020-09-30 10:38 UTC, GrandSchtroumpf commented on libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.html
> +    <a href="javascript:void(0)" class="mat-caption" (click)="openPrivacyPolicy()">Privacy Policy</a>
Use button instead of "a"

2020-09-30 10:38 UTC, GrandSchtroumpf commented on libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.scss
> +      position: inherit;
remove "position" you don't need it.

2020-09-30 10:38 UTC, GrandSchtroumpf commented on libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.scss
> +      margin: 16px 32px 16px 0px;
Organize your code so you don't have unsymetrics margins.

2020-09-30 10:38 UTC, GrandSchtroumpf commented on libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.scss
> +      width: auto;
this is the default value. don't specify it.

2020-09-30 10:38 UTC, GrandSchtroumpf commented on libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.ts
> +    Object.keys(this.form.controls)
Cleaner : 
```typescript
for (const key in this.form.controls) {
  this.form.get(key).setValue(event.value);
}
```

2020-09-30 10:38 UTC, GrandSchtroumpf commented on libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.ts
> +  form = new CookiesConsentForm();
For small form like that use a simple FormGroup. We create specific forms when we need typescript autocompletion and type checking. But here it's more a burden than an help : 
```typescript
form = new FormGroup({
    google: new FormControl(null, Validators.required),
    intercom: new FormControl(null, Validators.required),
    yandex: new FormControl(null, Validators.required),
})
```

2020-09-30 10:38 UTC, GrandSchtroumpf commented on libs/utils/src/lib/gdpr-cookie/cookie-form/cookie.form.ts
> +function createCookiesConsent(params?: Partial<CookiesConsent>): CookiesConsent {
remove this file.

2020-09-30 10:38 UTC, GrandSchtroumpf commented on libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.ts
> +    this.dialog.open(PrivacyPolicyComponent, { maxHeight: '80vh' });
set `maxWidth` too

2020-09-30 10:38 UTC, GrandSchtroumpf commented on libs/utils/src/lib/analytics/app-analytics.ts
> +export class FireAnalytics extends GDPRService {
Don't extends. Inject your GdprService into the contructor instead.
Composition is usually better than inheritance.

2020-09-30 10:38 UTC, GrandSchtroumpf commented on libs/utils/src/lib/intercom/intercom.module.ts
> +      updateOnRouterChange: true // will automatically run `update` on router event changes. Default: `false`
Might have a performance issue if it runs for each route change instead of only once...

2020-09-30 10:38 UTC, GrandSchtroumpf commented on libs/utils/src/lib/intercom/intercom.service.ts
> +      query.user$.pipe(
Never leave a long term subscription. You should never subscribe in a service. Always in a component

2020-09-30 10:38 UTC, GrandSchtroumpf commented on libs/utils/src/lib/intercom/intercom.service.ts
> +        ).subscribe(user => {
This logic should be a method triggered by the login / logout methods of the auth service.
Using a observable here is counter efficient.

2020-09-30 10:38 UTC, GrandSchtroumpf commented on libs/utils/src/lib/intercom/intercom.service.ts
> +    return user
Cleaner : 
```typescript
const widget = { activator: "#intercom" };
if (user) {
  const { email, uid, firstName } = user;
  return { email, widget, user_uid: uid, name: firstName };
}
return { widget };
```

2020-09-30 12:24 UTC, RemcoSimonides commented on apps/festival/festival/src/app/app.component.ts
> +  template: '<router-outlet></router-outlet><cookie-banner></cookie-banner><safari-banner><safari-banner>',
They are indeed on top of each other now;
![image](https://user-images.githubusercontent.com/27687382/94684533-79161e80-0328-11eb-8033-e5ac3d8f8542.png)

I don't think it's a good idea to remove safari banner. Also because it may be even more important once we know how many users use old versions of Safari (https://github.com/blockframes/blockframes/issues/3580)

2020-09-30 12:25 UTC, RemcoSimonides commented on apps/festival/festival/src/app/app.component.ts
> +  template: '<router-outlet></router-outlet><cookie-banner></cookie-banner><safari-banner><safari-banner>',
Maybe it's an idea to place them on above each other, or to show the Safari banner underneath the cookie banner?

2020-09-30 13:07 UTC, RemcoSimonides commented on libs/utils/src/lib/gdpr-cookie/cookie-banner/cookie-banner.component.html
> +    <button fxFlex="1 0 auto" mat-button (click)="changePreferences()">Change preferences</button>
![image](https://user-images.githubusercontent.com/27687382/94689070-b382ba00-032e-11eb-9461-5510eef25724.png)

2020-09-30 13:22 UTC, pldespaigne commented on apps/festival/festival/src/app/app.component.ts
> +  template: '<router-outlet></router-outlet><cookie-banner></cookie-banner><safari-banner><safari-banner>',
I thought Safari banner was made because of some weird behavior of the browser.
And we said something about it & Twillio during the visio meeting no ?

I guess it's better to keep it to be sure.

2020-09-30 13:22 UTC, RemcoSimonides commented on libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.html
> +    <a href="javascript:void(0)" class="mat-caption" (click)="openPrivacyPolicy()">Privacy Policy</a>
I can't seem to figure out how I can make it look like the design when I use `button`. Do you know?
![image](https://user-images.githubusercontent.com/27687382/94690713-bb435e00-0330-11eb-9327-37d218376425.png)

2020-09-30 13:30 UTC, RemcoSimonides commented on libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.scss
> +      width: auto;
Position and width are actually useful because they overwrite other values. I don't know where they come from, or what to do against this. I had the same situation recently somewhere else. So if there is something I could do, I'd like to know :)
![image](https://user-images.githubusercontent.com/27687382/94691604-ca76db80-0331-11eb-9265-d1e8e3eec57a.png)

2020-09-30 14:39 UTC, GrandSchtroumpf commented on libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.html
> +    <a href="javascript:void(0)" class="mat-caption" (click)="openPrivacyPolicy()">Privacy Policy</a>
```html
<button mat-button ...>
```

2020-09-30 14:54 UTC, RemcoSimonides commented on libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.html
> +    <a href="javascript:void(0)" class="mat-caption" (click)="openPrivacyPolicy()">Privacy Policy</a>
Not the same, but looks good!

2020-09-30 14:55 UTC, RemcoSimonides commented on libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.ts
> +  form = new CookiesConsentForm();
I'll refactor this when I start on my next PR https://projects.invisionapp.com/d/main#/console/19607961/420299224/preview
For this one I also need to set the initial values with whatever is already saved

2020-09-30 16:12 UTC, RemcoSimonides commented on libs/user/src/lib/auth/+state/auth.service.ts
> +    private gdprService: GDPRService
I don't like to have to use `Intercom`, `GDPRService`, or `IntercomService` in AuthService....

2020-09-30 16:13 UTC, RemcoSimonides commented on libs/user/src/lib/auth/+state/auth.service.ts
> +      this.ngIntercom.update(getIntercomOptions(user));
`ngIntercom.update` should do the trick instead of rebooting intercom like we did before. Now we should even keep the conversation before and after sign in/up. I haven't tested yet... I'll warn Marie first ^^

2020-09-30 16:14 UTC, RemcoSimonides commented on libs/user/src/lib/auth/+state/auth.service.ts
>      window.location.reload();
No need to reboot Intercom on signout because the page is reloaded on signout, so it's reinitiated anyway

2020-10-01 07:53 UTC, RemcoSimonides commented on libs/user/src/lib/auth/+state/auth.service.ts
> +      this.ngIntercom.update(getIntercomOptions(user));
It does work!

2020-10-01 08:56 UTC, GrandSchtroumpf approved these changes

2020-10-01 08:56 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/app.module.ts
> +    !intercom ? intercomService.disable() : intercomService.enable();
Do the opposite : `intercom ? enable() : disable()`
And just for the beauty of the code, put the ternary after the yandex if statement.

2020-10-01 08:56 UTC, GrandSchtroumpf commented on libs/user/src/lib/auth/+state/auth.service.ts
> +    private gdprService: GDPRService
why ?

2020-10-01 08:56 UTC, GrandSchtroumpf commented on libs/user/src/lib/auth/+state/auth.service.ts
> +    localStorage.setItem('gdpr', gdpr);
I don't think this will do anything. When you reload the page the Javascript thread is shutted down. Also I don't understand why you need this line as you didn't mutated the gdpr object

2020-10-01 08:56 UTC, GrandSchtroumpf commented on libs/user/src/lib/auth/+state/auth.service.ts
> +    const gdpr = localStorage.getItem('gdpr');
You're not using it. You should remove it.

2020-10-01 08:56 UTC, GrandSchtroumpf commented on libs/user/src/lib/auth/+state/auth.service.ts
> +    this.db.doc<User>(`users/${userCredential.user.uid}`).valueChanges().pipe(take(1)).subscribe(user => {
Do you really need the whole user for the intercom options or it would work with the user credential data ?

If you nede the whole user, use the `UserService` : 
```typesript
const user = await this.userService.getValue(this.user.uid);
const options = getIntercomOptions(user);
this.ngIntercom.update(options);
```

2020-10-01 08:56 UTC, GrandSchtroumpf commented on libs/utils/src/lib/gdpr-cookie/gdpr-service/gdpr-service.ts
> +    return JSON.parse(localStorage.getItem('gdpr')) ?? {};
do `JSON.parse(localStorage.getItem('gdpr') ?? '{}');` instead.

2020-10-01 08:56 UTC, GrandSchtroumpf commented on libs/utils/src/lib/intercom/intercom.module.ts
> +export class IntercomAppModule {}
I don't see the benefice of this module. Do you plan to add more stuff ? Else remove it

2020-10-01 08:56 UTC, GrandSchtroumpf commented on libs/utils/src/lib/intercom/intercom.service.ts
> +export class IntercomService {
Couldn't you implement this service into the gdpr service instead of having two classes ? Looks overkill to me

2020-10-01 09:04 UTC, RemcoSimonides commented on libs/user/src/lib/auth/+state/auth.service.ts
> +    this.db.doc<User>(`users/${userCredential.user.uid}`).valueChanges().pipe(take(1)).subscribe(user => {
Almost! I do have the uid and email in user credential data, but the displayName is empty. I could edit some code somewhere which also updates the displayName on credentialData when the User data is updated? Then I don't need to get the whole user.

Using the UserService in AuthService will give a circular dependency warning :/

2020-10-01 09:04 UTC, RemcoSimonides commented on libs/user/src/lib/auth/+state/auth.service.ts
> +    private gdprService: GDPRService
To prevent circular dependencies. It's not the case now, but I try to avoid using services in services because of this

2020-10-01 09:47 UTC, RemcoSimonides commented on libs/user/src/lib/auth/+state/auth.service.ts
> +    const gdpr = localStorage.getItem('gdpr');
I've refactored it a little bit so the `localStorage.setItem('gdpr', gdpr)` is at least before `window.location.reload()`. But getting and setting the gdpr from localStorage is to prevent the settings to dissapear in the `localStorage.clear()` ;)

2020-10-01 09:49 UTC, RemcoSimonides commented on libs/utils/src/lib/intercom/intercom.service.ts
> +export class IntercomService {
Obviously this is possible; but I think their purpose are for different things. Whereas the IntercomService is to control the intercom pop-up on the website, and the GDPR service is just for the cookie settings. I think we should keep these separate from each other

2020-10-01 11:16 UTC, merged