Feat 3188 - storage rules
blockframes/blockframes pull request #3577
Opened 2020-08-27 15:32 UTC by phpgeekfr

2020-09-11 13:57 UTC, GrandSchtroumpf commented on tools/mandatory-env-vars.json
> +  { "key": "IMGIX_TOKEN", "msg": "API key for the video player is missing." }
Imgix !== video player. Also give a link to the right documentation in notion.

2020-09-11 13:57 UTC, GrandSchtroumpf commented on apps/backend-functions/src/media.ts
> +      await from.delete();
I'm not sure to understand when this code runs.

2020-09-11 13:57 UTC, GrandSchtroumpf commented on apps/backend-functions/src/media.ts
> +    return doc.update({ [fieldToUpdate]: '' });
I think you should use `FieldValue` for this kind of update. Not sure though

2020-09-11 13:57 UTC, GrandSchtroumpf commented on apps/backend-functions/src/media.ts
> +    // ! this will not work with array in the path like for poster
poster isn't an array anymore I think.

2020-09-11 13:57 UTC, GrandSchtroumpf commented on apps/backend-functions/src/media.ts
> +    return createHash('md5').update(toSign).digest('hex');
Are we always using md5 for the hashes ?

2020-09-11 13:57 UTC, GrandSchtroumpf commented on apps/backend-functions/src/media.ts
> +  if (!(await isAllowedToDelete(data.ref, context.auth.uid))) { throw new Error('Permission denied. User is not allowed'); }
It's a little bit too much on one line : 
```typescript
const canDelete = await isAllowedToDelete(data.ref, contet.auth.uid);
if (canDelete) {
  throw ...
}
```

2020-09-11 13:57 UTC, GrandSchtroumpf commented on apps/backend-functions/src/media.ts
> +  if (['protected', 'public'].includes(refParts[0])) {
Maybe you can create a type with 'protected', 'public' & 'tmp' if it makes sense at some point to avoid typos.

2020-09-11 13:57 UTC, GrandSchtroumpf commented on apps/backend-functions/src/media.ts
> +  const pathInfo = {} as any;
type it:  `Record<string, string>` ?

2020-09-11 13:57 UTC, GrandSchtroumpf commented on apps/backend-ops/src/firestoreMigrations/0035.ts
> +export async function upgrade(_: Firestore, storage: Storage) {
Why do you need the first params if you don't use it ?

2020-09-11 13:57 UTC, GrandSchtroumpf commented on apps/backend-ops/src/syncStorage.ts
> +import { loadAdminServices, getDocAndPath } from "@blockframes/firebase-utils";
Are you sure you need it ?

2020-09-11 13:57 UTC, GrandSchtroumpf commented on libs/firebase-utils/src/lib/watermark.ts
> +export async function upsertWatermark(user: PublicUser, bucketName: string, protectedMedia = false): Promise<any> {
Better to have the third params as a string literal : 
```typescript
export async function upsertWatermark(user: PublicUser, bucketName: string, privacy: FilePrivacy = 'public')
```
If we need other folders in the future it's better than using a boolean.

2020-09-11 13:57 UTC, GrandSchtroumpf commented on libs/firebase-utils/src/lib/watermark.ts
> +  const ref = `${protectedMedia ? 'protected' : 'public'}/users/${user.uid}/watermark/${user.uid}.svg`;
With comment above you can do `${privacy}/users/...`

2020-09-11 13:57 UTC, GrandSchtroumpf commented on libs/media/src/lib/+state/media.service.ts
> +  private breakpointsWidth = [600, 1024, 1440, 1920];
just "breakpoints". It's always on width. I think theses variables exists somewhere though. It would be better to import them that hardcode them here.

2020-09-11 13:57 UTC, GrandSchtroumpf commented on libs/media/src/lib/+state/media.service.ts
> +    const tasks = files.map(file => this.storage.upload(`tmp/${file.path}${file.fileName}`, file.data));
It would be nice if the `file.path` doesn't have the last "/", as it makes the code a little bit harder to read. And a little more prompt to error

2020-09-11 13:57 UTC, GrandSchtroumpf commented on libs/media/src/lib/+state/media.service.ts
> +    ref = !ref.startsWith('/') ? `/${ref}` : ref;
If you can stripe out the 'protected" in case of a mistake in the params.

2020-09-11 13:57 UTC, GrandSchtroumpf commented on libs/media/src/lib/+state/media.service.ts
> +    const f = this.functions.httpsCallable('getMediaToken');
I think it's better/cleaner to set that as a params of the service: 
```typescript
class MediaService {
  private getMediaToken = this.unctions.httpsCallable('getMediaToken');
}
```

2020-09-11 13:57 UTC, GrandSchtroumpf commented on libs/media/src/lib/+state/media.service.ts
> +    if (['public', 'protected'].includes(refParts[0])) {
Same as discussed above.

2020-09-11 13:57 UTC, GrandSchtroumpf commented on libs/media/src/lib/+state/media.service.ts
> +    const sizes = getImgSize(ref);
Can you do : 
```typescript
const params = getImgSize(ref).map(size => ({ ...p, w: size } as ImageParameters));
const tokens = protectedMedia
  ? await this.getProtectedMediaToken(ref, params)
  : [];
const urls = params.map((param, index) => {
  if (tokens[index]) { param.s = tokens[index] };
  return `${getImgIxResourceUrl(ref, params)} ${param.w}w`;
})
```

2020-09-11 13:57 UTC, GrandSchtroumpf commented on libs/media/src/lib/+state/media.service.ts
> +  generatePdfUrl(ref: string): Promise<string> {
Do we really need all these methods ? Look like a lot a repetition here.

2020-09-11 13:57 UTC, GrandSchtroumpf commented on libs/media/src/lib/+state/media.service.ts
> +  async generateImgIxUrl(ref: string, p: any = {}): Promise<string> {
p shouldn't be any. Can it be a string ? a number ? an array ? ...
Also give a better name.

2020-09-11 13:57 UTC, GrandSchtroumpf commented on libs/media/src/lib/+state/media.service.ts
> +    }
Can you do : 
```typescript
const refParts = ref.split('/');
const privacy = refParts.shift();
if (['public', 'protected'].includes(privacy)) {
  ref = refParts;
}
```

2020-09-11 14:03 UTC, phpgeekfr commented on apps/backend-functions/src/media.ts
> +    return createHash('md5').update(toSign).digest('hex');
This is what imgIx expect yes

2020-09-11 14:07 UTC, phpgeekfr commented on apps/backend-functions/src/media.ts
> +      await from.delete();
linkFile Is called at each new file on the storage.
We only take care about the `tmp` dir.
If the ref of the file in tmp dir is found on the document in db, the file is moved to the right dir.
If the ref is not found on db, we delete it because it means that this file is lost

2020-09-11 14:18 UTC, GrandSchtroumpf requested changes

2020-09-11 14:18 UTC, GrandSchtroumpf commented on libs/media/src/lib/+state/media.service.ts
> +      p.s = (await this.getProtectedMediaToken(ref, [p]))[0];
What is p ? What it s ? What is the first value returned by `getProtectedMediaToken` ?
This line it pretty unreadable.

2020-09-11 14:18 UTC, GrandSchtroumpf commented on libs/media/src/lib/directives/image-reference/imgix-helpers.ts
> +  return `https://${firebase.projectId}${parameters.s ? `-${protectedMediaDir}` : ''}.imgix.net/${ref}?${query}`;
Create intermediary variables to make it more readable.
```typescript
const something = parameters.s ? `${firebase.projectId}-${protectedMediaDir}` : firebase.projectId}:
return `https://${something }.imgix.net/${ref}?${query}`
```

2020-09-11 14:18 UTC, GrandSchtroumpf commented on libs/media/src/lib/+state/media.service.ts
> +    let clientWidth = 1024;
Why is it hardcoded ?

2020-09-11 14:18 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/cropper/cropper.component.ts
> +      const fileName = sanitizeFileName(this.file.name.replace(/(\.[\w\d_-]+)$/i, `.webp`));
I remember we had some issues some sanitizing the filename. Are you sure of you ?
Also use single-quote for 'webp'

2020-09-11 14:18 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/cropper/cropper.component.ts
> +  /** Returns an observable of the download url of an image based on its reference */
observable ? Not a Promise as typed ?

2020-09-11 14:18 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/upload/file-upload/file-upload.component.ts
> +  @Input() protected = false;
I would prefer `@Input privacy: Privacy` as string literal

2020-09-11 14:18 UTC, GrandSchtroumpf commented on libs/media/src/lib/directives/image-reference/background-reference.directive.ts
> +        this.mediaService.generateBackgroundImageUrl(image, this.parameters)
Change to : 
```typescript
this.mediaService.generateBackgroundImageUrl(image, this.parameters)
 .then(url => this.ref$.next(url))
 .catch(err => this.ref$.next(''));
```

2020-09-11 14:18 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/components/promotional-links/promotional-links.pipe.ts
> +        const url = useImgIx ? await this.mediaService.generatePdfUrl(ref) : ref;
Can the url change depending on external values than the links & movie ?
Like, if there are some state in the media service that change can it impact the result ?
If yes, change `pure: true` to `pure: false`

2020-09-11 14:18 UTC, GrandSchtroumpf commented on libs/utils/src/lib/file-sanitizer.ts
> +export function getStoragePath(path: string, protectedMedia = false): string {
Use a string literal instead of a boolean.

2020-09-11 15:05 UTC, phpgeekfr commented on apps/backend-ops/src/firestoreMigrations/0035.ts
> +export async function upgrade(_: Firestore, storage: Storage) {
This is how migrations are started.
CF `apps/backend-ops/src/migrations.ts`
```
    for (const migration of migrations) {
      console.info(`applying migration: ${migration.version}`);
      await migration.upgrade(db, storage);
      console.info(`done applying migration: ${migration.version}`);
    }
```

2020-09-11 15:06 UTC, phpgeekfr commented on apps/backend-ops/src/syncStorage.ts
> +import { loadAdminServices, getDocAndPath } from "@blockframes/firebase-utils";
It is used in this file but the entire file will be removed in https://github.com/blockframes/blockframes/pull/3669

2020-09-11 15:15 UTC, phpgeekfr commented on libs/media/src/lib/+state/media.service.ts
> +    ref = !ref.startsWith('/') ? `/${ref}` : ref;
It is a private method called by methods that already strips it out. But it can add another check if you want

2020-09-11 15:26 UTC, phpgeekfr commented on libs/media/src/lib/+state/media.service.ts
> +    let clientWidth = 1024;
Not my code but this is the default width for the image that can be changed after :
```
    if (!!window || !!window.innerWidth) {
      clientWidth = clamp(window.innerWidth, this.breakpointsWidth);
    }
```

Do you want to put this in env or something?

2020-09-11 15:29 UTC, phpgeekfr commented on libs/media/src/lib/components/cropper/cropper.component.ts
> +      const fileName = sanitizeFileName(this.file.name.replace(/(\.[\w\d_-]+)$/i, `.webp`));
The sanitizeFileName method has been changed. It is now only replacing spaces by "-" and make sure that the file length is not more than 100  (max is 255). So It should not create issues. (also updated the quotes for wepb)

2020-09-11 15:49 UTC, GrandSchtroumpf commented on apps/backend-functions/src/media.ts
> +      await from.delete();
Maybe add a comment to explain that we delete() lost files.

2020-09-11 15:50 UTC, GrandSchtroumpf commented on libs/media/src/lib/+state/media.service.ts
> +    let clientWidth = 1024;
No it's fine. Maybe add a comment "// default width".

2020-09-11 16:18 UTC, phpgeekfr commented on libs/media/src/lib/+state/media.service.ts
> +    }
No I can't because I don't want to shift the array if it does not include public or protected. But I made some updates on this method that make it more readable

2020-09-11 16:24 UTC, GrandSchtroumpf requested changes

2020-09-11 16:24 UTC, GrandSchtroumpf commented on libs/media/src/lib/+state/media.service.ts
> +    }
You're not reusing `refParts` later so there is no problem.
- if privacy is 'public' or 'protected' you reassign the ref with the shifted version
- else you keep ref as it is.

2020-09-15 07:56 UTC, phpgeekfr commented on apps/backend-functions/src/media.ts
> +    return doc.update({ [fieldToUpdate]: '' });
I don't understand your remark

2020-09-15 10:32 UTC, GrandSchtroumpf approved these changes

2020-09-15 10:32 UTC, GrandSchtroumpf commented on libs/firebase-utils/src/lib/firebase-utils.ts
> +    throw new Error(`Upload Error : File Path ${filePath}
I recommend to do : 
```typescript
const error  = `Upload Error : File Path ${filePath} is malformed.`;
const solution = 'It should at least contain 3 slash.';
const example = 'Example: 'public/collection/id/field/fileName';
throw new Error(`${error} ${solution}\n${example}`);
```

2020-09-15 10:32 UTC, GrandSchtroumpf commented on libs/media/src/lib/+state/media.service.ts
> +    const f = this.functions.httpsCallable('deleteMedia');
Do the same as for `getMediaToken` by putting it at the top.

2020-09-16 09:55 UTC, merged