fix(anonymize-db.ts): first draft for consistent user/org anonymisation
blockframes/blockframes pull request #3618
Opened 2020-09-03 16:44 UTC by george43g

- fixed bugs
- consistent users
- attempting consistent orgs, introduced types
- looking for feedback and testing

2020-09-04 09:10 UTC, GrandSchtroumpf commented on tools/scripts/anonymize-db.ts
> +  for (const key of keys) if (!(key in doc)) return false;
you can do :
```typescript
return keys.every(key => key in doc);
```

2020-09-04 09:10 UTC, GrandSchtroumpf commented on tools/scripts/anonymize-db.ts
> +function isA<T>(doc: any, ...keys: string[]): doc is T {
Maybe rename it `hasKeys`. I understand the `isAs` refering to the type guard, but I think `hasKeys` describe more the javascript underlying logic.
Also, I would use a real array instead of spread operator.

2020-09-04 09:10 UTC, GrandSchtroumpf commented on tools/scripts/anonymize-db.ts
> +// function isOrg(doc: any): doc is Organization {
Remove if not used.

2020-09-04 09:10 UTC, GrandSchtroumpf commented on tools/scripts/anonymize-db.ts
> +  for (const key of keys) if (!(key in doc)) throw Error('Wrong document type found!');
Same as above : 
```typescript
function assertType<T>(doc: any, ...keys: string[]): asserts doc is T {
  return !isA(doc, keys);
}
```

2020-09-04 09:10 UTC, GrandSchtroumpf commented on tools/scripts/anonymize-db.ts
> +    const [, newUser] = foundUserTuple;
Use "_" if you don't need a parameter.

2020-09-04 09:27 UTC, GrandSchtroumpf requested changes

2020-09-04 09:27 UTC, GrandSchtroumpf commented on tools/scripts/anonymize-db.ts
> +const userTable: [string, User][] = []; // uid, newEmail
Use records for that, it's more natural for Javascript than matrix : 
```typescript
const newUsers: Record<string, User> = {};
const newOrgs: Record<string, User> = {};
```

2020-09-04 09:27 UTC, GrandSchtroumpf commented on tools/scripts/anonymize-db.ts
> +    Object.assign(user, newUser);
I find it difficult to read. Object.assign is usually used to do shallow copy, but here you're using it to mutate the user. 
To keep separation of concern I would have done : 
```typescript
function updateUser(user: User) {
  if (!newUsers[user.uid]) {
    newUsers[user.uid] = fakeUser(user);
  }
  return { ...user, ...newUsers[user.uid] };
}

function fakeUser(user: Partial<User> = {}) {
  const { firstName, lastName } = faker.name;
  const email = fakeEmail(firstName);
  return {
    ...user,
    firstName,
    lastName,
    email
  }
}

// Now you can reuse it for updating the org
function fakeEmail(name: string) {
  const random = Math.random().toString(36).replace(/[^a-z]+/g, '').substr(0, 3);
  return `dev+${name.replace(/\W/g, '').toLowerCase()}-${random}@cascade8.com`;
}
```

2020-09-04 09:27 UTC, GrandSchtroumpf commented on tools/scripts/anonymize-db.ts
> +function updateOrg(org: Organization) {
Same as above.

2020-09-04 12:06 UTC, george43g commented on tools/scripts/anonymize-db.ts
> +  for (const key of keys) if (!(key in doc)) throw Error('Wrong document type found!');
an assertion function must only throw if it fails, they are a return type `void`

2020-09-04 13:24 UTC, GrandSchtroumpf approved these changes

2020-09-08 08:16 UTC, GrandSchtroumpf commented on tools/scripts/anonymize-db.ts
> +  if (hasKeys<T>(doc, ...keys)) throw Error('WRONG OBJECT TYPE!');
I think it's `if (!hasKeys(...))` isn't it ?

2020-09-08 08:16 UTC, GrandSchtroumpf commented on tools/scripts/anonymize-db.ts
> +function processInvitation(i: Invitation): Invitation {
You can do `function processInvitation(i: Partial<Invitation> = {}): Invitation {`

2020-09-08 08:16 UTC, GrandSchtroumpf commented on tools/scripts/anonymize-db.ts
> +function updateUser(user: User | PublicUser) {
You might want to do `updateUser(user: Partial<User> | Partial<PublicUser>)`

2020-09-08 08:54 UTC, GrandSchtroumpf commented on tools/scripts/anonymize-db.ts
> +    return newUsers?.[user.uid] || (newUsers[user.uid] = processUser(user));
Quite compact and difficult to read. Many do it into 2 lines.

2020-09-08 08:54 UTC, GrandSchtroumpf commented on tools/scripts/anonymize-db.ts
> +  function pathHasAny(...paths: string[]) {
Remove the spread operator here. It makes things difficult to understand.

2020-09-08 08:54 UTC, GrandSchtroumpf commented on tools/scripts/anonymize-db.ts
> +    return !paths.every((path) => !docPath.includes(path));
Avoid double negation. Using `some` instead of `every` might help.

2020-09-08 08:54 UTC, GrandSchtroumpf commented on tools/scripts/anonymize-db.ts
> +  try {
It's not super clear what happens here. Why not just `docPath.includes('users/')` or `docPath.startWith('users/')` ?

2020-09-08 14:03 UTC, george43g commented on tools/scripts/anonymize-db.ts
> +// tslint:disable: no-console
There is a console.time()

2020-09-08 14:04 UTC, GrandSchtroumpf commented on tools/scripts/anonymize-db.ts
> +// tslint:disable: no-console
Ok

2020-09-08 14:09 UTC, george43g commented on tools/scripts/anonymize-db.ts
> +function processInvitation(i: Invitation): Invitation {
This creates an error because the type that's returned is no longer guaranteed to be an invitation, so it would have to return a Partial<Invitation> as well.

2020-09-08 14:09 UTC, george43g commented on tools/scripts/anonymize-db.ts
> +function updateUser(user: User | PublicUser) {
same as above

2020-09-08 15:09 UTC, merged