dashboard title view
blockframes/blockframes pull request #3634
Opened 2020-09-08 14:38 UTC by Mussuranae

New dashboard title view with tabs and summary components

2020-09-08 14:46 UTC, pldespaigne requested changes

2020-09-08 14:46 UTC, pldespaigne commented on apps/festival/festival/src/app/dashboard/title/view/view.module.ts
>      RouterModule.forChild(routes)
I don't think you need router for this page

2020-09-08 14:46 UTC, pldespaigne commented on apps/festival/festival/src/app/dashboard/title/view/view.module.ts
>  }];
remove unused routes

2020-09-08 14:46 UTC, pldespaigne commented on apps/festival/festival/src/app/dashboard/title/view/view.component.html
>      <router-outlet></router-outlet>
delete unused `router-outlet`

2020-09-08 15:25 UTC, Mussuranae commented on apps/festival/festival/src/app/dashboard/title/view/view.module.ts
>      RouterModule.forChild(routes)
I need at least to put the route for the component because nothing appears if I don't do it.... I don't know why...

2020-09-09 08:03 UTC, pldespaigne approved these changes

2020-09-09 09:10 UTC, merged