Movie dashboard
blockframes/blockframes pull request #3663
Opened 2020-09-11 08:00 UTC by Mussuranae

Change the last tab in festival dashboard view and change the dashboard view in catalog

2020-09-11 08:18 UTC, GrandSchtroumpf requested changes
Create a shell component to hold the form and inject it inside each page

2020-09-11 15:04 UTC, GrandSchtroumpf requested changes

2020-09-11 15:04 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/dashboard/components/view/shell/shell.component.ts
> +  @Input() form = new MovieForm(this.query.getActive());
Here the movie is static. If ever we have a design sometime that enable user to switch from one movie to the other we'll need to make it an observable : 
```typescript
private _form = new BehaviourSubject<MovieForm>(undefined);
public form$ = this._form.asObservable();
@Input()
set form(form: MovieForm) {
  this._form.next(form);
}
get form(): MovieForm {
  return this._form.getValue();
}

ngOnInit() {
  this.sub = this.query.selectActive().subscribe(movie => {
    this.form = new MovieForm();
    this.cdr.markForCheck();
  })
}
ngOnDestroy() {
  this.sub.unsubscribe();
}
```
The code above should be future proof.

2020-09-11 15:09 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/title/view/view.component.html
> +      <article fxLayout="row" fxLayout.lt-md="column" fxFlex>
I think you don't need this article

2020-09-11 16:38 UTC, Mussuranae commented on apps/festival/festival/src/app/dashboard/title/view/view.component.html
> +            {{ movie.contentType | toLabel: 'contentType' | async }}
There is the `title-feature` component but it adds also genres, languages and countries...

2020-09-11 16:44 UTC, Mussuranae commented on apps/festival/festival/src/app/dashboard/title/view/view.component.html
> +          <h6>{{ getDirectors(movie) }}</h6>
Yep, the displayName pipe

2020-09-14 07:16 UTC, Mussuranae commented on libs/movie/src/lib/movie/dashboard/components/view/shell/shell.component.html
> +<router-outlet></router-outlet>
But your css trick works !! so section is not needed anymore xD

2020-09-15 10:16 UTC, GrandSchtroumpf requested changes

2020-09-15 10:16 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/dashboard/title/view/view.component.html
>        <div class="movie-info" fxLayout="column" fxLayoutAlign="start start">
In a next PR it would make sense to factorize the content to not repeat ourselves in every app.

2020-09-15 10:16 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/dashboard/title/view/view.component.scss
> +  padding: 53px 24px 17px 24px;
Same as above. Do symmetric padding and multiple of 8. If you cannot let talk with Stéphanie

2020-09-15 10:16 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/dashboard/components/view/artistic/artistic.component.ts
> +    this.subscription = this.movieQuery.selectActive().subscribe(movie => {
up 👆

2020-09-15 11:03 UTC, Mussuranae commented on apps/festival/festival/src/app/dashboard/title/view/view.component.html
>        <div class="movie-info" fxLayout="column" fxLayoutAlign="start start">
Yes, to do a header movie component for dashboard like the one we have for marketplace ? I thought it also it would be a good idea.

2020-09-15 15:08 UTC, GrandSchtroumpf approved these changes

2020-09-15 15:08 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/dashboard/components/view/shell/shell.component.ts
> +  public routerData$ = this.routerQuery.selectData('animation');
Reorganize your properties.

2020-09-15 15:08 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/dashboard/components/view/shell/shell.component.ts
> +  @Input() routes;
type your routes

2020-09-16 08:16 UTC, merged