Filter out already invited emails
blockframes/blockframes pull request #3739
Opened 2020-09-21 15:12 UTC by RemcoSimonides

We shouldn't be able to send an invitation to someone who was already invited.

- [ ] Add email Facet to prod_users and staging_users on Algolia too

2020-09-22 07:45 UTC, GrandSchtroumpf commented on libs/ui/src/lib/algolia/chips-autocomplete/algolia-chips-autocomplete.component.ts
> +  @Input()
We've got a decorator to perform that : 
```typescript
@Input() @boolean unique;
```
Use it instead.

2020-09-22 07:45 UTC, GrandSchtroumpf commented on libs/invitation/src/lib/form/user/user.component.ts
> +  @Input() set invitations(invitations: Invitation[]) {
If possible the algolia logic should remain in the autocomplete algolia component

2020-09-22 09:18 UTC, RemcoSimonides commented on libs/invitation/src/lib/form/user/user.component.ts
> +  @Input() set invitations(inv) {
I don't like what I have to do here. Invitations come in this component a little later. Is there a way to make this prettier?

2020-09-22 09:19 UTC, RemcoSimonides commented on libs/invitation/src/lib/form/user/user.component.html
> +    [filters]="_invitations | mapDeepKey:'toUser.email'"
As invitations is an array, I created a mapDeepKey pipe to handle arrays.

2020-09-22 09:22 UTC, RemcoSimonides commented on libs/ui/src/lib/algolia/chips-autocomplete/algolia-chips-autocomplete.component.ts
> +      } else {
Ahh didn't test this with a `string[][]` yet.

2020-09-22 10:54 UTC, GrandSchtroumpf commented on libs/invitation/src/lib/form/user/user.component.ts
> +  @Input() set invitations(inv) {
Don't use a setter. Use the normal @Input(). And verify in the pipe if the value exist.

2020-09-22 10:55 UTC, GrandSchtroumpf commented on libs/ui/src/lib/algolia/chips-autocomplete/algolia-chips-autocomplete.component.ts
> +      } else {
I don't understand what you're trying to achieve here...

2020-09-22 10:56 UTC, GrandSchtroumpf requested changes

2020-09-22 10:56 UTC, GrandSchtroumpf commented on libs/utils/src/lib/pipes/deep-key.pipe.ts
> +    return value.map(obj => deepKey.split('.').reduce((result, key) => result[key], obj));
Update the deepKey pipe to support array instead of creating a new pipe

2020-09-22 11:55 UTC, GrandSchtroumpf requested changes

2020-09-22 11:55 UTC, GrandSchtroumpf commented on libs/ui/src/lib/algolia/chips-autocomplete/algolia-chips-autocomplete.component.ts
> +  private getFilter(filter: string): string {
Personally I would have done something like : 
```typescript
@Input() filters: string[];

private getFilter() {
  const format = filter => this.unique && !filter.includes(':') ? `${this.displayWithPath}:-${filter}` : filter;
  return this.filter.map(format);
}
```
It would be much cleaner in the end.

2020-09-22 12:17 UTC, RemcoSimonides commented on libs/ui/src/lib/algolia/chips-autocomplete/algolia-chips-autocomplete.component.ts
> +  private getFilter(filter: string): string {
Looks good but doesn't work. `@Input() filters` first receives null object because a the passed down `invitations | deepkey:'toUsers.email'` is first null and then gets the value. So I can't call `getFilter()` the way you'd make in ngOnInit(). I am curious if you have a solution for this :)

If you don't have any; check my last commit in which I remove support for the matrix ;)

2020-09-22 13:32 UTC, GrandSchtroumpf commented on libs/ui/src/lib/algolia/chips-autocomplete/algolia-chips-autocomplete.component.ts
> +  private getFilter(filter: string): string {
Just had a default value : 
```typescript
const format = filter => this.unique && !filter.includes(':') ? `${this.displayWithPath}:-${filter}` : filter;
return this.filter?.map(format) || [];
```

2020-09-23 08:13 UTC, GrandSchtroumpf commented on libs/ui/src/lib/algolia/chips-autocomplete/algolia-chips-autocomplete.component.ts
> +        splitValue(value, this.separators).forEach(v => {
You can factorize that : 
```typescript
const values = typeof value === 'string' ? splitValue(value, this.separators) : [value];
for (const v of values) {
  if (this.unique && !!v) this.addedFilters.push(v);
  this.form.add(v);
}
```
Or something like that.

2020-09-23 08:37 UTC, GrandSchtroumpf approved these changes

2020-09-23 08:37 UTC, GrandSchtroumpf commented on libs/ui/src/lib/algolia/chips-autocomplete/algolia-chips-autocomplete.component.ts
> +    this.searchCtrl.setValue(null);
Normally you could just do that `this.searchCtrl.reset()` without the need to set the value on the `input.nativeElement`. I think.

2020-09-23 08:37 UTC, GrandSchtroumpf commented on libs/ui/src/lib/algolia/chips-autocomplete/algolia-chips-autocomplete.component.ts
> +      if (this.unique && !!v) this.addedFilters.push(v[this.displayWithPath]);
what if there is no `displayWithPath` or `v[this.displayWithPath]` doesn't exist ?

2020-09-23 09:52 UTC, RemcoSimonides commented on libs/ui/src/lib/algolia/chips-autocomplete/algolia-chips-autocomplete.component.ts
> +    this.searchCtrl.setValue(null);
Sadly this.searchCtrl doesn't update the input field by default :/

2020-09-23 10:07 UTC, GrandSchtroumpf approved these changes

2020-09-23 10:23 UTC, merged