adding notes and statements to movie form
blockframes/blockframes pull request #3783
Opened 2020-09-23 14:24 UTC by fritzschoff

issue State issue number in your PR to close it when PR merged: issue #XXX
e.g. : "Resolve the bundle size ❤️: issue #1234"

2020-09-23 14:53 UTC, GrandSchtroumpf requested changes

2020-09-23 14:53 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/dashboard/tunnel/movie-tunnel.routes.ts
> +        loadChildren: () => import('@blockframes/movie/form/promotional-elements/media-notes/notes.module').then(m => m.MovieFormNotesModule)
Why the path is not just `@blockframes/movie/form/note` ?
Do we **really** need this depth ?

2020-09-23 14:53 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/+state/movie.model.ts
> +export function createMovieNote(note: Partial<MovieNote>): MovieNote {
initialize it with an empty object

2020-09-23 14:53 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/+state/movie.model.ts
> +  return {
Use the `createPerson` here if it exists

2020-09-23 14:53 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/movie.form.ts
> +function createMovieNoteControls(note: Partial<MovieNote>) {
note should be optional

2020-09-23 14:53 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/movie.form.ts
> +  constructor(note: Partial<MovieNote>) {
note should be optional

2020-09-23 14:53 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/promotional-elements/media-notes/notes.component.ts
> +  roles = ['producer', 'director', 'other'];
don't we have a static const for that ? It's better to have a centralized way of managing that because we need to display it after. We want to keep the same values.

2020-09-23 14:53 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/shell/shell.component.ts
> +        shouldDisplay: status.valueChanges.pipe(map(prodStatus => !['development', 'shooting'].includes(prodStatus)))
You should add `startWith` to have the first value if needed. Also avoid negation here, it's easy to make a mistake here.
Better is to create a reusable function.
```typescript
isStatus(form: FormControl, status: string[]) {
  return form.valueChanges.pipe(
    startWith(form.value),
    map(prodStatus => status.includes(prodStatus))
   )
}
```

2020-09-23 14:53 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/promotional/media-notes/notes.component.html
> +<ul>
Is it needed to use a ul/li if there is only one element ?

2020-09-23 14:53 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/promotional/media-notes/notes.component.html
> +    <ng-container *ngIf="!(movie.promotional.get('notes').controls.length) else notes">
Use the missing-controls. It should manage the kind of behavior. If not implement it.

2020-09-23 15:46 UTC, GrandSchtroumpf requested changes

2020-09-23 15:46 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/promotional-elements/media-notes/notes.component.ts
> +  roles = ['producer', 'director', 'other'];
It's not in the movie marketplace ?

2020-09-23 15:46 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/shell/shell.component.ts
> +        shouldDisplay: isStatus(statusCtrl , [prodStatus.released, prodStatus.post_production, prodStatus.finished])
Hmmm no, you want to check the keys not the values here. Use the string literals. But make sure the `isStatus` only accept the right keys.

2020-09-23 15:46 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/shell/shell.component.ts
> +function isStatus(prodStatusCtrl: FormControl, acceptableStatus: string[]) {
`acceptableStatus` should be of type `(keyof ProductionStatus)[]` or something like that.

2020-09-23 15:46 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/shell/shell.component.ts
> +    map(prodStatus => acceptableStatus.includes(staticConsts.productionStatus[prodStatus]))
Check on the keys, not the values.

2020-09-23 15:46 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/promotional/media-notes/notes.component.html
> +<ul>
up ?

2020-09-23 15:46 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/promotional/media-notes/notes.component.html
> +<ng-container *ngIf="!(movie.promotional.get('notes').controls.length) else notes">
Use missing controls

2020-09-23 15:48 UTC, fritzschoff commented on libs/movie/src/lib/movie/form/summary/promotional/media-notes/notes.component.html
> +    <ng-container *ngIf="!(movie.promotional.get('notes').controls.length) else notes">
would require a new component like `missing-form-list`since there is nothing to input, since controls array is empty. Can be implemented after Friday, to close otherwise

2020-09-24 09:24 UTC, GrandSchtroumpf requested changes

2020-09-24 09:24 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/dashboard/tunnel/summary/summary.component.ts
> +          if (field === 'originalLanguages') {
You could create a function to transform camelCase into label. Like that it would work all the time.
I'm pretty sure you can find this function on stackoverflow.

2020-09-24 09:24 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/promotional/media-images/media-images.component.html
> +      {{ images | json }}
You display a json to the end user ? Really ?

2020-09-24 09:24 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/promotional/media-images/media-images.component.ts
> +  public objectHasNoValue() {
There is pipe in `hasKeys` that will check recursively if object is empty. I think it should work here :
```html
<ng-container *ngIf="stillPhoto | hasKeys: 'controls'">
```

2020-09-24 09:24 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/promotional/media-notes/notes.component.html
> +<ng-container *ngIf="!(movie.promotional.get('notes').controls.length) else notes">
Now that you've got missing-control, you shouldn't need the ng-container. 
It should looks like that : 
```html
<missing-control  [control]="movie.promotional.get('notes')" [link]="link">
      <ng-container *ngFor="let note of movie.promotional.get('notes').controls">
        <span>{{ note.value.firstName }} {{ note.value.lastName }} - {{ note.value.role | titlecase | maxLength: 30 }} -
          {{ note.value.note.ref | fileName }}</span>
      </ng-container>
</missing-control>
```

2020-09-24 09:24 UTC, GrandSchtroumpf commented on libs/ui/src/lib/missing-control/missing-control.component.ts
> +    return !(!!control.value);
just `!control.value` ^^

2020-09-24 09:24 UTC, GrandSchtroumpf commented on libs/ui/src/lib/missing-control/missing-control.component.ts
> +        Object.values(control.controls).forEach(c => this.isMissing(c));
You're not returning anything here. Use `some` instead : 
```typescript
if (control instanceof FormGroup) {
  const values = Object.values(control.controls);
  return values.length ? values.some(c => this.isMissing(c)) : true;
}
```

2020-09-24 09:26 UTC, fritzschoff commented on libs/ui/src/lib/missing-control/missing-control.component.ts
> +    return !(!!control.value);
:D damn

2020-09-24 09:54 UTC, fritzschoff commented on libs/ui/src/lib/missing-control/missing-control.component.ts
> +        Object.values(control.controls).forEach(c => this.isMissing(c));
that doesn't work like that. If you do that, you are showing the value AND the `missing` keyword

2020-09-24 10:35 UTC, GrandSchtroumpf approved these changes

2020-09-24 10:35 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/promotional/media-images/media-images.component.html
> +    <ng-container *ngIf="stillPhoto | hasKeys: 'controls'">
You shouldn't have to check for that. If you're inside the ng-template you should already know that the stillPhoto have a value.

2020-09-24 10:35 UTC, GrandSchtroumpf commented on libs/ui/src/lib/missing-control/missing-control.component.ts
> +        Object.values(control.controls).forEach(c => this.isMissing(c));
But you need to return something. The line is currently doing nothing.

2020-09-24 12:29 UTC, merged