Issue still photo
blockframes/blockframes pull request #3792
Opened 2020-09-24 13:18 UTC by fritzschoff

2020-09-24 13:19 UTC, fritzschoff commented on apps/backend-functions/src/movie.ts
bit lost here... dunno what do to?

2020-09-24 13:19 UTC, fritzschoff commented on apps/backend-functions/src/movie.ts
what is an empty still_photo?

2020-09-24 13:37 UTC, phpgeekfr commented on apps/backend-functions/src/movie.ts
>    }
Since still_photo is now an array. You can skip this check

2020-09-25 11:49 UTC, phpgeekfr requested changes
Still some issues to fix and also check my comments on slack

2020-09-25 11:49 UTC, phpgeekfr commented on libs/movie/src/lib/movie/form/shell/shell.component.ts
> +      notes: promotional.notes.filter(note => !!note)
should be ` notes: promotional.notes.filter(note => !!note?.ref) ` I think

2020-09-25 11:49 UTC, phpgeekfr commented on apps/backend-functions/src/media.ts
> -
Still need this (updated for array) to handle update of still_photo

2020-09-25 11:49 UTC, phpgeekfr commented on apps/backend-functions/src/media.ts
> +    before.promotional.still_photo.filter(photo => !!photo)
.filter(photo => !!photo) should not be needed here

2020-09-25 11:49 UTC, phpgeekfr commented on apps/backend-functions/src/media.ts
> -
you should also handle notes here CF cleanOrgMedias

2020-09-25 11:49 UTC, phpgeekfr commented on apps/backend-functions/src/media.ts
> +    before.promotional.still_photo.filter(photo => !!photo)
you should also handle notes here CF cleanOrgMedias

2020-09-25 11:49 UTC, phpgeekfr commented on apps/backend-functions/src/movie.ts
>    }
You can remove this

2020-09-25 12:55 UTC, phpgeekfr approved these changes
Good job !

2020-09-25 12:56 UTC, merged