test
blockframes/blockframes pull request #3801
Opened 2020-09-25 15:23 UTC by fritzschoff

2020-09-25 16:38 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/additional-information/additional-information.component.html
> +      <ng-container *ngFor="let cert of certs; let last = last">
Just do : `{{ certs | translateSlug: 'CERTIFICATIONS' }}`
The pipe takes care of list join

2020-09-25 16:38 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/additional-information/additional-information.component.html
> +    <ng-container *ngIf="movie.originalRelease.controls.length; else emptyReleases">
Same comment for all below.

2020-09-28 10:49 UTC, GrandSchtroumpf requested changes

2020-09-28 10:49 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/additional-information/additional-information.component.html
> +                <ng-container *ngIf="unit.value === 'boxoffice_dollar'">
@Mussuranae I think we've got an issue with the key here. I don't see the point of naming unit "boxoffice_dollar". The best would be to match the keys of the [CurrencyPipe](https://angular.io/api/common/CurrencyPipe) in angular (which the same as the svgIcon names).
Like that we could transform this code into : 
```html
<mat-icon [svgIcon]="unit.value" id="currency-icon"></mat-icon>
```
Which makes much more sense than using *ngIf

2020-09-28 10:49 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/additional-information/additional-information.component.html
> +      <ng-container *ngFor="let cert of certs.controls">
Hmmm this shouldn't work. You should not iterate over the controls but the values.

2020-09-28 10:49 UTC, GrandSchtroumpf commented on libs/ui/src/lib/missing-control/missing-control.component.html
> +<ng-template #content [ngTemplateOutlet]="child || value" [ngTemplateOutletContext]="{ $implicit: control }">
Update the context to provide the value & the control: 
```html
<ng-template #content [ngTemplateOutlet]="child || value" [ngTemplateOutletContext]="{ $implicit: control, control }">
```

2020-09-28 10:49 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/review/review.component.html
> +              <ng-template>
Use the `let-revueLink` here

2020-09-29 08:10 UTC, Mussuranae commented on libs/movie/src/lib/movie/form/summary/additional-information/additional-information.component.html
> +                <ng-container *ngIf="unit.value === 'boxoffice_dollar'">
Yes I see, I will do a migration script for that, that makes sense

2020-09-30 08:33 UTC, GrandSchtroumpf requested changes

2020-09-30 08:33 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/shooting-information/shooting-information.component.ts
>        tap(value => {
Do it in the subscribe instead of the tap : 
```typescript
const keys = ['completed', 'planned', 'progress'] as const;
....
this.sub = this.disabledForm.valueChanges.pipe(
  distinctUntilChanged(),
  filter(value => !!value),
).subscribe(value => this.activate(value));

const active = keys .find(key => hasValue(this.form.shooting.value.dates[key]));
this.disabledForm.setValue(active);
....
activate(activeKey: 'completed' | 'planned' | 'progress') {
  for (const key of keys) {
    if (key === activeKey) {
      this.form.shooting.get('dates').get(key).enable();
    } else {
      this.form.shooting.get('dates').get(key).disable();
      this.form.shooting.get('dates').get(key).reset();
    }
  }
}
```

2020-09-30 08:33 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/shooting-information/shooting-information.component.ts
> +  private handleStateOfShootingDateForm(state: 'disable' | 'enable') {
Normally you shouldn't need that, enable, disable & reset apply for children : 
https://angular.io/api/forms/AbstractControl#enable
https://angular.io/api/forms/AbstractControl#disable
https://angular.io/api/forms/FormGroup#reset

2020-09-30 08:33 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/additional-information/additional-information.component.html
> +                <ng-container *ngIf="unit === 'boxoffice_dollar'">
Clelia has a PR to fix this :
https://github.com/blockframes/blockframes/pull/3821
You might check with her about that.

2020-09-30 08:33 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/additional-information/additional-information.component.html
> +      <ng-container *ngFor="let cert of certs">
You don't need that. The translateSlug already iterate over each item.
```html
{{ cert | translateSlug: 'CERTIFICATIONS' }}
```

2020-09-30 08:33 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/main/main.component.html
> +        <ng-template let-runningTime="control">{{ runningTime.get('time').value | duration }}</ng-template>
Don't use the control here :
```html
<ng-template let-runningTime>{{ runningTime.time | duration }}</ng-template>
```

2020-09-30 08:33 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/promotional/media-images/media-images.component.html
> +    <ng-template let-images="control">
Don't use the control : 
```html
<ng-template let-images>
  <div fxLayout *ngFor="let image of images">
    <mat-icon svgIcon="eye" color="primary"></mat-icon>
    <span>{{ image.ref | fileName | maxLength: 30 }}</span>
  </div>
</ng-template>
```

2020-09-30 08:33 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/promotional/media-notes/notes.component.html
> +    <ng-template let-notes="control">
Same as above don't use the control.

2020-09-30 08:33 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/promotional/media-videos/media-videos.component.html
> +      <ng-template let-links="control">
Same as above don't use the control.

2020-09-30 08:33 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/review/review.component.html
> +              <ng-template #content>{{ customPrize.get('name').value }} </ng-template>
Remove content, use `let-name` : 
```html
<ng-template let-name>{{ name }}</ng-template>
```
Same for below

2020-09-30 08:33 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/review/review.component.html
> +              <ng-container *ngIf="customPrize.get('premiere')">
You already have "premiere" :
```html
<ng-container *ngIf="premiere">
  <span>{{ premiere | titlecase }} Premiere</span>
</ng-container>
```

2020-09-30 08:33 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/review/review.component.html
> +              <ng-template>
Same comment

2020-09-30 08:33 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/sales-pitch/sales-pitch.component.html
> +            <missing-control [control]="goal.get('target')" [link]="link">
I don't see why we need a missing control here. Should it be a : 
```html
<ng-template let-goals>
  <ng-container *ngFor="let goal of goals">
    <span>{{ goal.target | titlecase }}{{ last ? '' : ', ' }}</span>
  </ng-container>
</ng-template>
```

2020-09-30 08:33 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/sales-pitch/sales-pitch.component.html
> +        <ng-template let-audienceGoals="control">
Same as audienceGoals

2020-09-30 08:44 UTC, fritzschoff commented on libs/movie/src/lib/movie/form/summary/promotional/media-images/media-images.component.html
> +    <ng-template let-images="control">
you need a control here since there are many more controls like fileName you don't want to check

2020-09-30 09:01 UTC, fritzschoff commented on libs/movie/src/lib/movie/form/shooting-information/shooting-information.component.ts
>        tap(value => {
``` 
  for (const key of keys) {
``` 
why do you iterate over a string?

2020-09-30 09:35 UTC, fritzschoff commented on libs/movie/src/lib/movie/form/summary/sales-pitch/sales-pitch.component.html
> +            <missing-control [control]="goal.get('target')" [link]="link">
cause target is a formcontrol ?

2020-09-30 09:35 UTC, fritzschoff commented on libs/movie/src/lib/movie/form/summary/sales-pitch/sales-pitch.component.html
> +        <ng-template let-audienceGoals="control">
same above

2020-09-30 09:57 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/shooting-information/shooting-information.component.ts
>        tap(value => {
I'm not: 
```typescript
const keys = ['completed', 'planned', 'progress'] as const;
```
Like that you don't need to use a switch case and repeat yourself.

2020-09-30 10:01 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/sales-pitch/sales-pitch.component.html
> +            <missing-control [control]="goal.get('target')" [link]="link">
So you want to display "missing" for each target of a goal that is not set ?

2020-09-30 10:17 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/promotional/media-images/media-images.component.html
> +    <ng-template let-images="control">
You're not using the control so you don't need it.

2020-09-30 10:43 UTC, GrandSchtroumpf approved these changes
👍

2020-09-30 10:43 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/promotional/media-images/media-images.component.html
> +            {{ image.value.ref | fileName | maxLength: 30 }}
This shouldn't be `image.value.ref` but `image.ref` as you're taking the value of the image, not the control : 
```html
<div fxLayout *ngFor="let image of images">
  <mat-icon svgIcon="eye" color="primary"></mat-icon>
  <span>{{ image.value.ref | fileName | maxLength: 30 }}</span>
</div>
```

2020-09-30 12:19 UTC, merged