added participant component
blockframes/blockframes pull request #3847
Opened 2020-10-02 08:43 UTC by OmarSebouai

Participant Component - Issue#3758

This is the participant component. As seen in the last meeting, we are providing the participant panel in standalone.

Usage: 
`
<event-participants-nav [participants]="arrayOfParticipantConnected$ | async">
  <event-video
    [arrayOfParticipantConnected$]="arrayOfParticipantConnected$"
    [$participantConnectedDataSource]="$participantConnectedDataSource"
    [localParticipantConnected$]="localParticipantConnected$"
    [localPreviewTracks$]="localPreviewTracks$"
    [dominantParticipantForBuyer$]="dominantParticipantForBuyer$"
    [event]="event"
    ></event-video>
</event-participants-nav>
`

![image](https://user-images.githubusercontent.com/70688475/94904725-05951e00-049c-11eb-93c6-baf76534d8cf.png)

2020-10-02 10:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.html
> +                <span>{{getInitialFromParticipant(participant)}}</span>
Never use method in for BoundText or inputs. It's trigger at every change detection. Use pure pipes instead that use memorization.

2020-10-02 10:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.html
> +                <caption class="mat-caption name">{{participant.firstName}} {{participant.lastName}}</caption>
Caption is used to describe something like an image, a graph, a table... It doesn't seems to be the case here. Use material component or correct semantic like p, span, .. or headings.

2020-10-02 10:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.html
> +<!--            <mat-icon svgIcon="close" color="warn" class="close"></mat-icon>-->
Remove comment if you don't use.

2020-10-02 10:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.html
> +          <hr>
use material component divider.

2020-10-02 10:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.html
> +      <div class="action">
Use material component or correct semantic (footer, ...)

2020-10-02 10:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.html
> +  <button mat-icon-button class="menu-button" (click)="drawer.toggle()" *ngIf="!drawer.opened">
Use the right method. If the button is display only when drawer is closed then use drawer.open().

2020-10-02 10:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.html
> +  <button mat-icon-button class="menu-button" (click)="drawer.toggle()" *ngIf="!drawer.opened">
Also extract the `*ngIf` logic in a parent `<ng-container *ngIf="!drawer.opened">` for better separation of concern.

2020-10-02 10:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.html
> +  <ng-content></ng-content>
Wrap this into a `<mat-sidenav-content>`

2020-10-02 10:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +    width: 30%;
Isn't it too big on large screen ?

2020-10-02 10:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +@import 'node_modules/@angular/flex-layout/mq';
You're not using it. Remove it.

2020-10-02 10:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +    background-color: #33305B;
We should color based on the current theme. Check with Stéphanie if we can apply a color from the theme here.

2020-10-02 10:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +  pointer-events: none;
why do you need to remove the point-events ? It'll break swipe effect on tablet...

2020-10-02 10:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +  .sidenav {
Use tag name instead of class for the selector.

2020-10-02 10:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +      display: flex;
use the `FlexLayoutModule` in the html : 
```html
<nav fxLayout="column">
```

2020-10-02 10:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +    div {
Only apply style on element that needs it. Here you're removing the border of everything even the element doesn't have a border already.

2020-10-02 10:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +        margin-right: 5px;
There is no tag with the class "mat-icon" in the html. Use tag selector when possible.
use multiple of 8 for the margin & padding.

2020-10-02 10:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +        background-color: white;
Use theme colors. 
By using material component (when possible) you won't have to bother about that because they are already wired to the theme.

2020-10-02 10:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +      .title {
Use flexLayout : 
```html
<header fxLayout fxLayoutAlign="space-between center">
```
Same each time you use flex or grid

2020-10-02 10:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +        .mat-icon {
Don't change the size of mat-icon. We keep the same everywhere in the app.

2020-10-02 10:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +          height: 10%;
I'm not comfortable using a % on height. I think if you use the right material component you won't need that anymore.

2020-10-02 10:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +        height: 80%;
Why not taking the rest of the space instead of 80% ? 
If so use `flex: 1` in css or better `<tag fxFlex>`

2020-10-02 10:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +        overflow: scroll;
Why are you forcing the scroll ? And not displaying it.

2020-10-02 10:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +          margin: 10px;
Use 16px (2 * 8)

2020-10-02 10:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +              background-color: white;
Use theme color

2020-10-02 10:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +            .profile {
There are component for that in the material library

2020-10-02 10:42 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.html
> +              <div class="profile">
We've got the avatar of the participant. It's better to use it. Check the `ImageReferenceModule` from `@blockframes/media` to display images. You can use a `*ngIf="participant.avatar; else initials"` to fallback to the initials.

2020-10-02 10:42 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +              span {
I don't understand the benefit of this style if the container already apply center center. Only apply style that is required.

2020-10-02 10:42 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +              color: white;
Use theme colors

2020-10-02 10:42 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +            .mat-caption {
All the mat-caption are wrapping text node that are not affected by flex. Why using it ?

2020-10-02 10:42 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +            .close {
You commented out this tag. Remove unnecessary code.

2020-10-02 10:42 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +        background-color: #5C597B;
Use the attribute "color" of the `mat-icon-button` directive

2020-10-02 10:42 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +        opacity: 0.5;
Don't reduce opacity it reduce contrast which makes it difficult for color-blind people to find the action button.

2020-10-02 10:45 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.html
> +      <div class="action">
Looks like an action button but there is not (click) event. Either semantic is wrong or feature is missing.

2020-10-02 10:50 UTC, GrandSchtroumpf requested changes
Please use material components, use tag for the selectors and don't apply unnecessary css.

2020-10-02 10:50 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +    right: 0;
top: 8px; right: 8px;

2020-10-02 10:50 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +    pointer-events: all;
Remove this part if you remove pointer event: none on container.

2020-10-02 10:50 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.ts
> +import { Participant as IParticipantMeeting } from 'twilio-video';
why creating an alias ?

2020-10-02 10:50 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.ts
> +  getInitialFromParticipant(participant){
type your code and use a pipe instead.

2020-10-02 10:50 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.ts
> +  ngOnInit(): void {
Remove onInit and constructor if you don't use

2020-10-02 10:50 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.ts
> +  @Input() participants: IParticipantMeeting[];
We should get the user from Firestore instead to have access to the avatar.

2020-10-06 11:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +          font-size: 0.7em;
use angular material typography instead of overriding the size. I think a class="mat-caption" would do the job here : 
https://material.angular.io/guide/typography

2020-10-06 11:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +        mat-icon {
Better set a padding on header : 
```html
header {
  padding: 0 8px;
}
```

2020-10-06 11:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +        height: unset;
Then don't set it ;)

2020-10-06 11:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +            width: 7vh;
The matListAvatar set the height & width already : 
https://github.com/angular/components/blob/master/src/material/list/list.scss#L10

2020-10-06 11:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +            border-radius: 50%;
This should be managed by the matListAvatar directive :
https://github.com/angular/components/blob/master/src/material/list/list.scss#L145

2020-10-06 11:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.html
> +        <mat-list-item>
Use mat-list-item way of dealing with text & avatar: 
https://material.angular.io/components/list/overview#lists-with-avatars

```html
<mat-list-item>
  <span matListAvatar>...</span>
  <h3 matLine>{{participant.festivalData | displayName}}</h3>
  <span matLine>{{ participant.festivalData.organizationName }}</span>
</mat-list-item>
```
Here I use the displayName pipe that you can find in "@blockframes/utils/pipes" :
In the module:
```typescript
import { DisplayNameModule } from '@blockframes/utils/pipes';
```

2020-10-06 11:37 UTC, OmarSebouai commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +        height: unset;
It seems like there was a fixed set on the original mat-list-item (56px)

2020-10-06 11:38 UTC, OmarSebouai commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +            border-radius: 50%;
Will have a closer look into this and make a quick feedback. We didn't plan on implementing avatars at first but at this point, we're already into it =)

2020-10-06 11:45 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +            border-radius: 50%;
You don't need to implement the avatar img right now. We can merge this PR without.
But by using the matListAvatar directive you use the theme & style of material (and blockframes). So it won't break the UI feeling.

2020-10-06 11:47 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +        height: unset;
Then let's keep the mat-list-item height. By keeping default css values as much as possible it makes it much easier to keep a UI harmony across all apps, and update it everywhere at once.

2020-10-06 13:54 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +          text-align: left;
Is it really required ?

2020-10-06 13:54 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
>        background-color: var(--whiteBackground);
sorry I missed this one. whiteBackground might be a little aggressive on dark mode. You can use `var(--background-card)`. It should be white on light mode & black on dark mode.

2020-10-06 13:54 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.ts
> +  @Input() participants$: Observable<IParticipantMeeting[]>;
Never pass an observable as input you'll loose all the benefice of ChangeDetectionStrategy.OnPush. 
The async pipe should be given by the parent: 
```html
<event-meeting-participants-nav [participants]="participants | async">
```

2020-10-06 13:54 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +          font-size: 1em;
I think that you can remove this size. The h3 + matLine should do the job of making the first line bigger than the second.

2020-10-06 14:26 UTC, OmarSebouai commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.ts
> +  @Input() participants$: Observable<IParticipantMeeting[]>;
Oh ok!

2020-10-06 15:27 UTC, GrandSchtroumpf approved these changes
Looks pretty good 👍. I left you one comment on the changeDetection that I missed. 
@pldespaigne will test the branch to see if everything work well, it would be cool if you can provide him a set of participant fixtures so he can test the component easily.
Sorry it took so much time for this one. Now it should go faster for the next ones.

2020-10-06 15:27 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.ts
> +  styleUrls: ['./participants-nav.component.scss']
ah ! I missed this one : Use `changeDetection: ChangeDetectionStrategy.OnPush` to only run the change detection when the input change.

2020-10-06 15:51 UTC, OmarSebouai commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.ts
> +  styleUrls: ['./participants-nav.component.scss']
True! Thanks for all your feedback, we'll make sure we take everything into account for the next push!

Btw, I added in the original comment the code we use to wrap the participant component and add participants.

2020-10-06 16:00 UTC, OmarSebouai commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.ts
> +  styleUrls: ['./participants-nav.component.scss']
It's weird. Somehow, the change isn't applied with the `changeDetection: ChangeDetectionStrategy.OnPush` line. But it does work when we remove it.

2020-10-06 16:13 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.ts
> +  styleUrls: ['./participants-nav.component.scss']
Which changes are not applied ? `ChangeDetectionStrategy.OnPush` should only trigger the changes when the input is updated. This can happen when you pass an array for example as an input and you mutate it with `paraticipant.push()` in the parent component instead making an immutable change.

2020-10-07 09:59 UTC, pldespaigne requested changes
Your component is not part of any module, so right now it cannot be mounted in the app.
Please add a `participants-nav.module.ts` module in the same folder as the component.

This way it became self contained and can be mounted anywhere.

2020-10-07 09:59 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.html
> +  <mat-sidenav #sidenav [position]="'end'" [mode]="'over'" [autoFocus]="true">
you don't need to use brackets for constant primitives like strings, moreover the sidenav should be in `side` mode so that it doesn't close automatically when the user click outside

`<mat-sidenav #sidenav position="end" mode="over">`

2020-10-07 09:59 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.html
> +          <span matListAvatar class="avatar-text ">{{participant | eventInitialParticipant}}</span>
You haven't committed the `eventInitialParticipant` pipe, I was unable to review it and to test it's behavior

2020-10-07 09:59 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.scss
> +mat-sidenav-container {
Please add `height: 100%` to the `mat-sidenav-container` so that your component will take the space of it's parent.
I have tested it and without `height: 100%` and your component is not visible.

2020-10-07 09:59 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/participant-nav/participants-nav.component.ts
> +  selector: 'event-meeting-participants-nav',
if the `participants` input is mandatory you can force it in the selector like that:

`selector: '[participants] event-meeting-participants-nav',`

2020-10-07 09:59 UTC, pldespaigne commented on package.json
> +    "twilio-video": "^2.7.2",
please also add typing:

`npm i @types/twilio @types/twilio-video --save-dev`

2020-10-21 08:31 UTC, pldespaigne approved these changes
SGTM 👍

2020-10-22 12:50 UTC, merged