Feat(E2E): Add movie form e2e test to Festival App & skip for Catalog
blockframes/blockframes pull request #3862
Opened 2020-10-06 07:04 UTC by xmano

Skip movie form test for Catalog App as UI is not updated. 

Add Step 1 for Movie Form test for Festival App new form UI.

2020-10-06 07:06 UTC, xmano commented
Migrated to new branch:

![image](https://user-images.githubusercontent.com/8731418/95169466-8a4fa700-07d0-11eb-9336-91cd098824bb.png)


http://localhost:4200/c/o/dashboard/tunnel/movie/1dPPD8KtuGqvQcAytVWx/main

2020-10-06 08:40 UTC, RemcoSimonides requested changes

2020-10-06 08:40 UTC, RemcoSimonides commented on apps/festival/festival-e2e/src/support/movie-tunnel-tests/1-main.ts
> +  //TODO:
Describe what still has to be done

2020-10-06 08:40 UTC, RemcoSimonides commented on apps/festival/festival-e2e/src/support/movie-tunnel-tests/1-main.ts
> +export const MAIN_PARTIAL_COUNTRIES = ['Fr', 'pol', 'it'];
Make it all 2-letter codes; `['Fr', 'Pl', 'It']`

2020-10-06 08:40 UTC, RemcoSimonides commented on apps/festival/festival-e2e/src/support/movie-tunnel-tests/index.ts
> +import { mainTest } from './1-main';
Isn't it possible to export directly?
`export { mainTest } from './1-main'`

2020-10-06 08:40 UTC, RemcoSimonides commented on apps/festival/festival-e2e/src/support/pages/dashboard/movietunnel/TunnelStorylinePage.ts
> +//import TunnelCreditsPage from "./TunnelCreditsPage";
Remove

2020-10-06 08:40 UTC, RemcoSimonides commented on apps/festival/festival-e2e/src/support/pages/dashboard/movietunnel/index.ts
>  ﻿import MovieTunnelStartPage from './MovieTunnelStartPage';
If possible; export directly here too

2020-10-06 08:40 UTC, RemcoSimonides commented on apps/festival/festival-e2e/src/support/utils/utils.ts
> +//import { TitlesListPage, StartTunnelPage, TunnelMainPage } from '../pages/dashboard';
Remove

2020-10-06 08:40 UTC, RemcoSimonides commented on apps/festival/festival-e2e/src/support/pages/dashboard/movietunnel/TunnelStorylinePage.ts
> +    cy.get('catalog-tunnel-synopsis', { timeout: 5000 });
Sometimes you use `{ timeout: TO.PAGE_LOAD }` for example, but you dont use it every time. Is there a reason for this?

2020-10-06 08:49 UTC, phpgeekfr commented on apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-end.spec.ts
> +describe.skip('User can navigate to the movie tunnel, complete required fields, and send the movie', () => {
Can you add a comment explaining why It is skip along with an issue number if needed ?

2020-10-06 08:49 UTC, phpgeekfr commented on apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel.spec.ts
Can you add a comment explaining why It is skip along with an issue number if needed ?

2020-10-06 08:49 UTC, phpgeekfr commented on apps/festival/festival-e2e/src/fixtures/movies.json
> +{"versionInfo":{"languages":{"english":{"subtitle":false,"original":true,"dubbed":false,"caption":false}}},"documents":{"chainOfTitles":[]},"id":"056cKWz9hCamDCgdIzeY","movieReview":[],"_type":"movie
I don't understand why you need to commit this and why you are not using `tools/fixtures` generated fixtures

2020-10-06 08:49 UTC, phpgeekfr commented on apps/festival/festival-e2e/src/support/movie-tunnel-tests/index.ts
> +import { mainTest } from './1-main';
New tests will be imported I guess ? If not, this file is not very useful ;)

2020-10-06 08:49 UTC, phpgeekfr commented on apps/catalog/catalog-e2e/src/support/pages/dashboard/TitlesListPage.ts
> +    cy.get('catalog-title-list [test-id=add-movie]', { timeout: 30000 })
{ timeout: 30000 }) => why not use the vars you created for that?

2020-10-06 10:56 UTC, xmano commented on apps/festival/festival-e2e/src/support/movie-tunnel-tests/1-main.ts
> +export const MAIN_PARTIAL_COUNTRIES = ['Fr', 'pol', 'it'];
Ok.

2020-10-06 11:02 UTC, xmano commented on apps/festival/festival-e2e/src/support/pages/dashboard/movietunnel/TunnelStorylinePage.ts
> +    cy.get('catalog-tunnel-synopsis', { timeout: 5000 });
Added TO enum.

2020-10-06 11:20 UTC, xmano commented on apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel-end.spec.ts
> +describe.skip('User can navigate to the movie tunnel, complete required fields, and send the movie', () => {
#3874 added.

2020-10-06 11:22 UTC, xmano commented on apps/catalog/catalog-e2e/src/integration/dashboard/movie-tunnel.spec.ts
#3874 added

2020-10-06 11:23 UTC, xmano commented on apps/festival/festival-e2e/src/support/movie-tunnel-tests/index.ts
> +import { mainTest } from './1-main';
Yes creating the test structure. We will use the folder for new tests to organize tests.

2020-10-06 11:24 UTC, xmano commented on apps/catalog/catalog-e2e/src/support/pages/dashboard/TitlesListPage.ts
> +    cy.get('catalog-title-list [test-id=add-movie]', { timeout: 30000 })
Existing code and this will be changed again in fix for #3874. So leaving it for now.

2020-10-06 11:37 UTC, xmano commented on apps/festival/festival-e2e/src/support/movie-tunnel-tests/index.ts
> +import { mainTest } from './1-main';
Yes. Done.

2020-10-06 11:44 UTC, xmano commented on apps/festival/festival-e2e/src/fixtures/movies.json
> +{"versionInfo":{"languages":{"english":{"subtitle":false,"original":true,"dubbed":false,"caption":false}}},"documents":{"chainOfTitles":[]},"id":"056cKWz9hCamDCgdIzeY","movieReview":[],"_type":"movie
Removing it.

2020-10-06 11:45 UTC, xmano commented on apps/festival/festival-e2e/src/support/movie-tunnel-tests/1-main.ts
> +  //TODO:
It will be address further tests. This PR is WIP.

2020-10-06 11:49 UTC, xmano commented on apps/festival/festival-e2e/src/support/pages/dashboard/movietunnel/index.ts
>  ﻿import MovieTunnelStartPage from './MovieTunnelStartPage';
Direct export does not work for some reason here. Will leave it as it is.

2020-10-06 13:11 UTC, xmano commented on apps/festival/festival-e2e/src/support/pages/dashboard/movietunnel/TunnelStorylinePage.ts
> +//import TunnelCreditsPage from "./TunnelCreditsPage";
Removed.

2020-10-06 13:12 UTC, xmano commented on apps/festival/festival-e2e/src/support/utils/utils.ts
> +//import { TitlesListPage, StartTunnelPage, TunnelMainPage } from '../pages/dashboard';
Good catch. Removed.

2020-10-06 13:18 UTC, xmano commented on apps/festival/festival-e2e/src/support/pages/dashboard/movietunnel/TunnelStorylinePage.ts
> +//import TunnelCreditsPage from "./TunnelCreditsPage";
Removed.

2020-10-06 13:18 UTC, xmano commented on apps/festival/festival-e2e/src/support/utils/utils.ts
> +//import { TitlesListPage, StartTunnelPage, TunnelMainPage } from '../pages/dashboard';
Done

2020-10-07 09:15 UTC, phpgeekfr approved these changes

2020-10-07 09:37 UTC, RemcoSimonides approved these changes

2020-10-07 09:37 UTC, RemcoSimonides commented on apps/festival/festival-e2e/src/integration/dashboard/movie-tunnel.spec.ts
> +import {
Can be on one line

2020-10-07 09:37 UTC, RemcoSimonides commented on apps/festival/festival-e2e/src/integration/dashboard/movie-tunnel.spec.ts
> +const users  =  [ userFixture.getByUID(USER.Jean) ];
I see some double spaces in this line

2020-10-07 09:37 UTC, RemcoSimonides commented on apps/festival/festival-e2e/src/support/movie-tunnel-tests/1-main.ts
> +export const MAIN_PARTIAL_COUNTRIES = ['Fr', 'pol', 'it'];
You've changed it for catalog, not for festival yet ;)

2020-10-09 02:10 UTC, xmano commented on apps/festival/festival-e2e/src/integration/dashboard/movie-tunnel.spec.ts
> +import {
Changed to single line.

2020-10-09 02:11 UTC, xmano commented on apps/festival/festival-e2e/src/integration/dashboard/movie-tunnel.spec.ts
> +const users  =  [ userFixture.getByUID(USER.Jean) ];
Fixed.

2020-10-09 02:29 UTC, merged