Add cookie settings to profile page
blockframes/blockframes pull request #3921
Opened 2020-10-09 13:38 UTC by RemcoSimonides

To do issue #2403 

https://projects.invisionapp.com/d/main#/console/19607961/420299224/preview

2020-10-09 13:41 UTC, RemcoSimonides commented on libs/utils/src/lib/gdpr-cookie/cookie-dialog/cookie-dialog.component.scss
> +  position: unset !important;
💀

2020-10-09 13:41 UTC, RemcoSimonides commented on libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.scss
> +  position: unset !important;
💀

2020-10-09 13:43 UTC, RemcoSimonides commented on libs/user/src/lib/auth/pages/profile-cookie/profile-cookie.component.ts
> +import { CookiesConsentForm } from '@blockframes/utils/gdpr-cookie/cookie-form/cookie.form';
CookiesConsentForm is still in this separate file; but I think this is best because it's now used in two components; cookie-dialog.component.ts and profile-cookie.component.ts.
What do you say @GrandSchtroumpf , still leave it here?

2020-10-09 13:52 UTC, GrandSchtroumpf requested changes

2020-10-09 13:52 UTC, GrandSchtroumpf commented on libs/user/src/lib/auth/pages/profile-cookie/profile-cookie.component.html
> +<mat-card>
It's kind of weird to pu the cookies form in a card just la that. Why do you need a card ?

2020-10-09 13:52 UTC, GrandSchtroumpf commented on libs/user/src/lib/auth/pages/profile-cookie/profile-cookie.component.html
> +<footer fxLayout fxLayoutAlign="center center">
Why the footer is not in the card ?

2020-10-09 13:52 UTC, GrandSchtroumpf commented on libs/user/src/lib/auth/pages/profile-cookie/profile-cookie.component.ts
> +import { CookiesConsentForm } from '@blockframes/utils/gdpr-cookie/cookie-form/cookie.form';
ok

2020-10-09 13:52 UTC, GrandSchtroumpf commented on libs/user/src/lib/auth/pages/profile-cookie/profile-cookie.component.ts
> +  styleUrls: ['profile-cookie.component.scss']
add changeDetection

2020-10-09 13:52 UTC, GrandSchtroumpf commented on libs/user/src/lib/auth/pages/profile-view/profile-view.component.html
> +  <section>
I think you don't need this section

2020-10-09 13:52 UTC, GrandSchtroumpf commented on libs/utils/src/lib/gdpr-cookie/cookie-dialog/cookie-dialog.component.html
> +<mat-card>
Same. I've got the feeling you don't need the mat-card

2020-10-09 13:52 UTC, GrandSchtroumpf commented on libs/utils/src/lib/gdpr-cookie/cookie-dialog/cookie-dialog.component.scss
> +  position: unset !important;
If you remove the mat-card you won't need that anymore.

2020-10-09 13:52 UTC, GrandSchtroumpf commented on libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.scss
> +  position: unset !important;
I really don't understand why you need that here.

2020-10-09 13:52 UTC, GrandSchtroumpf commented on libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.ts
> +      const allAccepted = !Object.keys(data).some(key => !data[key]);
Prefer using "every" instead of using negative operators: 
```typescript
const allAccepted = Object.keys(data).every(key => data[key]));
```

2020-10-09 13:59 UTC, RemcoSimonides commented on libs/user/src/lib/auth/pages/profile-cookie/profile-cookie.component.html
> +<footer fxLayout fxLayoutAlign="center center">
Designs
Here the button is outside the card; https://projects.invisionapp.com/d/main#/console/19607961/420299224/preview
And here it is within the card; https://projects.invisionapp.com/d/main#/console/19607961/418991527/preview

2020-10-09 14:01 UTC, RemcoSimonides commented on libs/utils/src/lib/gdpr-cookie/cookie-form/cookie-form.component.ts
> +      const allAccepted = !Object.keys(data).some(key => !data[key]);
Nice! I was searching for this :D

2020-10-12 08:55 UTC, RemcoSimonides commented on libs/user/src/lib/auth/pages/profile-view/profile-view.component.html
> +  <section>
I do; has to do with the padding added. It's theoretically possible to remove `section`, but then the scss would get quite a lot more complicated.

2020-10-13 09:30 UTC, GrandSchtroumpf approved these changes

2020-10-13 09:31 UTC, merged