Issue3756 seller join meeting
blockframes/blockframes pull request #3941
Opened 2020-10-12 15:28 UTC by OmarSebouai

Issue #3756 

This pull request contains some work that are present in the Issue #3754 to allow you to join a Twilio Room (otherwise, this won't be testable).

The BUYER view isn't available for this pull request. If you want to test it, you can simple remove the *ngIf="isSeller" line in:
`/libs/event/src/lib/component/meeting/video/video-component.html line 1`

This way, everyone will have a Seller View and be able to see each other.

2020-10-14 13:55 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/avatar-initial/avatar-initial.component.scss
> +  width: 10vh;
Use px. Or better use material typography

2020-10-14 13:55 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/avatar-initial/avatar-initial.component.scss
> +  border-radius: 50%;
A rounded text ?

2020-10-14 13:56 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/+state/meeting.service.ts
> +    });
same as above

2020-10-14 13:56 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/+state/meeting.service.ts
> +      .then(async (value: ErrorResultResponse) => {
use `async/await` instead

2020-10-14 13:56 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/+state/meeting.service.ts
> +      })
use `async/await` instead

2020-10-14 13:56 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/+state/meeting.service.ts
> +    });
use `async/await` instead

2020-10-14 13:56 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/+state/meeting.service.ts
> +      if (!!tracksOfParticipants && tracksOfParticipants.length > 0) {
Remove this `if` as `getParticipantOfParticipantsMapAlreadyInRoom` should always return an array.
Moreover if the array is empty the `for` loop bellow will not run.

2020-10-14 13:56 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/+state/meeting.service.ts
> +        }
The `for` loop can be factorized into a `.forEach`. also you don't need to `await` between each iteration.
Instead you can add promises to an array and do `await Promise.all()` after the loop to `await` concurently.

2020-10-14 13:56 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/+state/meeting.service.ts
> +    const localMeetingParticipant = await this.createIParticipantMeeting(room.localParticipant, event, true );
you don't need this `const`

2020-10-14 13:56 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/+state/meeting.service.ts
> +    await this.setUpRoomEvent(room, event);
you don't need to `await` here

2020-10-14 13:56 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/+state/meeting.service.ts
> +        organizationName: 'To Be Implemented',
Don't leave this in the code, an empty string is better in case we forget about it and it goes to production.

But in this case you can do something like
```Typescript
const remoteOrg = await this.orgService.getValue(remoteUser.orgId);

...
organizationName: remoteOrg.denomination.full,
```

2020-10-14 13:56 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/+state/meeting.service.ts
> +    const remoteUser = await this.userService.getUser(twilioParticipant.identity)
you forget the `;`

2020-10-14 13:56 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/+state/meeting.service.ts
> +    } as IParticipantMeeting;
put the return type in the function prototype

2020-10-14 13:59 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/container-video/container-video.component.ts
> +    console.log('ngOnDestroy')
Please remove console.log

2020-10-14 13:59 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/video/video.component.scss
> +  position: relative;
Do you have absolute children ? If not remove this.

2020-10-14 13:59 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/video/video.component.scss
> +  mat-grid-tile {
Remove dead code.

2020-10-14 15:05 UTC, OmarSebouai commented on libs/event/src/lib/components/meeting/avatar-initial/avatar-initial.component.scss
> +  width: 10vh;
We wanted to have a circle with text inside (to mock avatar). Instead, we will be using a section with vw size to make the circle, and matcaption for the text.

2020-10-14 15:05 UTC, OmarSebouai commented on libs/event/src/lib/components/meeting/avatar-initial/avatar-initial.component.scss
> +  border-radius: 50%;
See above

2020-10-14 15:14 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/avatar-initial/avatar-initial.component.scss
> +  width: 10vh;
Would it work if you use the class `.mat-list-avatar` on the span ? Else use px & breakpoints if it breaks on tablet.

2020-10-14 15:25 UTC, OmarSebouai commented on libs/event/src/lib/components/meeting/+state/meeting.service.ts
> +    const isDominantSpeaker = twilioParticipant.identity === event.organizedBy.uid
see above

2020-10-15 09:12 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/+state/meeting.service.ts
> +  getIfIsReelOwner(event: Event) {
please use `event.isOwner` anyway is it will be the single source of truth, we are in the process of fixing it

2020-10-16 12:25 UTC, pldespaigne requested changes

2020-10-16 12:25 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/container-video/container-video.component.ts
> +  isSeller: boolean;
You only use `isSeller` to pass it down to the `event-meeting-video` component.
So why don't you use `event.isOwner` directly in the `event-meeting-video` component ?

2020-10-16 12:25 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/container-video/container-video.component.ts
> +  //Input event meeting
useless comment

2020-10-16 12:25 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/container-video/container-video.component.ts
> +  //All Remote Participants in the room Twilio (all participant connected without local)
prefer ts-doc sytax `/** ... */`

2020-10-16 12:25 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/container-video/container-video.component.ts
> +  }
indentation

2020-10-16 12:25 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/container-video/container-video.component.ts
> +  }
why do you need to emit event to the parent, only to call the service ? could you not call the service directly in the `event-meeting-video` component ?

2020-10-16 12:25 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/participant/participant.abstract.ts
> +  detachTracks(tracks) {
type

2020-10-16 12:25 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/participant/participant.abstract.ts
> +  attachParticipantTracks(participant: Participant, container) {
type

2020-10-16 12:25 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/participant/participant.abstract.ts
> +  attachTracks(tracks, container) {
type

2020-10-16 12:25 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/participant/remote/remote.component.ts
> +  constructor(private renderer: Renderer2, private elm: ElementRef) {
`renderer` is unused

2020-10-16 12:25 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/video/video.component.ts
> +  @Input() isSeller: boolean;
delete this and use `event.isOwner` directly in the html

Don't resolve comment if they are not fixed, either discuss it or fix it, but don't do this, it's like you don't care of the review

![image](https://user-images.githubusercontent.com/5858657/96257825-5b4ce880-0fbb-11eb-85b0-362216bc6be7.png)

2020-10-16 12:46 UTC, OmarSebouai commented on libs/event/src/lib/components/meeting/+state/meeting.service.ts
> +  }
Indeed, after applying the change, we still had issues with this. I think we took this sample directly from the twilio demo. Will look further into it!

2020-10-16 14:45 UTC, OmarSebouai commented on libs/event/src/lib/components/meeting/+state/meeting.service.ts
> +  }
Hey PL, here is the documentation regarding this function from Mozilla: https://developer.mozilla.org/fr/docs/Web/API/MediaDevices/getUserMedia

We can replace it like that if you agree:
```
  async isAudioAvailable(): Promise<boolean> {
    try {
      await navigator.mediaDevices.getUserMedia({audio: true});
      return true;
    } catch (err) {
      return false;
    }
  }
```

2020-10-19 08:10 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/+state/meeting.service.ts
> +  }
Hey 👋 , this solution ☝️ looks perfect to me

2020-10-19 13:02 UTC, pldespaigne requested changes

2020-10-19 13:02 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/participant/remote/remote.component.ts
> +  @ViewChild('remoteVideo') containerRemoteVideo: ElementRef;
use an `*ngFor` in the template instead of this

2020-10-19 13:02 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/video/video.component.ts
> +  @Input() getTwilioParticipant: (uid: string) => Participant;
never pass functions as input

2020-10-22 12:48 UTC, OmarSebouai commented on libs/event/src/lib/components/meeting/+state/meeting.service.ts
> +        arrayOfLocalTrack.push(track.track);
We didn't understand this comment. Can we have more info?

2020-10-26 16:58 UTC, pldespaigne requested changes

2020-10-26 16:58 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/+state/meeting.service.ts
> +  localParticipant: IParticipantMeeting;
Right now this variable is not used (you set it's value in `roomJoined`, but you never use it afterward). So either you delete it, or you use it but in this case you can ensure that the local participant is not stored in `connectedParticipants$` this way you will not need to filter on it.

2020-10-26 16:58 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/+state/meeting.service.ts
> +  setUpRoomEvent(room: Room, event: Event): void {
- Question : Do you need the `room` param ? Could not use `this.activeRoom` ?
- You can also `import { EventEmitter } from 'events';` and then do `(this.activeRoom as EventEmitter).on`, this way the linter error is gone

2020-10-26 16:58 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/+state/meeting.service.ts
> +  deactivateLocalTracks(activeRoom: Room): void {
Could you also use `this.activeRoom` instead ?

2020-10-26 16:58 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/+state/meeting.service.ts
> +  removeParticipant(participant: IParticipantMeeting | Participant): void {
All you need as param is `identity: string`

2020-10-26 16:58 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/+state/meeting.service.ts
> +            })
Please use `async/await`, also I noticed that you always call `createIParticipantMeeting` just before `addParticipant`, so I think it's better to call `createIParticipantMeeting` from inside of `addParticipant`

2020-11-30 09:27 UTC, pldespaigne commented
Closing & Deleting : We are done implementing the core of the feature, we don't need this PR as example anymore

2020-11-30 09:27 UTC, closed without merging