Issue debug movie form
blockframes/blockframes pull request #3998
Opened 2020-10-19 14:00 UTC by fritzschoff

2020-10-20 10:30 UTC, GrandSchtroumpf requested changes

2020-10-20 10:30 UTC, GrandSchtroumpf commented on libs/organization/campaign/src/lib/form/proposal/proposal.component.html
> +      <!-- Received -->
On the design the current amount is first: 
https://www.figma.com/file/x1s9SZZT2mts6kmBuIk9uU/MVP-Media-Financiers?node-id=1204%3A1144

2020-10-20 10:30 UTC, GrandSchtroumpf commented on libs/ui/src/lib/static-autocomplete/input/input-autocomplete.component.ts
>      this.displayFn = (name: string) => {
you can do it on one line

2020-10-20 10:30 UTC, GrandSchtroumpf commented on libs/ui/src/lib/tunnel/layout/layout.component.ts
> +  const currentIndex = allPath.map((route, i) => route.path === currentPath ? i : undefined).filter(i => !!i);
Do `const index = allPath.findIndex(route => route.path === currentPath)`

2020-10-20 10:30 UTC, GrandSchtroumpf commented on libs/ui/src/lib/tunnel/layout/layout.component.ts
> +  const allSections = steps.map(({ routes }) => routes);
Ideally we would have a getter `canDisplay()` that would check the current value of the move form
```typescript
const routes = steps.map(s => s.routes)
  .flat()
  .filter(route => route.canDisplay());
const index = routes.findIndex(r => r.path === currentPath);
if (index >= 0) {
  return routes[index + arithmeticOperator];
}
```
You can also do it with : 
```typescript
const Promise.all(routes.map(r => r.shouldDisplay.pipe(take(1)).toPromise().then(canDisplay => canDisplay ? r : undefined)));
```
But it's really ugly.
I think updating the steps would be cleaner

2020-10-20 11:49 UTC, fritzschoff commented on libs/organization/campaign/src/lib/form/proposal/proposal.component.html
> +      <!-- Received -->
I know, but the error message you get when you type something in the first input, it doesn't make sense cause you didn't specified the other input yet

2020-10-20 14:42 UTC, fritzschoff commented on libs/movie/src/lib/movie/form/shell/shell.component.ts
> +      routes: step.routes.filter((route: RouteDescription) => (!(route?.shouldDisplay) || !route.shouldDisplay))
```
This expression is not callable.
  Each member of the union type '{ <S extends RouteDescription>(predicate: (value: RouteDescription, index: number, array: RouteDescription[]) => value is S, thisArg?: any): S[]; (predicate: (value: RouteDescription, index: number, array: RouteDescription[]) => unknown, thisArg?: any): RouteDescription[]; } | { ...; }' has signatures, but none of those signatures are compatible with each other.ts(2349)
```

2020-10-20 14:42 UTC, fritzschoff commented on libs/movie/src/lib/movie/form/shell/shell.component.ts
> +      routes: step.routes.filter((route: RouteDescription) => (!(route?.shouldDisplay) || !route.shouldDisplay))
any idea? Otherwise I need to add shouldDisplay to every route?

2020-10-20 14:56 UTC, GrandSchtroumpf commented on libs/organization/campaign/src/lib/form/proposal/proposal.component.html
> +      <!-- Received -->
ok ok

2020-10-21 08:08 UTC, GrandSchtroumpf approved these changes

2020-10-21 08:08 UTC, GrandSchtroumpf commented on libs/ui/src/lib/tunnel/layout/layout.component.ts
> +    return filteredPath?.path ? filteredPath.path : false;
Put back the previous code, it was working I think: 
```typescript
const allRoutes = steps.map(({ routes }) => routes.map(r => r.path));
const allPath = allRoutes.flat();
const current = parseUrlWithoutFragment(url);
const index = allPath.indexOf(current);
if (index >= 0) {
  return allPath[index + arithmeticOperator];
}
```

2020-10-21 08:14 UTC, fritzschoff commented on libs/ui/src/lib/tunnel/layout/layout.component.ts
> +    return filteredPath?.path ? filteredPath.path : false;
check the template, that code won't work anymore!

2020-10-21 08:21 UTC, GrandSchtroumpf commented on libs/ui/src/lib/tunnel/layout/layout.component.ts
> +    return filteredPath?.path ? filteredPath.path : false;
I'm sorry I don't see the difference with what you've got already, except the "false" : 
```typescript
const allRoutes = steps.map(({ routes }) => routes.map(r => r.path));
const allPath = allRoutes.flat();
const current = parseUrlWithoutFragment(url);
const index = allPath.indexOf(current);
if (index >= 0) {
  return allPath[index + arithmeticOperator] ?? false;
}
```

2020-10-21 09:11 UTC, merged