Move Budget from movie to campaign
blockframes/blockframes pull request #4022
Opened 2020-10-21 14:12 UTC by GrandSchtroumpf

- Create budget on campaign
- Remove "totalBudget" from movie
- Update current dashboard
- Update summary

2020-10-21 14:24 UTC, fritzschoff requested changes

2020-10-21 14:24 UTC, fritzschoff commented on libs/organization/campaign/src/lib/form/summary/profits/profits.component.ts
> -  constructor() { }
as you promised. GJ

2020-10-21 14:24 UTC, fritzschoff commented on libs/organization/campaign/src/lib/+state/campaign.model.ts
> +  estimatedBudget?: string;
it changed to a number! 
![image](https://user-images.githubusercontent.com/39312833/96732472-a6e70400-13b8-11eb-8717-3bd639dba8dc.png)

2020-10-21 14:24 UTC, fritzschoff commented on libs/organization/campaign/src/lib/dashboard/financing/financing.component.ts
> +  styleUrls: ['./financing.component.scss']
on pushy push pls

2020-10-21 14:24 UTC, fritzschoff commented on libs/organization/campaign/src/lib/form/budget/budget.component.html
> +      <!-- TODO 3788 update hint, error, etc -->
This issue is removed on github. remove it here as well !

2020-10-21 14:24 UTC, fritzschoff commented on libs/organization/campaign/src/lib/form/budget/budget.component.html
> +        <input matInput type="number" [formControl]="budget.get('producerFees')" placeholder="" />
`placeholder=""` what are you achieving with that?

2020-10-21 14:24 UTC, fritzschoff commented on libs/organization/campaign/src/lib/form/budget/budget.component.html
> +          {{ budget.value | budget | currency: budget.get('currency').value || 'USD' }}
since pipes are pure by default, are you sure you don't want to use the valueChanges observable?

2020-10-21 14:24 UTC, fritzschoff commented on libs/organization/campaign/src/lib/form/form.ts
> +    estimatedBudget: new HostedMediaForm(campaign.estimatedBudget),
I thought you moved totalBudget and not estimatedBudget? and also why do you put estimatedBudget in a hostedMediaForm? You want to upload numbers to our storage?

2020-10-21 14:24 UTC, fritzschoff commented on libs/organization/campaign/src/lib/form/profits/profits.component.scss
> +  border-top-width: 2px;
why is this mat-divider different then the other ones ?

2020-10-21 14:25 UTC, GrandSchtroumpf commented on libs/organization/campaign/src/lib/+state/campaign.model.ts
> +  estimatedBudget?: string;
I should find a better name I guess. It's a PDF that you upload.

2020-10-21 14:26 UTC, GrandSchtroumpf commented on libs/organization/campaign/src/lib/form/budget/budget.component.html
> +        <input matInput type="number" [formControl]="budget.get('producerFees')" placeholder="" />
I'm achieving a copy pasting ;)

2020-10-21 14:28 UTC, GrandSchtroumpf commented on libs/organization/campaign/src/lib/form/budget/budget.component.html
> +          {{ budget.value | budget | currency: budget.get('currency').value || 'USD' }}
In this case it works because it's only mat-form-field inputs that trigger markForCheck at each change. So .value it updated.

2020-10-21 14:29 UTC, GrandSchtroumpf commented on libs/organization/campaign/src/lib/form/profits/profits.component.scss
> +  border-top-width: 2px;
It's not. It's like that in several pages from the tunnel. I'll work on the design review next week.

2020-10-22 07:54 UTC, fritzschoff approved these changes

2020-10-22 07:54 UTC, merged