update file selector
blockframes/blockframes pull request #4069
Opened 2020-10-23 15:15 UTC by pldespaigne

fix #3947

2020-10-27 13:02 UTC, fritzschoff requested changes

2020-10-27 13:02 UTC, fritzschoff commented on libs/utils/src/lib/pipes/fileName.pipe.ts
> +      return 'unknown';
above you returned an empty string and here 'unknown'. Maybe make it consistent, if there is no specific case to be handled?

2020-10-27 13:34 UTC, GrandSchtroumpf requested changes

2020-10-27 13:34 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/dashboard/event/edit/edit.component.html
> +              Manage Files
wrap with a span

2020-10-27 13:34 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/dashboard/event/edit/edit.component.html
> +          <ng-container *ngIf="files.value.length > 0; else noFiles">
do `ngIf="files.value.length else empty"`

2020-10-27 13:34 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/dashboard/event/edit/edit.component.html
> +                {{file | filePath: ' > ' | async}}
use span

2020-10-27 13:34 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/dashboard/event/edit/edit.component.scss
> +  mat-divider {
If you really need that, I think you've got a design issue

2020-10-27 13:34 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/dashboard/event/edit/edit.component.scss
> +        min-width: 28px;
Don't change the size of the icon. mat-list has predefined style for it, keep it.

2020-10-27 13:34 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/file-selector/file-selector.component.html
> +        <ng-container *ngIf="orgFiles.length > 0; else noOrgFiles">
same as about, let's keep it consistent `ngIf="orgFiles.length else empty"`

2020-10-27 13:34 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/file-selector/file-selector.component.html
> +            <div fxLayout="row" fxLayoutAlign="space-between center">
use predefined style from angular material :
```html
<mat-list-item *ngFor="let file of orgFiles">
  <mat-icon mat-list-icon [svgIcon]="file | fileTypeImage : 'icon'"></mat-icon>
  <div mat-line>{{file | fileName}}</div>
   <button mat-icon-button (click)="toggleSelection()" >...</button>
</mat-list-item>
```

2020-10-27 13:34 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/file-selector/file-selector.component.html
> +          {{movie.title.international}} ({{moviesFiles[movie.id].length}} files)
use span

2020-10-27 13:34 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/file-selector/file-selector.component.html
> +            <mat-list-item *ngFor="let file of moviesFiles[movie.id]">
same as above

2020-10-27 13:34 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/file-selector/file-selector.component.html
> +        <mat-list>
Maybe you can make it lazy rendered : 
https://material.angular.io/components/expansion/overview#lazy-rendering

2020-10-27 13:34 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/file-selector/file-selector.component.html
> +          <ng-container *ngIf="moviesFiles[movie.id].length > 0; else noMovieFiles">
Same as above

2020-10-27 13:34 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/file-selector/file-selector.component.html
> +      <mat-list-item *ngFor="let file of selectedFiles">
Same as above

2020-10-27 13:34 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/file-selector/file-selector.component.scss
> +  height: 60vh;
Don't use vh here. There is no reason for that.

2020-10-27 13:34 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/file-selector/file-selector.component.scss
> +      mat-icon {
Same here. Using span will do the right margin. Also, always use multiple of 8.

2020-10-27 13:34 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/file-selector/file-selector.component.scss
> +  border-left: solid 1px var(--borderGrey);
use `var(--foreground-divider)` instead

2020-10-27 13:34 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/file-selector/file-selector.component.scss
> +  padding: 0 0 0 12px;
As above use multiple of 8px. Also specify : 
```scss
padding-bottom: 16px;
```

2020-10-27 13:34 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/file-selector/file-selector.component.scss
> +    overflow-y: auto;
You shouldn't need that, you're hiding dust under the carpet.

2020-10-27 13:34 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/file-selector/file-selector.component.scss
> +        mat-icon {
don't override mat-icon style

2020-10-27 13:34 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/file-selector/file-selector.component.ts
> +  escapeHandler = (event: KeyboardEvent) => {
methods should be after constructor. Any reason not to define it as a method ?

2020-10-27 13:34 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/file-selector/file-selector.component.ts
> +  unSelect(file: string) {
create a `toggleSelection` instead.

2020-10-27 13:34 UTC, GrandSchtroumpf commented on libs/utils/src/lib/pipes/fileName.pipe.ts
> +@Pipe({
one line

2020-10-27 13:34 UTC, GrandSchtroumpf commented on libs/utils/src/lib/pipes/fileName.pipe.ts
> +@Pipe({
Is it a pure pipe (no side effect) ? output will not change if input is the same ?

2020-10-27 13:34 UTC, GrandSchtroumpf commented on libs/utils/src/lib/pipes/fileName.pipe.ts
> +    return `${collection}${separator}${docName}${separator}${folder}${separator}${fileName}`;
do `[collection, docName, folder, fileName].join(separator)`

2020-10-27 13:34 UTC, GrandSchtroumpf commented on libs/utils/src/lib/pipes/fileName.pipe.ts
> +      docName = org?.denomination?.public ?? 'Unknown Organization';
Looks like it'll create issues with the result.

2020-10-27 13:42 UTC, pldespaigne commented on libs/media/src/lib/components/file-selector/file-selector.component.html
> +              <ng-container *ngIf="isSelected(file); else notSelected">
I was first thinking about doing it with a boolean as you said, but this come at the cost of code complexity and readability for almost no perf gain because `selectedFiles` is a string array that will never be bigger than ~100 items.

I decided to favor code readability/complexity but I can change that if you want, what do you think ?

2020-10-27 15:18 UTC, pldespaigne commented on apps/festival/festival/src/app/dashboard/event/edit/edit.component.scss
> +  mat-divider {
We got a design issue, here is what happen if I remove `position: static`
![image](https://user-images.githubusercontent.com/5858657/97322339-fcffef80-186f-11eb-98b6-ac6cfa18b23f.png)

2020-10-27 15:33 UTC, pldespaigne commented on libs/media/src/lib/components/file-selector/file-selector.component.html
> +        <mat-list>
I might be wrong, but I don't think it's useful since every calculation are already done.

2020-10-27 15:38 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/file-selector/file-selector.component.html
> +        <mat-list>
Depends on how heavy is the rendering (the most expansive part in the frontend). You judge.

2020-10-27 15:46 UTC, pldespaigne commented on libs/utils/src/lib/pipes/fileName.pipe.ts
> +      docName = org?.denomination?.public ?? 'Unknown Organization';
I didn't understand, I did this to always have a result without error for the user.

2020-10-27 15:57 UTC, pldespaigne commented on libs/utils/src/lib/pipes/fileName.pipe.ts
> +@Pipe({
pure as an angel

2020-10-28 08:49 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/dashboard/event/edit/edit.component.scss
> +  mat-divider {
It's because you're in a mat-card. If you fight against the card design, don't use it.
Use a simple article with a 
```scss
background-color: var(--background-card);
border-radius: 4px;
```

2020-10-28 08:49 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/file-selector/file-selector.component.html
> +<div fxLayout="row" class="container">
rename section

2020-10-28 08:49 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/file-selector/file-selector.component.html
> +<section fxLayout="row">
Maybe I'm wrong but it looks more like a header than a section to me.

2020-10-28 08:49 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/file-selector/file-selector.component.scss
> +  width: 100%;
display:block is already width 100%. Remove unnecessary css

2020-10-28 08:49 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/file-selector/file-selector.component.html
> +  <div class="selected" fxLayout="column" fxLayoutAlign="space-between">
Maybe rename it "aside"

2020-10-28 08:49 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/file-selector/file-selector.component.scss
> +      height: 90%;
Why 90% ? If this is 100% - header then you can do for example : 
```typescript
header {
  height: 40px;
}
section {
  height: calc(100% - 40px);
  mat-tab-group {
    width: 60%;
  }
  aside {
    width: 40%;
  }
}
```
Or 
```scss
:host {
  display: flex;
  flex-direction: column;
}
section {
  flex: 1;
  mat-tab-group {
    width: 60%;
  }
  aside {
    width: 40%;
  }
}
```

2020-10-28 09:51 UTC, GrandSchtroumpf approved these changes

2020-10-28 09:53 UTC, fritzschoff approved these changes

2020-10-28 09:53 UTC, merged