video player now takes in reference as argument
blockframes/blockframes pull request #4131
Opened 2020-11-03 10:17 UTC by RemcoSimonides

Video player now takes in a file reference instead of an eventId. Making it possible to use the media-player component for a video file in any component instead of event only

- [ ] update screening events in migration

2020-11-03 10:23 UTC, RemcoSimonides commented on apps/backend-functions/src/player.ts
> +        if (event.isPrivate && !await isUserInvitedToEvent(uid, event.meta.titleId)) {
I added `await` in front of `isUserInvitedToEvent` because it returns a Promise. I didn't think not awaiting would work but maybe I am wrong?

2020-11-03 15:38 UTC, pldespaigne commented on apps/backend-functions/src/player.ts
> +        if (event.isPrivate && !await isUserInvitedToEvent(uid, event.meta.titleId)) {
100% correct

2020-11-03 15:48 UTC, pldespaigne requested changes

2020-11-03 15:48 UTC, pldespaigne commented on apps/backend-functions/src/player.ts
> +              return unauthorized;
If the user is not invited to the meeting, either he is an org member and we already authorized him at the beginning or he is not an org member and we should return "unauthorized".

But here the check for `case: 'orgs'` & `case: 'movies'` will never be executed

2020-11-04 09:11 UTC, pldespaigne approved these changes

2020-11-04 09:40 UTC, pldespaigne commented on apps/backend-functions/src/player.ts
> +  if (!access && security === 'protected') {
those two condition are the same now

2020-11-04 10:02 UTC, merged