Runningtime data
blockframes/blockframes pull request #4202
Opened 2020-11-10 08:29 UTC by Mussuranae

Rework running time to set time as a number only

2020-11-10 10:02 UTC, GrandSchtroumpf requested changes

2020-11-10 10:02 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/pipes/running-time.pipe.ts
> +    return (typeof value === 'number') ? `${value} min` : '';
This should deal with the whole runningTime. Also extract it in a function to be reusable : 
```typesript
function formatRunningTime(value: MovieRunningTime) {
  if (value.time && value.status) return ...;
  if (value.time && !value.status) return ...;
  if (!value.time && value.status) return ...;
  return '';
}
....
transform(value: MovieRunningTime): string {
  return formatRunningTime(value);
}
```

2020-11-10 11:19 UTC, Mussuranae commented on libs/movie/src/lib/movie/pipes/running-time.pipe.ts
> +    return (typeof value === 'number') ? `${value} min` : '';
I can't display the status because the design is a little different depending on which platform the user is (marketplace or dashboard)

2020-11-10 13:12 UTC, GrandSchtroumpf requested changes

2020-11-10 13:12 UTC, GrandSchtroumpf commented on libs/firebase-utils/src/lib/firestoreMigrations/0041.ts
> +  } else delete runningTime.time;
Add a new line

2020-11-10 13:12 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/marketplace/main/main.component.html
> +          <ng-container *ngIf="movie.runningTime.time">)</ng-container>
No, I don't want to see that again.

2020-11-12 15:02 UTC, Mussuranae commented on libs/movie/src/lib/movie/+state/movie.model.ts
>      status: '',
'' is the default value, there is no mandatory status for the moment, it if on discussion (or at least Anastasiia think about it).

2020-11-12 15:10 UTC, GrandSchtroumpf approved these changes

2020-11-12 15:10 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/pipes/running-time.pipe.ts
> +export function formatRunningTime(runningTime?: MovieRunningTime, isStatusNeeded: boolean = true) {
```typescript
export function formatRunningTime(runningTime?: MovieRunningTime, showStatus: boolean = true) {
  if (!runningTime) return '';
  const { time, status } = runningTime;
  if (showStatus) {
    if (time && status) return `${time} min (${screeningStatus[status]})`;
    if (!status) return `${time} min`;
    if (!time) return screeningStatus[status];
  }
  if (time) {
    return status === "estimated" ? `≈ ${time} min` : `${time} min`;
  }
}
```

2020-11-12 15:10 UTC, GrandSchtroumpf commented on libs/ui/src/lib/marketplace/pages/wishlist/wishlist.component.html
> +          <span>{{ element.runningTime.time | getRunningTime }}</span>
Remove .time : `<span>{{ element.runningTime | getRunningTime }}</span>`

2020-11-12 15:45 UTC, merged