Fix bugs in video upload
blockframes/blockframes pull request #4213
Opened 2020-11-10 16:23 UTC by RemcoSimonides

- [x] Remove UI issue with file-upload
- [x] Delete reference from db in case an upload fails
- [ ] Delete reference from db from array (still photo / otherVideos) - not sure which reference to delete

2020-11-10 16:24 UTC, RemcoSimonides commented on libs/media/src/lib/components/upload/widget/upload-widget.component.ts
> +    } else {
Read comment - describes an issue I have with array (still photos / otherVideos)

2020-11-10 16:26 UTC, RemcoSimonides commented on libs/media/src/lib/components/upload/widget/upload-widget.component.ts
> +  @HostListener('window:beforeunload', [ '$event' ])
Is this allowed? Function gets called when the page is destroyed and it does work.

I am afraid ngOnDestroy won't be called for this component since it stays open as long as there are tasks; and there will always be tasks if paused/cancelled. Only when the tasks are removed, the component closes. Deleting reference is therefore also called on `removeTask()` function

2020-11-11 09:52 UTC, phpgeekfr commented on libs/media/src/lib/components/upload/widget/upload-widget.component.ts
> +    const currentMediaValue = getDeepValue(docData, fieldToUpdate);
I think that you can use `getDocAndPath` method here

2020-11-11 09:52 UTC, phpgeekfr commented on libs/media/src/lib/components/upload/widget/upload-widget.component.ts
> +  @HostListener('window:beforeunload', [ '$event' ])
I'm not the good person to answer this. @GrandSchtroumpf  ?

2020-11-11 09:52 UTC, phpgeekfr commented on libs/media/src/lib/components/upload/widget/upload-widget.component.ts
> +      if (state === 'paused' || state === 'canceled') {
we remove ref if state is paused ? What happens if I un-pause ?

2020-11-11 09:52 UTC, phpgeekfr commented on libs/media/src/lib/components/upload/widget/upload-widget.component.ts
> +    } else {
For this, I think we can say that we will not use same ref for different video ( I guess).
Here is how it's done in `apps/backend-functions/src/media.ts`

```
    if (Array.isArray(savedRef)) {
      savedRef = savedRef.map(e => e.ref || e).find(ref => ref === filePath) || '';
    } else if (!!savedRef.ref) {
      savedRef = savedRef.ref;
    }
```

2020-11-11 10:15 UTC, pldespaigne commented on libs/media/src/lib/components/upload/widget/upload-widget.component.ts
> +  @HostListener('window:beforeunload', [ '$event' ])
SGTM, from what I recall we are using similar `beforeunload` elsewhere in the code

2020-11-11 10:15 UTC, pldespaigne commented on libs/media/src/lib/components/upload/widget/upload-widget.component.ts
> +      if (state === 'paused' || state === 'canceled') {
I think it's ok because if you have paused upload when you leave the page (`beforeunload`) those will never complete and so we should clean them from the db

2020-11-11 10:19 UTC, RemcoSimonides commented on libs/media/src/lib/+state/media.service.ts
> +      instance.injector = Injector.create({ providers: [{ provide: 'tasks', useValue: this._tasks }, { provide: 'db', useValue: this.db }] });
Doing that gave an error. This solved it.

2020-11-11 10:20 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/upload/widget/upload-widget.component.ts
> +  @HostListener('window:beforeunload', [ '$event' ])
If the page reload you shouldn't care about anything, the browser will kill every process for you.

2020-11-11 10:20 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/upload/widget/upload-widget.component.ts
> +    const filePathElements = path.split('/');
You'll need to create a function to get the segments:
```typescript
function storageSegment(path: string) {
  const segments = path.split('/');
  const tmp = segments.shift();
  const privacy = segments.shift();
  const filename = segments.pop();
  const field = segments.pop();
  const docPath = segment;
  return { tmp, privacy, docPath, field, filename };
}
```

2020-11-11 10:22 UTC, RemcoSimonides commented on libs/media/src/lib/components/upload/widget/upload-widget.component.ts
> +  @HostListener('window:beforeunload', [ '$event' ])
We don't
![image](https://user-images.githubusercontent.com/27687382/98799985-18423180-2410-11eb-9baf-296e81115a1f.png)

2020-11-11 10:24 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/upload/widget/upload-widget.component.ts
> +  @HostListener('window:beforeunload', [ '$event' ])
For me you should either use `beforeunload` to tell the user that the uploads are not done and if he close the page they will break. Else you can remove this code.

2020-11-11 10:28 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/media-videos/media-videos.component.html
>          filePrivacy="public">
Isn't it "public" the default ?

2020-11-12 09:25 UTC, RemcoSimonides commented on libs/media/src/lib/components/upload/widget/upload-widget.component.ts
> +    const filePathElements = path.split('/');
This function was similar as getDocAndPath. I've merged the two functions into one; the older one (which was only for back-end) also throws errors if the path is invalid.

2020-11-12 09:30 UTC, RemcoSimonides commented on libs/utils/src/lib/pipes/deep-key.pipe.ts
> +export const getDeepValue = (object: Object, path: string) => path.split('.').reduce((result, key) => result?.[key], object);
This pipe now also exports the main function (as it was in the `value-by-path.pipe.ts`. I could also move this function to `utils/helper.ts` for example?

2020-11-12 10:36 UTC, GrandSchtroumpf commented on libs/utils/src/lib/file-sanitizer.ts
> +  const collection = filePathElements.shift();
This only works if you're in a collection, not sub-collection

2020-11-12 10:36 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/upload/widget/upload-widget.component.ts
> +    const docSnapshot = await this.db.collection(collection).doc(docId).get().toPromise();
```typescript
const { docPath, field } = dissectFilePath(path);
const snapshot = await this.db.doc(docPath).get().toPromise();
```

2020-11-12 10:36 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/upload/widget/upload-widget.component.ts
> +    const currentMediaValue = getDeepValue(docData, fieldToUpdate);
name it `const media = getDeepValue(docData, fieldToUpdate);` and type it.

2020-11-12 10:56 UTC, GrandSchtroumpf requested changes

2020-11-12 10:56 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/upload/widget/upload-widget.component.ts
> +    if (Array.isArray(currentMediaValue)) {
```typescript
if (Array.isArray(media)) {
  const update = media.filter(ref => typeof ref === 'string' ? ref !== path : ref.ref !== path);
  return snapshot.update({ [field]: update });
} else {
  return snapshot.update({ [field]: null });
}
```

2020-11-12 10:56 UTC, GrandSchtroumpf commented on libs/media/src/lib/components/upload/widget/upload-widget.component.ts
> +    if (Array.isArray(currentMediaValue)) {
OR : `snapshot.get(field).update(null)`
https://firebase.google.com/docs/reference/js/firebase.firestore.FieldValue

2020-11-12 10:56 UTC, GrandSchtroumpf commented on libs/utils/src/lib/file-sanitizer.ts
> +    filePath = filePathElements.join('/');
remove it

2020-11-12 10:56 UTC, GrandSchtroumpf commented on libs/utils/src/lib/file-sanitizer.ts
> +  let isInTmpDir = false;
```typescript
const isTmp = segments[0] === 'tmp';
if (isTmp) segment.shift();
```

2020-11-12 10:56 UTC, GrandSchtroumpf commented on libs/utils/src/lib/file-sanitizer.ts
> +  let security: string;
```typescript
const privacy = segments.shift();
```

2020-11-12 10:56 UTC, GrandSchtroumpf commented on libs/utils/src/lib/file-sanitizer.ts
> +  if (!docId || !collection) {
```typescript
if (docPath.split('/').length % 2 !== 0) {
  throw new Error(`Doc path "${docPath}" is not a document.`);
}
```

2020-11-12 13:26 UTC, RemcoSimonides commented on libs/media/src/lib/components/upload/widget/upload-widget.component.ts
> +    if (Array.isArray(currentMediaValue)) {
`snapshot.get()` returns the data of the field. It's not possible to call update on the data.

2020-11-12 15:49 UTC, RemcoSimonides commented on libs/utils/src/lib/file-sanitizer.ts
> +  const collection = filePathElements.shift();
This isn't going to work because `field` is sometimes separated by a `/`. For example this path: `/public/movies/36JVeZckRc4c8rJim78J/promotional.videos/screener/abc.mp4`

It would be better to have `/promotional.videos.screener/` instead of `/promotional.videos/screener/` and be able to support subcollections; but in order to fix that we need to write a migration etc..

2020-11-13 10:20 UTC, RemcoSimonides commented on libs/media/src/lib/components/upload/widget/upload-widget.component.ts
> +    if (Array.isArray(currentMediaValue)) {
`media.filter()` isn't callable because the types weren't matching. `media.findIndex()` does work.

2020-11-13 10:23 UTC, RemcoSimonides commented on libs/media/src/lib/components/upload/widget/upload-widget.component.ts
> +      // Chose to only update the reference field and not the whole object to not lose potential useful data (e.g. jwPlayerId)
Hee @pldespaigne , Should we remove the whole media object if an upload fails, or should I only empty the ref?

2020-11-13 10:31 UTC, RemcoSimonides commented on libs/utils/src/lib/file-sanitizer.ts
> +  if (!docId || !collection) {
docPath isn't going to work because `field` is sometimes separated by a `/`. For example this path: `/public/movies/36JVeZckRc4c8rJim78J/promotional.videos/screener/abc.mp4`

It would be better to have `/promotional.videos.screener/` instead of `/promotional.videos/screener/` and be able to support subcollections; but in order to fix that we need to write a migration etc.. (noted in issue #4241)

2020-11-13 10:53 UTC, GrandSchtroumpf approved these changes

2020-11-16 08:42 UTC, pldespaigne commented on libs/media/src/lib/components/upload/widget/upload-widget.component.ts
> +      // Chose to only update the reference field and not the whole object to not lose potential useful data (e.g. jwPlayerId)
Looks like a UX question but I would say no since you don't want your 3 paragraphs description to be deleted because of a bad connection ^^

2020-11-16 09:11 UTC, merged