UT(security-rules): Add read test for Movies collection (WIP)
blockframes/blockframes pull request #4231
Opened 2020-11-11 14:58 UTC by xmano

Fix #4199 

Need a way to do multiple auth. Researching about this.

2020-11-11 15:13 UTC, xmano commented
Refactoring to multiple describe block for different auth user and trying it.

2020-11-19 06:05 UTC, xmano commented
@phpgeekfr : in the below function, shouldn't the condition be testing inequality with existing data?

```
    function isNotUpdatingField(fieldArray) {
			return ( !incomingData()[fieldArray[0]][fieldArray[1]].keys().hasAll([fieldArray[2]]) ||  incomingData()[fieldArray[0]][fieldArray[1]][fieldArray[2]] == existingData()[fieldArray[0]][fieldArray[1]][fieldArray[2]] )
        || ( !incomingData()[fieldArray[0]].keys().hasAll([fieldArray[1]]) ||  incomingData()[fieldArray[0]][fieldArray[1]] == existingData()[fieldArray[0]][fieldArray[1]] )
        || ( !incomingData().keys().hasAll([fieldArray[0]]) ||  incomingData()[fieldArray[0]] == existingData()[fieldArray[0]] );
    }
```

2020-11-19 12:01 UTC, phpgeekfr requested changes

2020-11-19 12:01 UTC, phpgeekfr commented on apps/backend-ops/src/firestore-rules.spec.ts
> +    db  = await initFirestoreApp(projectId, 'firestore.rules', testFixture, {uid: 'uid-super-admin'});
change this naming `uid-super-admin` because it refers to superAdmin at org level.

"true" super admins are blockframes admins

2020-11-19 12:01 UTC, phpgeekfr commented on firestore.rules
clean this file please

2020-11-19 12:01 UTC, phpgeekfr commented on apps/backend-ops/src/firestore-rules.spec.ts
> +describe.only('Blockframe Super Admin', () => {
Blockframe Super Admin => Blockframe  Admin

2020-11-19 12:05 UTC, xmano commented on apps/backend-ops/src/firestore-rules.spec.ts
> +  test("In maintenance, super admin should be able to read MAINTENANCE doc", async () => {
Yes true.. will correct the test. No relation to maintenance.

2020-11-19 12:08 UTC, xmano commented on firestore.rules
Yes done.

2020-11-19 12:11 UTC, phpgeekfr commented on apps/backend-ops/src/firestore-rules.spec.ts
> +    https://stackoverflow.com/questions/56800074/jest-each-name-access-object-key
remove this

2020-11-19 12:11 UTC, phpgeekfr commented on apps/backend-ops/src/firestore-rules.spec.ts
> +    */
clean unused comments

2020-11-19 12:11 UTC, phpgeekfr commented on apps/backend-ops/src/firestore-rules.spec.ts
> +    const draftMovieTitle = 'MI-0d7';
it should be draftMovieId

2020-11-19 12:14 UTC, xmano commented on apps/backend-ops/src/firestore-rules.spec.ts
> +    https://stackoverflow.com/questions/56800074/jest-each-name-access-object-key
ok

2020-11-19 12:15 UTC, xmano commented on apps/backend-ops/src/firestore-rules.spec.ts
> +    */
ok

2020-11-19 12:40 UTC, xmano commented on apps/backend-ops/src/firestore-rules.spec.ts
> +  test("In maintenance, even super admin shouldn't be able to read all users", async () => {
ok correct the naming to have bfAdmin as top most for the app

2020-11-20 02:15 UTC, xmano commented on apps/backend-ops/src/firestore-rules.spec.ts
> +  test("In maintenance, even super admin shouldn't be able to read admin user", async () => {
This test block is for blockframe admin. I have also added test for Org Admin and they can read user collection.

2020-11-20 02:16 UTC, xmano commented on apps/backend-ops/src/firestore-rules.spec.ts
> +    db  = await initFirestoreApp(projectId, 'firestore.rules', testFixture, {uid: 'uid-super-admin'});
uid-bfAdmin : App super admin
uid-sAdmin :  Org super admin
uid-admin: org admin
uid-xxx :  other users

2020-11-20 02:17 UTC, xmano commented on apps/backend-ops/src/firestore-rules.spec.ts
> +describe.only('Blockframe Super Admin', () => {
Using uid-bfAdmin as block frame admin for the tests.

2020-11-20 02:22 UTC, xmano commented on apps/backend-ops/src/firestore-rules.spec.ts
> +    const draftMovieTitle = 'MI-0d7';
Usind Id suffix for var names

2020-11-20 02:24 UTC, xmano commented
Requesting review:

![image](https://user-images.githubusercontent.com/8731418/99749990-91731000-2b05-11eb-9e04-9cb5303f2246.png)

2020-11-20 07:43 UTC, xmano commented
Only 1 failure which I need to debug:

![image](https://user-images.githubusercontent.com/8731418/99773244-2be94880-2b32-11eb-9df4-9cf99117d50a.png)

2020-11-20 09:45 UTC, phpgeekfr commented on apps/backend-ops/src/firestore-rules.spec.ts
> +    testFixture["_META/_MAINTENANCE"].endedAt = null;
here you should use startMaintenance(db)

2020-11-20 09:45 UTC, phpgeekfr commented on apps/backend-ops/src/firestore-rules.spec.ts
> +    testFixture["_META/_MAINTENANCE"].endedAt = true;
here you should use endMaintenance(db)

2020-11-20 09:45 UTC, phpgeekfr commented on apps/backend-ops/src/firestore-rules.spec.ts
> +    const maintRef = db.doc("_META/_MAINTENANCE");
you should export and use `maintenanceRef` in libs/firebase-utils/src/lib/maintenance.ts

2020-11-20 09:45 UTC, phpgeekfr commented on apps/backend-ops/src/firestore-rules.spec.ts
> +    const adminRef = db.doc("blockframesAdmin/uid-sAdmin");
this line is not correct, there should be only blockframesAdmin ids  in `blockframesAdmin` collection.

2020-11-20 09:45 UTC, phpgeekfr commented on apps/backend-ops/src/firestore-rules.spec.ts
> +    const adminRef = db.doc("blockframesAdmin/uid-sAdmin");
same, should be bf-admin

2020-11-20 12:57 UTC, xmano commented on apps/backend-ops/src/firestore-rules.spec.ts
> +    const adminRef = db.doc("blockframesAdmin/uid-sAdmin");
corrected.

2020-11-20 12:58 UTC, xmano commented on apps/backend-ops/src/firestore-rules.spec.ts
> +    const adminRef = db.doc("blockframesAdmin/uid-sAdmin");
good catch. corrected.

2020-11-20 14:12 UTC, xmano commented on apps/backend-ops/src/firestore-rules.spec.ts
> +    testFixture["_META/_MAINTENANCE"].endedAt = null;
Using imports from @blockframes/utils/maintenance to access this. Also we are testing security rules so we need to minimize other interactions.

2020-11-20 14:12 UTC, xmano commented on apps/backend-ops/src/firestore-rules.spec.ts
> +    testFixture["_META/_MAINTENANCE"].endedAt = true;
as above.. Using imports from @blockframes/utils/maintenance to access this.

2020-11-20 14:13 UTC, xmano commented on apps/backend-ops/src/firestore-rules.spec.ts
> +    const maintRef = db.doc("_META/_MAINTENANCE");
as above.

2020-11-20 15:34 UTC, phpgeekfr approved these changes

2020-11-20 15:34 UTC, phpgeekfr commented on apps/backend-ops/src/firestore-rules.spec.ts
> +    const maintRef = db.doc("_META/_MAINTENANCE");
can you use ${META_COLLECTION_NAME}/${MAINTENANCE_DOCUMENT_NAME} ?

2020-11-20 15:47 UTC, xmano commented on apps/backend-ops/src/firestore-rules.spec.ts
> +    const maintRef = db.doc("_META/_MAINTENANCE");
used metaDoc const

2020-11-20 15:53 UTC, merged