preview component
blockframes/blockframes pull request #4232
Opened 2020-11-11 15:33 UTC by pldespaigne

- minimal twilio service
- video component
- lobby preview

2020-11-11 15:56 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/event/lobby/lobby.component.html
> +      <span matTooltip="Your browser don't have the permission to access the camera">
Put the tooltip on the button directly.

2020-11-11 15:56 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/event/lobby/lobby.component.html
> +      <span matTooltip="Your browser don't have the permission to access the microphone">
Same here.

2020-11-11 15:56 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/event/lobby/lobby.component.ts
> +      audioTrack?.disable();
Why do you disable it ?

2020-11-11 16:13 UTC, GrandSchtroumpf requested changes

2020-11-11 16:13 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/video/video.component.html
> +<div class="name">
```html
<span class="name">{{ name }}</span>
```
And apply some padding on it directly.

2020-11-11 16:13 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/video/video.component.html
> +<div class="controls">
footer ?

2020-11-11 16:13 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/video/video.component.ts
> +  get userInitials() {
If you end up having to get the initial in several component, create a pipe for that.

2020-11-11 16:13 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/video/video.component.scss
> +    width: 100%;
do `bottom: 0; top: 0; left: 0; right: 0;` instead of widht/height

2020-11-11 16:13 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/video/video.component.scss
> +      fill: var(--foreground-divider);
--foreground-text maybe ?

2020-11-11 16:13 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/video/video.component.scss
> +    width: 100%;
Maybe use: `position: absolute; bottom: 0; top: 0; left: 0; right: 0;` ?

2020-11-11 16:13 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/video/video.component.scss
> +    &.hidden {
Another solution would be to use the z-index to put the svg or the video in front (if you use absolute for both).

2020-11-11 16:13 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/video/video.component.scss
> +  &>div {
```scss
.name, .controls {
  position: absolute;
  transition: transform 0.3s ease-in-out;
}
```

2020-11-11 16:13 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/video/video.component.scss
> +      transform: translateY(40px);
`translateY(100%)` I think would be safer.

2020-11-11 16:13 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/video/video.component.scss
> +      transform: translateY(-40px);
`translateY(-100%)`

2020-11-11 16:13 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/video/video.component.scss
> +      border-radius: 0 5px 0 0;
Always put 4px for border-radius.

2020-11-11 16:13 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/video/video.component.scss
> +      border-radius: 0 0 0 5px;
4px

2020-11-11 16:13 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/video/video.component.scss
> +  &:hover>div.name,
&:hover .name, &:hover .controls {
  transform: translateY(0);
}

2020-11-11 16:13 UTC, GrandSchtroumpf commented on libs/event/src/lib/layout/edit/edit.component.ts
> +    this.eventLink = `/c/o/marketplace/event/${this.form.value.id}/${this.form.value.type === 'meeting' ? 'lobby' : 'session'}`;
use 2 lines : 
```typescript
const type = this.form.value.type === 'meeting' ? 'lobby' : 'session';
this.eventLink = `/c/o/marketplace/event/${this.form.value.id}/${type}`;
```

2020-11-11 16:13 UTC, GrandSchtroumpf commented on libs/ui/src/lib/icon-service.ts
> +  { name: 'mute', url: 'assets/icons/mute.svg' },
⚠ Put the icon in the alphabetic order ⚠

2020-11-11 16:21 UTC, pldespaigne commented on apps/festival/festival/src/app/marketplace/event/lobby/lobby.component.html
> +      <span matTooltip="Your browser don't have the permission to access the camera">
That was my first try but tooltip doesn't show on disabled button

2020-11-11 16:21 UTC, pldespaigne commented on apps/festival/festival/src/app/marketplace/event/lobby/lobby.component.html
> +      <span matTooltip="Your browser don't have the permission to access the microphone">
That was my first try but tooltip doesn't show on disabled button

2020-11-11 16:37 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/video/video.component.scss
> +      fill: var(--foreground-divider);
`--foreground-text` is not a sufficient contrast with `background: var(--primary)`

2020-11-12 10:33 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/video/video.component.scss
> +    width: 100%;
this doesn't work, I suspect it's because of the `viewBox` attribute

2020-11-12 10:33 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/video/video.component.scss
> +    &.hidden {
video is not absolute

2020-11-12 10:37 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/video/video.component.scss
> +    width: 100%;
doing this ☝️ make the parent take 0x0px since all it's children are absolute, this make the component invisible for the user

2020-11-12 10:42 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/video/video.component.html
> +<div class="controls">
it's not really a footer, moreover controls are in the top-right corner, should I use `<footer>` anyway ?

2020-11-12 10:44 UTC, pldespaigne commented on libs/ui/src/lib/icon-service.ts
> +  { name: 'mute', url: 'assets/icons/mute.svg' },
The whole file is not in alphabetic order 😞 
If it's really important, I think we can create a dedicated issue for the cleaning sprint

2020-11-12 11:54 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/event/lobby/lobby.component.html
> +        [name]="userName"
Would be better to have a ng-content for that  :
```html
<meeting-video [video]="track.video" [audio]="track.audio" local>
  {{ user | displayname }}
</meeting-video>
```

2020-11-12 11:54 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/event/lobby/lobby.component.html
> +      <ng-container *ngIf="track.video; else noVideoTrack">
```html
<ng-container *ngIf="track.video as video">
  <button mat-icon-button (click)="toggleLocalTrack('video')">
    <mat-icon *ngIf="video.isEnabled" svgIcon="videocam"></mat-icon>
    <mat-icon *ngIf="!video.isEnabled" svgIcon="videocam_off"></mat-icon>
  </button>
</ng-container>
<ng-container *ngIf="!track.video">
  <button mat-icon-button disabled matTooltip="Your browser don't have the permission to access the camera">
    <mat-icon svgIcon="videocam"></mat-icon>
  </button>
</ng-container>
```

2020-11-12 11:54 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/event/lobby/lobby.component.html
> +      <ng-template #noAudioTrack>
same as above

2020-11-12 11:54 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/event/lobby/lobby.component.ts
> +  public track$ = new BehaviorSubject<{
Create and export an interface for that in the service and reuse it here.

2020-11-12 11:54 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/event/lobby/lobby.component.ts
> +  public userName: string;
```typescript
public user = this.authQuery.user;
```

2020-11-12 11:54 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/event/lobby/lobby.component.ts
> +    this.twilioService.getLocalTrack('video').then(videoTrack => {
Update the service to be able to do that :
```typescript
const [ video, audio ] =  await this.twilioService.getLocalTrack();
this.track$.next({ video, audio });
```

2020-11-12 11:54 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/event/lobby/lobby.component.ts
> +    this.twilioService.cleanLocalTrack('video');
Update the service to be `this.twilioService.cleanTrack()`

2020-11-12 11:54 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/+state/twilio.model.ts
> +
```typescript
export interface LocalTracks {
  video: LocalVideoTrack,
  audio: LocalAudioTrack,
}
export type TrackKind = keyof LocalTracks;
export type AllTracks = [LocalVideoTrack, LocalAudioTrack];
```

2020-11-12 11:54 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/+state/twilio.service.ts
> +  async getLocalTrack(kind: TrackKind): Promise<LocalVideoTrack | LocalAudioTrack | null> {
```typescript
async load<T extends TrackKind>(key: T, getKey: () => Promise<LocalTrack[T]>): Promise<LocalTrack[T]> {
  if (!this.track[key]) {
    this.track[key] = await getKey();
  }
  return this.track[key];
}

async getLocalTrack(): Promise<AllTracks>
async getLocalTrack<T extends TrackKind>(kind: T): Promise<LocalTrack[T]>
async getLocalTrack<T extends TrackKind>(kind?: T): Promise<LocalTrack[T] | AllTracks> {
  const getTrack = key => this.load(key, createLocalVideoTrack());
  if (!kind) return Promise.all(['video', 'audio'].map(getTrack));
  return getTrack(kind);
}
```

2020-11-12 11:54 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/+state/twilio.service.ts
> +  cleanLocalTrack(kind: TrackKind) {
```typescript
cleanLocalTrack(kind?: TrackKind) {
  const clean = (key: TrackKind) => {
      this.localTrack[key].stop();
      this.localTrack[key].removeAllListeners();
      this.localTrack[key] = null;
  }
  kind ? clean(kind) : ['video', 'audio'].forEach(clean);
}
```

2020-11-12 11:54 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/video/video.component.scss
> +      fill: var(--foreground-divider);
This is an issue with the theme having not enough contrast. We'll fix that with Stéphanie.
Use --foreground-text, or white. But not divider.

2020-11-12 12:01 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/video/video.component.ts
> +  setUpTracks(...trackAndKinds: { track: (VideoTrack | AudioTrack | undefined), kind: TrackKind}[]) {
It would be easier like that: 
```typescript
setupTracks<T extends TrackKind>(kind: T | T[]) {
  const kinds = Array.isArray(kind) ? kind : [kind];
  for (const key of kinds) {
    const track = this.tracks[key];
    if (!track) return this.remoteTrackState$[kind].next(false);
    ...
  }
}
```

2020-11-12 13:19 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/video/video.component.scss
> +      fill: var(--foreground-divider);
No that's not an issue with the theme, the background is set to `--primary` to have a nice blue circle
but no text variable have been created to write on a `--primary` background.

This is a realy specific use case here, so it might be good to hardcode colors maybe ?

2020-11-12 13:50 UTC, pldespaigne commented on apps/festival/festival/src/app/marketplace/event/lobby/lobby.component.html
> +        [name]="userName"
I don't see the point, it will require that we enforce `ng-content` is only a string, and we will need to get it's value in the ts to compute initials

2020-11-12 14:23 UTC, pldespaigne commented on apps/festival/festival/src/app/marketplace/event/lobby/lobby.component.ts
> +    this.twilioService.getLocalTrack('video').then(videoTrack => {
I have updated the service, however doing this will prevent the user to see it's video preview until he accept both video & audio permission.
Where as doing separate `getTrack('video')` & `getTrack('audio')` allow us to show meaningful ui as soon as corresponding permission is accepted.

2020-11-12 14:28 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/video/video.component.ts
> +  setUpTracks(...trackAndKinds: { track: (VideoTrack | AudioTrack | undefined), kind: TrackKind}[]) {
I don't see the point, spread parameter is doing exactly this without using arrays.

2020-11-12 14:32 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/video/video.component.ts
> +  setUpTracks(...trackAndKinds: { track: (VideoTrack | AudioTrack | undefined), kind: TrackKind}[]) {
Ok sorry, I think your comment was about not using a `track` param and use only a `kind` param, SGTM

2020-11-12 15:25 UTC, GrandSchtroumpf approved these changes

2020-11-12 15:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/+state/twilio.service.ts
> +      } catch (error) {
What's the goal of the catch ?
Could you do `this.track[kind] = await createTrack().catch(err => null)` ?

2020-11-12 16:01 UTC, merged