Issue algolia service
blockframes/blockframes pull request #4277
Opened 2020-11-18 15:13 UTC by fritzschoff

2020-11-18 16:10 UTC, GrandSchtroumpf requested changes

2020-11-18 16:10 UTC, GrandSchtroumpf commented on libs/utils/src/lib/algolia/helper.utils.ts
> +            parseFilters(filters[key], operator)
This doesn't do anything.
This one should work: 
```typescript
function parseFilters(filters: MovieIndexFilters, operator: ' AND ' | ' OR ' = ' OR ', prefix?: string) {
  const filter = []
  for (const [key, value] of Object.entries(filters)) {
    const path = [prefix, key].filter(v => !!v).join('.');
    if (value === null || value === undefined) {
      filter.push(undefined);
    } else if (typeof value === 'object') {
      const deepFilter = parseFilters(value, operator, path);
      filter.push(deepFilter);
    } else {
      filter.push(`${path} >= ${value ?? 0}`)
    }
  }
  return filter.filter(v => !!v).join(operator);
}
```

2020-11-19 09:58 UTC, GrandSchtroumpf approved these changes

2020-11-19 09:58 UTC, GrandSchtroumpf commented on libs/utils/src/lib/algolia/algolia.service.ts
> +            return algoliasearch(algolia.appId, algolia.searchKey).initIndex(algoliaIndex[name]);
Here you initialize the index each time you call the method. I think it's an mistake. Use memorization as I told you in the previous comments

2020-11-19 09:58 UTC, GrandSchtroumpf commented on libs/utils/src/lib/algolia/algolia.service.ts
> +    query<K extends keyof AlgoliaQueries>(name: K, config: AlgoliaQueries[K]) {
What about the return type ?

2020-11-19 10:12 UTC, fritzschoff commented on libs/utils/src/lib/algolia/algolia.service.ts
> +    query<K extends keyof AlgoliaQueries>(name: K, config: AlgoliaQueries[K]) {
will throw a type error since algolia typed the function. Tried to cast it with `as` but it didn't let me.

2020-11-19 10:13 UTC, fritzschoff commented on libs/utils/src/lib/algolia/algolia.service.ts
> +    query<K extends keyof AlgoliaQueries>(name: K, config: AlgoliaQueries[K]) {
Will check again if I can override it

2020-11-19 10:43 UTC, merged