video-room & service refactoring
blockframes/blockframes pull request #4281
Opened 2020-11-18 16:46 UTC by pldespaigne

2020-11-19 09:16 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/+state/twilio.model.ts
>  export interface Tracks {
Better : `type Tracks = LocalTracks | RemoteTracks`

2020-11-19 09:16 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/+state/twilio.service.ts
> +        }).catch(e => {}) // browser denied audio permission : catch error to avoid breaking and do nothing
Using `Promise.allSettled` should avoid this issue

2020-11-19 09:16 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/+state/twilio.service.ts
> +    const cleanTrack = (track: LocalVideoTrack | LocalAudioTrack) => { track?.stop(); track?.removeAllListeners(); }
use 3lines

2020-11-19 09:16 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/+state/twilio.service.ts
> +            console.log('upserting', track.sid, track.kind);
remove console log and below

2020-11-19 09:16 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/+state/twilio.service.ts
> +          entity => {
Maybe type it here `(entity: RemoteAttendee) => ` to avoid type casting below

2020-11-19 09:16 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/room/video-room.component.ts
> +    this.twilioService.initLocal(
Use `displayName` method in the utils/pipe, it'll apply titlecase : 
```typescript
await this.twilioService.initLocal(displayName(this.authQuery.user));
this.twilioService.connect(this.eventId);
```

2020-11-19 09:16 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/room/video-room.component.ts
> +  @HostListener('window:beforeunload')
Put HostListener at the top of the file, even if it's beforeunload

2020-11-19 16:43 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/+state/twilio.query.ts
> +  // TODO This is for debug purpose only, this should be deleted before merging
Delete then.

2020-11-19 16:43 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/+state/twilio.service.ts
> +    return (Promise as any).allSettled(promises);
Can't you do something like that ? (I use all instead of allSettled because I don't remember the result)
```typescript
const [ video, audio] = Promise.all([
  createLocalVideoTrack(),
  createLocalAudioTrack()
]);
const currentLocal = this.twilioQuery.localAttendee;
this.twilioStore.update(currentLocal.id, { tracks: { video, audio: entity.tracks.audio } });
```

2020-11-19 16:43 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/room/video-room.component.ts
> +    // TODO before merging this should be replaced with the commented line bellow
Do it ^^

2020-11-19 16:43 UTC, GrandSchtroumpf commented on libs/utils/src/lib/pipes/display-name.pipe.ts
> +export function displayName(value: Person | Person[], textTransform: TextTransform = 'uppercase'): string {
I think @Mussuranae did a function for that already. Can you check with her so we don't have any duplication ?

2020-11-19 17:30 UTC, pldespaigne commented on libs/event/src/lib/components/meeting/+state/twilio.query.ts
> +  // TODO This is for debug purpose only, this should be deleted before merging
not until, you give you approval for the "grid" and that the PR is not a draft anymore

2020-11-20 16:51 UTC, GrandSchtroumpf commented on apps/backend-functions/src/twilio.ts
> +  const identity = `${user.firstName[0].toUpperCase()}${user.firstName.substr(1).toLowerCase()} ${user.lastName[0].toUpperCase()}${user.lastName.substr(1).toLowerCase()}`;
Could you create a reusable function for that ?

2020-11-20 16:51 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/+state/twilio.service.ts
> +      (track: (RemoteAudioTrack | RemoteVideoTrack | RemoteDataTrack), publication: RemoteTrackPublication, participant: RemoteParticipant) => {
You don't have a `type Track = RemoteAudioTrack | RemoteVideoTrack | RemoteDataTrack` ?

2020-11-23 09:54 UTC, pldespaigne commented on apps/backend-functions/src/twilio.ts
> +  const identity = `${user.firstName[0].toUpperCase()}${user.firstName.substr(1).toLowerCase()} ${user.lastName[0].toUpperCase()}${user.lastName.substr(1).toLowerCase()}`;
I tried to used the `displayName` function as I did in the front, but it gave me import errors

2020-11-24 09:02 UTC, GrandSchtroumpf requested changes

2020-11-24 09:02 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/room/video-room.component.html
> +<section class="video">
```html
<ng-container *ngIf="attendees$ | async as attendees">
  <section [gdColumns]="attendees.length | roomColumns">
    <meeting-video *ngFor="let attendee of attendees"  [attendee]="attendee"></meeting-video>
  </section>

  <footer *ngIf="(local$ | async) as local">
    ...
  </footer>
</ng-container>

```

2020-11-25 08:47 UTC, GrandSchtroumpf approved these changes

2020-11-25 08:47 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/+state/twilio.service.ts
> +    ]) as [ LocalVideoTrack, LocalAudioTrack ];
It's `[ (LocalVideoTrack | null), (LocalAudioTrack | nulll) ]`
But `createLocalVideoTrack().catch(e => null)` doesn't imply the right type ?

2020-11-25 09:26 UTC, merged