Check whether owner is present in meeting sessions
blockframes/blockframes pull request #4308
Opened 2020-11-23 14:19 UTC by RemcoSimonides

![request access](https://user-images.githubusercontent.com/27687382/99972753-35c3b380-2d9f-11eb-89ee-6c4f1e5b4a35.gif)

2020-11-23 14:20 UTC, RemcoSimonides commented on apps/festival/festival/src/app/marketplace/event/session/session.component.ts
> +  async ngOnDestroy() {
Maybe it would be good to use 
`@HostListener('window:beforeunload', [ '$event' ])
  beforeUnloadHandler() {}`
here too - to make sure owner the is not present anymore when browser is closed

2020-11-23 14:48 UTC, pldespaigne requested changes

2020-11-23 14:48 UTC, pldespaigne commented on libs/event/src/lib/+state/event.firestore.ts
>    // TODO removed real-time shared state from firestore issue#3748
could you remove the todo comment as we decided to keep the code here

2020-11-23 14:48 UTC, pldespaigne commented on apps/festival/festival/src/app/marketplace/event/session/session.component.ts
> +  async ngOnDestroy() {
totally ! do it, like I did for the [video-room](https://github.com/blockframes/blockframes/blob/d3064214c62b394c5218b8a497e39a8d49d805bd/libs/event/src/lib/components/meeting/room/video-room.component.ts#L26)

2020-11-25 09:37 UTC, pldespaigne requested changes

2020-11-25 09:37 UTC, pldespaigne commented on apps/festival/festival/src/app/marketplace/event/lobby/lobby.component.html
> +            <a mat-flat-button disabled color="accent">Waiting for owner...</a>
Maybe add something like `<p>You will be able to request access when the owner will start the meeting</p>`. to be more clear

2020-11-25 09:37 UTC, pldespaigne commented on apps/festival/festival/src/app/marketplace/event/session/session.component.ts
> +  }
delete this, and put `@HostListener` directly on `ownerLeaves()`

2020-11-25 09:37 UTC, pldespaigne commented on apps/festival/festival/src/app/marketplace/event/session/session.component.ts
>        tap(async event => {
Idk if it will fix the `beforeunlaod` problem, but you can try to remove all this observable logic and use
`this.event = this.eventQuery.getActive();` instead

2020-11-25 10:24 UTC, RemcoSimonides commented on apps/festival/festival/src/app/marketplace/event/lobby/lobby.component.html
> +            <a mat-flat-button disabled color="accent">Waiting for owner...</a>
That's too long. I changed it to `Waiting for organizer to start the meeting...`

2020-11-25 10:24 UTC, RemcoSimonides commented on apps/festival/festival/src/app/marketplace/event/session/session.component.ts
>        tap(async event => {
I'm quite sure this won't work and I need to receive the changes to the event doc anyway... In this observable I do have this.event = event to make the `beforeunload` completely synchronous

2020-11-25 10:45 UTC, RemcoSimonides commented on apps/festival/festival/src/app/marketplace/event/session/session.component.ts
> +          const meta = {...event.meta} as Meeting
Had to _duplicate_ the object because the event from subscription is readonly

2020-11-25 13:31 UTC, pldespaigne approved these changes

2020-11-25 13:31 UTC, pldespaigne commented on apps/festival/festival/src/app/marketplace/event/session/session.component.ts
> +          await this.service.update(event.id, { meta });
`await this.service.update(event.id, (e: MeetingEvent): MeetingEvent => ({ ...e, meta: {...e.meta, ownerIsPresent: true } }))`

2020-11-25 13:55 UTC, merged