WIP Feat 3932
blockframes/blockframes pull request #4320
Opened 2020-11-24 13:04 UTC by phpgeekfr

2020-11-26 14:47 UTC, GrandSchtroumpf commented on apps/backend-functions/src/movie.ts
> +    let i, j, subEventIds;
could you type it ?

2020-11-26 14:47 UTC, GrandSchtroumpf commented on apps/backend-functions/src/movie.ts
> +  const eventIds = events.docs.map(e => e.id);
Use a 
```typescript
const promises = events.map(e db.collection('invitations').where('docId', '==', e.id)).then(s => s.docs);
const invitations = awat Promise.all(promises);
invitations.flat().forEach(d => batch.delete(d.ref));
```

2020-11-26 14:53 UTC, GrandSchtroumpf requested changes

2020-11-26 14:53 UTC, GrandSchtroumpf commented on apps/backend-functions/src/movie.ts
> +  const orgs = await db.collection('orgs').where('id', 'in', movie.orgIds).get();
Same as above

2020-11-26 14:53 UTC, GrandSchtroumpf commented on libs/admin/src/lib/admin-panel/pages/movie/movie.component.ts
> +        const invitations = await this.invitationService.getValue(ref => ref.where('docId', 'in', subEventIds));
Same as above

2020-11-26 14:53 UTC, GrandSchtroumpf commented on libs/admin/src/lib/admin-panel/pages/movie/movie.component.ts
> +    const orgs = await this.organizationService.getValue(ref => ref.where('id', 'in', movie.orgIds));
same

2020-11-26 14:53 UTC, GrandSchtroumpf commented on libs/firebase-utils/src/lib/maintenance.ts
> +const maintenanceRef = (db?: FirebaseFirestore.Firestore, checkMissingVars = true) => {
Avoid boolean parameters in a function, prefer config object, it's easier to read/understand when you invoke it : 
```typescript
const maintenanceRef = (db?: FirebaseFirestore.Firestore, { checkMissingVars = true }: MaintenanceOptions) => {
```

2020-11-26 14:53 UTC, GrandSchtroumpf commented on libs/firebase-utils/src/lib/util.ts
> +export function loadAdminServices(checkMissingVars = true): AdminServices {
Same as above

2020-11-26 18:18 UTC, phpgeekfr commented on libs/firebase-utils/src/lib/util.ts
> +export function loadAdminServices(checkMissingVars = true): AdminServices {
I can do it but it requires to update all call `loadAdminServices()` by `loadAdminServices({})`. Your call ;)

2020-11-27 09:35 UTC, GrandSchtroumpf approved these changes
Nice

2020-11-27 09:35 UTC, GrandSchtroumpf commented on libs/admin/src/lib/admin-panel/pages/movie/movie.component.ts
> +    const chunk = 10; // max 10 items in "in" queries
remove this

2020-11-27 09:35 UTC, GrandSchtroumpf commented on libs/firebase-utils/src/lib/util.ts
> +export function loadAdminServices(checkMissingVars = true): AdminServices {
```typescript
export function loadAdminServices(options: Options = {}): AdminServices {
```

2020-11-27 15:23 UTC, merged