Rework event details form
blockframes/blockframes pull request #4370
Opened 2020-12-01 14:34 UTC by RemcoSimonides

To do in issue #4290 
- [x] (1) Change checkboxes for toggles for "All day" and "Private"
- [x] (2) add an autofilled input "Meeting link" filled with the meeting session url + a copy to clipboard button to copy it (already implemented for invitations)
- [x] (3) Add a hint below "Organized by": "This person will be the one displayed in the invitations sent to buyers."
- [x] (4) Remove "Files" from the Meeting block and create a dedicated card called "My Files for this Meeting"
- [x] (5) Change the subtitles of "My Files.." for: 
"Add the files you'll want to share during the meeting.
(line break) If you can't find the files you're looking for, you can upload them directly in My Files (hyperlink) page."
- [x] (6) Change "Manage Files" button text for: "Attach the files you want to share during the meeting" and align it to left

2020-12-01 14:59 UTC, pldespaigne commented on apps/festival/festival/src/app/dashboard/event/edit/edit.component.html
> +              <input matInput type="text" disabled [value]="getLink()">
the `getLink()` function will be called a gazillion time per second, it's better to use a static value initialized in the `ngOnInit `

2020-12-01 15:05 UTC, pldespaigne requested changes

2020-12-01 15:05 UTC, pldespaigne commented on apps/festival/festival/src/app/dashboard/event/edit/edit.component.html
> +    <!-- <event-analytics [eventId]="form.id.value"></event-analytics> -->
uncomment

2020-12-01 15:05 UTC, pldespaigne commented on libs/user/src/lib/auth/components/terms-conditions/terms-conditions.component.ts
> +    const app = getCurrentApp(this.routerQuery);
weird to have a component with code in `constructor `instead of `ngOnInit ` 🤔

2020-12-02 08:36 UTC, RemcoSimonides commented on libs/user/src/lib/auth/components/terms-conditions/terms-conditions.component.ts
> +    const app = getCurrentApp(this.routerQuery);
Only removed a random `;` but changed it to ngOnInit anyway ;)

2020-12-02 08:46 UTC, pldespaigne approved these changes

2020-12-02 09:04 UTC, merged