Algolia org on user
blockframes/blockframes pull request #4371
Opened 2020-12-01 15:01 UTC by Mussuranae

Update user index on algolia to put the org denomination of the user on it.
Fix #4356

2020-12-01 15:16 UTC, phpgeekfr requested changes

2020-12-01 15:16 UTC, phpgeekfr commented on apps/backend-functions/src/users.ts
> +    before.orgId !== after.orgId
you test the orgId which is fine, but don't we need to test the org name also ? What if it changed ?

2020-12-01 15:16 UTC, phpgeekfr commented on libs/firebase-utils/src/lib/algolia/algolia.ts
> +      orgName: orgData ? orgData.denomination : {}
You should use `orgName` here like this we only store in algolia the value we use for the org name.

2020-12-01 15:16 UTC, phpgeekfr commented on libs/invitation/src/lib/form/user/user.component.html
> +          <span *ngIf="user.firstName">{{ user.firstName && user.lastName | titlecase }}</span>
Why not using `{{ user | displayUser | async }}` here ?

2020-12-01 15:16 UTC, phpgeekfr commented on libs/invitation/src/lib/form/user/user.component.html
> +          <span *ngIf="user.orgName.public || user.orgName.full">({{ user.orgName.public ? user.orgName.public : user.orgName.full }})</span>
If you use orgName to put data in algolia like I said above, you could just do `<span *ngIf="user.orgName">({{ user.orgName }})</span>`

2020-12-01 15:19 UTC, Mussuranae commented on apps/backend-functions/src/users.ts
> +    before.orgId !== after.orgId
So I checked that in the code, and on the `onOrganizationUpdate` funciton, there was something to forbidden the update of the name
``` 
if (!before || !after || !after.denomination.full) {
    console.error('Invalid org data, before:', before, 'after:', after);
    throw new Error('organization update function got invalid org data');
  }
```
in the `orgs.ts` in backend-functions.
So I don't know if it's very useful now :/

2020-12-01 15:21 UTC, Mussuranae commented on libs/invitation/src/lib/form/user/user.component.html
> +          <span *ngIf="user.firstName">{{ user.firstName && user.lastName | titlecase }}</span>
Because the pipe use the orgId on the user, but as we don't save the orgId but directly the organization's name, I can't use it anymore. I tried to update the pipe but can't succeed between the PublicUser and AlgoliaUser type....

2020-12-01 16:44 UTC, phpgeekfr commented on apps/backend-functions/src/users.ts
> +    before.orgId !== after.orgId
what if an admin change the name directly in db ?

2020-12-01 16:44 UTC, phpgeekfr commented on libs/invitation/src/lib/form/user/user.component.html
> +          <span *ngIf="user.firstName">{{ user.firstName && user.lastName | titlecase }}</span>
`Because the pipe use the orgId on the user,` I made you review my PR about this

2020-12-01 16:45 UTC, phpgeekfr commented on libs/invitation/src/lib/form/user/user.component.html
> +          <span *ngIf="user.firstName">{{ user.firstName && user.lastName | titlecase }}</span>
I don't see any reason why you can't use `{{ user | displayUser | async }}` since I added a check on orgId to prevent error

2020-12-01 16:47 UTC, phpgeekfr commented on libs/invitation/src/lib/form/user/user.component.html
> +          <span *ngIf="user.firstName">{{ user.firstName && user.lastName | titlecase }}</span>
` I tried to update the pipe but can't succeed between the PublicUser and AlgoliaUser type` for this pipe to work we only need lastName & firstName. both publicUser and algoliaUsers have this attributes

2020-12-01 16:49 UTC, phpgeekfr commented on apps/backend-functions/src/users.ts
> +    before.orgId !== after.orgId
and it's always better to evaluate the good data. what if in the future we allow orgName changes? Will you remember that this need to be updated?

2020-12-02 14:07 UTC, Mussuranae commented on libs/invitation/src/lib/form/user/user.component.html
> +          <span *ngIf="user.firstName">{{ user.firstName && user.lastName | titlecase }}</span>
See last commit....

2020-12-02 14:20 UTC, phpgeekfr approved these changes

2020-12-02 14:20 UTC, phpgeekfr commented on apps/backend-functions/src/orgs.ts
> +    //! When users will be able to change their org's name, we have to take care of the org ENS name
Outdated comment, org name can be changed on app.

ENS was an ethereum related thing. this can be removed

2020-12-02 15:50 UTC, merged