creating of consents collection
blockframes/blockframes pull request #4407
Opened 2020-12-07 14:57 UTC by SamirTouira

Related to : #4327 
First step : creation of collection "consents" with interface in progress
WIP

2021-01-05 11:35 UTC, phpgeekfr requested changes

2021-01-05 11:35 UTC, phpgeekfr commented on angular.json
>          "lint": {
can you revert formatting changes so only your changes are visible?

2021-01-05 11:35 UTC, phpgeekfr commented on libs/consents/src/lib/consents.module.ts
> +export class ConsentsModule {}
this file is not required, remove it

2021-01-05 11:35 UTC, phpgeekfr commented on libs/consents/tsconfig.json
> +}
update this file to look like other libraries

2021-01-05 11:35 UTC, phpgeekfr commented on libs/consents/src/index.ts
> +export * from './lib/consents.module';
this file is not required right now

2021-01-05 11:35 UTC, phpgeekfr commented on nx.json
>    },
same as `angular.json` file

2021-01-05 11:35 UTC, phpgeekfr commented on tsconfig.base.json
> +      "@blockframes/consents": ["libs/consents/src/index.ts"]
since `index.ts` is not needed right now, can you update to reflect other libs config ?

2021-01-05 11:35 UTC, phpgeekfr commented on tsconfig.json
> -}
do not remove this one

2021-01-06 09:58 UTC, SamirTouira commented on tsconfig.base.json
> +      "@blockframes/consents": ["libs/consents/src/index.ts"]
the only file in blockframes is this right ? if I've understood, I can delete the line 63 and delete aswell index.ts if it's not needed for the moment

2021-01-06 10:02 UTC, phpgeekfr commented on tsconfig.base.json
> +      "@blockframes/consents": ["libs/consents/src/index.ts"]
for me, `""@blockframes/consents": ["libs/consents/src/index.ts"]` should look like `"@blockframes/consents/*": ["libs/consents/src/lib/*"],`  and yes index.ts can be deleted

2021-01-06 11:16 UTC, SamirTouira commented on tsconfig.json
> -}
from my side, I've got `  "extends": "../../tsconfig.base.json"` in line 2, isn't the right way ?

2021-01-06 11:21 UTC, phpgeekfr commented on tsconfig.json
> -}
In this PR you are removing this file `tsconfig.json`. Don't remove it

2021-01-06 16:06 UTC, phpgeekfr approved these changes

2021-01-06 17:05 UTC, merged