Currency on dialog form
blockframes/blockframes pull request #4598
Opened 2020-12-18 13:40 UTC by Mussuranae

Add a currency icon on the investment dialog form.
![image](https://user-images.githubusercontent.com/48033264/102620722-c1322980-413e-11eb-8b7b-2610bade192d.png)

I need suggestion for the getCurrencySymbol function, I have the feeling that it is not the best way but I prefer to use the function instead of doing if statement in the html.

2020-12-18 13:45 UTC, fritzschoff requested changes

2020-12-18 13:45 UTC, fritzschoff commented on apps/financiers/financiers/src/app/marketplace/title/view/view.component.html
> +            <span matPrefix>{{ getCurrencySymbol((campaign$ | async)?.currency, 'wide') }}</span>
There is a currency pipe you can use. 
```
 amount | currency: form.getCurrency() : 'symbol' : '1.0-0' 
 ``` 
 blockframes/libs/organization/campaign/src/lib/form/fundings/fundings.component.html

2020-12-18 14:41 UTC, fritzschoff requested changes

2020-12-18 14:41 UTC, fritzschoff commented on apps/financiers/financiers/src/app/marketplace/title/view/view.component.ts
> +          currency: getCurrencySymbol(this.currency, 'wide'),
whydo you need that?

2020-12-18 14:41 UTC, fritzschoff commented on apps/financiers/financiers/src/app/marketplace/title/view/view.component.ts
> +      this.currency = data.currency;
do you need that?

2020-12-18 15:02 UTC, Mussuranae commented on apps/financiers/financiers/src/app/marketplace/title/view/view.component.ts
> +          currency: getCurrencySymbol(this.currency, 'wide'),
To change the template of the email, the currency should be updated depending on the film/campaign. It's a rough data in the template for now but it should be updated after the next hotfix if we implement this commit. And we don't want a `EUR 123` but `€123` in the email.

2020-12-18 15:03 UTC, Mussuranae commented on apps/financiers/financiers/src/app/marketplace/title/view/view.component.ts
> +      this.currency = data.currency;
It's related to the comment above

2020-12-21 14:13 UTC, fritzschoff approved these changes

2020-12-21 14:13 UTC, fritzschoff commented on apps/financiers/financiers/src/app/marketplace/title/view/view.component.ts
>        switchMap(id => this.campaignService.valueChanges(id))
add a tap here so you don't need to subscribe to the campaign$ two lines below.
``` 
   this.campaign$ = this.movieQuery.selectActiveId().pipe(
      switchMap(id => this.campaignService.valueChanges(id)),
      tap(campaign => this.currency= campaing.currency)
```

2020-12-21 14:50 UTC, merged