UT(Feat): Add new app to manage firestore security rules.
blockframes/blockframes pull request #4606
Opened 2020-12-21 10:38 UTC by xmano

Improving manageability of firestore sec rules.

2020-12-21 14:15 UTC, xmano commented
Reorganised tests separately as collections based.

![image](https://user-images.githubusercontent.com/8731418/102786151-10898b80-43c5-11eb-99d8-491464c5bf03.png)


![image](https://user-images.githubusercontent.com/8731418/102786175-1aab8a00-43c5-11eb-89c1-e1caea890d31.png)


Skipped tests will be added as a part of later commits.

2020-12-22 12:41 UTC, phpgeekfr requested changes
- [ ] maybe add the files in a dedicated `firestore` folder. So we can then add the ones for the storage
- [ ] you still have `apps/backend-ops/src/campaign-rules.spec.ts` that is now crashed

2020-12-22 12:41 UTC, phpgeekfr commented on apps/rules/src/tests/contracts.spec.ts
> +testFixture[metaDoc].endedAt = true;
this
```
const metaDoc = `${META_COLLECTION_NAME}/${MAINTENANCE_DOCUMENT_NAME}`;
testFixture[metaDoc] = {};
testFixture[metaDoc].endedAt = true;
```
is repeated in each file. can you move it to libs `libs/testing/src/lib` ?

2020-12-22 12:41 UTC, phpgeekfr commented on apps/rules/src/tests/blockframe.spec.ts
>  describe('Notification Rules Tests', () => {
this test `Notification Rules Tests` is already in `apps/rules/src/tests/notification.spec.ts`

2020-12-22 12:41 UTC, phpgeekfr commented on apps/rules/src/tests/blockframe.spec.ts
>  describe('Notification Rules Tests', () => {
same for `With User in TO field` and others

2020-12-22 12:41 UTC, phpgeekfr commented on package.json
> +    "build:rules": "",
is this useful ?

2020-12-22 12:41 UTC, phpgeekfr commented on apps/rules/src/tests/blockframe.spec.ts
>    apps,
can you rename to `blockframes` with a `s` ?

2020-12-22 12:42 UTC, phpgeekfr commented on apps/rules/src/main.ts
> +console.log('Hello World!');
is this file required ?

2020-12-22 12:59 UTC, xmano commented on apps/rules/src/main.ts
> +console.log('Hello World!');
will check if build fails by removing this. i need to commit it first.

2020-12-22 12:59 UTC, xmano commented on apps/rules/src/tests/blockframe.spec.ts
>    apps,
ok

2020-12-22 13:00 UTC, xmano commented on package.json
> +    "build:rules": "",
it was for making build pass on CI.

2020-12-22 13:02 UTC, xmano commented on apps/rules/src/tests/blockframe.spec.ts
>  describe('Notification Rules Tests', () => {
removed these tests from 'blockframes.spec.ts'

2020-12-22 13:46 UTC, phpgeekfr commented on package.json
> +    "build:rules": "",
ok but `npm build rules` crashed on my side

2020-12-22 14:11 UTC, xmano commented on apps/rules/src/tests/contracts.spec.ts
> +testFixture[metaDoc].endedAt = true;
moved it fixtures/data.ts

2020-12-22 14:11 UTC, xmano commented
`$ npx jest apps/rules/src/tests/firestore/*.spec.ts`

![image](https://user-images.githubusercontent.com/8731418/102897215-a4bf2580-448d-11eb-9388-a888a1878e1b.png)


![image](https://user-images.githubusercontent.com/8731418/102897259-b9032280-448d-11eb-98c2-60cba8c0ba93.png)

2020-12-22 15:01 UTC, phpgeekfr requested changes

2020-12-22 15:01 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +export const metaDoc = `${META_COLLECTION_NAME}/${MAINTENANCE_DOCUMENT_NAME}`;
can't you put this in `libs/utils/src/lib/maintenance/index.ts` ?

2020-12-23 09:03 UTC, xmano commented on apps/rules/src/tests/firestore/permission.spec.ts
> +testFixture[metaDoc].endedAt = true;
sorry. removed it.

2020-12-23 09:07 UTC, xmano commented on apps/rules/src/tests/firestore/contracts.spec.ts
> +  assertSucceeds,
ok

2020-12-23 09:07 UTC, xmano commented on apps/rules/src/tests/firestore/organization.spec.ts
> +  assertSucceeds,
ok removed

2020-12-23 09:07 UTC, xmano commented on apps/rules/src/tests/firestore/permission.spec.ts
> +  assertSucceeds,
removed

2020-12-23 09:09 UTC, xmano commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +export const metaDoc = `${META_COLLECTION_NAME}/${MAINTENANCE_DOCUMENT_NAME}`;
yes it can be. done!

2020-12-23 10:12 UTC, xmano commented on apps/rules/src/tests/firestore/invitation.spec.ts
> +  assertSucceeds,
removed

2020-12-23 10:12 UTC, xmano commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +testFixture[metaDoc].endedAt = true;
it had give some issues. i leave it like this since it works fine.

2020-12-23 10:13 UTC, xmano commented
Made changes and ran the firestore rules unit-tests again:

![image](https://user-images.githubusercontent.com/8731418/102985664-8ad91d80-4535-11eb-87cd-015ff8fbd11d.png)

2020-12-23 10:20 UTC, phpgeekfr approved these changes

2020-12-23 10:29 UTC, merged