Issue 3908
blockframes/blockframes pull request #4612
Opened 2020-12-22 08:49 UTC by fritzschoff

close #3908

2020-12-22 08:59 UTC, Mussuranae approved these changes

2020-12-22 08:59 UTC, pldespaigne approved these changes

2020-12-22 08:59 UTC, pldespaigne commented on libs/movie/src/lib/movie/form/movie.shell.config.ts
> +  async onSave({ publishing }: FormSaveOptions): Promise<void> {
There is no need to explicitly type here, InetlliSense will do it for you

2020-12-22 08:59 UTC, pldespaigne commented on libs/ui/src/lib/tunnel/exit/exit.component.ts
> +      }
Is this the intended behavior ?
"If the user click outside of the dialog, we neither save nor navigate"

2020-12-22 09:15 UTC, fritzschoff commented on libs/ui/src/lib/tunnel/exit/exit.component.ts
> +      }
yes we do nothing, just close modal

2021-01-05 13:53 UTC, GrandSchtroumpf requested changes

2021-01-05 13:53 UTC, GrandSchtroumpf commented on libs/ui/src/lib/tunnel/exit/exit.component.ts
> +    for (const name in this.configs) {
Use Promise.all

2021-01-05 13:53 UTC, GrandSchtroumpf commented on libs/ui/src/lib/tunnel/exit/exit.component.ts
> +  redirect() {
This is not the right way to handle exit. What happens if the user click on the browser back button ?

2021-01-05 14:13 UTC, closed without merging