Admin invite user to join org
blockframes/blockframes pull request #4635
Opened 2020-12-30 11:15 UTC by Mussuranae

Here is the problem :
when an admin invite user to join org, then remove the invitation, and invite again the same user, there is only one email sent to the user to invite him on the platform, but 2 invitations were sent.
This is because we don't remove the user in the authentication part when we delete the first invitation, so the second email isn't sent correctly.

I create a backend function when an invitation is removed to delete also the user in the authentication part IF the user hasn't orgId already (that would mean he joined an other org or create his own) and if there is no other invitation (if 2 organizations sent him an invitation, we don't want to delete his account if one of the org cancel its invitation).

I'm opened to more improvement and in case I didn't think about an other scenario.

Fix #2638

2020-12-30 11:28 UTC, Mussuranae commented on apps/backend-functions/src/invitation.ts
> +
Is it better here to check the uid or the email of the user ?

2021-01-05 10:52 UTC, phpgeekfr requested changes

2021-01-05 10:52 UTC, phpgeekfr commented on apps/backend-functions/src/main.ts
> +/** Trigger: when an invitation is updated (e. g. when invitation.status change). */
wrong comment

2021-01-05 10:52 UTC, phpgeekfr commented on apps/backend-functions/src/invitation.ts
> +  if(invitation.type === "joinOrganization"
Should `mode === 'invitation'` be also tested ?

2021-01-05 10:52 UTC, phpgeekfr commented on apps/backend-functions/src/invitation.ts
> +    if(invitationsSnap.docs.length > 1 || !!toUser.orgId) {
can you rename `invitationsSnap` to existingInvitationToJoinOrg or someting like this ?

2021-01-05 10:52 UTC, phpgeekfr commented on apps/backend-functions/src/invitation.ts
> +
If you look at `inviteUsers` you should see that every inviation of this kind will have toUser.uid and toUser.email

2021-01-05 10:52 UTC, phpgeekfr commented on apps/backend-functions/src/invitation.ts
> +  if(invitation.type === "joinOrganization"
Because if this is a 'request' user don't want to delete his account if we want to cancel his request to join org

2021-01-08 13:30 UTC, phpgeekfr requested changes

2021-01-08 13:30 UTC, phpgeekfr commented on libs/organization/src/lib/organization/components/member-add/member-add.component.ts
> +      if (invitationsExist) throw new Error('There is already invitation existing for one or more of these users');
there is already *an* invitation no ?

2021-01-08 13:30 UTC, phpgeekfr commented on libs/invitation/src/lib/+state/invitation.service.ts
> +    const f = this.functions.httpsCallable('isInvitationToJoinOrgExisted');
You can declare httpCallable like this 
```
private isInvitationToJoinOrgExisted = this.functions.httpsCallable('isInvitationToJoinOrgExisted');
```

Also, the name `isInvitationToJoinOrgExisted` is not correct I think

2021-01-08 13:30 UTC, phpgeekfr commented on apps/backend-functions/src/invitation.ts
> +export async function isInvitationToJoinOrgExists(userEmails: string[]) {
I think that parameters are wrong, an httpcallable always have  `data` and `context`

2021-01-08 13:30 UTC, phpgeekfr commented on apps/backend-functions/src/invitation.ts
> +    const existingInvitationToJoinOrg = await invitationCollectionRef.get();
Is this check useful ? This should not append thank to your new `isInvitationToJoinOrgExists` method

2021-01-08 13:30 UTC, phpgeekfr commented on apps/backend-functions/src/invitation.ts
> +  let invitationExists = false;
this is incorrect. Your method will return directly after the first item of your array

you can do 
```
  for (let email of userEmails) {
    const invitationRef = db.collection('invitations')
    .where('type', '==', 'joinOrganization')
    .where('toUser.email', '==', email);
    const invitationDocs = await invitationRef.get();

    if(invitationDocs.docs.length) {
      return true;
    }
  }
 return false;
  ```

2021-01-08 13:30 UTC, phpgeekfr commented on apps/backend-functions/src/invitation.ts
> +  let invitationExists = false;
you could also have done a promise.all to make the queries in parallel

2021-01-08 13:30 UTC, phpgeekfr commented on apps/backend-functions/src/invitation.ts
> +    admin.auth().deleteUser(toUser.uid);
do not delete auth. let `onUserDelete` do the job

2021-01-08 13:30 UTC, phpgeekfr commented on apps/backend-functions/src/invitation.ts
> +    if(existingInvitationToJoinOrg.docs.length > 1 || existingInvitationToAttendEvent.docs.length > 1 || !!toUser.orgId) {
I think you should only check if user have an orgId or a lastName/firstName  (by fetching real user from DB, not by using toUser)

2021-01-08 13:30 UTC, phpgeekfr commented on apps/backend-functions/src/invitation.ts
> +  context: EventContext
why this ? you don't use context here

2021-01-08 13:30 UTC, phpgeekfr commented on apps/backend-functions/src/invitation.ts
> +    if(existingInvitationToJoinOrg.docs.length > 1 || existingInvitationToAttendEvent.docs.length > 1 || !!toUser.orgId) {
So if invitation is deleted, user that received his credentials by emails will not be able to login ?

2021-01-08 13:31 UTC, Mussuranae commented on libs/organization/src/lib/organization/components/member-add/member-add.component.ts
> +      if (invitationsExist) throw new Error('There is already invitation existing for one or more of these users');
Yeah, good catch ! or maybe plural also. I will change that !

2021-01-08 13:34 UTC, phpgeekfr commented on apps/backend-functions/src/invitation.ts
> +  if(invitation.mode === "invitation" && !!toUser) {
should'nt you check the invitation.status also ?

2021-01-08 14:19 UTC, Mussuranae commented on apps/backend-functions/src/invitation.ts
> +    const existingInvitationToJoinOrg = await invitationCollectionRef.get();
Yeah I think you're right, but as it is not implemented on prod, we can maybe have the case of several invitation to join an organization ? Do we plan to clean the db for that ? What do we plan for invitation that are pending for x months etc ?
There is no `onInvitationUpdate` backend function, maybe we can create one and delete others invitations to join org when an user accepted one ?

2021-01-08 14:46 UTC, Mussuranae commented on apps/backend-functions/src/invitation.ts
> +  if(invitation.mode === "invitation" && !!toUser) {
I wasn't sure because if user accepted to join an org, and several months later he changed to an other org (by asking us for example), there would be always an invitation accepted but not pending or declined, and we don't want to delete the user if there is other invitation. What do you think about that ?

2021-01-08 14:50 UTC, phpgeekfr commented on apps/backend-functions/src/main.ts
> +export const onInvitationDeleteEvent = onDocumentDelete('invitations/{invitationID}', onInvitationDelete);
remove this and make it part of `onInvitationUpdateEvent`

2021-01-08 15:08 UTC, Mussuranae commented on apps/backend-functions/src/invitation.ts
> +    if(existingInvitationToJoinOrg.docs.length > 1 || existingInvitationToAttendEvent.docs.length > 1 || !!toUser.orgId) {
Yes, but the user is deleted only if there is no other invitation (to join organization or to attend an event). I added the check of the firstname and lastname, so normally it will remove the user only if he/she has no other invitation and never finish his/her register on the app.

2021-01-08 16:18 UTC, phpgeekfr requested changes

2021-01-08 16:18 UTC, phpgeekfr commented on apps/backend-functions/src/invitation.ts
> +  if (!invitationDoc) {
this if statement need to return somehting no matter what , rest of code will crash otherwise

2021-01-08 16:18 UTC, phpgeekfr commented on apps/backend-functions/src/invitation.ts
> +  }
still possible to use promise.all to speed up process

2021-01-08 16:18 UTC, phpgeekfr commented on apps/backend-functions/src/invitation.ts
> +    const user = await getUser(invitationDocBefore.toUser.uid)
you also need to check if toUser exists

2021-01-13 10:51 UTC, phpgeekfr commented on apps/backend-functions/src/invitation.ts
> +  const isInvitationExist = invitationQuery.some(d => d.docs.length > 0)
missing `;` and you can directly do ` return invitationQuery.some(d => d.docs.length > 0);` if you want

2021-01-13 10:51 UTC, phpgeekfr commented on apps/backend-functions/src/invitation.ts
> +  if (!invitationDoc && !!invitationDocBefore.toUser) {
you must `return; ` event if toUser is undefined. 
What if invitation is deleted bu with fromUser?

2021-01-14 09:23 UTC, phpgeekfr approved these changes

2021-01-14 09:53 UTC, merged