Issue 2555
blockframes/blockframes pull request #4678
Opened 2021-01-07 14:01 UTC by fritzschoff

close #2555 

this function is not tested, cause the firebase emulator is currently not able to handle pub sub functions.

2021-01-07 15:48 UTC, phpgeekfr commented
> close #2555
> 
> this function is not tested, cause the firebase emulator is currently not able to handle pub sub functions.

can't you test if by changing the `.schedule('0 4 * * *')` in main.ts ?

2021-01-07 15:54 UTC, phpgeekfr requested changes

2021-01-07 15:54 UTC, phpgeekfr commented on apps/backend-functions/src/internals/invitations/events.ts
> +    toUserId: event.toUser.uid,
`event` does not have `toUser`  . You are mistaking with `invitations`. 
As the comments above says :
```
// 1 Fetch events that are about to start
  // 2 Fetch attendees (invitations accepted)
  // 3 Create notifications
  ```

2021-01-07 15:54 UTC, phpgeekfr commented on apps/backend-functions/src/internals/invitations/events.ts
> +  const eventsCollection = await db.collection('events').where('date', '<', beginningDateObject).get();
`event` does not have `date` attribute  but `start` and `end`

2021-01-07 15:56 UTC, phpgeekfr commented on apps/backend-functions/src/internals/invitations/events.ts
> +  const beginningDateObject = new Date(beginningDate);
maybe :
```
const startDate = new Date(Date.now() +( 86400 *1000)); // now plus 1 day
```

2021-01-07 16:35 UTC, fritzschoff commented
![image](https://user-images.githubusercontent.com/39312833/103918134-af74ee00-510e-11eb-8ca2-a94421ce902c.png)
its getting triggered, but I can't see my console.log..

2021-01-07 16:36 UTC, fritzschoff commented
George said I could test it in the google cloud console, but there are also no logs.. pretty annoying. Will need to unit test but jest is bugged with the wrong types...

2021-01-08 09:51 UTC, phpgeekfr commented on apps/backend-functions/src/main.ts
> +export const scheduledNotifications = functions.pubsub.schedule('*/5 * * * *')// every day at 4 AM
do not commit your  test ;)

2021-01-08 10:27 UTC, fritzschoff commented on apps/backend-functions/src/main.ts
> +export const scheduledNotifications = functions.pubsub.schedule('*/5 * * * *')// every day at 4 AM
haha, promise I won't

2021-01-08 10:27 UTC, fritzschoff commented on apps/backend-functions/src/main.ts
> +export const scheduledNotifications = functions.pubsub.schedule('*/5 * * * *')// every day at 4 AM
could be quite expensive

2021-01-21 14:02 UTC, phpgeekfr commented
> this function is not tested, cause the firebase emulator is currently not able to handle pub sub functions.

It is now.

2021-01-21 14:02 UTC, xmano commented on apps/backend-functions/jest.config.js
>  };
correct coverage directory to insode backend-functions and keep it last for consistency. please.

2021-01-21 14:13 UTC, xmano commented on apps/backend-functions/src/internals/invitations/events.spec.ts
> +    await clearFirestoreData({ projectId: getTestingProjectId() });
I think when emulator is started data is not persisted. So it is ok to remove this.

But make sure to clear data in afterAll()

2021-01-21 14:13 UTC, xmano commented on apps/backend-functions/src/internals/invitations/events.spec.ts
> +    const invitations = [
Can you move this to a fixture file?

This way we can reuse also if needed.

2021-01-21 14:36 UTC, phpgeekfr approved these changes

2021-01-21 15:21 UTC, merged