Implement list page
blockframes/blockframes pull request #4687
Opened 2021-01-08 09:15 UTC by RemcoSimonides

About to fix 4479
This is still work in progress!

2021-01-08 15:39 UTC, GrandSchtroumpf requested changes

2021-01-08 15:39 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/event/list/list.component.ts
>        map(events => events.filter(event => !!event.meta.titleId)),
I think this could be solved now with the `!=` operator

2021-01-08 15:39 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/event/list/list.component.ts
>      const query = ref => ref.orderBy('end').startAt(new Date());
```
ref => ref.where('meta.titleId', '!=', undefined).orderBy('end').startAt(new Date());
```
try undefined, null, "", whatever

2021-01-08 15:39 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/event/list/list.component.html
> +<list-page [items]="timeFrames">
```html
<list-page [items]="events$ | async | toTimeFrame">
  <ng-template listPageListItem let-timeFrame>
    <h2>{{ timeFrame.name }}</h2>
    <ng-container *ngFor="let event of timeFrame.events">
      
    </ng-container>
  </ng-template>
</list-page>
```

2021-01-08 15:39 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/event/list/list.component.ts
> +    this.sub = this.service.queryByType(['screening'], query).pipe(
```typescript
function filterByOrgIds(events: Event[], orgIds: string[]) {
  if (!orgIds?.length) return events;
  return events.filter(event => orgIds.include(event.orgId));
}
....

const orgIds = this.form.valueChanges.pipe(startWith(this.form.value));
const query = ref => ref.where('meta.titleId', '!=', undefined).orderBy('end').startAt(new Date());
this.event$ = this.service.queryByType(['screening'], query).pipe(
  withLatestFrom(orgIds$),
  map(([ events, orgIds ]) => filterByOrgIds(events, orgIds)),
  tap(events => this.setTitle(events.length)))
);

private setTitle(amount: number) {
  amount === 0 ? this.dynTitle.setPageTitle('Screening List', 'Empty') : this.dynTitle.setPageTitle('Screening List');
}
```

2021-01-08 15:39 UTC, GrandSchtroumpf commented on libs/ui/src/lib/list/page/list-page.component.ts
> +@Directive({ selector: '[listPageAppBar]' })
put it back as before and don't for `{read: TemplateRef}`

2021-01-11 13:00 UTC, RemcoSimonides commented on apps/festival/festival/src/app/marketplace/event/list/list.component.ts
>        map(events => events.filter(event => !!event.meta.titleId)),
undefined doesn't work
null also includes the ones with empty string in meta.titleId
'' excludes the ones that are undefined too

2021-01-11 13:01 UTC, RemcoSimonides commented on apps/festival/festival/src/app/marketplace/event/list/list.component.ts
> +    this.sub = this.service.queryByType(['screening'], query).pipe(
Had to use combineLatest() because withLatestFrom() didn't trigger when new values in searchForm.

2021-01-12 09:25 UTC, GrandSchtroumpf requested changes

2021-01-12 09:25 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/event/list/list.component.html
> +  <ng-template listPageEmpty *ngIf="loading">
empty & loading are not the same things. If you need a specific loading you should update the list-page component to support loading the same way as empty.
- loading: `| async` didn't emit yet
- empty: no items

2021-01-12 09:25 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/event/list/list.component.ts
> +        this.loading = false;
It should be managed by the list-page component

2021-01-12 13:29 UTC, RemcoSimonides commented on libs/utils/src/lib/pipes/filter-by-date.pipe.ts
> +    if (!events) return;
In order to return `undefined` instead of `[]` to the list-page component I need to return undefined ☝️ 

The process is coming through this pipe before there are events because of the combineLatest where searchForm triggers from the start

2021-01-12 13:33 UTC, GrandSchtroumpf approved these changes

2021-01-12 13:44 UTC, merged