updated static model
blockframes/blockframes pull request #4719
Opened 2021-01-12 16:24 UTC by fritzschoff

close #2347 
close #4703

2021-01-12 17:56 UTC, phpgeekfr commented on libs/utils/src/lib/static-model/static-model.ts
> +  trailer: 'Trailer',
This also need to be part of the migration

2021-01-13 08:55 UTC, phpgeekfr commented on libs/firebase-utils/src/lib/firestoreMigrations/0048.ts
> +        if(data.originCountries.includes(coteDIvoire) || data.originCountries.includes(antartica)) {
this if can be removed I think since `patchKey` is handling all cases

2021-01-13 08:55 UTC, phpgeekfr commented on libs/firebase-utils/src/lib/firestoreMigrations/0048.ts
> +        if(data?.originalRelease.length) {
`?` is not supposed to be after `originalRelease` instead of `data` ?

2021-01-13 08:56 UTC, phpgeekfr commented on libs/firebase-utils/src/lib/firestoreMigrations/0048.ts
> +                }
I think you want :
```
 return {
                 ...release
                country: patchKey(release.country),
                
                }  
     ```
     
     so country is not overrided by ...release

2021-01-13 08:57 UTC, fritzschoff commented on libs/firebase-utils/src/lib/firestoreMigrations/0048.ts
> +        if(data.originCountries.includes(coteDIvoire) || data.originCountries.includes(antartica)) {
true but I want to minimize the iteration of the objects if it is not necessary

2021-01-13 08:57 UTC, phpgeekfr commented on libs/firebase-utils/src/lib/firestoreMigrations/0048.ts
> +        }
same for `?` and `...location` position

2021-01-13 08:58 UTC, fritzschoff commented on libs/firebase-utils/src/lib/firestoreMigrations/0048.ts
> +                }
true

2021-01-13 08:58 UTC, phpgeekfr commented on libs/firebase-utils/src/lib/firestoreMigrations/0048.ts
> +        const stakeholdersKeys = Object.keys(data?.stakeholders);
why  `data?`

2021-01-13 08:58 UTC, fritzschoff commented on libs/firebase-utils/src/lib/firestoreMigrations/0048.ts
> +        if(data?.originalRelease.length) {
no because if originalRelease doesn't exist on data, it throws

2021-01-13 09:01 UTC, phpgeekfr requested changes

2021-01-13 09:03 UTC, phpgeekfr commented on libs/firebase-utils/src/lib/firestoreMigrations/0048.ts
> +        if(data?.originalRelease.length) {
this should not be `data.originalRelease?.length` ?

2021-01-13 09:03 UTC, fritzschoff commented on libs/firebase-utils/src/lib/firestoreMigrations/0048.ts
> +        const stakeholdersKeys = Object.keys(data?.stakeholders);
why not?

2021-01-13 09:18 UTC, phpgeekfr commented on libs/firebase-utils/src/lib/firestoreMigrations/0048.ts
> +        const stakeholdersKeys = Object.keys(data?.stakeholders);
cuz data is coming from `const data = movie.data() as MovieDocument;` 
So data should not be undefined, unless we have empty movie doc. You can let it but i'm not sure it is usefull

2021-01-13 09:59 UTC, fritzschoff commented
![image](https://user-images.githubusercontent.com/39312833/104436869-67cae800-558e-11eb-8dd6-e1c0f9428760.png)

2021-01-13 09:59 UTC, phpgeekfr approved these changes
LGTM despite bad file indent .

Also instead of 
```
data.originalRelease = data.originalRelease.map(release => {
                return {
                    ...release,
                    country: patchKey(release.country),
                }
            })
  ```
  
  you can do 
  ````
data.originalRelease = data.originalRelease.map(release => ({
                    ...release,
                    country: patchKey(release.country),
            }))
```

2021-01-13 09:59 UTC, fritzschoff commented
![Uploading image.png…]()

2021-01-13 10:58 UTC, merged