Consents collection
blockframes/blockframes pull request #4756
Opened 2021-01-15 14:48 UTC by SamirTouira

Consent collection saves itself correctly in firebase.
Related to : #4327 

How it works : 

To see if the createConsent backend-function works, you can just for example select a file .component.html related to its .component.ts file that you want, and add this code in the html file for the consent button : 

`  <ng-container *ngIf="!(loadingTunnel.asObservable() | async); else loading">
    <a mat-flat-button color="accent" (click)="consent()">Consent!</a>
  </ng-container>`

in its component.ts file, just add this (you can add also the import MatSnackBarModule in the appropriate module.ts file) : 

`
import { ConsentsService } from '@blockframes/consents/+state/consents.service';
import { MatSnackBar } from '@angular/material/snack-bar';

  constructor(
    private consentsService: ConsentsService,
    private snackbar: MatSnackBar
  ) {}

  async consent() {
    const status = await this.consentsService.createConsent('share', 'Ar293JRrE20');
    if (status === true) {
      this.snackbar.open('Consent succefully created !', 'close', { duration: 5000 });
    } else {
      this.snackbar.open('Consent has not been created.', 'close', { duration: 5000 });
    }
  }
`

2021-01-15 15:07 UTC, phpgeekfr requested changes
Create a type in consents.firestore 
```
export type ConsentType = 'access' | 'share';
```

And replace all occurences of ` 'access' | 'share';`

2021-01-15 15:07 UTC, phpgeekfr commented on apps/backend-functions/src/consent.ts
> +export const createConsent = async (
can you try with a transaction instead ? 
```
export const createConsent = async (
  data: { consentType: 'access' | 'share'; ip: string; docId: string; filePath?: string },
  context: CallableContext
): Promise<boolean> => {
  const { consentType, ip, docId, filePath } = data;

  if (!context?.auth) {
    throw new Error('Permission denied: missing auth context.');
  }

  await db.runTransaction(async tx => {
    const userSnap = await tx.get(db.doc(`users/${context.auth.uid}`));
    const userData = userSnap.data() as PublicUser;

    if (!userData) {
      throw new Error('Invalid user');
    }
    if (!userData.orgId) {
      throw new Error('Invalid organization');
    }

    if (!docId) {
      throw new Error('Undefined docId');
    }
    if (!ip) {
      throw new Error('Undefined ip');
    }

    let consent = _createConsent({
      id: userData.orgId,
    });

    const consentSnap = await tx.get(db.doc(`consents/${consent.id}`));
    const consentData = consentSnap.data() as any;

    if (!!consentData) {
      consent = _createConsent(consentData);
    }

    if (consentType === 'access') {
      if (!filePath) {
        throw new Error('Invalid filePath');
      }

      const access = createAccess({
        lastName: userData.lastName,
        firstName: userData.firstName,
        email: userData.email,
        userId: userData.uid,
        date: new Date(),
        filePath,
        docId,
        ip,
      });

      consent.access.push(access);
    } else if (consentType === 'share') {
      const share = createShare({
        lastName: userData.lastName,
        firstName: userData.firstName,
        email: userData.email,
        userId: userData.uid,
        date: new Date(),
        docId,
        ip,
      });

      consent.share.push(share);
    }
    tx.set(consentSnap.ref, consent);
  });

  return true;
};
```

2021-01-15 15:11 UTC, SamirTouira commented on libs/consents/src/test-setup.ts
> +import 'jest';
because I've seen in the others libs this line added, so I thought it was necessary. if not, I can remove this line

2021-01-15 15:19 UTC, phpgeekfr commented on libs/consents/src/test-setup.ts
> +import 'jest';
ok. Some have it and some don't. Maybe @xmano can tell more

2021-01-15 15:22 UTC, xmano commented on libs/consents/src/test-setup.ts
> +import 'jest';
If needed to compile then use it otherwise import jest can be removed

2021-01-19 08:49 UTC, phpgeekfr approved these changes

2021-01-19 10:52 UTC, merged