merge pdf viewer & puppet, refactor pdf control
blockframes/blockframes pull request #4775
Opened 2021-01-19 08:49 UTC by pldespaigne

related to #4002

2021-01-19 16:07 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/event/session/session.component.ts
> +            let control: MeetingMediaControl;
if you're not reusing it after the switch, remove the let

2021-01-19 16:07 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/event/session/session.component.ts
> +                  meta  = { ...event.meta, controls: { ...event.meta.controls, [event.meta.selectedFile]: control } };
create a variable `controls`: 
```typescript
const control = await this.createPdfControl(file, event.id);
const controls = { ...event.meta.controls, [event.meta.selectedFile]: control };
const meta = { ...event.meta, controls };
```

2021-01-19 16:14 UTC, pldespaigne commented on apps/festival/festival/src/app/marketplace/event/session/session.component.ts
> +            let control: MeetingMediaControl;
I can't use `const`  here because it must be initialized.
And if I declare `const` inside `case :` I got a block-scope re-declaration error.

2021-01-20 10:51 UTC, GrandSchtroumpf commented on libs/media/src/lib/file/controls/controls.component.ts
> +    this.eventService.update({
Why not doing : 
```typescript
const event = this.event;
event.meta.controls[this.event.meta.selectedFile] = control;
this.eventService({ event });
```

2021-01-20 10:51 UTC, GrandSchtroumpf commented on libs/media/src/lib/file/puppets/puppets.component.ts
> +  @Input() set event(value: Event<Meeting>) {
Why do you need to do that ?

2021-01-20 10:51 UTC, GrandSchtroumpf commented on libs/media/src/lib/pdf/control/control.component.html
> +  {{ control.currentPage }} / {{ control.totalPages }}
could you put that in a span ?

2021-01-20 11:03 UTC, GrandSchtroumpf requested changes

2021-01-20 11:03 UTC, GrandSchtroumpf commented on libs/media/src/lib/video/viewer/viewer.component.ts
> +declare const jwplayer: any;
would be nice to have a nice interface at some point when we'll use the `on` methods

2021-01-20 11:03 UTC, GrandSchtroumpf commented on libs/media/src/lib/video/viewer/viewer.component.ts
> +    this.waitForPlayerReady = new Promise(res => this.signalPlayerReady = res);
I don't get this...

2021-01-20 12:33 UTC, pldespaigne commented on libs/media/src/lib/video/viewer/viewer.component.ts
> +declare const jwplayer: any;
I think the best would be to open a PR for `@type/jwplatform` so that everyone could benefit form the typing.

2021-01-20 16:10 UTC, pldespaigne commented on libs/media/src/lib/video/viewer/viewer.component.ts
> +    this.waitForPlayerReady = new Promise(res => this.signalPlayerReady = res);
It's a promise mechanism to prevent triggering action on the player before it's ready.
I did it like this so I'm able to create the promise and resolve it from different places in the code

```TypeScript
// instantiate promise and it's resolver
private signalPlayerReady: () => void;
private waitForPlayerReady: Promise<void>;

...

// assign resolver to this.signalPlayerReady
this.waitForPlayerReady = new Promise(res => this.signalPlayerReady = res);

...

await this.waitForPlayerReady;

...

// resolve the promise
this.player.on('ready', () => this.signalPlayerReady());
```

2021-01-20 16:34 UTC, GrandSchtroumpf approved these changes

2021-01-20 16:34 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/event/session/session.component.scss
> +        // remove the line bellow to break everything
Change by "when used with a flex parent, we need to set a min-height"

2021-01-20 16:34 UTC, GrandSchtroumpf commented on libs/media/src/lib/pdf/viewer/viewer.component.scss
> +    place-content: center;
Didn't you want `justify-content` ?

2021-01-20 16:34 UTC, GrandSchtroumpf commented on libs/media/src/lib/video/control/control.component.html
> +  {{ control.position | timecode }}
Can you put this one and the one below in a span ?

2021-01-20 16:34 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/event/session/session.component.html
> +                <span>
why do you need a span ?

2021-01-20 16:34 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/event/session/session.component.scss
> +      margin: 8px 0 8px 16px;
change for : 
```css
margin: 8px 0;
margin-right: 16px;
```

2021-01-20 17:10 UTC, merged