toggles could be uncheck
blockframes/blockframes pull request #4808
Opened 2021-01-22 10:13 UTC by SamirTouira

related to: #4789 

The buttons Premiere can be unchecked now

2021-01-22 10:23 UTC, fritzschoff requested changes

2021-01-22 10:23 UTC, fritzschoff commented on libs/movie/src/lib/movie/form/reviews/reviews.component.html
> +                #group="matButtonToggleGroup" (change)="onChange()" (click)="onClick(group)">
it is a bit redundant if you setting on every change the variable to true.
can you try something like that?
```typescript
,mat-button-toggle ... (change)="isChecked($event);

and in your ts file

isChecked(change: MatButtonToggleChange) {
if(this.form.get('premiereType').value === change.value) this.form.get('premiereType').reset();
}

2021-01-22 10:23 UTC, fritzschoff commented on libs/movie/src/lib/movie/form/reviews/reviews.component.html
> +                #group="matButtonToggleGroup" (change)="onChange()" (click)="onClick(group)">
if so, then you also can delete the ref variable group and the click event listener.

2021-01-22 10:23 UTC, fritzschoff commented on libs/movie/src/lib/movie/form/reviews/reviews.component.ts
> +  toggleChanged: boolean;
you can remove that

2021-01-22 11:29 UTC, SamirTouira commented on libs/movie/src/lib/movie/form/reviews/reviews.component.html
> +                #group="matButtonToggleGroup" (change)="onChange()" (click)="onClick(group)">
It strangly doesn't work. its toLabel('premiereType' isn't recognized... I don't really know how to get the value of these Premiere buttons after have tried many things

2021-02-02 15:42 UTC, fritzschoff approved these changes

2021-02-02 16:32 UTC, merged