Issue running time
blockframes/blockframes pull request #4821
Opened 2021-01-26 13:51 UTC by fritzschoff

2021-01-26 14:34 UTC, phpgeekfr reviewed
LGTM for the migration & model part

2021-01-26 14:34 UTC, phpgeekfr commented on libs/firebase-utils/src/lib/firestoreMigrations/0051.ts
> +    if (movie.contentType === 'serie') {
you could add `else if`

2021-01-26 14:34 UTC, phpgeekfr commented on libs/movie/src/lib/movie/+state/movie.firestore.ts
> +  series?: string
Can you give an example  of interface `Title` for  a serie (The simpsons maybe ;) ) ?

2021-01-26 14:44 UTC, fritzschoff commented on libs/movie/src/lib/movie/+state/movie.firestore.ts
> +  series?: string
```
{
original: Les Simpsons,
international: The simpsons,
series: The simpsons
}
```

2021-01-26 14:57 UTC, fritzschoff commented on libs/movie/src/lib/movie/+state/movie.firestore.ts
> +  series?: string
https://www.google.de/url?sa=i&url=https%3A%2F%2Fit-admin.at%2F&psig=AOvVaw19jdt-btKNUr4Nx-5zgPFC&ust=1611759454355000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCLjFkoDuue4CFQAAAAAdAAAAABAD

2021-01-26 14:58 UTC, fritzschoff commented on libs/movie/src/lib/movie/+state/movie.firestore.ts
> +  series?: string
![logo-default](https://user-images.githubusercontent.com/39312833/105861672-438bf400-5fef-11eb-90d3-179f5a3a2665.jpg)

2021-01-26 15:27 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/main/main.component.html
> +      <article flxLayout="row" fxLayoutAlign="start start" fxLayoutGap="24px"
Use `<ng-template #series>` instead: 
```typescript
<ng-container *ngIf="!(form | isType: 'series') else series">

</ng-container>

<ng-template #series>

</ng-tempate>
```

2021-01-26 15:27 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/pipes/is-series.pipe.ts
> +@Pipe({
Create a more generic pipe, like hasStatus

2021-01-26 15:27 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/+state/movie.firestore.ts
> +  series?: string
What is "series" ? Is it the "season name" ?

2021-01-26 15:35 UTC, fritzschoff commented on libs/movie/src/lib/movie/pipes/is-series.pipe.ts
> +@Pipe({
not sure where the hasStatus pipe is generic

2021-01-26 15:35 UTC, fritzschoff commented on libs/movie/src/lib/movie/+state/movie.firestore.ts
> +  series?: string
yes

2021-01-26 15:35 UTC, fritzschoff commented on libs/movie/src/lib/movie/form/main/main.component.html
> +      <article flxLayout="row" fxLayoutAlign="start start" fxLayoutGap="24px"
you don't want to nothing if content Type is series, no need for a template here

2021-01-27 08:44 UTC, GrandSchtroumpf requested changes

2021-01-27 08:44 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/+state/movie.firestore.ts
> +  series?: string
As discussed in the catalog channel in slack, the `season` should be a number.
Add a comment about the params to precise it's the index of the season if the content type is "series"

2021-01-27 08:44 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/main/main.component.html
> +      <article flxLayout="row" fxLayoutAlign="start start" fxLayoutGap="24px"
When you've got something like : 
```html
<ng-container *ngIf="a"></ng-container>
<ng-container *ngIf="!a"></ng-container>
```
Except if you can inline them, you should use : 
```html
<ng-container *ngIf="a else noA"></ng-container>
<ng-template #notA></ng-template>
```
This is especially true if you open subscriptions with async

2021-01-27 08:44 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/pipes/is-series.pipe.ts
> +@Pipe({
It's generic because you can pass arguments. I gave an example in a comment above: 
```html
<ng-container *ngIf="!(form | isType: 'series') else series">
```
Here `isType` take an argument giving us the ability to perform different actions depending on the type

2021-01-27 08:55 UTC, fritzschoff commented on libs/movie/src/lib/movie/+state/movie.firestore.ts
> +  series?: string
we have decided to get rid of season, remember the call yesterday after the bi monthly? and we want series to a number, but not for now.

2021-01-27 09:19 UTC, fritzschoff commented on libs/movie/src/lib/movie/form/main/main.component.html
> +      <article flxLayout="row" fxLayoutAlign="start start" fxLayoutGap="24px"
![image](https://user-images.githubusercontent.com/39312833/105970016-2efc3a00-6089-11eb-80e5-8516d79fc39a.png)
 looks good ?

2021-01-27 09:38 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/+state/movie.firestore.ts
> +  series?: string
We want the number now, but we don't want to order by season number now.

2021-01-27 09:46 UTC, fritzschoff commented on libs/movie/src/lib/movie/form/main/main.component.html
> +      <ng-container *ngIf="form.contentType.valueChanges | async | isType: 'series'; else notSeries">
![image](https://user-images.githubusercontent.com/39312833/105973315-e2b2f900-608c-11eb-9dc8-5b7d9afe91b2.png)
@2amarkina can you approve this change?

2021-01-27 09:50 UTC, 2amarkina commented on libs/movie/src/lib/movie/form/main/main.component.html
> +      <ng-container *ngIf="form.contentType.valueChanges | async | isType: 'series'; else notSeries">
ok !  just to be sure for the order : 

1. international title
2. original title
3. title ref
4. content type
5. nb of episodes
6. series name
7. running time
8. “status” - if it is there

2021-01-27 09:54 UTC, GrandSchtroumpf approved these changes

2021-01-27 09:54 UTC, fritzschoff commented on libs/movie/src/lib/movie/form/main/main.component.html
> +      <ng-container *ngIf="form.contentType.valueChanges | async | isType: 'series'; else notSeries">
![image](https://user-images.githubusercontent.com/39312833/105974213-fd39a200-608d-11eb-940b-975fa40d6496.png)
@GrandSchtroumpf @2amarkina

2021-01-27 09:55 UTC, fritzschoff commented on libs/movie/src/lib/movie/form/main/main.component.html
> +      <ng-container *ngIf="form.contentType.valueChanges | async | isType: 'series'; else notSeries">
![image](https://user-images.githubusercontent.com/39312833/105974422-2b1ee680-608e-11eb-98df-72303b632d83.png)

2021-01-27 13:07 UTC, merged