Reminder screening emails
blockframes/blockframes pull request #4827
Opened 2021-01-28 12:59 UTC by Mussuranae

Send 2 emails : first, one day before the event starts, second, one hour before the event starts

2021-01-28 13:36 UTC, phpgeekfr requested changes

2021-01-28 13:36 UTC, phpgeekfr commented on apps/backend-functions/src/internals/invitations/events.ts
> +    .get();
Maybe yan you create a function  like  
```
fetchEventsStaringIn(from: number, to: number) {
  return await db.collection('events')
      .where('start', '>=', new Date(Date.now() + from))
       .where('start', '<', new Date(Date.now() +to))
       .get();
}
```

2021-01-28 13:36 UTC, phpgeekfr commented on apps/backend-functions/src/internals/invitations/events.ts
> +  invitationsHourSnaps.forEach(snap => snap.docs.forEach(doc => invitationsHour.push(doc.data() as InvitationDocument)));
Same, create a function that takes `eventsDayCollection.docs` or `eventsHourCollection.docs`
and returns invitations

2021-01-28 13:36 UTC, phpgeekfr commented on apps/backend-functions/src/internals/invitations/events.ts
> +  }
Same, create a function that takes invitations ( invitationsDay or invitationsHour) and notificationType as input

2021-01-28 13:36 UTC, phpgeekfr commented on apps/backend-functions/src/notification.ts
>        // await sendMailFromTemplate({ to: user.email, templateId: 'TODO#4046', data: {} }, appKey); // @TODO #4046
Transform into a switch/case with 

```
    await sendMail({ to: user.email, subject: notification.type, text: 'test' })
    .then(_ => notification.email.isSent = true)
    .catch(e => notification.email.error = e.message);
  ``` 
  as try catch default

2021-01-28 13:36 UTC, phpgeekfr commented on apps/backend-functions/src/notification.ts
> +        .catch(e => { notification.email.error = e.message });
you can remove `{` and  `}`

````
  .then(_ => notification.email.isSent = true )
     .catch(e => notification.email.error = e.message );
  ```

2021-01-28 13:36 UTC, phpgeekfr commented on apps/backend-functions/src/notification.ts
> +        .catch(e => { notification.email.error = e.message });
only difference with above is templateId, create a function to not repeat yourself.
Then in the switchCase you can do
```
      switch (notification.type) {
        case 'eventIsAboutToStart':
          yourNewFunction(templateIds.eventReminder.oneHour)
          break
        case 'oneDayReminder':
         yourNewFunction(templateIds.eventReminder.oneDay)
          break;
      
        default:

          await sendMail({ to: user.email, subject: notification.type, text: 'test' })
          .then(_ => notification.email.isSent = true)
          .catch(e => notification.email.error = e.message);
          break;
      }
```

For `await sendMailFromTemplate(template, 'festival') // TODO guess appKey`
we have user  so you can use `getOrgAppKey`

2021-01-28 13:36 UTC, phpgeekfr commented on libs/notification/src/lib/+state/notification.firestore.ts
>    'eventIsAboutToStart' |
please add comment
 // 1h (or 15 min ?) efore event start
// 24h before event start

2021-01-28 13:36 UTC, phpgeekfr commented on package-lock.json
>          },
you pushed package-lock.json but no changes in package.json, can you remove from commit ?

2021-01-28 17:00 UTC, phpgeekfr approved these changes

2021-01-29 08:08 UTC, Mussuranae commented on apps/backend-functions/src/internals/invitations/events.ts
>    const db = admin.firestore();
Nop, good catch !

2021-01-29 08:31 UTC, merged