4693 import analytics in firestore and use
blockframes/blockframes pull request #4828
Opened 2021-01-28 14:22 UTC by RemcoSimonides

- [ ] Create rules so movie owners can read analytics

2021-01-28 14:26 UTC, RemcoSimonides commented on libs/movie/src/lib/movie/components/movie-analytics-chart/movie-analytics-chart.component.ts
> +    this.delayTime$
In `home.component.ts` this component is used. When that page is first loaded, it triggers `orgQuery.selectActive()` 3 times, causing the graphs to rerender multiple times. Therefore I kept this workaround with a delay that waits 3 seconds before showing the graphs. Preferably I'd rather see the `orgQuery.selectActive()` to trigger only once but I didn't manage to do this yet. Is this a known issue? Or do you know a solution? @GrandSchtroumpf

2021-01-28 14:29 UTC, RemcoSimonides commented on libs/utils/src/lib/analytics/analytics.store.ts
> +}
This `analytics.store.ts` and `analytics.service.ts` are the only added files. Do you think it's better to create a separate lib for analytics?

I could move components and interfaces for analytics from Movie lib to Analytics lib then. Same for org, event or whatever more analytics will be added later.

2021-01-28 16:19 UTC, GrandSchtroumpf requested changes

2021-01-28 16:19 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/home/home.component.ts
> +      switchMap(({ id }) => this.movieService.valueChanges(fromOrg(id))),
You're doing twice the query. This is not a good idea. Better would be to load the analytics directly from the HTML with a pipe : 
```html
<ng-template colRef="anaytics" let-movie="item">{{ movie.id | getTitleAnalytics | async }}</ng-template>
```
And the pipe : 
```typescript
@Pipe({ name: 'getTitleAnalytics' })
export class GetTitleAnalyticsPipe implements PipeTransform {
  constructor(private analyticsService: AnalyticsService) {}
  transform(titleId: string) {
    return this.analyticsService.valueChanges(titleId);
  }
}
```

2021-01-28 16:19 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/dashboard/title/activity/activity.component.ts
> +    this.movieAnalytics$ = this.analyticsService.valueChanges([this.movieId]);
I think you don't need the array in the params of `valueChanges` here.

2021-01-28 16:19 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/components/movie-analytics-chart/movie-analytics-chart.component.ts
> +    this.delayTime$
I would have to do it with you directly I think to understand better the whole situation.

2021-01-28 16:19 UTC, GrandSchtroumpf commented on libs/ui/src/lib/dashboard/pages/home/home.component.ts
> +    this.movieAnalytics$ = this.orgQuery.selectActive().pipe(
We should leverage the pipe system described above I think. It would make the code easier. Let's discuss that during a call.

2021-01-28 16:19 UTC, GrandSchtroumpf commented on libs/utils/src/lib/analytics/analytics.store.ts
> +}
We could create a lib if we've got some analytics related components. But for now we can keep it here.

2021-01-29 09:04 UTC, RemcoSimonides commented on apps/catalog/catalog/src/app/dashboard/home/home.component.ts
> +      switchMap(({ id }) => this.movieService.valueChanges(fromOrg(id))),
On the `home.component` the movieAnalytics is sent as one to movie analytics chart component
`<movie-analytics-chart [analyticsData]="movieAnalytics$ | async"></movie-analytics-chart>`
So it can't be split up here

There is already a AnalyticsPipe which does what you suggest here. It is used on dashboard/titles page.
`<ng-template colRef="view" let-movie="item">{{ movie.id | getViews | async }}</ng-template>`

2021-01-29 15:38 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/title/activity/activity.component.ts
> +    this.movieAnalytics$ = this.analyticsService.valueChanges([this.movieId]);
If I pass in an array, it returns an array and that's what I need

2021-01-29 16:44 UTC, GrandSchtroumpf approved these changes

2021-01-29 16:44 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/home/home.component.ts
> +      switchMap(ids => this.analyticsService.valueChanges(ids))
You forgot to add the title : 
```typescript
tap(ids => ids.length ? this.dynTitle.setPageTitle('Seller\'s Dashboard') : this.dynTitle.setPageTitle('New Title'))
```

2021-02-01 09:12 UTC, merged