New File architecture - Front end
blockframes/blockframes pull request #4836
Opened 2021-01-29 17:07 UTC by pldespaigne

related to #4002

2021-02-02 10:33 UTC, GrandSchtroumpf commented on libs/media/src/lib/+state/file-uploader.service.ts
> +          console.warn('INVALID METADATA: upload will be skipped!');
You don't want to see it in sentry ?

2021-02-02 10:33 UTC, GrandSchtroumpf commented on libs/media/src/lib/+state/file-uploader.service.ts
> +    const flattenedTasks = ([] as AngularFireUploadTask[]).concat(...tasks);
We are not using flat already in the project ? You can update the tsconfig to support flat.

2021-02-02 10:33 UTC, GrandSchtroumpf commented on libs/media/src/lib/file/file-new-uploader/file-uploader.component.ts
> +  @Input() set allowedFileType(fileType: AllowedFileType | AllowedFileType[]) {
can you rename `accept` like the `<input type="file" accept="..." />`.
as `@Input` is an exposed API I think it's better to have it to accept, and rename the local `public accept` to something else.

2021-02-02 10:33 UTC, GrandSchtroumpf commented on libs/media/src/lib/file/file-new-uploader/file-uploader.component.ts
> +    console.log(this.displayFile); // TODO REMOVE DEBUG LOG
reove

2021-02-02 10:33 UTC, GrandSchtroumpf commented on libs/media/src/lib/file/file-new-uploader/file-uploader.component.ts
> +      this.state = 'ready';
add tabulation

2021-02-02 10:33 UTC, GrandSchtroumpf commented on libs/media/src/lib/file/file-new-uploader/file-uploader.component.ts
> +  ngOnChanges(changes: SimpleChanges) { // TODO REMOVE DEBUG LOG
remove

2021-02-02 10:33 UTC, GrandSchtroumpf commented on libs/media/src/lib/file/file-new-uploader/file-uploader.component.ts
> +    console.log('selected', files, this.metadata); // TODO REMOVE DEBUG LOG
remove

2021-02-02 10:33 UTC, GrandSchtroumpf commented on libs/media/src/lib/file/file-new-uploader/file-uploader.component.ts
> +      if (!files) {
You can refactor

2021-02-03 09:42 UTC, pldespaigne commented on libs/media/src/lib/+state/file-uploader.service.ts
> +          console.warn('INVALID METADATA: upload will be skipped!');
I don't think this will be logged into sentry, this console.warn are just useful for devs to debug anyway, I can remove them if you want

2021-02-09 16:14 UTC, GrandSchtroumpf requested changes

2021-02-09 16:14 UTC, GrandSchtroumpf commented on libs/media/src/lib/file/viewers/viewers.component.ts
> +  @Input() storagePath: string;
should be only "ref"

2021-02-09 16:14 UTC, GrandSchtroumpf commented on libs/media/src/lib/image/directives/image.directive.ts
> +  @Input() set storagePath(value: string) {
Put back `ref`

2021-02-09 16:14 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/+state/movie.model.ts
> +    financialDetails: params.financialDetails ?? { storagePath: '', privacy: 'protected' },
```typescript
function createMedia(media: Partial<Media> = {}) {
  return {
    storagePath: '',
    ...media
  }
}
```

2021-02-09 16:14 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/components/prize-card/prize-card.component.html
> +<!-- <img [storagePath]="prize.logo.storagePath" asset="empty_festival.webp" alt="Festival brand logo"> -->
Remove prize.logo & put img back.

2021-02-09 16:14 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/media-files/media-files.component.ts
> +  metadatas: Record<string, FileMetaData> = {
find a way to refactor. For example: 
```typescript
getMetadata('protected/movies/${docId}/promotional.presentation_deck')
```

2021-02-09 16:14 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/media-files/media-files.component.ts
> +  storagePaths: Record<string, string> = {
I wouldn't change the path in this PR. Looks dangerous.

2021-02-09 16:14 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/media-videos/media-videos.component.ts
> +    // this.sub = this.movieQuery.selectActive().subscribe((movie: Movie) => {
Clean ?

2021-02-09 16:14 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/media-videos/media-videos.component.ts
> +  // getPath(pathPart: 'screener' | 'otherVideos') {
clean ?

2021-02-09 16:14 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/movie.form.ts
> +// function createMovieHostedVideoControl(hostedVideo: Partial<HostedVideo> = {}, metadata?: Partial<FileMetaData>) {
clean ?

2021-02-09 16:51 UTC, phpgeekfr commented on apps/backend-functions/src/media.ts
> +        const match = (eventData.meta as Meeting).files.some(file => file.storagePath === storagePath);
Sorry I don't get your question

2021-03-04 17:23 UTC, closed without merging