Refactor cropper
blockframes/blockframes pull request #4930
Opened 2021-02-12 14:41 UTC by RemcoSimonides

State issue number in your PR to close it when PR merged: issue #XXX
e.g. : "Resolve the bundle size ❤️: issue #1234"

2021-02-12 15:01 UTC, RemcoSimonides commented on libs/media/src/lib/file/file-new-uploader/file-uploader.component.ts
> +  private computeState() {
Actually double in here now... removing it

2021-02-12 15:02 UTC, RemcoSimonides commented on libs/movie/src/lib/movie/components/picture-upload/picture-upload.component.ts
> +    this.moviePictureForm.get('still_photo').push({ storagePath: '' });
Not sure if `{ storagePath: '' }` is needed. Could just be `''`?

2021-02-12 15:04 UTC, RemcoSimonides commented on libs/movie/src/lib/movie/form/media-files/media-files.component.ts
> +
Removing this too

2021-02-12 15:56 UTC, pldespaigne requested changes

2021-02-12 15:56 UTC, pldespaigne commented on libs/movie/src/lib/movie/components/picture-upload/picture-upload.component.ts
> +    this.moviePictureForm.get('still_photo').push({ storagePath: '' });
I think it should be `push(new StorageFileForm())`

2021-02-15 08:35 UTC, pldespaigne approved these changes

2021-02-15 08:45 UTC, merged