fix  TypeError: templateRef.createEmbeddedView is not a function
blockframes/blockframes pull request #4974
Opened 2021-02-19 12:01 UTC by phpgeekfr

2021-02-19 12:02 UTC, phpgeekfr commented on libs/ui/src/lib/list/page/list-page.component.html
> +      <ng-content [ngTemplateOutlet]="appBar"></ng-content>
Issue is solved but now sure if this is the right thing to do. Can you confirm @RemcoSimonides  ?

2021-02-22 08:54 UTC, RemcoSimonides requested changes

2021-02-22 08:54 UTC, RemcoSimonides commented on libs/ui/src/lib/list/page/list-page.component.html
> +      <ng-content [ngTemplateOutlet]="appBar"></ng-content>
`ngTemplateOutlet` is not an attribute of `ng-content`. You can remove the attribute and it will still work (somehow)
The source of the issue is caused by this change: https://github.com/blockframes/blockframes/commit/c495a445e66dae4e0c367985ffe3649e2f59349f
In which 
` @ContentChild(PageAppBarSearchDirective) appBar: PageAppBarSearchDirective;` doesn't have `{ read: TemplateRef }` in there. That's what is causing the error. If you add `{ read: TemplateRef }`, then `*ngIf="!!appBar"` doesn't work anymore.

@GrandSchtroumpf  do you have an idea how to fix this?

2021-02-23 11:11 UTC, phpgeekfr commented
So I can just remove it ? Since it still works with only `<ng-content></ng-content>`

2021-02-23 12:46 UTC, RemcoSimonides requested changes

2021-02-23 12:46 UTC, RemcoSimonides commented on libs/ui/src/lib/list/page/list-page.component.html
> +      <ng-content></ng-content>
Alright, I got it. Add a select
`<ng-content select="list-page-app-bar"></ng-content>`

2021-02-23 13:01 UTC, RemcoSimonides approved these changes

2021-02-23 13:33 UTC, merged