Fix E2E issues in CI
blockframes/blockframes pull request #5033
Opened 2021-02-27 14:11 UTC by xmano

Run tests for all apps
Use chrome browser as default for test instead of electron

2021-02-27 14:37 UTC, xmano commented
Need to update Docker Image to include latest chrome browser:

```
# The image shall be pushed to dockerhub:
#    docker build -t blockframes/ci:latest .
#    docker push blockframes/ci:latest
```

I have to understand this step and will continue fixing the issue after this.

2021-03-02 11:38 UTC, xmano commented
I don't have permission to push Docker image to blockframes/ci
Let me know how to resolve this.

I think we can go ahead with the config of E2E with chrome browser.

2021-03-02 13:09 UTC, phpgeekfr commented on angular.json
>          "lint": {
can you revert the "format" changes ? so we only see what was updated?

2021-03-02 13:09 UTC, phpgeekfr commented on .circleci/config.yml
> +      - image: zenmano/ci:browsers-latest
I think we should stick with blockframes image. Is this for test purposes?

2021-03-02 13:09 UTC, phpgeekfr commented on apps/financiers/financiers-e2e/src/integration/app.spec.ts
> +  it.skip('should display welcome message', () => {});
you skipped it because it crash ?

2021-03-02 13:17 UTC, xmano commented on angular.json
>          "lint": {
Ok will do it

2021-03-02 13:18 UTC, xmano commented on .circleci/config.yml
> +      - image: zenmano/ci:browsers-latest
Yes i need a way to publish to blockframes. Maybe @george43g can help here?

2021-03-02 13:19 UTC, xmano commented on apps/financiers/financiers-e2e/src/integration/app.spec.ts
> +  it.skip('should display welcome message', () => {});
Tests are not ready.. We need to add this later. Not in this PR scope.

2021-03-02 13:35 UTC, phpgeekfr commented on .circleci/config.yml
> +      - image: zenmano/ci:browsers-latest
yes, ask @george43g for this.

2021-03-17 07:11 UTC, george43g requested changes

2021-03-17 07:11 UTC, george43g commented on angular.json
> -            "tsConfig": [
definitely revert all of these formatting changes

2021-03-17 07:11 UTC, george43g commented on .circleci/config.yml
> -      - image: blockframes/ci:latest
revert these changes as well

2021-03-17 07:11 UTC, george43g commented on .circleci/Dockerfile
> +FROM circleci/node:12-browsers
and revert these as well. I will add it in and push and merge it in now

2021-03-17 07:35 UTC, xmano commented on .circleci/Dockerfile
> +FROM circleci/node:12-browsers
ok

2021-03-17 07:35 UTC, xmano commented on .circleci/config.yml
> -      - image: blockframes/ci:latest
ok

2021-03-17 09:23 UTC, xmano commented on .circleci/config.yml
> +      - image: zenmano/ci:browsers-latest
ok

2021-03-17 09:39 UTC, george43g approved these changes

2021-03-17 09:40 UTC, phpgeekfr commented
Finally, thanks :)

2021-03-17 09:43 UTC, phpgeekfr commented on apps/financiers/financiers-e2e/tsconfig.json
> +    "types": ["cypress", "node", "cypress-wait-until"],
extra comma here

2021-03-17 09:45 UTC, xmano commented on apps/financiers/financiers-e2e/tsconfig.json
> +    "types": ["cypress", "node", "cypress-wait-until"],
removed

2021-03-17 11:12 UTC, merged