Update org rules
blockframes/blockframes pull request #5483
Opened 2021-04-05 11:15 UTC by xmano

Create unit-tests for organization security rules.

2021-04-08 12:09 UTC, xmano commented
All tests are passing 

![image](https://user-images.githubusercontent.com/8731418/114024155-580f2700-9891-11eb-92e5-595e9c5d8edb.png)

2021-04-08 14:36 UTC, xmano commented
Closing another PR that I had opened by mistake:
https://github.com/blockframes/blockframes/pull/5484

Will continue the development here due to conflicts there.

2021-04-09 10:12 UTC, phpgeekfr requested changes

2021-04-09 10:12 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +      'uid-user2': 'admin',
uid-user2 is member of org `O001`. So it should not be referenced here

2021-04-09 10:12 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +      'uid-user2': 'member',
uid-user2 is member of org `O001`. So it should not be referenced here

2021-04-09 10:12 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +    userIds: ['uid-c8'],
'uid-c8' is already part of 'orgs/O005' it should not be member of another org

2021-04-09 10:34 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +      'uid-user2': 'member',
since `uid-c8` is orgMember of `O005` it should be referenced here

2021-04-09 10:49 UTC, xmano commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +    userIds: ['uid-c8'],
Removed uid-c8 from O005. So this case is solved.

2021-04-09 11:19 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/organization.spec.ts
> +//Carts sub collection
I don't think the cart sub-collection is used in front..

2021-04-09 11:21 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/organization.spec.ts
> +//Carts sub collection
Just checked with  @GrandSchtroumpf . cart sub collection is not used. I will make a PR to clean code

2021-04-09 11:28 UTC, xmano commented on apps/rules/src/tests/firestore/organization.spec.ts
> +//Carts sub collection
I have written the tests for the code that exists. If needed we could remove both.

2021-04-09 11:32 UTC, xmano commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +      'uid-user2': 'admin',
created a new admin 'uid-admin4' so uid-user2 is cleared from here.

2021-04-09 12:10 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +  'permissions/O004': {
given existing test in `apps/rules/src/tests/firestore/permission.spec.ts`  'permissions/O004' should not exist because we have a test where we create it alongside with org..

2021-04-09 12:13 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +  'orgs/O004': {
same here .. `orgs/O004` is created in `'org not yet created, should be able to create document` so creating it here will make previous test fall

2021-04-09 12:19 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/organization.spec.ts
> +//Carts sub collection
code that exists but it not used.. please remove tests

2021-04-09 12:52 UTC, xmano commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +  'orgs/O004': {
Separated new org creation to orgId 'O0X4'

2021-04-09 12:52 UTC, xmano commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +  'permissions/O004': {
Updated test.. removed the conflict.

2021-04-09 12:59 UTC, xmano commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +  'permissions/O004': {
Corrected this in permission test with O0X4

2021-04-09 13:00 UTC, xmano commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +      'uid-user2': 'admin',
created uid-admin4 for this.

2021-04-09 13:00 UTC, xmano commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +      'uid-user2': 'member',
uid-user5 created

2021-04-09 13:01 UTC, xmano commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +    userIds: ['uid-c8'],
removed from O005 so should be ok for O003

2021-04-09 13:01 UTC, xmano commented on apps/rules/src/tests/firestore/organization.spec.ts
> +//Carts sub collection
Removing the tests - need to remove subcollection in a future PR.

2021-04-09 13:04 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/organization.spec.ts
> +      const cartDocRef = db.doc('orgs/O001');
cartDocRef ?

2021-04-09 13:04 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +  'orgs/O001/carts/C001': {
not needed

2021-04-09 13:06 UTC, xmano commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +  'orgs/O001/carts/C001': {
removed it.

2021-04-09 13:08 UTC, xmano commented on apps/rules/src/tests/firestore/organization.spec.ts
> +      const cartDocRef = db.doc('orgs/O001');
changed to orgDocRef

2021-04-09 13:09 UTC, xmano commented on apps/rules/src/tests/firestore/organization.spec.ts
> +//Carts sub collection
removed

2021-04-09 13:37 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +    orgId: 'O005'
uid-user5 have `orgId: 'O005'` but user id is not inside `'orgs/O005` . not logical

2021-04-09 13:38 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +    orgId: 'O006',
same as `uid-user5 have orgId: 'O005' but user id is not inside 'orgs/O005 . not logical`

2021-04-09 13:38 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +    uid: 'uid-admin4',
same as `uid-user5 have orgId: 'O005' but user id is not inside 'orgs/O005 . not logical`

2021-04-09 13:40 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/organization.spec.ts
> +      const orgDocRef = db.doc('orgs/O004');
orgs/O004 already exists and `uid-user5` is not part of it. So this test fail but not for the good reason

2021-04-09 13:42 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/organization.spec.ts
> +      const orgDocRef = db.doc('orgs/O004');
you should try to update orgDoc where current user is member of this org

2021-04-09 13:43 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/organization.spec.ts
> +      const orgDocRef = db.doc('orgs/O004');
update this ID to a non-existant one

2021-04-09 13:48 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +    orgId: 'O0X4'
since uid-user4 is used in permission tests to create org and permission doc. User should not have orgId setted. You should be able to remove it

2021-04-09 13:56 UTC, xmano commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +    orgId: 'O006',
added in O006

2021-04-09 13:59 UTC, xmano commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +    uid: 'uid-admin4',
added to O004

2021-04-09 14:06 UTC, xmano commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +    orgId: 'O0X4'
ok

2021-04-09 14:24 UTC, xmano commented on apps/rules/src/tests/firestore/organization.spec.ts
> +      const orgDocRef = db.doc('orgs/O004');
Actually the test only check for non-equality to OrgId.. but I am setting this to 'O0X5'. In this case existence of other org is immaterial.

2021-04-09 14:38 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/organization.spec.ts
> +      const orgDocRef = db.doc('orgs/O004');
you still want to create an org with id orgs/O004
but this org already exists.

use a non-existing one ..

2021-04-09 14:39 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/organization.spec.ts
> +      const orgDocRef = db.doc('orgs/O004');
> Actually the test only check for non-equality to OrgId.. but I am setting this to 'O0X5'. In this case existence of other org is immaterial.

I aggree but in this case you are not testing "create" but "update"

2021-04-09 14:45 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/organization.spec.ts
> +      const orgDocRef = db.doc('orgs/O004');
and also, this test should not be inside `'With User as Org Member'` because we are creating the org..

2021-04-09 14:46 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/organization.spec.ts
> +      const orgDocRef = db.doc('orgs/O001');
uid-admin4 is not part of  `orgs/O001`. update to orgs/O004 ... or test is not relevant..

2021-04-09 14:47 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/organization.spec.ts
> +      const orgDocRef = db.doc('orgs/O001');
uid-admin4 is not part of orgs/O001. update to orgs/O004 ... or test is not relevant..

2021-04-09 14:47 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/organization.spec.ts
> +    test('id == orgId & status: pending, should be able to create document', async () => {
here we are creating an org. so describe `With User as Org Member` is not good

2021-04-09 14:48 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/organization.spec.ts
> +      const orgDocRef = db.doc('orgs/O001');
uid-admin5 is not part of orgs/O001. so  test is not relevant..

2021-04-09 14:50 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/permission.spec.ts
> +      const docName = 'permissions/O0X4';
org is not created so `describe('With User as Org Member'` is not correct for this test

2021-04-12 08:43 UTC, xmano commented on apps/rules/src/tests/firestore/organization.spec.ts
> +    test('id == orgId & status: pending, should be able to create document', async () => {
Update the description:

"With User as or going to be Org Member"

2021-04-12 08:45 UTC, xmano commented on apps/rules/src/tests/firestore/permission.spec.ts
> +      const docName = 'permissions/O0X4';
Updated to "as or going to be Org Member"

2021-04-12 08:54 UTC, xmano commented on apps/rules/src/tests/firestore/organization.spec.ts
> +      const orgDocRef = db.doc('orgs/O004');
Good point about existing OrgID, so I have updated this to O0X4.

Did not understand that it is testing for "update", the test is about creating only.

Last point has been taken care of by updating the description of the test suite to include "as or to be".. there is separate comment for this.

2021-04-12 09:08 UTC, xmano commented on apps/rules/src/tests/firestore/organization.spec.ts
> +      const orgDocRef = db.doc('orgs/O001');
According to the rules test is OK.

But I think your point to test for deletion of own OrgId is better. So I am changing this to O004.

2021-04-12 09:17 UTC, xmano commented on apps/rules/src/tests/firestore/organization.spec.ts
> +      const orgDocRef = db.doc('orgs/O001');
The rule for read mentions only to be `if isSignedIn()`. Hence the test as such is relevant. 

If the idea is to check for own Org then rule needs to be updated first.

2021-04-12 09:18 UTC, xmano commented on apps/rules/src/tests/firestore/organization.spec.ts
> +      const orgDocRef = db.doc('orgs/O001');
As above. We will track this review request according to the resolution for the above.

2021-04-12 09:22 UTC, xmano commented
Org test
![image](https://user-images.githubusercontent.com/8731418/114371946-a593d880-9b9e-11eb-854a-c3e78338f808.png)

Permission
![image](https://user-images.githubusercontent.com/8731418/114371956-aaf12300-9b9e-11eb-9de8-74cb5b25e875.png)

2021-04-14 13:02 UTC, xmano commented on apps/rules/src/tests/firestore/organization.spec.ts
> +      const orgDocRef = db.doc('orgs/O001');
I have updated to org to O004. So corrected this.

2021-04-14 13:03 UTC, xmano commented
Ran all dependent test:

![image](https://user-images.githubusercontent.com/8731418/114714602-e2eb9800-9d4f-11eb-90dc-4cc138387663.png)

![image](https://user-images.githubusercontent.com/8731418/114714566-db2bf380-9d4f-11eb-98f0-c38b8b302997.png)

firebase-utils:
![image](https://user-images.githubusercontent.com/8731418/114714666-f0a11d80-9d4f-11eb-900c-43b712a82d98.png)

2021-04-14 13:10 UTC, phpgeekfr approved these changes
LGTM

2021-04-14 13:30 UTC, merged