Consent users modales
blockframes/blockframes pull request #5563
Opened 2021-04-13 17:08 UTC by SamirTouira

2021-04-26 11:28 UTC, Mussuranae requested changes

2021-04-26 11:28 UTC, Mussuranae commented on libs/campaign/src/lib/marketplace/financing/financing.component.ts
Delete the space. Same for the one below.

2021-04-26 11:28 UTC, Mussuranae commented on libs/campaign/src/lib/marketplace/financing/financing.component.ts
> +  changeDetection: ChangeDetectionStrategy.OnPush,
Comma isn't needed.

2021-04-26 11:28 UTC, Mussuranae commented on libs/campaign/src/lib/marketplace/financing/financing.component.ts
> +        typeof value === 'number' ? formatCurrency(value, this.locale, campaign.currency) : '',
I don't think you need to change that. Same for the sentence below.

2021-04-26 11:28 UTC, Mussuranae commented on libs/campaign/src/lib/marketplace/financing/financing.component.ts
> +      tap((campaign) => (this.totalFundings = getTotalFundings(campaign.fundings)))
You dont need the parenthesis for the argument

2021-05-04 15:22 UTC, SamirTouira commented on libs/admin/src/lib/admin-panel/components/crm-form-dialog/crm-form-dialog.component.html
> +    <button mat-flat-button color="warn" (click)="confirm()">{{ titleCaseWord(data.confirmButtonText) }}</button>
Ok I will, but I don't know if i'm able to doing this quickly. I need to learn some stuff about pipes

2021-05-05 08:40 UTC, Mussuranae requested changes

2021-05-05 08:40 UTC, Mussuranae commented on libs/admin/src/lib/admin-panel/components/crm-form-dialog/crm-form-dialog.component.html
> +  <p *ngIf="data.confirmButtonText == 'accept' && data.title == 'Confidentiality Reminder'" class="space-p"></p>
What is this ?

2021-05-05 08:40 UTC, Mussuranae commented on libs/admin/src/lib/admin-panel/components/crm-form-dialog/crm-form-dialog.component.html
> +    <ng-template #hasAsubTitle>{{ data.subTitle }}</ng-template>
If I understand well, like this the subtitle will appear only if the title is equal to `Confidentiality Reminder`. What if I want to put a subtitle in this modal but not in MF, the title won't be `Confidentiality Reminder`, my subtitle won't appear.
It should be a 'default' location for all data we can pass to this modal.

2021-05-05 08:40 UTC, Mussuranae commented on libs/admin/src/lib/admin-panel/components/crm-form-dialog/crm-form-dialog.component.html
> +      <span class="space"></span>
What is this bis ????

2021-05-05 08:53 UTC, SamirTouira commented on libs/admin/src/lib/admin-panel/components/crm-form-dialog/crm-form-dialog.component.html
> +    <ng-template #hasAsubTitle>{{ data.subTitle }}</ng-template>
If the title is equal to `Confidentiality Reminder`, the dialog will open with the corresponding text in html and if you want to use another dialog text, <`ng-template #hasAsubTitle>{{ data.subTitle }}</ng-template>` is here to display dynamically the subtitle that you want

2021-05-05 09:14 UTC, SamirTouira commented on libs/admin/src/lib/admin-panel/components/crm-form-dialog/crm-form-dialog.component.html
> +    <ng-template #hasAsubTitle>{{ data.subTitle }}</ng-template>
I think I know what you mean for this, if i move `<ng-template #hasAsubTitle>{{ data.subTitle }}</ng-template>` under the the closed `</ng-container>`, your subtitle will appear for all datas

2021-05-05 09:16 UTC, Mussuranae commented on libs/admin/src/lib/admin-panel/components/crm-form-dialog/crm-form-dialog.component.html
> +    <ng-template #hasAsubTitle>{{ data.subTitle }}</ng-template>
Did you try ? Because I agree if there is no subtitle, it will show the `ng-template` bbuuuttt this ng-template is inside the `*ngIf="data.title == 'Confidentiality Reminder'"`. I guess it won't appear if you let it inside the if.

2021-05-05 16:27 UTC, Mussuranae approved these changes

2021-05-05 19:06 UTC, merged