Test the Demo Request
blockframes/blockframes pull request #5797
Opened 2021-05-14 15:12 UTC by xmano

Using Mailosaur

![image](https://user-images.githubusercontent.com/8731418/118291204-ef047a00-b4f4-11eb-8cb1-110bcab06d6d.png)

2021-05-14 15:44 UTC, Mussuranae requested changes

2021-05-14 15:44 UTC, Mussuranae commented on apps/festival/festival-e2e/src/integration/dashboard/email-test.ts
> +    })
Is there always one email or can it be several emails ? What happened if there is several emails ?

2021-05-14 15:44 UTC, Mussuranae commented on apps/festival/festival-e2e/src/integration/dashboard/email-test.ts
> +  it.only('Wait for API to load', () => {
I guess the `.only` isn't usefull here, no ,

2021-05-14 15:44 UTC, Mussuranae commented on apps/festival/festival-e2e/src/integration/landing/demo-request.ts
> +//Test if email is sent correctly.
I guess you can delete this file, and move the previous one `email-test` here. The test is on the landing page, it should be inside the landing folder.

2021-05-14 15:44 UTC, Mussuranae commented on libs/landing/src/lib/shell/shell.component.html
> +        <!-- <button test-id="send-request" fxFlexAlign="center" mat-flat-button color="accent" type="submit">Send Request</button> -->
This one can be removed.

2021-05-14 15:44 UTC, Mussuranae commented on libs/landing/src/lib/shell/shell.component.ts
> +        information.testEmailTo = 'test@zjfwnf90.mailosaur.net'
Can you re-use this information in the test instead of "recreating" it (line 11 inside the `email-test.ts`) ?
If not, maybe add a comment to explain that the email has to be the same that the one in the test, and put the path to go on the e2e test file.

2021-05-17 09:28 UTC, xmano commented on libs/landing/src/lib/shell/shell.component.ts
> +        information.testEmailTo = 'test@zjfwnf90.mailosaur.net'
Added this to `@blockframes/e2e/utils`


`
//Email Test IDs
export const serverId = 'zjfwnf90'; // Replace SERVER_ID with an actual Mailosaur Server ID
export const testEmail = `test@${serverId}.mailosaur.net`;
`

2021-05-17 09:29 UTC, xmano commented on libs/landing/src/lib/shell/shell.component.html
> +        <!-- <button test-id="send-request" fxFlexAlign="center" mat-flat-button color="accent" type="submit">Send Request</button> -->
Removed.

2021-05-17 09:30 UTC, xmano commented on apps/festival/festival-e2e/src/integration/dashboard/email-test.ts
> +  it.only('Wait for API to load', () => {
Right. I missed it while cleaning.

2021-05-17 09:30 UTC, xmano commented on apps/festival/festival-e2e/src/integration/dashboard/email-test.ts
> +    })
in `beforeEach()` we clean up all e-mails. At a time only one test-suite can run so should be ok.

2021-05-17 09:31 UTC, xmano commented on apps/festival/festival-e2e/src/integration/landing/demo-request.ts
> +//Test if email is sent correctly.
Yes will re-organise the tests and do some more cleanups. Thanks.

2021-06-09 12:57 UTC, phpgeekfr commented
@xmano are you going to work again on this PR or can we close it ?

2021-06-30 06:49 UTC, xmano commented
> @xmano are you going to work again on this PR or can we close it ?

Almost done with the PR.

Cleanup, Test, Review and merge. Should get done today!

2021-06-30 06:59 UTC, xmano commented on apps/festival/festival-e2e/src/integration/landing/demo-request.ts
> +//Test if email is sent correctly.
Ok I am yet to do this. Will be working on moving it to proper place. You may review other stuff.

2021-06-30 08:23 UTC, Mussuranae approved these changes
Almost done, congrats for the email testing ! that's a super new feature !

2021-06-30 08:23 UTC, Mussuranae commented on apps/catalog/catalog-e2e/src/integration/landing/account-creation.spec.ts
> +      console.log(result)
Do you need this console.log ?

2021-06-30 08:23 UTC, Mussuranae commented on apps/festival/festival-e2e/src/integration/dashboard/email-test.ts
> +  it('Wait for API to load', () => {
Maybe find a better description for the test ;)

2021-06-30 08:58 UTC, xmano commented on apps/catalog/catalog-e2e/src/integration/landing/account-creation.spec.ts
> +      console.log(result)
No need really. But since it is in test code it really doesn't harm. However I will remove it. and put proper cy.log()

2021-06-30 08:58 UTC, xmano commented on apps/festival/festival-e2e/src/integration/dashboard/email-test.ts
> +  it('Wait for API to load', () => {
Sure.

2021-06-30 09:36 UTC, xmano commented on apps/catalog/catalog-e2e/src/integration/landing/account-creation.spec.ts
> +      console.log(result)
Added appropriate cy.log

2021-06-30 10:31 UTC, xmano commented on apps/festival/festival-e2e/src/integration/landing/demo-request.ts
> +//Test if email is sent correctly.
Deleted demo-request.ts. Moved email-test.ts from dashboard to landing/email-check.spec.ts

2021-06-30 10:34 UTC, xmano commented on apps/festival/festival-e2e/src/integration/dashboard/email-test.ts
> +  it('Wait for API to load', () => {
Changed to "Request Demo and verify request email"

2021-07-01 12:54 UTC, merged