email information for users requesting app access ok
blockframes/blockframes pull request #5891
Opened 2021-05-28 17:54 UTC by SamirTouira

issue: #5806 

Do not forget to deploy the backend-functions after this merge

2021-05-28 18:16 UTC, Mussuranae requested changes
Almost :D

2021-05-28 18:16 UTC, Mussuranae commented on apps/backend-functions/src/notification.ts
> +async function requestAccessAppEmail(recipient: User, notification: NotificationDocument) {
Same.

2021-05-28 18:16 UTC, Mussuranae commented on apps/backend-functions/src/notification.ts
> +        await requestAccessAppEmail(recipient, notification)
Change to `requestAppAccessEmail`.

2021-05-28 18:23 UTC, SamirTouira commented
I changed that 👍

2021-05-31 08:57 UTC, Mussuranae approved these changes
LGTM :+1:

2021-05-31 12:52 UTC, merged