Filter query param urls
blockframes/blockframes pull request #6043
Opened 2021-06-14 09:05 UTC by iPR0D1G1

Ressolved save form state in URL for easy searching of filters state.
fixed: #4098

2021-06-14 09:57 UTC, pldespaigne requested changes

2021-06-14 09:57 UTC, pldespaigne commented on apps/catalog/catalog/src/app/marketplace/organization/list/list.component.ts
> +    )
please put it in one line

2021-06-14 09:57 UTC, pldespaigne commented on apps/catalog/catalog/src/app/marketplace/organization/list/list.component.ts
> +    )
please put it in one line

2021-06-14 09:57 UTC, pldespaigne commented on apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.ts
> +    )
please put it in one line

2021-06-14 09:57 UTC, pldespaigne commented on apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.ts
> +    }
I'm not sure to understand why `.length` could be 0, could explain whit a comment ?

2021-06-14 09:57 UTC, pldespaigne commented on apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.ts
> +    )
please put it in one line

2021-06-14 09:57 UTC, pldespaigne commented on apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.ts
> +    if (decodedData && Object.keys(decodedData).length > 0) {
same thing for the comment please

2021-06-14 09:57 UTC, pldespaigne commented on apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
> +  ChangeDetectorRef, OnDestroy, AfterViewInit
I think `AfterViewInit` is not used anymore, please remove it

2021-06-14 09:57 UTC, pldespaigne commented on apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
> +          console.log({ search, avails })
remove `console.log`

2021-06-14 10:19 UTC, iPR0D1G1 commented on apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.ts
> +    }
In case there is an error in decodeUrl method, we return an empty object
`let decodedData = {};`

2021-06-14 10:21 UTC, iPR0D1G1 commented on apps/catalog/catalog/src/app/marketplace/title/avails/map/avails-map.component.ts
> +    if (decodedData && Object.keys(decodedData).length > 0) {
In case there is an error in decodeUrl method, we return an empty object
let decodedData = {};

2021-06-14 14:45 UTC, GrandSchtroumpf submitted a review, later dismissed

2021-06-14 14:45 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
> +      ...avails as any
Please to not use `as any`

2021-06-14 14:45 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
> +    if (unparsedSearch) {
I think you can just do : 
```typescript
this.searchForm.patchAllValue(search ?? {});
```
It should remove the rest below

2021-06-14 14:45 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
> +    const sub = combineLatest([
Better to multicast the result of the observable instead of creating it twice : 
```typescript
const search$ = combineLatest([
  this.searchForm.value$,  // value$ is a helper we've for in the EntityForm
  this.availsForm.valus$
]).pipe(
  shareReplay(1), // Make sure we don't run the observable twice
);
const updateUrl = search$.pipe(
  skip(1),
  throttleTime(1000),
).subscribe(([search avails]) => {
  const { query, genres, originCountries, contentType } = search;
  const update = { avails, search:  { query, genres, originCountries, contentType } };
  encodeUrlAndNavigate(this.router, this.route, update);
});

const sub = search$.pipe(
  distinctUntilChanged()
);
```

2021-06-14 14:45 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
> +    this.subs.forEach(
format in 1line

2021-06-14 14:45 UTC, GrandSchtroumpf commented on libs/utils/src/lib/form/form-state-url-encoder.ts
> +export function decodeUrl(
Better to ad a generic type here to avoid `any`: 
```typescript
export function decordUrl<T>(route: ActivatedRoute): T {
  const { formValue } = activatedRoute.snapshot.queryParams;
  try {
    const fromUrl = decodeURIComponent(formValue ?? '{}');
    return JSON.parse(fromUrl, reviver); // see comment about reviver
  } catch(err) {
    console.warn(err);
    return {};
  }
}
```

2021-06-14 14:45 UTC, GrandSchtroumpf commented on libs/utils/src/lib/form/form-state-url-encoder.ts
> +export function encodeUrlAndNavigate(
I think naming is not clear as I expect the router to change. Better name if `encoreUrl`.

2021-06-14 14:45 UTC, GrandSchtroumpf commented on libs/utils/src/lib/form/form-state-url-encoder.ts
> +    router.navigate(
format it like that for readability : 
```typescript
router.navigate(['.'], {
  queryParams: { formValue },
  relativeTo: route,
  replaceUrl: true,
});
```

2021-06-15 07:58 UTC, iPR0D1G1 commented on apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
> +    if (unparsedSearch) {
patchAllValue doesn't update all fields(notably formcontrol fields).
patchValue doesn't update all fields(notably formlist fields).

2021-06-15 08:03 UTC, iPR0D1G1 commented on apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
> +    const sub = combineLatest([
Both combineLatest combinations are not identical.
one is composed of two observables
`const sub = combineLatest([
      this.searchForm.valueChanges.pipe(
        startWith(this.searchForm.value)
      ),
      this.availsForm.valueChanges.pipe(
        startWith(this.availsForm.value)
      ),
      this.bucketQuery.selectActive().pipe(startWith(undefined))
    ])`
    
    and 
`const subStateUrl = combineLatest([
      this.searchForm.valueChanges.pipe(
        startWith(this.searchForm.value)
      ),
      this.availsForm.valueChanges.pipe(
        startWith(this.availsForm.value)
      ),
    ])`

2021-06-15 10:32 UTC, pldespaigne requested changes

2021-06-15 10:32 UTC, pldespaigne commented on apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
> +    const sub = combineLatest([
I think what @GrandSchtroumpf meant is that, let's try to see if it works

```TypeScript
const search$ = combineLatest([
  this.searchForm.valueChanges.pipe(startWith(this.searchForm.value)),
  this.availsForm.valueChanges.pipe(startWith(this.availsForm.value)),
  this.bucketQuery.selectActive().pipe(startWith(undefined))
]).pipe(shareReplay(1);

const sub = search$.pipe(
  distinctUntilChanged(),
  debounceTime(300),
  switchMap(async ([_, availsValue, bucketValue]) => [await this.searchForm.search(), availsValue, bucketValue]),
).subscribe( /*... THE REST OF THE CODE ...*/ );

const subStateUrl = search$.pipe(skip(1)).subscribe(([search, avails]) => { /* ... CODE ...*/ });
```

2021-06-15 10:32 UTC, pldespaigne commented on apps/catalog/catalog/src/app/marketplace/title/list/list.component.ts
> +      }
The goal of `patchValue`/`patchAllValue` is to replace only the defined values, that why you don't need the `if`s anymore. `patchValue` will leave the form untouched if the value is `undefined` whereas `setValue` will overwrite no matter what.

Also there is no need to create an alias for search if you create a `const` with the same name afterward:

```TypeScript
const { search: unparsedSearch, avails = {} } = decodeUrl(this.route);
...
const search: any = unparsedSearch; // this is useless

// prefer this instead
const { search, avails } = decodeUrl(this.route);
```

So overall you can probably replace the whole code block by:
```TypeScript
const { search, avails } = decodeUrl(this.route);

// patch everything
this.searchForm.patchValue(search);

// ensure FromList are also patched
this.searchForm.genres.patchAllValue(search.genres);
this.searchForm.originCountries.patchAllValue(search.originCountries);

this.availsForm.patchValue(avails);
```

2021-06-15 10:32 UTC, pldespaigne commented on apps/catalog/catalog/src/app/marketplace/title/avails/calendar/avails-calendar.component.ts
> +    private activatedRoute: ActivatedRoute
Please be careful when you mark an issue as resolved, be sure that you actually made the changes

![image](https://user-images.githubusercontent.com/5858657/122037851-4a1bdc00-cdd5-11eb-989b-6b4b73f04a94.png)

2021-06-16 08:21 UTC, pldespaigne approved these changes

2021-06-16 10:12 UTC, merged