E2E Test failure on CI # 5760
blockframes/blockframes pull request #6047
Opened 2021-06-15 10:00 UTC by phpgeekfr

2021-06-16 14:39 UTC, phpgeekfr commented
@xmano  I added `|| true` to end of commands so CI can go to next step even if some tests are red, but this will make the tick green even if tests have failed ..

Example here: 
![image](https://user-images.githubusercontent.com/1194344/122239605-5bdaad80-cec1-11eb-9fc0-f94d9d4c8967.png)


So we will need to look into logs to get results.

We will be able to remove `|| true` when the tests are green

2021-06-16 14:41 UTC, phpgeekfr commented
@george43g do you know if there is way to continue to next step even if we have a red tick on some step  ? Instead of using `|| true`

2021-06-17 03:59 UTC, xmano commented
> @xmano I added `|| true` to end of commands so CI can go to next step even if some tests are red, but this will make the tick green even if tests have failed ..
> 
> Example here:
> ![image](https://user-images.githubusercontent.com/1194344/122239605-5bdaad80-cec1-11eb-9fc0-f94d9d4c8967.png)
> 
> So we will need to look into logs to get results.
> 
> We will be able to remove `|| true` when the tests are green

In case of E2E tests, all the individual Apps are run even if there is a failure in some. So I don't understand what you are trying to do here.

The issue I am raising is of some App E2Es not running fully or getting aborted in between sometimes. This is causing tests to be skipped and incomplete results to be posted.

2021-06-17 04:01 UTC, xmano reviewed
Can you explain a bit about the changes?

Is there anything that can prevent tests from getting skipped?

2021-06-18 07:19 UTC, george43g commented
> @george43g do you know if there is way to continue to next step even if we have a red tick on some step ? Instead of using `|| true`

Yes there's a way to fix this - I'll organise a fix tonight in the CI config

2021-06-18 07:21 UTC, george43g requested changes

2021-06-18 07:21 UTC, george43g commented on .circleci/config.yml
> +      - run-e2e-tests:
we already do this in CI branch - why add it?

2021-06-18 07:21 UTC, george43g commented on .circleci/config.yml
> +      - run: echo "export PROJECT_ID=\"$(cut -d'/' -f2\<<<$CIRCLE_BRANCH)\"" >> $BASH_ENV
Is this to run e2e on any branch rather than CI? or against eny firebase project?

2021-06-18 07:21 UTC, george43g commented on .circleci/config.yml
> +            command: npx nx run crm-e2e:e2e:ci --headless || true
I'll be able to find a better fix shortly, I think you can configure it to continue despite failure

2021-06-23 08:19 UTC, phpgeekfr commented
@xmano  
> So I don't understand what you are trying to do here.

this was a workaround to have every test on all app working all the time. I thought this is what you wanted

2021-06-23 08:20 UTC, phpgeekfr commented on .circleci/config.yml
> +      - run-e2e-tests:
So every user can run e2e on ci

2021-06-23 08:20 UTC, phpgeekfr commented on .circleci/config.yml
> +      - run: echo "export PROJECT_ID=\"$(cut -d'/' -f2\<<<$CIRCLE_BRANCH)\"" >> $BASH_ENV
yes

2021-06-23 08:21 UTC, phpgeekfr commented
Closing this one so @george43g and @xmano can find a better workaround

2021-06-23 08:21 UTC, closed without merging