Contract item
blockframes/blockframes pull request #6054
Opened 2021-06-17 07:12 UTC by iPR0D1G1

2021-06-17 12:45 UTC, pldespaigne requested changes
Please also rename the `contract-item` folder simply into `item`. since it's already in a `contract folder`.

The path should now be like that `libs/contract/src/lib/contract/item/contrac-item.component.html`

2021-06-17 14:07 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html
> +          [columns]="columns"
Columns are the same in every contract-item modulo the action column. Better would be to add the action column only if there is a `colActionTemplate` inside the contract-item.
I think you can do something like that : 
```typescript
actionTemplate?: TemplateRef<unknown>;
@ContentChild('colActionTemplate') set colActionsTemplate(template: TemplateRef<unknown>) {
  if (template) {
    this.column.push('action');
    this.actionTemplate = template;
    this.cdr.marckForCheck();
  }
}
```

2021-06-17 14:07 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html
> +              <footer fxLayout fxLayoutAlign="space-between" class="footer">
As PL pointed out, I think it's better to do `<footer contractFooter>` to avoid adding unecessary nodes.

2021-06-17 14:07 UTC, GrandSchtroumpf commented on libs/contract/src/lib/contract/contract-item/contrac-item.component.html
> +
Please format

2021-06-17 14:07 UTC, GrandSchtroumpf commented on libs/contract/src/lib/contract/contract-item/contrac-item.component.html
> +            <ng-template  *ngIf="showColActionsTemplate" colAction="action" label="Actions" let-termIndex="index">
Use `*ngIf="colActionsTemplate"` instead of creating another `showColActionsTemplate` variable.

2021-06-17 14:07 UTC, GrandSchtroumpf commented on libs/contract/src/lib/contract/contract-item/contrac-item.component.ts
> +    return Boolean(this.colActionsTemplate);
In the repo we usually cast into a boolean with "!!" instead of "Boolean()"

2021-06-17 14:07 UTC, GrandSchtroumpf commented on libs/contract/src/lib/contract/contract-item/contrac-item.component.ts
> +@Component({
For ng-content it's better to create a Directive instead of a full component, it will prevent the compiler to run the template & style AST parsers for this.

2021-06-21 06:33 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html
> +          [columns]="columns"
As described in the comment above, you shouldn't need to specify the columns at all in the input. It should be a property of the component and should me updated only if there is a colActionTemplate

2021-06-21 06:33 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html
> +            <footer fxLayout fxLayoutAlign="space-between" class="footer" footer>
you don't need a directive "footer" here. The tag of the component should be enough. Also no need to provide a class to select it in the css. Better to access it with hierarchy selector: 
```css
contract-item footer { ... }
```

2021-06-21 06:33 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.scss
> +footer.footer {
See comment above

2021-06-21 06:47 UTC, GrandSchtroumpf requested changes

2021-06-21 06:47 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html
> +            <ng-template #colActionTemplate label="Actions" let-termIndex="index" let-titleId="titleId">
As described in [this issue](https://github.com/blockframes/blockframes/issues/5984) the `colActionTemplate` should have this API : 
```typescript
<ng-template termAction let-term let-index="index">
```
The `let-term` should be $implicit & and the `let-index` should be names "index" and not `termIndex`.
The label here is unused. You should remove it.
You can replace the directive `termAction` with a pseudo id `#termAction` if you prefer as it doesn't require any Input.

You don't need to provide the titleId as you can get it from the contract which is in your scope.

2021-06-21 06:47 UTC, GrandSchtroumpf commented on libs/contract/src/lib/contract/item/contract-item.component.html
> +        <ng-template [ngTemplateOutlet]="actionTemplate"
See comment above above template outlet context

2021-06-21 06:47 UTC, GrandSchtroumpf commented on libs/contract/src/lib/contract/item/contract-item.component.ts
> +      this.initialColumns.push('action');
you'll also need to update the columns here.

2021-06-21 06:47 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html
> +        <contract-item
You can format it on one line now :)

2021-06-21 06:47 UTC, GrandSchtroumpf commented on libs/contract/src/lib/contract/item/contract-item.component.ts
> +  @Input() contract: BucketContract;
Put all the properties (contract, priceTemplate, actionTemplate, colActionTemplate, trackId) above the constructor. In most programming language, a class is usually built like this  :
```typescript
class MyClass {
  property1;
  property2;
  constructor() {}
  method1() {}
  method2() {}
}
```

2021-06-21 06:47 UTC, GrandSchtroumpf commented on libs/contract/src/lib/contract/item/contract-item.component.ts
> +  styleUrls: ['./contract-item.component.scss']
always use `ChangeDetectionStrategy.OnPush` for the component

2021-06-21 07:01 UTC, iPR0D1G1 commented on apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.html
> +            <ng-template #colActionTemplate label="Actions" let-termIndex="index" let-titleId="titleId">
I just verified and there's nowhere implicit variable term from let-term is used within the ng-template.
can we simply not put it...

2021-06-21 08:14 UTC, pldespaigne requested changes

2021-06-21 08:14 UTC, pldespaigne commented on apps/catalog/catalog/src/app/marketplace/title/selection/selection.module.ts
> -    ImageModule,
This module is probably needed for the images to be shown

2021-06-21 08:20 UTC, pldespaigne approved these changes

2021-06-21 08:50 UTC, merged