Offer List #6070
blockframes/blockframes pull request #6075
Opened 2021-06-21 11:07 UTC by iPR0D1G1

Offer List #6070

2021-06-23 08:45 UTC, GrandSchtroumpf commented on libs/admin/src/lib/admin-panel/admin-panel.module.ts
> +  { path: 'offers', component: OffersComponent },
Best would be to create a module for this component and lazyload it. I know we don't do that for the other component of the module, but we plan to improve that progressively : 
```typescript
{ path: 'offers', loadChildren: () => import('./pages/offer/list/list.module').then(m => OfferListModule) }
```

2021-06-23 08:45 UTC, GrandSchtroumpf commented on libs/admin/src/lib/admin-panel/pages/offers/offers.component.ts
> +  offers = queryChanges.call(this.offerService, {
We usually put a $ at the end of the properties when it's an observable: `offers$`

2021-06-23 08:45 UTC, GrandSchtroumpf commented on libs/admin/src/lib/admin-panel/pages/offers/offers.component.ts
> +    //@ts-ignore
Create a type for that in the same file and cast the query : 
```typescript
type OfferWithContracts = Offer & { contracts: Contract[] };
const queryOffer: Query<OfferWithContracts> = {
  path: 'offers',
  contracts: offer => ({
    path: 'contracts',
    queryFn: ref => ref.where('offerId', '==', offer.id)
  })
}
@Component({ .... })
export class OfferListComponent {
  offers$ = queryChanges.call(this.offerService, queryOffer);
}
```

2021-06-23 08:45 UTC, GrandSchtroumpf commented on libs/admin/src/lib/admin-panel/pages/offers/offers.component.ts
> +  subs: Subscription[] = [];
You don't have any subscriptions. Remove it, and the ngOnDestroy

2021-06-23 08:45 UTC, GrandSchtroumpf commented on libs/admin/src/lib/admin-panel/pages/offers/offers.module.ts
> +export class OffersModule { }
If you import the component directly in the AdminPanelModule you don't need a module for the component.
But following the comment above I would like you to lazy load this component, so you need a module, but you'll need to import every dependancy required in the component (`MatTabsModule`, ...) and a `RouterModule.forChild()`

2021-06-23 08:45 UTC, GrandSchtroumpf commented on libs/admin/src/lib/admin/toolbar-top/toolbar-top.component.html
> +  <button mat-button routerLink="/c/o/admin/panel/offers">
always use a `a` tag when using `routerLink`. Also you might want to add a routerLinkActive class.

2021-06-23 10:43 UTC, iPR0D1G1 commented on libs/admin/src/lib/admin/toolbar-top/toolbar-top.component.html
> +  <button mat-button routerLink="/c/o/admin/panel/offers">
Just verified the design and there's no need for a routerLinkActive class. the design doesn't specifies which link is currently active.

2021-06-24 17:01 UTC, pldespaigne requested changes

2021-06-24 17:01 UTC, pldespaigne commented on libs/utils/src/lib/pipes/total.pipe.ts
> +export class TotalPipeModule { }
I also created a similar pipe in `/lib/admin-panel/pages/offers/shell/shell.component.ts` (at the bottom of the file)
Could please delete my pipe, and use yours in the `shell.component.html`

2021-06-25 08:53 UTC, iPR0D1G1 commented on libs/admin/src/lib/admin-panel/pages/offers/list/offer-list.component.scss
> +}
@GrandSchtroumpf  Told me to do this.

2021-06-25 09:04 UTC, iPR0D1G1 commented on libs/utils/src/lib/pipes/join.pipe.ts
> +export class JoinPipeModule { }
this is intended to be used by @GrandSchtroumpf in the future.

2021-06-25 10:03 UTC, GrandSchtroumpf approved these changes

2021-06-25 10:03 UTC, GrandSchtroumpf commented on libs/admin/src/lib/admin-panel/pages/offers/list/offer-list.component.ts
> +    if (value === 'pending') {
Prefer switch case here : 
```typescript
switch (value) {
  case 'pending': return offer.status === value;
  case ...
  default: true;
}
```

2021-06-25 10:03 UTC, GrandSchtroumpf commented on libs/admin/src/lib/admin/toolbar-top/toolbar-top.component.html
> +  <a mat-button routerLink="/c/o/admin/panel/offers">
I think you only need `routerLink="offers"`

2021-06-25 10:03 UTC, GrandSchtroumpf commented on libs/contract/src/lib/offer/list/list.component.ts
> +export class ListComponent {
Looks like you're not using this component. Can we remove it?

2021-06-25 10:03 UTC, GrandSchtroumpf commented on libs/utils/src/lib/pipes/total.pipe.ts
> +  transform(data: unknown[], path: string,): number {
remove trailing "," in the params

2021-06-25 10:13 UTC, iPR0D1G1 commented on libs/admin/src/lib/admin/toolbar-top/toolbar-top.component.html
> +  <a mat-button routerLink="/c/o/admin/panel/offers">
<img width="1434" alt="Bildschirmfoto 2021-06-25 um 11 12 29 AM" src="https://user-images.githubusercontent.com/22674720/123409624-4989ff00-d5a6-11eb-9bfc-86a8c172ff03.png">
We actually need the entire correct url for proper routing.

2021-06-25 11:03 UTC, pldespaigne approved these changes

2021-06-25 11:04 UTC, merged