crm offer shel
blockframes/blockframes pull request #6095
Opened 2021-06-22 15:56 UTC by pldespaigne

implements #6080

2021-06-23 08:26 UTC, GrandSchtroumpf requested changes

2021-06-23 08:26 UTC, GrandSchtroumpf commented on libs/admin/src/lib/admin-panel/pages/offers/shell/shell.component.scss
> +  height: calc(100% - 80px);
It should be `min-height`

2021-06-23 08:26 UTC, GrandSchtroumpf commented on libs/admin/src/lib/admin-panel/pages/offers/shell/shell.component.html
> +      <p>Offer created: {{offer.date.toDate() | date: 'dd/MM/yyyy'}}</p>
Avoid toDate() in the template. Use the `formatFromFirestore` in the service.

2021-06-23 08:26 UTC, GrandSchtroumpf commented on libs/admin/src/lib/admin-panel/pages/offers/shell/shell.component.html
> +      <p>Total: {{ offer | incomes | currency: offer.contracts[0].incomes[0].currency }}</p>
Better would be to have the currency on the offer directly. Update the service & datamodel for that.

2021-06-23 08:26 UTC, GrandSchtroumpf commented on libs/admin/src/lib/admin-panel/pages/offers/shell/shell.component.html
> +      <a mat-icon-button (click)="goBack()">
If it's a goBack(), use a button. I think it should be a routerLink toward the offer list though.

2021-06-23 08:26 UTC, GrandSchtroumpf commented on libs/admin/src/lib/admin-panel/pages/offers/shell/shell.component.ts
> +      buyerOrg: (offer: Offer) => ({
```typescript
buyerOrg: (offer: Offer) => ({ path: `orgs/${offer.buyerId}` })
```

2021-06-23 08:26 UTC, GrandSchtroumpf commented on libs/admin/src/lib/admin-panel/pages/offers/shell/shell.component.ts
> +    switchMap(offerId => queryChanges.call(this.offerService, {
I think you don't need to user querychange for that. Split the offer & the contract list : 
```typescript
const queryContract = (offerId: string) => ({ ... });
....
offer$ = this.offerId$.pipe(
  switchMap(offerId => this.offerService.valueChanges('')
);
contracts = this.offerId$.pipe(
  switchMap(offerId => queryChanges.call(this.offerService, queryContract(offerId))
)
```

2021-06-23 08:26 UTC, GrandSchtroumpf commented on libs/admin/src/lib/admin-panel/pages/offers/shell/shell.component.ts
> +          path: 'incomes',
I think it would be better to have the same id for the contract & the incomes for many reasons. Could you update the service that create income ?

2021-06-24 12:50 UTC, phpgeekfr approved these changes
LGTM

2021-06-24 12:50 UTC, phpgeekfr commented on libs/admin/src/lib/admin-panel/pages/offers/shell/shell.component.ts
> +export class IncomesPipe implements PipeTransform {
Pipe is used only on this component? No need to move it elsewhere ?

2021-06-24 12:50 UTC, phpgeekfr commented on libs/admin/src/lib/admin-panel/pages/offers/shell/shell.component.ts
> +export type ContractWithIncome = Contract & { income: Income };
this adds income property to Contract type ?

2021-06-24 12:51 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/shell.component.ts
> +export class IncomesPipe implements PipeTransform {
For now yes, we might move extract it if needed

2021-06-24 12:53 UTC, RemcoSimonides commented on libs/contract/src/lib/offer/+state/offer.service.ts
> +      date: offer?.date.toDate(),
We have a `toDate()` function for this

2021-06-24 12:53 UTC, RemcoSimonides commented on libs/organization/src/lib/organization/components/chip/chip.component.html
>  </a>
Don't show this component yet if you don't have the `org` yet. That will save some `?`

2021-06-24 12:55 UTC, pldespaigne commented on libs/organization/src/lib/organization/components/chip/chip.component.html
>  </a>
that's what I do already, but I did this for extra safety in case someone use the `<org-chip>` without `*ngIf`, otherwise it breaks

2021-06-24 12:55 UTC, pldespaigne commented on libs/contract/src/lib/offer/+state/offer.service.ts
> +      date: offer?.date.toDate(),
wut ?

2021-06-24 15:47 UTC, merged