Implementation Offer view
blockframes/blockframes pull request #6123
Opened 2021-06-28 11:30 UTC by iPR0D1G1

#6072

2021-06-28 15:35 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.html
> +            <a mat-icon-button [routerLink]="['./../', id,]" matTooltip="Edit">
you don't need `./../`, I think you can go with only `../`

2021-06-28 15:35 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.scss
> +  & > * {
applying the style to **everything** bellow seems weird

2021-06-28 15:35 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.scss
> +    padding-bottom: 0 !important;
never ever use `!important`

2021-06-28 15:35 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.scss
> +  transform: translateX(-16px);
never use `transform`

2021-06-28 15:35 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.ts
> +  })
We prefer to use `FormGroup` instead of from builder

2021-06-28 15:35 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.ts
> +      //@ts-ignore
I hope you will not let this in the final PR

2021-06-28 15:37 UTC, pldespaigne commented
Also don't commit your `package-lock.json` unless you installed a new package in the repo

2021-06-29 13:27 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.scss
> +  .no_pd {
prefer `nopd` or `no-pd`

2021-06-29 13:27 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.scss
> +    margin-bottom: -24px;
never use negative values

2021-06-29 13:27 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.scss
> +  p + * {
please don't use this kind of selectors

2021-06-29 13:27 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.scss
> +  gap: 8px;
better to use `fxLayoutGap` in the html as css gap is not yet well supported on safari

2021-06-29 13:27 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.scss
> +}
This is really not clean, we don't want a pixel perfect copy of the design !
We want easy to read and to maintain code.

Please delete all this css, and use only:
- flex (preferably directly in the html with `fxLayout`)
- padding & margin **only with px** (multiple of 4)
- `width: 100%`

2021-06-29 13:27 UTC, pldespaigne commented on libs/ui/src/lib/confirm-input/confirm-input.component.html
> +    <input matInput type="text" [formControl]="actionConfirm" placeholder="{{data.placeholder||''}}">
As I told you already multiple time: use `??` instead of `||` !
Also never use `{{ }}` for an attribute !

2021-06-29 13:27 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.ts
> +    this.subs.forEach(_ => _.unsubscribe());
please name your params (like `s` or `sub`) instead of `_`

2021-06-30 10:09 UTC, iPR0D1G1 commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.ts
> +import { map, shareReplay, tap } from 'rxjs/operators';
Remove shareReplay operator, it's not useful.

2021-06-30 10:09 UTC, iPR0D1G1 commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.ts
> +  public offer$ = this.shell.offer$.pipe(shareReplay(1));
remove shareReplay

2021-07-01 11:40 UTC, pldespaigne requested changes

2021-07-01 11:40 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.html
> +          <span *ngIf="(titleId|getTitle | async) as title">{{title.title?.international}}</span>
![image](https://user-images.githubusercontent.com/5858657/124114881-670b0d00-da6d-11eb-8434-5b63cf00d265.png)

2021-07-01 11:40 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.ts
> +  public confirmDialog: MatDialogRef<unknown>;
This is not needed

2021-07-01 11:40 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.ts
> +    )
You don't need to hydrate the contract, all the data you want is already in there, or can be obtained through pipes

2021-07-02 09:20 UTC, pldespaigne approved these changes

2021-07-02 09:20 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.ts
> +  subscriptions: Subscription[] = [];
this can be private, also you don't need it to be an array

2021-07-02 09:20 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.ts
> +    this.subscriptions.push(sub);
please format like that:

```TypeScript
this.sub = this.offer$.subscrib(offer => {
  const { status, specificity, delivery } = offer;
  this.form.patchValue({ status, specificity, delivery });
}); 
```

2021-07-02 09:44 UTC, pldespaigne approved these changes

2021-07-02 09:44 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.ts
> +  subscription: Subscription;
the sub is used only inside the class, so it's better to put it private

2021-07-02 10:31 UTC, merged