WIP - Filter by Production Year
blockframes/blockframes pull request #6198
Opened 2021-07-02 14:59 UTC by SamirTouira

issue: #6066 

the last thing that I must do (the more hard I guess) is investigating to find movies corresponding to the year set in the filter.

2021-07-08 17:05 UTC, SamirTouira commented
@RemcoSimonides correct me if I'm wrong but I still continue to think that it is not possible technically to fill the colour bar of the slider only to the right if the min value isn't 0 or if the max value is set before the min value, because even if the label is formatted, Algolia find nothing instead of finding all movies under or equal to 2030. Otherwise if it's doable, I am not able / not enough skilled to do it, sorry. I can only do right to left 2030 to 1970 with the colour bar only to the left

![image](https://user-images.githubusercontent.com/52285231/124959121-2e45d780-e01b-11eb-8e7e-4cc1f9e85c32.png)

2021-07-14 07:20 UTC, RemcoSimonides requested changes
I'll create my PR and show you the solution. You got close! Nice try 👍 :)
Solution: #6290

2021-07-14 07:20 UTC, RemcoSimonides commented on libs/movie/src/lib/movie/form/filters/production-year/production-year.component.ts
> +    if (this.componentForm.value >= minYear && this.componentForm.value <= maxYear) {
You just set componentForm to `minYear` and then you check it's value if it's `>= minYear` and `<= maxYear`? It will always be equal to minYear in this case 😅

2021-07-14 07:20 UTC, RemcoSimonides commented on libs/movie/src/lib/movie/form/filters/production-year/production-year.component.ts
> +      this.componentForm = this.form;
Because of this the componentForm is equal to form... No need to create a separate formControl if you do this.

2021-07-14 07:20 UTC, RemcoSimonides commented on libs/movie/src/lib/movie/form/filters/production-year/production-year.component.ts
> +      return this.componentForm.value;
returning a value in `ngOnInit()` function? That value isn't going anywhere

2021-07-14 07:20 UTC, RemcoSimonides commented on libs/movie/src/lib/movie/form/filters/production-year/production-year.component.ts
> +    if (value >= minYear && value <= maxYear) {
value is always equal or bigger than minYear and smaller or equal to maxYear. You can't slide the slider further than these values, can you?

2021-07-14 07:20 UTC, RemcoSimonides commented on libs/movie/src/lib/movie/form/filters/production-year/production-year.component.ts
> +    const invertedValue =  maxYear - value + minYear;
You've repeated this formula twice now ;) that means you can make it reusable

2021-07-14 07:20 UTC, RemcoSimonides commented on libs/movie/src/lib/movie/form/search.form.ts
> +      search['filters'] = `release.year >= ${maxYear - this.release.value + minYear}`;
searchForm shouldn't have inverted value here anymore (1970 instead of expected 2030 for example). It should already be inverted by now. So when there is a bug within the searchForm and you try to debug it, you don't need to follow all the code to figure out why there is 1970 instead of 2030. Keep the logic and complexity within the component for this 'inverted' value.

2021-07-14 07:42 UTC, RemcoSimonides commented
Closing in favor of #6290

2021-07-14 07:42 UTC, closed without merging