Add a title to an offer.
blockframes/blockframes pull request #6203
Opened 2021-07-05 10:20 UTC by iPR0D1G1

fixed: #6161

2021-07-05 10:52 UTC, iPR0D1G1 reviewed
reviewed

2021-07-05 11:22 UTC, pldespaigne requested changes

2021-07-05 11:22 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.ts
> +    })
After a quick verification, `titleId` cannot be known in advance (as offer can be on several movies), also the rest of info can be extracted from the `offer`.

So please refactor like that:
```TypeScript
async addContract(offer: Offer) {
  const { id, buyerId, buyerUserId, specifity } = offer;
  const contractId = this.contractService.createId();
  const contract = createSale({ id: contractId, specificity, buyerId, buyerUserId, offerId: id });
  // ....
```

2021-07-05 11:22 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.ts
> +    } catch (err) { this.loading$.next(false) }
You don't need to set loading to false here, as it will be done in any case bellow.
In stead it can be cool to display a user friendly message in a snack-bar to inform that the creation has failed.

2021-07-05 11:22 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.ts
> +      this.router.navigate([`../`, id, 'form'], { relativeTo: this.route })
I don't think the route should be `../` relative to `/<OFFER_ID>`.

Are you sure the redirection is done on `/<OFFER_ID>/<CONTRACT_ID>/form` ?

2021-07-05 11:22 UTC, pldespaigne commented on libs/contract/src/lib/contract/+state/contract.model.ts
> -
Please try to avoid to commit changes that are not meaningful, it "pollute" the PR.

You don't need to modify it for this PR it's ok, but please try to be careful for the next time :)

2021-07-05 11:22 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.ts
> +  public loading$ = new Subject<boolean>();
initialize to `false`

2021-07-05 11:22 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.scss
> +  display: grid;
please avoid `display: grid`

2021-07-05 11:22 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.html
> +    <button mat-flat-button color="primary" class="add-title margin-bottom" gdAlignRows="center" (click)="addTitle(offer,contracts[0])" [disabled]="loading$ | async">
you can add a flex & centered section around the button to center it

2021-07-05 11:34 UTC, iPR0D1G1 commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.ts
> +      this.router.navigate([`../`, id, 'form'], { relativeTo: this.route })
It is relative to `/<OFFER_ID>/view` and consequently it routes fine to the appropriate page.

2021-07-05 13:09 UTC, pldespaigne requested changes
Please be more careful, you should test your code more. Try to use the features you implements.
You broke the `offer-list` page with this code if you create a new contract.

2021-07-06 07:52 UTC, pldespaigne approved these changes

2021-07-06 07:52 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/shell/offer-view/offer-view.component.html
> +          </ng-container>
put the `<ng-template #noTitleYet>` bellow the `<ng-container *ngIf`

2021-07-06 07:52 UTC, pldespaigne commented on libs/admin/src/lib/admin-panel/pages/offers/list/offer-list.component.html
> +              </ng-container>
```html
<ng-container *ngIf="contract.titleId as titleId; else #noTitle">
  <span>{{ (titleId | getTitle | async).title.international | maxLength: 50 }}{{ last ? '' : ', ' }}</span>
</ng-container>
<ng-template #noTitle>
  <span>No Title Yet</span>
</ng-template>
```

2021-07-06 08:40 UTC, merged