refactor
blockframes/blockframes pull request #6236
Opened 2021-07-07 06:35 UTC by iPR0D1G1

Catalog contract list.
Fixed: #6196

2021-07-07 09:36 UTC, GrandSchtroumpf requested changes

2021-07-07 09:36 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/list/list.component.html
> +        <ng-template colRef="id" let-id><b>{{ id }}</b></ng-template>
This should be offerId actually. Something like that : 
```html
<ng-template colRef="offerId" let-offerId>
  <ng-container *ngIf="offerId | getOffer | async as offer">
    {{ offerId }} {{ offer.status | offerStatus }}
  </ng-container>
</ng-template>
```

2021-07-07 09:36 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/list/list.component.html
> +          <ng-container *ngIf="titleId">{{(titleId| getTitle | async)?.title?.international | maxLength:50}}
It's quite difficult to read. Prefer doing the query in the ng-container : 
```html
<ng-container *ngIf="titleId| getTitle | async as title">
  {{ title?.international | maxLength:50 }}
</ng-container>
```

2021-07-07 09:36 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/list/list.component.html
> +          <span class="capitalize">{{status??'No status'}}</span>
I don't think status is optimal; There is not reason to use "??"
Also use pipe `titlecase` or `uppercase` pipe instead of the class

2021-07-07 09:36 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/list/list.component.html
> +        <ng-template colRef="offerId" let-offerId>
This should actually come from the `_meta.createdAt`.

2021-07-07 09:36 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/list/list.component.scss
> +header[mat-tab-nav-bar] button {
Please remove this

2021-07-07 09:36 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/list/list.component.scss
> +.no-title-card {
Please check your css, this class is not used, and naming does not make sense in this context

2021-07-07 09:36 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/list/list.component.ts
> +type AllContractStatus = '' | 'contracts' | 'on_going_deals' | 'past_deals';
Please cleanup this file of everyting related to filters.

2021-07-07 09:36 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/dashboard.module.ts
> +        path: 'contracts', // Import bulk of movies
Remove comment

2021-07-07 09:36 UTC, GrandSchtroumpf commented on libs/utils/src/lib/pipes/get-income.pipe.ts
> +export class GetIncomePipe implements PipeTransform {
This pipe should be in the `libs\contract\src\lib\income\pipes.ts` file as it's related to the income only.

2021-07-07 09:36 UTC, GrandSchtroumpf commented on libs/utils/src/lib/pipes/get-offer.pipe.ts
> +export class GetOfferPipe implements PipeTransform {
Same as above, it should be in `libs\contract\src\lib\offer\pipes.ts`

2021-07-07 10:00 UTC, iPR0D1G1 commented on apps/catalog/catalog/src/app/dashboard/contracts/list/list.component.html
> +          <ng-container *ngIf="titleId">{{(titleId| getTitle | async)?.title?.international | maxLength:50}}
Actually, it can so happen that titleId is undefined, with the proposed approach above, getTitle will error out.

2021-07-07 10:00 UTC, iPR0D1G1 commented on apps/catalog/catalog/src/app/dashboard/contracts/list/list.component.html
> +          <ng-container *ngIf="titleId">{{(titleId| getTitle | async)?.title?.international | maxLength:50}}
Actually, it can so happen that titleId is undefined, with the proposed approach above, getTitle will error out.

2021-07-07 10:52 UTC, iPR0D1G1 reviewed
reviewed

2021-07-07 11:11 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/list/list.component.html
> +            <span class="box-around" *ngIf="(id|getOffer|async) as offer">{{offer?.status | titlecase}}</span>
also we don't want to display the status code here but a readable label. For that we need to add the value in the static-model. @pldespaigne can help you with that, and @2amarkina can give you the labels.
You can do that in another PR.

2021-07-07 11:11 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/list/list.component.scss
> +.box-around{
As explain above, better removing that for now until we create the appropriate component.

2021-07-07 11:11 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/list/list.module.ts
> +import { MatTooltipModule } from '@angular/material/tooltip';
You're not using any tooltip. Please cleanup your imports.

2021-07-07 11:11 UTC, GrandSchtroumpf commented on libs/contract/src/lib/contract/+state/contract.model.ts
> +    _meta: createDocumentMeta({ createdAt: new Date() }),
No you shouldn't have that. This can lead to a wrong information. Only set a empty object.
```typescript
_meta: {},
```

2021-07-07 11:11 UTC, GrandSchtroumpf commented on libs/contract/src/lib/contract/+state/contract.model.ts
> +    _meta: createDocumentMeta({ createdAt: new Date() }),
Same as above

2021-07-07 11:16 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/list/list.component.html
> +            <span class="box-around" *ngIf="(id|getOffer|async) as offer">{{offer?.status | titlecase}}</span>
here are the labels for each status: 
```
pending : New
negotiating: In Negotiation
accepted : Accepted
signing: On Signature
signed: Signed
declined: Declined
```

2021-07-07 13:40 UTC, GrandSchtroumpf approved these changes
If the date is displayed in the table even without transforming the Timestamp into a Date, then you can merge. Please make sure it's working before merging.

2021-07-07 14:55 UTC, pldespaigne requested changes

2021-07-07 14:55 UTC, pldespaigne commented on apps/catalog/catalog/src/app/dashboard/contracts/list/list.component.ts
> +  contracts$ = this.service.valueChanges(ref => ref.where('type', '==', 'sale'));
better to have `public` everywhere or nowhere to stay consistent

2021-07-07 14:55 UTC, pldespaigne commented on apps/catalog/catalog/src/app/dashboard/contracts/list/list.component.ts
> +    private dynTitle: DynamicTitleService,
this is not used

2021-07-07 14:55 UTC, pldespaigne commented on apps/catalog/catalog/src/app/dashboard/dashboard.component.html
>          <span matLine><b>Offers & Deals</b></span>
delete the comment as it was the link you added back

2021-07-08 12:37 UTC, GrandSchtroumpf approved these changes

2021-07-08 12:37 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/list/list.component.ts
> +export class LabelOfferStatusPipe implements PipeTransform {
You don't need to create a new pipe for that. You can add a new static-model in the `libs\utils\src\lib\static-model\static-model.ts` file below the `contractType` for example:
```typescript
export const offerStatus = {
  pending: 'New',
  negotiating: 'In Negotiation',
  ...
} as const
```
And add it in the end of the file in the `staticModel` export.
Then you can use the `toLabel` pipe.

2021-07-08 12:37 UTC, GrandSchtroumpf commented on libs/contract/src/lib/income/pipe.ts
> +    console.log('contract constructor');
Remove console.log

2021-07-08 12:37 UTC, GrandSchtroumpf commented on libs/contract/src/lib/income/pipe.ts
> +    if (!this.record[contractId]) {
I think you don't need the record anymore.

2021-07-09 07:57 UTC, GrandSchtroumpf approved these changes

2021-07-09 09:24 UTC, merged