feat(contract-view):finished design and functionality
blockframes/blockframes pull request #6265
Opened 2021-07-09 12:21 UTC by iPR0D1G1

fixed: #6197

2021-07-09 12:36 UTC, iPR0D1G1 reviewed
reviewed

2021-07-09 12:58 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/view/view.component.html
> +      <mat-icon svgIcon="arrow_back" color="primary" class="margin-bottom" [routerLink]="['./../..']"></mat-icon>
Here are some rules : 
- do not use [] on the routerLink if it doesn't use variables
- never put a `routerLink` on something else than a `<a>`
- never apply action on the mat-icon itself, wrap it inside a `button` or `a` tag.
- Avoir class like `margin-bottom`, prefer using precise selectors in the css or `fxLayoutGap` in the html when possible.

```html
<a mat-icon-button routerLink="../../.." color="primary">
  <mat-icon svgIcon="arrow_back"></mat-icon>
</a>
```

2021-07-09 12:58 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/view/view.component.html
> +    <header fxLayout="column" fxLayoutAlign="flex-start flex-start" class="margin-bottom">
You don't nee to "flex-"
```html
<header fxLayout="column" fxLayoutAlign="start start">

</header>
```

2021-07-09 12:58 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/view/view.component.html
> +      <div class="margin-bottom">
You don't need this div, remove it

2021-07-09 12:58 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/view/view.component.html
> +      <div fxLayout="row" fxLayoutAlign="space-between center" class="full_width margin-bottom">
Prefer class that explain what this section is about. Also "row" is the default fxLayout value. You don't need to specify.
```html
<div fxLayout fxLayoutAlgin="space-between center" class="actions">

</div>
```

2021-07-09 13:30 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/view/view.component.html
> +            <mat-icon svgIcon="check" color="primary"></mat-icon>
You don't need to specify color if button already specify it.

2021-07-09 13:30 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/view/view.component.html
> +        <div fxLayout="row" fxLayoutAlign="flex-start center" fxLayoutGap="16px">
Same as above : 
```html
<div fxLayout fxLayoutAlign="start center" fxLayoutGap="16px">
```

2021-07-09 13:30 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/view/view.component.html
> +      <b>
b is a inline tag while p is a block tag. `<b>` should be inside `<p>`

2021-07-09 13:37 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/view/view.component.html
> +          <p>{{ income.price | currency: income.currency }}</p>
It's actually a h2 : 
![image](https://user-images.githubusercontent.com/8143464/125085670-1fb6f900-e0cb-11eb-9d4b-233c69aabb9c.png)

2021-07-09 13:45 UTC, GrandSchtroumpf requested changes
I left you a bunch of comments. Also you'll need to update the `contract-item` to support the new columns.

2021-07-09 13:45 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/view/view.component.ts
> +  changeStatus(status: ContractStatus, id: string) {
If you use the callback of the update it'll actually use a transaction under the hood. Here it's not needed you can just do : 
```typescript
const id = this.route.snapshot.params.contractId as string;
this.contractService.update(id, { status })
  .finally()
  .catch()
```

2021-07-09 13:45 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/view/view.component.ts
> +        console.warn(err)
use error instead of warn as it's an error.

2021-07-09 13:45 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/view/view.component.ts
> +  declineContract(id: string) {
I think you can just call `changeStatus` from the template.
```html
<button (click)="changeStatus('accepted')"
```

2021-07-09 13:45 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/view/view.component.ts
> +  public openIntercom(): void {
either use public everywhere or nowhere. But take a side ;)

2021-07-09 13:45 UTC, GrandSchtroumpf commented on styles/style.scss
> +// .surface{
Remove it totally for now.

2021-07-09 13:45 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/view/view.component.scss
> +mat-card {
Should be : 
```scss
.surface {
  margin: 24px;
}
```

2021-07-09 13:45 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/view/view.component.html
> +    <contract-item [contract]="contract">
I'm not sure but I think the contract-item already has a surface-like style. Maybe there is a conflict here.

2021-07-09 13:48 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/view/view.component.html
> +    <b>
b is a inline tag while p is a block tag. `<b>` should be inside `<p>`.
Also this is actually a h2: 
![image](https://user-images.githubusercontent.com/8143464/125087783-1464cd00-e0cd-11eb-99a8-3b0e7731aa49.png)

2021-07-09 13:48 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/contracts/view/view.component.html
> +    <div fxLayout="row" fxLayoutAlign="space-between center" class="actions">
row is the default value for fxLayout : 
```html
<div class="actions" fxLayout fxLayoutAlign="space-between center" >
  <div fxLayout fxLayoutAlign="start center" fxLayoutGap="16px">
```

2021-07-13 14:43 UTC, GrandSchtroumpf approved these changes
👍

2021-07-14 08:36 UTC, merged