Created available materials
blockframes/blockframes pull request #6292
Opened 2021-07-14 09:56 UTC by iPR0D1G1

Renamed available-materials to available versions.
Created aailabe-materials and finished design.

2021-07-14 10:17 UTC, GrandSchtroumpf requested changes

2021-07-14 10:17 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/tunnel/summary/summary.component.html
> +      <movie-summary-available-versions [movie]="form" [link]="('available-materials' | getPath)">
you've got twice `movie-summary-available-versions` I think you mean `movie-summary-available-materials`

2021-07-14 10:17 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/shell/shell.component.ts
> +  }, {
This part should not be in the lib. It's specific to the catalog application. Add it in `apps\catalog\catalog\src\app\dashboard\tunnel\movie-tunnel.routes.ts`. You can take example in `apps\financiers\financiers\src\app\dashboard\tunnel\routes.ts`

2021-07-14 10:54 UTC, GrandSchtroumpf approved these changes

2021-07-15 08:27 UTC, GrandSchtroumpf requested changes

2021-07-15 08:27 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/+state/movie.firestore.ts
> +  availableMaterials?:StorageFile,
Please put it as :
```typescript
delivery?: {
  file: StorageFile;
}
```
And update the rest of the code accordingly

2021-07-15 09:25 UTC, iPR0D1G1 reviewed
reviewed

2021-07-15 09:28 UTC, GrandSchtroumpf approved these changes

2021-07-15 10:17 UTC, merged