adding logline to slide component
blockframes/blockframes pull request #6307
Opened 2021-07-15 15:07 UTC by jeremie74

2021-07-15 16:17 UTC, GrandSchtroumpf requested changes

2021-07-19 07:47 UTC, jeremie74 commented on libs/movie/src/lib/movie/components/slide/slide.component.html
> +    {{ movieView.logline | maxLength: 332}}
It's not 33 but 332 i don't understand.

2021-07-19 07:51 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/components/slide/slide.component.html
> +    {{ movieView.logline | maxLength: 332}}
Sorry typo: "I don't *think* logline should be limited to *332* characters".
You can remove the maxLength pipe altogether. And if it's not used in the rest of the component, remove the `MaxLengthModule` too.

2021-07-19 08:35 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/components/slide/slide.module.ts
>          MaxLengthModule
You're not using it in the template anymore. Please remove it

2021-07-19 08:39 UTC, jeremie74 commented on libs/movie/src/lib/movie/components/slide/slide.module.ts
>          MaxLengthModule
Its done maybee you hadn't the last commit

2021-07-19 08:48 UTC, GrandSchtroumpf approved these changes

2021-07-19 09:06 UTC, jeremie74 commented
Is there a responsive version or we shoud

2021-07-19 09:06 UTC, merged