Added available summary materials to movie summary
blockframes/blockframes pull request #6316
Opened 2021-07-19 09:44 UTC by iPR0D1G1

Fixed: #6202

2021-07-19 09:47 UTC, iPR0D1G1 reviewed
reviewed

2021-07-20 07:53 UTC, GrandSchtroumpf requested changes

2021-07-20 07:53 UTC, GrandSchtroumpf commented on libs/media/src/lib/pipes/storageFile.pipe.ts
> +@Pipe({ name: 'getDownloadUrl' })
I'v got the feeling that we already have a pipe like that. Can you double check ? Maybe the name of the pipe is `download`

2021-07-20 07:53 UTC, GrandSchtroumpf commented on libs/media/src/lib/pipes/storageFile.pipe.ts
> +import firebase from 'firebase';
Use AngularFireStorage insted of storage directly

2021-07-20 07:53 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/dashboard/delivery/delivery.component.html
> +    <span>Your {{file.storagePath | fileName}}</span>
text should be "Download Available Material"

2021-07-20 07:53 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/dashboard/delivery/delivery.component.html
> +    <mat-icon svgIcon="cloud_upload" color="primary"></mat-icon>
Apply the color on the a tag, not the icon

2021-07-20 07:53 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/dashboard/delivery/delivery.component.html
> +  <a fxLayout mat-flat-button [href]="file.storagePath | getDownloadUrl | async" target="_blank" *ngIf="file.storagePath">
it's mat-button not mat-flat-button

2021-07-20 07:53 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/dashboard/delivery/delivery.component.scss
> +  margin-bottom: 32px;
margin is to organise the tag depending on the other. Here there a no others. So better is to apply padding on the parent element.

2021-07-20 07:53 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/dashboard/delivery/delivery.component.scss
> +  span {
The link doesn't have 0.5 opacity in the UI.

2021-07-20 07:53 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/available-materials/available-materials.component.html
> +<!-- ORIGINAL VERSION -->
wrong comment

2021-07-20 07:53 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/available-materials/available-materials.component.ts
> +  styleUrls: ['./available-materials.component.scss']
Always use ChangeDetectionStrategy.OnPush

2021-07-20 11:13 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/available-materials/available-materials.component.html
> +<article>
You don't need this article, you can remove it. Just put a `display: block` on the `:host`

2021-07-20 11:13 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/dashboard/delivery/delivery.component.html
> +<section>
you don't need this section, you can remove it.

2021-07-20 11:13 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/dashboard/delivery/delivery.component.scss
> +section {
apply padding on the :host, and use the same padding everywhere: 
```scss
:host {
  padding: 24px;
}
```

2021-07-20 11:13 UTC, GrandSchtroumpf commented on libs/media/src/lib/pipes/storageFile.pipe.ts
> +  transform(storagePath: string, basePath: 'protected' | 'public' = 'public'): Observable<string> {
I think it would be better to provide a `StorageFile` directly as input no ?
Maybe it won't preserve memorization though 🤔.
I'm curious, could you do a quick test to see if it works ?

2021-07-20 11:15 UTC, GrandSchtroumpf requested changes

2021-07-20 11:15 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/dashboard/delivery/delivery.component.html
> +  <article class="surface">
You can also remove this article and apply the class on the `host` itself: 
```typescript
@Component({
  ...,
  // eslint-disable next-line // <-- eslint doesn't like to update the host directly for some reasons
  host: {
    class: 'surface'
  }
})
```

2021-07-20 12:07 UTC, iPR0D1G1 commented on libs/media/src/lib/pipes/storageFile.pipe.ts
> +  transform(storagePath: string, basePath: 'protected' | 'public' = 'public'): Observable<string> {
it preserves memorization.

2021-07-20 12:16 UTC, iPR0D1G1 reviewed
Reviewed

2021-07-20 12:31 UTC, GrandSchtroumpf requested changes

2021-07-20 12:31 UTC, GrandSchtroumpf commented on libs/media/src/lib/pipes/storageFile.pipe.ts
> +    console.log({storageFile})
remove console.log ;)

2021-07-20 12:31 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/dashboard/delivery/delivery.component.scss
> +  margin-left: 24px;
You should never apply margin on a host. Margin is a way to organise element between each other, so it should be set by the parent. There is no reason to apply a margin on the :host itself.

2021-07-20 12:31 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/dashboard/delivery/delivery.component.ts
> +  // eslint-disable next-line // <-- eslint doesn't like to update the host directly for some reasons
lol, remove my comment `// <-- eslint doesn't like to update the host directly for some` it was for you ^^
Also I'm not sure about the syntax for disabling eslint on one line, did you check ?

2021-07-20 12:31 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/form/summary/available-materials/available-materials.component.ts
> +  @Input() @boolean preview=true;
Hmmmm no, it should be the other way around. If it's true by default, then these would be the same: 
```html
<movie-summary-available-materials preview></movie-summary-available-materials>
<movie-summary-available-materials></movie-summary-available-materials>
```
While one should be preview, and the other not. So you need to set the default value to false

2021-07-20 12:31 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/dashboard/delivery/delivery.component.ts
> +  selector: 'movie-view-delivery',
better selector should be `dashboard-title-delivery`. As it's a page it's not super important though

2021-07-20 12:53 UTC, GrandSchtroumpf approved these changes

2021-07-20 13:25 UTC, merged