Price in CRM should be 0 by default if no price entered - hint message
blockframes/blockframes pull request #6318
Opened 2021-07-19 12:55 UTC by jeremie74

2021-07-19 13:40 UTC, RemcoSimonides requested changes

2021-07-19 13:40 UTC, RemcoSimonides commented on libs/admin/src/lib/admin-panel/pages/offers/shell/contract-form/contract-form.component.html
> +      <input type="number" matInput formControlName="price" />
Shouldn't the `min="0"` stay? Without it you can enter sub-zero numbers I think

2021-07-19 13:40 UTC, RemcoSimonides commented on libs/admin/src/lib/admin-panel/pages/offers/shell/contract-form/contract-form.component.html
> +      <mat-hint>If no price entered. Seller will recieve active price.</mat-hint>
comma, receive* and Asking Price*  (receive is incorrectly written in the design - correct way is receive*)
"If no price entered, Seller will receive Asking Price"

2021-07-19 13:40 UTC, RemcoSimonides commented on libs/admin/src/lib/admin-panel/pages/offers/shell/contract-form/contract-form.component.html
> +      <mat-error *ngIf="form.hasError('required', 'price')">Price field is required!</mat-error> -->
You can remove it. We aim to keep the repo clean from unused code ;)

2021-07-19 13:43 UTC, jeremie74 commented on libs/admin/src/lib/admin-panel/pages/offers/shell/contract-form/contract-form.component.html
> +      <mat-hint>If no price entered. Seller will recieve active price.</mat-hint>
Ok i copied it from an other page, i had a doubt and yes its receive

2021-07-19 13:43 UTC, jeremie74 commented on libs/admin/src/lib/admin-panel/pages/offers/shell/contract-form/contract-form.component.html
> +      <mat-error *ngIf="form.hasError('required', 'price')">Price field is required!</mat-error> -->
Yes but is someone change advice, we will have to put it, but ok ill do it

2021-07-19 13:48 UTC, jeremie74 commented on libs/admin/src/lib/admin-panel/pages/offers/shell/contract-form/contract-form.component.html
> +      <input type="number" matInput formControlName="price" />
yes it's true

2021-07-21 08:15 UTC, RemcoSimonides approved these changes

2021-07-21 08:15 UTC, RemcoSimonides commented on libs/admin/src/lib/admin-panel/pages/offers/shell/contract-form/contract-form.component.ts
> +          }
After small interaction with Francois we decided to not change the price to `0` and keep `null` instead. Can you undo this again? ^^

2021-07-21 08:18 UTC, jeremie74 commented on libs/admin/src/lib/admin-panel/pages/offers/shell/contract-form/contract-form.component.ts
> +          }
I understand it's a strange request

2021-07-21 09:59 UTC, merged