more details button same behavior as invitation for notification
blockframes/blockframes pull request #6334
Opened 2021-07-20 13:02 UTC by SamirTouira

issue #6071 second checkbox

2021-07-22 14:36 UTC, GrandSchtroumpf requested changes

2021-07-22 14:36 UTC, GrandSchtroumpf commented on libs/invitation/src/lib/components/item/item.component.html
> +                <a matLine [href]="'mailto:' + user.email">{{ user | displayUser | async }}</a>invited you to {{ event.type }}
You shouldn't apply `matLine` only on the `a`. It should wrap the whole sentence: 
```html
<p matLine>
  <a [href]="'mailto:' + user.email">{{ user | displayUser | async }}</a>invited you to {{ event.type }}
  <a [target]="targetLink" [href]="[applicationUrl.festival + '/c/o/marketplace/event/' + _invitation.eventId + '/lobby']" id="link">{{ event.title }}</a>.
</p>
<span matLine>({{ event | eventRange }})</span>
```

2021-07-22 14:36 UTC, GrandSchtroumpf commented on libs/invitation/src/lib/components/item/item.component.html
> +              <span matLine>({{event | eventRange }})</span>
Either you want 2 lines, and you do like comment above, or you want one line & you remove the matLine

2021-07-22 14:36 UTC, GrandSchtroumpf commented on libs/invitation/src/lib/components/item/item.component.html
> +                <span matLine>({{ event | eventRange }})</span>
Same here

2021-07-22 14:36 UTC, GrandSchtroumpf commented on libs/invitation/src/lib/components/item/item.component.html
> +              <span matLine>({{ event | eventRange }})</span>
Same here

2021-07-22 14:36 UTC, GrandSchtroumpf commented on libs/notification/src/lib/components/item/item.component.html
> +    <mat-icon svgIcon="more_vert">
Put the mat-icon on one line.

2021-07-22 14:36 UTC, GrandSchtroumpf commented on libs/notification/src/lib/components/item/item.component.html
> +  <a mat-button [target]="targetLink" [href]="notification.url">More Details</a>
The directive to use inside a `mat-menu` is `mat-menu-item` instead of `mat-button`: 
https://material.angular.io/components/menu/overview#menu-overview

2021-07-22 14:36 UTC, GrandSchtroumpf commented on libs/utils/src/lib/pipes/time-since.pipe.ts
> +    let interval = seconds / 31536000;
What is 31536000 ? For better readability put the calcul, for example : 
```typescript
let interval = seconds / (60 * 60 * 24 * 365) // sec in a year
```

2021-07-23 05:54 UTC, RemcoSimonides commented on libs/utils/src/lib/pipes/time-since.pipe.ts
> +    if (interval >= 1) return Math.floor(interval) + (interval === 1 ? ' month' : ' months');
Your months aren't working yet. I was expecting 2 or 3 months ago here
![image](https://user-images.githubusercontent.com/27687382/126742124-1278002c-afa8-40bf-8da2-587194537930.png)

2021-07-23 05:54 UTC, RemcoSimonides commented on libs/utils/src/lib/pipes/time-since.pipe.ts
> +    return this.timeSince(value);
No need to put timeSince in a separate function. You can put the code here directly

2021-07-23 06:00 UTC, RemcoSimonides commented
Let's first confirm with design team whether the 'more details' button is now as they want it to be

2021-07-23 08:09 UTC, GrandSchtroumpf commented on libs/invitation/src/lib/components/item/item.component.html
> +                <p matLine class="mat-body1">
try `mat-body` or `mat-body-1`

2021-07-23 09:02 UTC, SamirTouira commented on libs/utils/src/lib/pipes/time-since.pipe.ts
> +    if (interval >= 1) return Math.floor(interval) + (interval === 1 ? ' month' : ' months');
yes that's what I have see too :/ is it because this is old notifications? I don't understand why it works for minutes and seconds but not months

2021-07-23 10:36 UTC, RemcoSimonides commented on libs/utils/src/lib/pipes/time-since.pipe.ts
>      return Math.floor(seconds) + " seconds";
`interval === 0` is never because you check if it's bigger or equal to 1 before.
The issue that you're trying to solve has probably something to do with rounding.
You could do
`interval = Math.floor(seconds / 2592000);` instead
if you have that, then you can also change the return line to
`if (interval >= 1) return `${interval} ${interval === 1 ? 'month' : 'months'}``

2021-07-23 13:58 UTC, GrandSchtroumpf approved these changes

2021-07-23 17:54 UTC, merged