Ongoing button
blockframes/blockframes pull request #6380
Opened 2021-07-26 10:29 UTC by Mussuranae

A beautiful animated button made with Stéphanie <3 
Part of #6241

2021-07-27 14:16 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/components/header/header.component.html
> +        <bf-ongoing-button [eventId]="eventId"></bf-ongoing-button>
Hmmm it should look like : 
```html
<a event-button [routerLink]="...">
  Ongoing Screening
</a>
```

2021-07-27 14:18 UTC, GrandSchtroumpf commented on libs/ui/src/lib/ongoing-button/ongoing-button.component.html
> +  <div class="animated-icon">
I really have the feeling that you don't need that many tags

2021-07-27 14:18 UTC, GrandSchtroumpf commented on libs/ui/src/lib/ongoing-button/ongoing-button.component.html
> +        <path d="M0 0h24v24H0z" fill="none"/>
I don't see the benefite of having a path with fill none...

2021-07-27 14:45 UTC, GrandSchtroumpf commented on libs/ui/src/lib/ongoing-button/ongoing-button.component.html
> +<span class="mat-subheading-1 light-theme">
remoe light-theme, use the black color directly in the css

2021-07-27 14:45 UTC, GrandSchtroumpf commented on libs/ui/src/lib/ongoing-button/ongoing-button.component.scss
> +  margin: 0;
you shouldn't set the margin on the :host, it should be set by the parents

2021-07-27 14:45 UTC, GrandSchtroumpf commented on libs/ui/src/lib/ongoing-button/ongoing-button.component.scss
> +  justify-content: flex-start;
This is default

2021-07-27 14:45 UTC, GrandSchtroumpf commented on libs/ui/src/lib/ongoing-button/ongoing-button.component.scss
> +  white-space: nowrap;
I'm not sure about the benefice of using that.

2021-07-27 14:45 UTC, GrandSchtroumpf commented on libs/ui/src/lib/ongoing-button/ongoing-button.component.scss
> +  transition: background 1s;
specify `background-color 1s`, you don't want any easing on that ?

2021-07-27 14:45 UTC, GrandSchtroumpf commented on libs/ui/src/lib/ongoing-button/ongoing-button.component.html
> +      <path d="M0 0h24v24H0z" fill="none"/>
you don't need this path, it has fill="none"

2021-07-27 14:45 UTC, GrandSchtroumpf commented on libs/ui/src/lib/ongoing-button/ongoing-button.component.html
> +  <div class="outCircle">
This should be part of the svg : 
```html
<svg  height="24px" width="24px" viewBox="0 0 24 24">
  <circle r="20" cx="12" cy="12" fill="white"/>
  <path d="M8 5v14l11-7z" fill="#3C64F7"/>
</svg>
```

2021-07-27 14:48 UTC, Mussuranae commented on libs/ui/src/lib/ongoing-button/ongoing-button.component.scss
> +  white-space: nowrap;
It's because for some movie, the text is on 2 lines, but we want it only on one line. I force the text to be on one line like this.

2021-07-28 07:47 UTC, GrandSchtroumpf requested changes

2021-07-28 07:47 UTC, GrandSchtroumpf commented on libs/ui/src/lib/ongoing-button/ongoing-button.component.html
> +<span class="mat-subheading-1 light-theme">
Can you remove the light-theme ?

2021-07-28 07:47 UTC, GrandSchtroumpf commented on libs/ui/src/lib/ongoing-button/ongoing-button.component.html
> +    <!-- <div class="rotate">
Please remove the comments ?

2021-07-28 07:47 UTC, GrandSchtroumpf commented on libs/ui/src/lib/ongoing-button/ongoing-button.component.html
> +      <circle r="2" cx="19.5" cy="19.5" fill="#3C64F7" class="satellite" />
IF the color are css variable, you can set the `fill` attribute on the css, like that you can use css variables : 
```scss
svg {
  circle.out {
    fill: var(--primary); // example of variable color
  }
  circle.satellite {
    fill: var(--primary-light); // example of variable color
  }
}
```

2021-07-28 07:47 UTC, GrandSchtroumpf commented on libs/ui/src/lib/ongoing-button/ongoing-button.component.scss
> +  white-space: nowrap;
Then you also want to have the ellipsis to have the "..." at the end. Also the white-space should be on the span :
```scss
:host {
  overflow: hidden;
  max-width: ...: // it can also be set by the parent like that the button can have different width depending on the pages
}
span {
  display: overflow;
  text-overflow: ellipsis;
  white-space: nowrap;
}
```

2021-07-28 07:47 UTC, GrandSchtroumpf commented on libs/ui/src/lib/ongoing-button/ongoing-button.component.html
> +<div class="animated-icon">
For me you don't need this div. please remove it

2021-07-28 07:47 UTC, GrandSchtroumpf commented on libs/ui/src/lib/ongoing-button/ongoing-button.component.scss
> +  .animated-icon {
For me it should look like that :
```scss
svg {
  margin-right: 8px;
  circle.satellite {
    transform-origin: center;
    animation: circle 10s infinite linear;
  }
}
```
No other CSS is needed

2021-07-28 07:47 UTC, GrandSchtroumpf commented on libs/ui/src/lib/ongoing-button/ongoing-button.component.scss
> +span {
span doesn't have any margin by default, it looks like you're trying to override a style from a class.

2021-07-28 07:47 UTC, GrandSchtroumpf commented on libs/ui/src/lib/ongoing-button/ongoing-button.component.scss
> +  background-color: #8da4fa;
So it'll look exactly the same in light & dark ?

2021-07-28 07:47 UTC, GrandSchtroumpf commented on libs/ui/src/lib/ongoing-button/ongoing-button.component.scss
> +@keyframes pulse {
It's better to set the `from` & `to` on the keyframes instead of just the `to`

2021-07-28 07:47 UTC, GrandSchtroumpf commented on libs/ui/src/lib/ongoing-button/ongoing-button.component.html
> +      <path d="M8 5v14l11-7z" fill="#3C64F7"/>
If the path is too big you can use a polygon. Here is an example
```svg
<polygon points="8,8 16,12 8,16" />
```
points are x,y based on the viewbox
If it's still to big you just remove the distance of the points. Here are more examples with different distances : 
```svg
<polygon points="8,8 16,12 8,16" />
<polygon points="9,9 15,12 9,15" />
<polygon points="10,10 14,12 10,14" />
<polygon points="11,11 13,12 11,13" />
```

2021-07-28 08:25 UTC, Mussuranae commented on libs/ui/src/lib/ongoing-button/ongoing-button.component.html
> +    <!-- <div class="rotate">
Yes of course, but I wanted to keep it until the end of the modification

2021-07-28 08:26 UTC, Mussuranae commented on libs/ui/src/lib/ongoing-button/ongoing-button.component.html
> +      <circle r="2" cx="19.5" cy="19.5" fill="#3C64F7" class="satellite" />
I let you see with Stéphanie for the color, but at the beginning we decided the button should stay with the light theme colors. You can talk about it with her tomorrow :)

2021-07-28 10:03 UTC, Mussuranae commented on libs/ui/src/lib/ongoing-button/ongoing-button.component.scss
> +  background-color: #8da4fa;
Yes, it has to.

2021-07-28 13:45 UTC, Mussuranae commented on libs/ui/src/lib/ongoing-button/ongoing-button.component.scss
> +span {
Yes I'm ovevrriding the margin of the subheading-1 on the span. We need the typography of the h4 (font size and weight) but there is a margin by default and we don't want it.

2021-07-28 13:46 UTC, Mussuranae commented on libs/ui/src/lib/ongoing-button/ongoing-button.component.scss
> +  white-space: nowrap;
No, we can't put an ellipsis on that button, that has no sense. I discuss with Anastasiia about it and we will put it elsewhere in the header. I will also show the new place to Stéphanie to see with her if it's okay for the Design.

2021-07-29 07:58 UTC, GrandSchtroumpf requested changes

2021-07-29 07:58 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/title/view/view.component.html
> +              <a ongoing-button [routerLink]="['/c/o/marketplace/event', eventId]">Ongoing Screening</a>
I think the selector shouldn't be "ongoing-button". This is not the button which is ongoing. Either `event-button` as it's the button of the event, or `ongoing-event-button`

2021-07-29 07:58 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/title/view/view.component.ts
> +  public screeningOngoing = false;
This should be an Observable<string> :
```typescript
eventId: Observable<string | null>;
```

2021-07-29 07:58 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/title/view/view.component.ts
> +      screenings.sort(this.sortByDate);
It's already sorted by `end` date based on the query so it should be ok, you don't need to sort again as you know you'll get a screening that has started and not yet ended. If you want you can get the last one, like that you get the screening that will last the longer (to be safe)

2021-07-29 07:58 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/title/view/view.component.ts
> +    const events$ = this.eventService.queryByType(['screening'], q);
I'm pretty sure you don't need `queryByType`
```typescript
this.eventId$ = this.eventService.valueChanges(q).pipe(
  map(events => events.filter(s => s.start < new Date())),
  map(events => events.length ? events[events.length - 1].id : null), // return id of event that last the longer
);
```

2021-07-29 07:58 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/title/view/view.component.html
> +            <ng-container *ngIf="screeningOngoing">
Should be an observable here : 
```html
<ng-container *ngIf="eventId$ | async as eventId">
  <a event-button [routerLink]="['/c/o/marketplace/event', eventId]">Ongoing Screening</a>
</ng-container>
```

2021-07-29 09:00 UTC, GrandSchtroumpf approved these changes

2021-07-29 12:49 UTC, merged