Add filters to invitation page
blockframes/blockframes pull request #6384
Opened 2021-07-26 14:56 UTC by jeremie74

State issue number in your PR to close it when PR merged: issue #XXX
e.g. : "Resolve the bundle size ❤️: issue #1234"

2021-07-26 17:27 UTC, pldespaigne requested changes

2021-07-26 17:27 UTC, pldespaigne commented on libs/invitation/src/lib/invitation.component.scss
> +}
this should be a margin instead of a padding,
moreover you can simply use `static-select {` instead of `form static-select:first-child`

2021-07-26 17:27 UTC, pldespaigne commented on libs/invitation/src/lib/invitation.component.ts
> +      map((filters) => applyFilters(invitations, { type: filters.type, status: filters.status })))),
use `combineLatest` instead, double `pipe` is really not clean

```TypeScript
newObs$ = combineLatest([
  obsA$,
  obsB$,
]).pipe(
  tap(([valueA, valueB]) => /* ... */),
);
```

2021-07-26 17:27 UTC, pldespaigne commented on libs/utils/src/lib/static-model/types.ts
> +unitBox
remove these changes, indentation was good

2021-07-26 17:30 UTC, jeremie74 commented on libs/invitation/src/lib/components/list/list.component.ts
> +  //changeDetection: ChangeDetectionStrategy.OnPush
Hi PL, i don't think you are on the right commit, because i already change and uncomment.

2021-07-26 17:32 UTC, jeremie74 commented on libs/invitation/src/lib/components/list/list.component.ts
> +  //changeDetection: ChangeDetectionStrategy.OnPush
Are u on the right commit, because i don't see it commented in my code, and i am updated.

2021-07-27 10:14 UTC, jeremie74 commented on libs/invitation/src/lib/invitation.component.ts
> +      map((filters) => applyFilters(invitations, { type: filters.type, status: filters.status })))),
We need to have a switchmap to detect the state changement of the select form. If we combine the two observables to wait for the last emitted values, we can't use switchmap

2021-07-27 13:14 UTC, closed without merging