feat(crm,catalog):content projected list of existing holdbacks to contract-item
blockframes/blockframes pull request #6477
Opened 2021-08-18 12:12 UTC by iPR0D1G1

fixed:  #6472

2021-08-18 12:52 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/marketplace/title/selection/selection.component.ts
> +  orgId:string;
you can initialize it directly here : 
```typescript
orgId = this.orgQuery.getActiveId();
```

2021-08-18 12:52 UTC, GrandSchtroumpf commented on libs/contract/src/lib/contract/holdback/form/form.component.ts
> +  @Input() otherOrgHoldBacks:Holdback[]=[];
Rename to `@Input() existingHoldbacks?: Holdback[]`.
We use the "?" here because we don't want to display anything if there is no existingHoldbacks

2021-08-18 13:47 UTC, GrandSchtroumpf commented on libs/contract/src/lib/contract/holdback/form/form.component.html
> +  <button mat-flat-button *ngIf="otherOrgHoldBacks?.length" (click)="openHoldbackModal()">
If you don't initialize the input you can do : `*ngIf="existingHoldbacks"`

2021-08-18 13:47 UTC, GrandSchtroumpf commented on libs/contract/src/lib/contract/holdback/modal/holdback-modal.component.html
> +   {{data.addingToSelection?" You can still add this right to your selection.":''}}
Use ngIf instead : 
```typescript
<span>There are some holdbacks that exists for this right.</span>
<ng-container *ngIf="data.withWarning">
  <br/>
  <span>You can still add this right to your selection.</span>
</ng-container>
```

2021-08-18 13:47 UTC, GrandSchtroumpf commented on libs/contract/src/lib/contract/holdback/modal/holdback-modal.component.ts
> +    @Inject(MAT_DIALOG_DATA) public data: { holdbacks: Holdback[], addingToSelection:boolean },
change `addingToSelection` to `withWarning`

2021-08-19 16:42 UTC, pldespaigne requested changes

2021-08-19 16:42 UTC, pldespaigne commented on libs/movie/src/lib/movie/pipes/get-title-holdbacks.ts
> +    ).then(
prefer `async`/`await` over `then`

2021-08-20 07:47 UTC, GrandSchtroumpf commented on libs/contract/src/lib/contract/holdback/modal/holdback-modal.component.ts
> +    @Inject(MAT_DIALOG_DATA) public data: { holdbacks: Holdback[], withWarning:boolean },
Hmmm I would recommend to make the `withWarning` as optional instead. If it's undefined, then it'll work as if it were `false`

2021-08-20 07:47 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/pipes/get-title-holdbacks.ts
> +  async transform(titleId: string, { excludedOrgs = [] }: { excludedOrgs: string[] },): Promise<Holdback[]> {
titleId can be null in your case above. If it's null, return `of(undefined)`;

2021-08-20 07:47 UTC, GrandSchtroumpf commented on libs/contract/src/lib/contract/item/contract-item.component.html
> +  <ng-container *ngIf="contract?.titleId| getTitleHoldbacks:{excludedOrgs:[orgId]} | async as existingHoldbacks">
This pipe is getting a little bit out of control ^^. Can you rename : 
```html
<ng-container *ngIf="contract?.titleId | getExistingHoldbacks:orgId | async as holdbacks">
```
Don't try to see future uses. Keep it simple and stupid

2021-08-20 07:47 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/pipes/get-title-holdbacks.ts
> +        .where('buyerId', 'not-in', excludedOrgs)
keep it simple. Use one `excludedOrg` and use `!=` operator

2021-08-20 08:10 UTC, pldespaigne commented on libs/contract/src/lib/contract/item/contract-item.component.html
> +  <ng-container *ngIf="contract?.titleId| getTitleHoldbacks:{excludedOrgs:[orgId]} | async as existingHoldbacks">
I told him to do that, sorry @iPR0D1G1 it's my bad

2021-08-24 08:21 UTC, pldespaigne requested changes

2021-08-24 08:21 UTC, pldespaigne commented on libs/contract/src/lib/bucket/+state/bucket.model.ts
> +export interface BucketTerm extends TermBase<Date> {
You should not have empty types, if `BucketTerm` = `TermBase`, then it should be `Term extends BucketTerm`.
There is no use to create a third base type here, I though `BucketTerm` had some other properties not included in the `Term`

2021-08-24 08:25 UTC, pldespaigne commented on libs/contract/src/lib/bucket/+state/bucket.model.ts
> +export interface BucketTerm extends TermBase<Date> {
It's even that which is breaking the CI ^^
![image](https://user-images.githubusercontent.com/5858657/130583362-99edf662-08ae-4c4e-8d53-3a2e46140b26.png)

2021-08-24 09:14 UTC, pldespaigne approved these changes

2021-08-24 10:07 UTC, merged