refactor(avails specs)
blockframes/blockframes pull request #6499
Opened 2021-08-23 13:03 UTC by iPR0D1G1

fixed: #6490

2021-08-24 08:45 UTC, pldespaigne requested changes
`collidingDurations`, `collidingMedias` and `collidingTerritories` are generic function and maybe they could be used outside of holdbacks, maybe for the "IN TERM" functions ?
Could you try that ?

2021-08-24 08:45 UTC, pldespaigne commented on libs/contract/src/lib/avails/tests/holdbacks.spec.ts
> +  // collidingDurationHoldback, will collide with collidingAllTerm due to medias,duration attributes
remove comment

2021-08-24 08:45 UTC, pldespaigne commented on libs/contract/src/lib/avails/tests/holdbacks.spec.ts
> +//collidingMediaB will collide with nonCollidingMediaA
remove comment

2021-08-24 08:45 UTC, pldespaigne commented on libs/contract/src/lib/avails/tests/holdbacks.spec.ts
> +//collidingTerritoriesB will collide with nonCollidingTerritoriesA
remove comment

2021-08-24 08:45 UTC, pldespaigne commented on libs/contract/src/lib/avails/avails.ts
> +export function collidingDurations(durationA: Duration, durationB: Duration,) {
remove trailing `,`

2021-08-31 08:42 UTC, GrandSchtroumpf commented on libs/contract/src/lib/avails/avails.ts
> +    && avail.medias && allOf(avail.medias).in(term.medias)
why not using the `optional` here ?

2021-08-31 13:15 UTC, GrandSchtroumpf approved these changes

2021-08-31 13:40 UTC, merged