Updated ui of offer successfully created.
blockframes/blockframes pull request #6503
Opened 2021-08-24 10:45 UTC by iPR0D1G1

Fixed: #6488

2021-08-24 10:48 UTC, pldespaigne requested changes

2021-08-24 10:48 UTC, pldespaigne commented on apps/catalog/catalog/src/app/marketplace/title/selection/congratulations/congratulations.component.scss
> +}
Please ask confirmation to @GrandSchtroumpf but we should not try to style link
It should be done at theme level

2021-08-24 11:25 UTC, GrandSchtroumpf approved these changes

2021-08-24 11:25 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/marketplace/title/selection/congratulations/congratulations.component.html
>  <section fxLayout="column" fxLayoutAlign="center center" fxLayoutGap="16px">
remove this section, and apply the style directly on the `:host`

2021-08-24 11:25 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/marketplace/title/selection/congratulations/congratulations.component.html
> +    You can always find your contract offer on <a mat-button [routerLink]="['../../offer']" class="offer_and_deals"><strong>Offer & Deals</strong></a> page. <br />
Inside a `<p>` we don't apply the `mat-button` on a `a` tag.
Also, if you don't have any variable use the `routerLink` without `[]`.
So it should look like taht
```html
<a routerLink="../../offer">...</a>
```

2021-08-24 11:25 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/marketplace/title/selection/congratulations/congratulations.component.html
> +  <a mat-flat-button color="primary" [routerLink]="['../../offer']">See Offers & Deals</a>
same as above for the `routerLink`

2021-08-24 11:26 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/marketplace/title/selection/congratulations/congratulations.component.scss
> +.offer_and_deals{
remove this class

2021-08-24 11:53 UTC, pldespaigne approved these changes

2021-08-25 12:04 UTC, GrandSchtroumpf approved these changes

2021-08-25 12:04 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/marketplace/title/selection/congratulations/congratulations.component.scss
> +  a {
you shouldn't have to unset. You should remove it.

2021-08-25 12:21 UTC, merged