fixed(validators.ts):proper cross validation of date fields on update
blockframes/blockframes pull request #6580
Opened 2021-09-02 10:44 UTC by iPR0D1G1

2021-09-02 11:39 UTC, pldespaigne requested changes

2021-09-02 11:39 UTC, pldespaigne commented on libs/utils/src/lib/form/validators/validators.ts
> +      let toErrors = eventForm.controls['to'].errors;
```TypeScript
let fromErrors = eventForm.controls['from'].errors ?? {};
let toErrors = eventForm.controls['to'].errors ?? {};
```
and remove the others `?? {}` from everywhere else

2021-09-02 11:39 UTC, pldespaigne commented on libs/utils/src/lib/form/validators/validators.ts
> +      }
The logic is same for both case, could you try to factorize that in a helpers ? The idea is to avoid having the same code written twice.

Also please try to avoid checking several time the same conditions in the same if/else (e.g. `keyOnControl === toKey && from && to`)

2021-09-02 13:01 UTC, pldespaigne approved these changes
you forgot some `;` but otherwise SGTM

2021-09-03 11:25 UTC, GrandSchtroumpf approved these changes

2021-09-06 07:05 UTC, GrandSchtroumpf approved these changes

2021-09-06 07:35 UTC, merged