WIP #5895
blockframes/blockframes pull request #6674
Opened 2021-09-15 15:45 UTC by phpgeekfr

2021-09-28 14:13 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/dashboard/dashboard.module.ts
> +                  component: GuestListComponent,
use loadChildren for all the children components.

2021-09-28 14:13 UTC, GrandSchtroumpf commented on libs/event/src/lib/form/meeting/meeting.component.scss
> +  .mat-form-field-appearance-outline.mat-form-field-disabled .mat-form-field-outline {
Looks like somethink that should either be in the theme ?

2021-09-28 14:13 UTC, GrandSchtroumpf commented on libs/event/src/lib/form/screening/screening.component.scss
> +  .mat-form-field-appearance-outline.mat-form-field-disabled .mat-form-field-outline {
same as above

2021-09-28 14:13 UTC, GrandSchtroumpf commented on libs/event/src/lib/form/shell/shell.component.html
> +  <section fxLayout="column" fxLayoutGap="24px">
For me this is not necessary. `nav` is a block, and `mat-card` too I think. If not better set them as `block` than adding a parent with flexbox.

2021-09-28 14:13 UTC, GrandSchtroumpf commented on libs/event/src/lib/form/shell/shell.component.html
> +<div class="buttonContainer" fxLayoutAlign="center">
why do you need a container ?

2021-09-28 15:27 UTC, phpgeekfr commented on apps/festival/festival/src/app/dashboard/event/review/review.component.html
> +
This is already the case, you looked at an outdated version of the PR

2021-09-28 15:37 UTC, phpgeekfr commented on libs/event/src/lib/form/invitation/invitation.component.html
> +﻿<section class="invitations surface" fxLayout="column">
How can I handle the `fxLayout="column"` in that case ?

For many classes, can I :
```
host: {
    class: 'surface invitations'
  },
```
 ?

2021-09-29 09:45 UTC, phpgeekfr commented on libs/event/src/lib/form/meeting-files/meeting-files.component.html
> +﻿<section class="surface">
In fact, this is not working as intended, I would like to show you the changes

2021-09-29 15:09 UTC, phpgeekfr commented on libs/event/src/lib/form/shell/shell.component.html
> +<div class="buttonContainer" fxLayoutAlign="center">
I managed to remove the fxLayout in favor of small css update but Antoine and I did not found any way to remove container for expected results

2021-09-29 15:09 UTC, phpgeekfr commented on libs/event/src/lib/form/meeting/meeting.component.scss
> +  .mat-form-field-appearance-outline.mat-form-field-disabled .mat-form-field-outline {
@Poppe-A will ask @stephanie-cascade8 on this particular point.

2021-09-30 08:10 UTC, GrandSchtroumpf requested changes

2021-09-30 08:10 UTC, GrandSchtroumpf commented on libs/event/src/lib/form/shell/shell.component.scss
> +  margin: 16px 16px 0 16px;
just put 16px everywhere

2021-09-30 08:10 UTC, GrandSchtroumpf commented on libs/event/src/lib/form/shell/shell.component.ts
> +  changeDetection: ChangeDetectionStrategy.Default  // required for changes on "pristine" for the save button
I think that putting `markForCheck` after the pristine should help.

2021-09-30 08:10 UTC, GrandSchtroumpf commented on libs/event/src/lib/form/shell/shell.component.ts
> +      this.tabs$ = this.service.valueChanges(this.form.value.id).pipe(
avoid subcriptions in subscriptions. This is a super dangerous.

2021-09-30 08:10 UTC, GrandSchtroumpf commented on styles/components/mat-form-field.scss
> +    &.mat-form-field-disabled {
did you check with Stéphanie ?

2021-09-30 08:40 UTC, GrandSchtroumpf approved these changes

2021-09-30 09:14 UTC, phpgeekfr commented on libs/event/src/lib/form/shell/shell.component.ts
> +      this.tabs$ = this.service.valueChanges(this.form.value.id).pipe(
created #6780

2021-09-30 09:53 UTC, phpgeekfr commented on styles/components/mat-form-field.scss
> +    &.mat-form-field-disabled {
yes  @Poppe-A did

2021-09-30 10:05 UTC, phpgeekfr commented on libs/event/src/lib/form/meeting-files/meeting-files.component.html
> +    <mat-list-item *ngFor="let file of files.value; let i = index" (click)="previewFile(file)">
From the doc, mat-action-list should contain only a button. this is not the case here

2021-09-30 10:32 UTC, merged