Countdown working
blockframes/blockframes pull request #6769
Opened 2021-09-28 14:55 UTC by Poppe-A

#6643

2021-09-28 15:11 UTC, RemcoSimonides requested changes
Can you make it so you don't need `event-countdown` component but only the `counter` component?

I think `counter` component only needs start date as input and you can move all the `calcDateDiff()` code into this `counter` component so it's reusable

2021-09-29 07:45 UTC, RemcoSimonides commented on libs/event/src/lib/components/countdown/counter-display/counter-display.component.html
> +      *ngIf="newMinutes !== false"
No need for `!== false`, `*ngIf="newMinutes` is enough probably (if this component shouldnt show up when newMinutes is undefined, 0, '', or null)

2021-09-29 07:47 UTC, RemcoSimonides commented on libs/event/src/lib/components/countdown/counter-display/counter-display.component.html
> +  </span>
We have 3x the same component but with different values, right? There should be a way to refactor this to 1 ^^ not sure how yet though... let me think

2021-09-29 08:05 UTC, RemcoSimonides commented
Can you move the `counter` component to the ui lib btw? as it will not only be used for events

2021-09-30 08:32 UTC, RemcoSimonides requested changes
Cleaning time

2021-09-30 08:32 UTC, RemcoSimonides commented on libs/ui/src/lib/countdown/countdown.component.html
> +  <div class="counter-display" fxLayout="row" fxLayoutAlign="space-between center" fxLayoutGap="24px">
You could rename this element to `article`. This way you only have 1 article and 1 div in this element and you don't need the class names to access the element in the css. `fxLayout="row"` can be just `fxLayout`

2021-09-30 08:32 UTC, RemcoSimonides commented on libs/ui/src/lib/countdown/countdown.component.html
> +        <div class="numberContainer" fxLayout fxLayoutAlign="center center">
remove `class=numberContainer` if you did previous mentioned change ☝️

2021-09-30 08:32 UTC, RemcoSimonides commented on libs/event/src/lib/layout/view/view.module.ts
> +import { CountdownModule } from '@blockframes/ui/countdown/countdown.module'
`;` and add new line between imports and @NgModule

2021-09-30 08:32 UTC, RemcoSimonides commented on libs/ui/src/lib/countdown/countdown.component.html
> +          [@tempNumberAnim]>
Make indentation same as previous `<p>`

2021-09-30 08:32 UTC, RemcoSimonides commented on libs/ui/src/lib/countdown/countdown.component.ts
> +  example : ['hours', 'minutes']
Move this comment above the `@Input()` variable in the class

2021-09-30 08:32 UTC, RemcoSimonides commented on libs/ui/src/lib/countdown/countdown.component.ts
> +  It also needs a date property to calculate the end of the countdown
Above `@Input() date`

2021-09-30 08:32 UTC, RemcoSimonides commented on libs/ui/src/lib/countdown/countdown.component.ts
> +  Here we'll use -1 to express false or undefined.
Move above `time` variable

2021-09-30 08:32 UTC, RemcoSimonides commented on libs/ui/src/lib/countdown/countdown.component.ts
> +  @Input() timeUnits;
Add types to these variables

2021-09-30 08:32 UTC, RemcoSimonides commented on libs/ui/src/lib/countdown/countdown.component.ts
> +  }
Move `}` to previous line since there is nothing between the brackets

2021-09-30 08:32 UTC, RemcoSimonides commented on libs/ui/src/lib/countdown/countdown.component.ts
> +    ).subscribe()
`;`

2021-09-30 08:32 UTC, RemcoSimonides commented on libs/ui/src/lib/countdown/countdown.component.ts
> +    });
For naming consistency we should name `elm` to `unit`

2021-09-30 08:32 UTC, RemcoSimonides commented on libs/ui/src/lib/countdown/countdown.component.ts
> +        this.time[elm].current = this.time[elm].new as number;
Do you need `as number`?

2021-09-30 09:39 UTC, RemcoSimonides approved these changes

2021-09-30 09:39 UTC, RemcoSimonides commented on libs/ui/src/lib/countdown/countdown.component.ts
> +  selector: 'countdown-timer',
As the `date` and `timeUnits` inputs are mandatory, we should say in this selector they are mandatory by 
`selector: '[date][timeUnits] countdown-timer'`

2021-09-30 09:39 UTC, RemcoSimonides commented on libs/ui/src/lib/countdown/countdown.component.ts
> +    });
For code consistency you should use either both a `for const ... of ...` or both `forEach`.

2021-09-30 10:15 UTC, GrandSchtroumpf commented on libs/ui/src/lib/countdown/countdown.component.html
> +  <span class="mat-body-1">Event will start in :</span>
Use `p` or a heading instead of span. `p` & headings are `display: block` so you don't need a column around.

2021-09-30 10:15 UTC, GrandSchtroumpf commented on libs/ui/src/lib/countdown/countdown.component.html
> +<section fxLayout="column" fxLayoutAlign="center center" fxLayoutGap="16px">
You don't need this section.

2021-10-01 10:32 UTC, RemcoSimonides commented on libs/ui/src/lib/countdown/countdown.component.html
> +  <p class="mat-body-1">Event will start in :</p>
This shouldn't be in this component as it is specific for event. If you want to reuse the component on the maintenace page for example, then this needs to be moved.

2021-10-01 11:45 UTC, merged