feat(sales/imports):externalised import of sales into catalog app
blockframes/blockframes pull request #6775
Opened 2021-09-29 11:23 UTC by iPR0D1G1

fixed: 6752

2021-09-29 14:58 UTC, pldespaigne requested changes
I know the task wasn't well defined, that's my bad.
But please try to avoid copy pasting code from one place to another.
Please instead try to extract common logic in re-usable components/functions.

2021-09-29 14:58 UTC, pldespaigne commented on apps/catalog/catalog/src/app/dashboard/sales/import/import-sales.module.ts
> +    // Librairies
Libraries

2021-09-29 14:58 UTC, pldespaigne commented on apps/catalog/catalog/src/app/dashboard/sales/import/import-spreadsheet/import-spreadsheet.component.ts
> +}
The same type is copy/pasted across 2 files, please define it once and import it when needed

2021-09-29 14:58 UTC, pldespaigne commented on apps/catalog/catalog/src/app/dashboard/sales/import/import-sales-container/import-sales-container.component.ts
> +  public isUserBlockframesAdmin = false;
this is not used

2021-09-29 14:58 UTC, pldespaigne commented on apps/catalog/catalog/src/app/dashboard/sales/import/import-sales-container/import-sales-container.component.ts
> +  public importedFiles = false;
this is not used

2021-09-29 14:58 UTC, pldespaigne commented on apps/catalog/catalog/src/app/dashboard/sales/import/import-spreadsheet/import-spreadsheet.component.ts
> +  private file: File;
everything should be private except for `sheets` & `allowedTypes`

2021-09-29 14:58 UTC, pldespaigne commented on apps/catalog/catalog/src/app/dashboard/sales/import/import-spreadsheet/import-spreadsheet.component.ts
> +    }
This look like duplicated code, I think it's better to re-use components than to copy/past them

2021-09-30 05:25 UTC, iPR0D1G1 commented on apps/catalog/catalog/src/app/dashboard/sales/import/import-sales-container/import-sales-container.component.ts
> +  public importedFiles = false;
It is used within the corresponding template to either show the upload file prompt or a message indicating what happens after the file is processed.

2021-09-30 09:08 UTC, pldespaigne requested changes

2021-09-30 09:08 UTC, pldespaigne commented on apps/catalog/catalog/src/app/dashboard/sales/import/import-spreadsheet/import-spreadsheet.component.ts
> +}
This is a duplicate from `libs\import\src\lib\components\import-spreadsheet\import-spreadsheet.component.ts`

2021-10-05 07:36 UTC, closed without merging