feat(catalog-avails-view-shell):design and implementation of shell
blockframes/blockframes pull request #6791
Opened 2021-10-01 12:43 UTC by iPR0D1G1

fixed: #6702

2021-10-01 13:16 UTC, GrandSchtroumpf submitted a review, later dismissed

2021-10-01 13:16 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/avails/shell/shell.component.html
> +  <mat-card fxLayout="column" fxLayoutGap="16px">
don't use mat-card except if you use specific properties of the card (mat-card-image, ...)
If you just want a surface, use the class surface: 
```html
<section class="surface">

</section>
```
No need to specify column, nav is already a block

2021-10-01 13:16 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/avails/shell/shell.component.scss
> +mat-card, h2{
That's weird. I would use a padding on the :host and a margin on the header to separate it from the section.

2021-10-01 13:16 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/avails/shell/shell.component.ts
> +  ) as Observable<Movie>;
you shouldn't have to specify it. It cannot derive the type because it doesn't know that `id` is a string. Best is to type your `movieId$: Observable<string> = this...`

2021-10-01 13:16 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/avails/shell/shell.component.ts
> +    shareReplay({ bufferSize: 1, refCount: true }),
you don't need to shareReplay, `valueChanges` does it automatically

2021-10-01 13:16 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/avails/shell/shell.component.ts
> +    map(contracts => contracts.filter(contract => contract.type === 'mandate'))
you should use a Guardtype to avoid casting the type after : 
```typescript
map(contracts => contracts.filter(isMandate))
```
If it doesn't exist already, create the guard type.

2021-10-01 13:16 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/avails/shell/shell.component.ts
> +    map(contracts => contracts.filter(contract => contract.type === 'sale'))
Same as above with `isSale`

2021-10-01 13:16 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/avails/shell/shell.component.ts
> +  private getTerms$(contracts$: Observable<Contract[]>) {
Methods should be after the constructor

2021-10-01 13:16 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/avails/shell/shell.component.ts
> +        return this.termsService.valueChanges(
Never use the `in` operator, it works on up to 10 values. Prefer using an array of ids: 
```typescript
const list = contract.flatMap(movie => movie.termIds);
return this.termsService.valueChanges(list);
```

2021-10-01 13:16 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/dashboard/avails/shell/shell.component.ts
> +      shareReplay({ bufferSize: 1, refCount: true }),
Same as above

2021-10-04 08:50 UTC, pldespaigne commented on apps/catalog/catalog/src/app/dashboard/avails/shell/shell.component.html
> +    <h2>Project International Title</h2>
This should be the title of the movie

2021-10-04 08:53 UTC, pldespaigne commented on apps/catalog/catalog/src/app/dashboard/avails/shell/shell.component.scss
> +}
`:host` style should be at the top of the file

2021-10-04 08:56 UTC, pldespaigne commented on apps/catalog/catalog/src/app/dashboard/avails/shell/shell.component.ts
> +        return this.termsService.valueChanges(list);
Did you check if we can use `'in'` for more than 10 elements ?

2021-10-04 09:06 UTC, pldespaigne requested changes
Some small changes

2021-10-04 09:18 UTC, pldespaigne approved these changes

2021-10-04 09:18 UTC, pldespaigne commented on apps/catalog/catalog/src/app/dashboard/avails/shell/shell.component.ts
> +  );
```TypeScript
public movie$ = this.route.params.pipe(
  pluck('titleId'),
  switchMap((id: string) => this.movieService.valueChanges(id)),
);
```

2021-10-04 10:04 UTC, merged