events without login - Feat 6756
blockframes/blockframes pull request #6915
Opened 2021-10-20 07:56 UTC by phpgeekfr

2021-11-05 13:37 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/meeting/room/video-room.component.ts
> +    const name = displayName(this.authQuery.user || this.authQuery.anonymousCredentials);
Why not including this in the `this.authQuery.user` directly ? 
```typescript
class AuthQuery {
  get user() {
    return this._user || this.anonymousCredentials;
  }
}
```

2021-11-05 13:37 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/screening-item/screening-item.component.html
> +  <a matRipple [routerLink]="['/event', event.id, 'r', 'i']">
So all screening are not redirected to public page, even if you're connected ?

2021-11-05 13:37 UTC, GrandSchtroumpf commented on libs/event/src/lib/guard/event-access.guard.ts
> +    this.afAuth.authState.subscribe(u => {
you should NEVER open a subscription without unsubscribing it.

2021-11-05 13:37 UTC, GrandSchtroumpf commented on libs/event/src/lib/guard/event-access.guard.ts
> +    this.listenOnCurrentUserState();
remove this line. If the user logout we should redirect the page at this moment. Not by maintaining an observable with a guard.

2021-11-05 13:37 UTC, GrandSchtroumpf commented on libs/event/src/lib/guard/event-access.guard.ts
> +      switchMap(async ([currentUser, event, anonymousCredentials]) => {
For readability extract the logic in a method : 
```typescript
return combineLatest([
  this.authService.user,
  this.service.getValue(route.params.eventId as string),
  this.authQuery.anonymousCredentials$
]).pipe(
  switchMap(([user, event, credentials]) => this.guard(route, user, event, credentials))
);
```

2021-11-05 13:37 UTC, GrandSchtroumpf commented on libs/event/src/lib/guard/event-access.guard.ts
> +        if (!currentUser.isAnonymous) return true;
You might want to check if the user exist at this point : 
```typescript
if (!currentUser) return this.router.createUrlTree(['/']);
```

2021-11-05 13:37 UTC, GrandSchtroumpf commented on libs/event/src/lib/guard/event-access.guard.ts
> +                this.router.navigate(['/']);
Prefer `return this.router.createUrlTree(['/']);`

2021-11-05 13:37 UTC, GrandSchtroumpf commented on libs/event/src/lib/guard/event-access.guard.ts
> +            return hasAnonymousIdentity(anonymousCredentials, event.accessibility) || this.router.navigate([`/event/${event.id}`]);
Prefer return `this.router.createUrlTree([`/event/${event.id}`]);`

2021-11-05 13:37 UTC, GrandSchtroumpf commented on libs/event/src/lib/guard/event-access.guard.ts
> +              this.router.navigate(['/']);
same as above

2021-11-05 13:37 UTC, GrandSchtroumpf commented on libs/event/src/lib/guard/event-auth.guard.ts
> +          catchError(() => this.router.navigate(['/'])),
I think you just need to return the string `of('/')` at this point. 
- `catchError` expect an observable.
- The `sync` method check if the result is a string, if yes it returns a UrlTree.

2021-11-05 13:37 UTC, GrandSchtroumpf commented on libs/event/src/lib/guard/event-auth.guard.ts
> +            if (!validUser) {
I think it should be `if (!validUrl) return '/auth/identity'`. As explain above the `sync` method take care of strings

2021-11-05 13:37 UTC, GrandSchtroumpf commented on libs/event/src/lib/guard/event-auth.guard.ts
> +            if (org.status === 'pending') {
same here

2021-11-05 13:37 UTC, GrandSchtroumpf commented on libs/event/src/lib/guard/event-auth.guard.ts
> +          map(async user => {
you should use `switchMap` as the callback returns a promise.

2021-11-05 13:37 UTC, GrandSchtroumpf commented on libs/event/src/lib/guard/event-role.guard.ts
> +            return this.router.navigate([`/event/${eventId}`], { queryParams: next.queryParams });
return `createUrlTree` instead of navigate.

2021-11-05 15:07 UTC, GrandSchtroumpf commented on libs/event/src/lib/pages/lobby/lobby.component.ts
> +        this.attendeeStatus = this.event.isOwner ? 'owner' : attendees[this.authQuery.userId || this.authQuery.anonymousUserId]?.status;
this is quite difficult to read, maybe : 
```typescript
const uid = this.authQuery.userId || this.authQuery.anonymousUserId;
this.attendeeStatus = this.event.isOwner ? 'owner' : attendees[uid]?.status;
```

2021-11-05 15:22 UTC, GrandSchtroumpf commented on libs/event/src/lib/pages/login/login.component.html
> +<section bgAsset="stars_wallpaper.svg" fxLayout="column" fxLayoutAlign="center center">
same as above

2021-11-05 15:24 UTC, GrandSchtroumpf commented on libs/event/src/lib/pages/login/login.component.html
> +<ng-template #customSnackBarTemplate>
This is a ver long, not very explicit name. Prefer `#noAccount`

2021-11-05 15:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/pages/login/login.component.html
> +  <div class="custom-snackbar-message" fxLayoutGap="50px">
using `fxLayoutGap` doesn't do anything, you need a `fxLayout` for that. 
You've got a class but you don't use it, so you can remove it
Just set a margin-right on the span: 
```typescript
<ng-template #noAccount>
  <span class="snack-bar-text">This account does not exist.</span>
  <a mat-button routerLink="/auth/identity">CREATE ACCOUNT</a>
</ng-template>
```

```scss
.snack-bar-text {
  margin-right: 24px;
}
```

2021-11-05 15:25 UTC, GrandSchtroumpf commented on libs/event/src/lib/pages/login/login.component.ts
> +  public loginForm = new FormGroup({
name it `form`

2021-11-05 15:26 UTC, GrandSchtroumpf commented on libs/event/src/lib/pages/login/login.component.ts
> +  private snackbarDuration = 8000;
hardcode it directly when you call it. I don't see the benefice of having a property for that.

2021-11-05 15:27 UTC, GrandSchtroumpf commented on libs/event/src/lib/pages/role/role.component.html
> +<section bgAsset="stars_wallpaper.svg" fxLayoutAlign="center center">
same as above

2021-11-05 15:29 UTC, GrandSchtroumpf commented on libs/event/src/lib/pages/role/role.component.html
> +        <img [asset]="'event_organizer.svg'" alt="organizer image">
We never use img in the button. If it's an icon, use `mat-icon` & register the icon. Else don't use a mat-button.

2021-11-05 15:29 UTC, GrandSchtroumpf commented on libs/event/src/lib/pages/role/role.component.ts
> +  click(role: 'organizer' | 'guest') {
use a better name. Maybe `update`

2021-11-05 15:36 UTC, GrandSchtroumpf commented on libs/event/src/lib/pages/view/view.component.ts
> +      emailInvitation = await this.invitationService.getValue(anonymousCredentials?.invitationId);
you should not query this here as you only use it in the `invitation-only` case.
You need to change `map(([event, invitations]) ...)` to `map(async ([event, invitations]) ...)`

2021-11-05 15:37 UTC, GrandSchtroumpf commented on libs/event/src/lib/pages/view/view.component.ts
> +          case 'public':
if you return undefined, don't specify this case.

2021-11-05 15:38 UTC, GrandSchtroumpf commented on libs/event/src/lib/pages/view/view.component.ts
> +      this.invitation = invitation
This is better to store the observable and subscribe in the template with | async :
```typescript
this.invitation$ = combineLatest([ ... ]).pipe(...);
```

2021-11-05 15:39 UTC, GrandSchtroumpf commented on libs/event/src/lib/pages/view/view.component.ts
> +            if (emailInvitation) return emailInvitation;
get the emailInvitation here : 
```typescript
case 'invitation-only': {
  const regularInvitation = invitations.find(invitation => invitation.eventId === event.id) ?? null;
  if (regularInvitation) return regularInvitation;
  if (anonymousCredentials?.invitationId) {
    return this.invitationService.getValue(anonymousCredentials?.invitationId)
  }
} // No need to return undefined.
```

2021-11-05 15:40 UTC, GrandSchtroumpf commented on libs/notification/src/lib/notifications.guard.ts
> +    ).pipe(catchError(() => of()));
Why ? ^^

2021-11-05 15:43 UTC, GrandSchtroumpf commented on libs/ui/src/lib/layout/event/event.component.html
> +        <ng-content></ng-content>
Why not using a router-outlet inside of duplicating this component on every component ?
By using it on many components you rerender the whole DOM & query each time you change the page.

2021-11-05 15:47 UTC, GrandSchtroumpf commented on libs/ui/src/lib/layout/event/event.component.html
> +      <bf-footer></bf-footer>
for me this should be outside of the `main`

2021-11-05 15:50 UTC, GrandSchtroumpf commented on libs/user/src/lib/auth/components/widget/widget.component.html
> +    <article *ngIf="anonymousUser.firstName else login" fxLayout="row">
no need to specify `row` in the `fxLayout`, it's the default one.

2021-11-05 15:51 UTC, GrandSchtroumpf commented on libs/user/src/lib/auth/guard/anonymous-auth-guard.ts
> +@CollectionGuardConfig({ awaitSync: true })
no need to use  `CollectionGuardConfig`

2021-11-05 15:52 UTC, GrandSchtroumpf commented on libs/user/src/lib/auth/guard/anonymous-auth-guard.ts
> +    await this.authService.deleteAnonymousUser();
do we really want to wait here ?

2021-11-05 17:06 UTC, phpgeekfr commented on apps/backend-functions/src/internals/users.ts
> +        invitationStatus
@Poppe-A can you check ?

2021-11-05 17:06 UTC, phpgeekfr commented on apps/backend-functions/src/invitation.ts
> +    const isLastIndex = await getOrInviteUserByMail(
@Poppe-A can you check ?

2021-11-05 17:06 UTC, phpgeekfr commented on apps/backend-functions/src/notification.ts
> +  const link = getEventLink(
@Poppe-A can you check ?

2021-11-05 17:06 UTC, phpgeekfr commented on libs/ui/src/lib/layout/marketplace/aside/aside.component.ts
> +  selector: 'marketplace-aside',
@Poppe-A can you check ?

2021-11-05 17:07 UTC, phpgeekfr commented on libs/event/src/lib/components/screening-item/screening-item.component.html
> +  <a matRipple [routerLink]="['/event', event.id, 'r', 'i']">
everything about events on marketplace are now on public url : `/event/:eventId`

2021-11-05 17:08 UTC, phpgeekfr commented on libs/event/src/lib/pages/email/email.component.html
> +<section bgAsset="stars_wallpaper.svg" fxLayout="column" fxLayoutAlign="center center">
@Poppe-A can you check ?

2021-11-05 17:08 UTC, phpgeekfr commented on libs/event/src/lib/pages/email/email.component.html
> +  <div class="surface" fxLayout="column">
@Poppe-A can you check ?

2021-11-05 17:08 UTC, phpgeekfr commented on libs/event/src/lib/pages/email/email.component.html
> +    <button fxFlexAlign="start" mat-icon-button color="black" (click)="clickBack()">
@Poppe-A can you check ?

2021-11-05 17:09 UTC, phpgeekfr commented on libs/event/src/lib/pages/email/email.component.scss
> +    display: inline-block;
@Poppe-A can you check ?

2021-11-05 17:09 UTC, phpgeekfr commented on libs/event/src/lib/pages/email/email.component.html
> +      <div>
@Poppe-A can you check ?

2021-11-05 17:10 UTC, phpgeekfr commented on libs/event/src/lib/pages/email/email.component.html
> +      <a routerLink="../login">Log with existing account</a>
@Poppe-A can you check ?

2021-11-05 17:10 UTC, phpgeekfr commented on libs/event/src/lib/pages/email/email.component.scss
> +        text-decoration: underline;
@Poppe-A can you check ?

2021-11-05 17:10 UTC, phpgeekfr commented on libs/event/src/lib/pages/identity/identity.component.html
> +<section bgAsset="stars_wallpaper.svg" fxLayout="column" fxLayoutAlign="center center">
@Poppe-A can you check ?

2021-11-05 17:10 UTC, phpgeekfr commented on libs/event/src/lib/pages/identity/identity.component.ts
> +  public identityForm = new FormGroup({
@Poppe-A can you check ?

2021-11-05 17:10 UTC, phpgeekfr commented on libs/event/src/lib/pages/email/email.component.ts
> +  public emailForm = new FormGroup({
@Poppe-A can you check ?

2021-11-05 17:11 UTC, phpgeekfr commented on libs/event/src/lib/pages/identity/identity.component.ts
> +    this.authStore.updateAnonymousCredentials({
@Poppe-A can you check ?

2021-11-05 17:11 UTC, phpgeekfr commented on libs/event/src/lib/pages/login/login.component.html
> +<section bgAsset="stars_wallpaper.svg" fxLayout="column" fxLayoutAlign="center center">
@Poppe-A can you check ?

2021-11-05 17:11 UTC, phpgeekfr commented on libs/event/src/lib/pages/login/login.component.html
> +<ng-template #customSnackBarTemplate>
@Poppe-A can you check ?

2021-11-05 17:11 UTC, phpgeekfr commented on libs/event/src/lib/pages/login/login.component.html
> +  <div class="custom-snackbar-message" fxLayoutGap="50px">
@Poppe-A can you check ?

2021-11-05 17:11 UTC, phpgeekfr commented on libs/event/src/lib/pages/login/login.component.ts
> +  public loginForm = new FormGroup({
@Poppe-A can you check ?

2021-11-05 17:12 UTC, phpgeekfr commented on libs/notification/src/lib/notifications.guard.ts
> +    ).pipe(catchError(() => of()));
so the guard run without error if you are logged in as anonymous

2021-11-05 17:14 UTC, phpgeekfr commented on libs/ui/src/lib/layout/event/event.component.html
> +        <ng-content></ng-content>
@Poppe-A we will check this together, we will need no re-think the url structure to separate email, login, identity, role pages from session, view, ended lobby
But for this I need to rework guards

2021-11-05 17:14 UTC, phpgeekfr commented on libs/event/src/lib/pages/role/role.component.html
> +        <img [asset]="'event_organizer.svg'" alt="organizer image">
@Poppe-A can you check ?

2021-11-05 17:15 UTC, phpgeekfr commented on libs/event/src/lib/pages/role/role.component.html
> +<section bgAsset="stars_wallpaper.svg" fxLayoutAlign="center center">
@Poppe-A can you check ?

2021-11-05 17:15 UTC, phpgeekfr commented on libs/event/src/lib/pages/login/login.component.ts
> +  private snackbarDuration = 8000;
@Poppe-A can you check ?

2021-11-05 17:15 UTC, phpgeekfr commented on libs/event/src/lib/pages/role/role.component.ts
> +  click(role: 'organizer' | 'guest') {
@Poppe-A can you check ?

2021-11-05 17:16 UTC, phpgeekfr commented on libs/ui/src/lib/layout/event/event.component.html
> +      <bf-footer></bf-footer>
@Poppe-A can you check ?

2021-11-05 17:16 UTC, phpgeekfr commented on libs/user/src/lib/auth/components/widget/widget.component.html
> +    <article *ngIf="anonymousUser.firstName else login" fxLayout="row">
@Poppe-A can you check ?

2021-11-08 20:58 UTC, phpgeekfr commented on libs/event/src/lib/guard/event-auth.guard.ts
> +          catchError(() => this.router.navigate(['/'])),
I tried but this does not work

2021-11-08 21:12 UTC, phpgeekfr commented on libs/event/src/lib/guard/event-auth.guard.ts
> +            if (!validUser) {
This is working only when we first enter the guard, but not when user goes from valid to invalid

2021-11-09 10:56 UTC, phpgeekfr commented on apps/backend-functions/src/internals/users.ts
> +        invitationStatus
yes it is the expected behaviour

2021-11-09 11:03 UTC, phpgeekfr commented on libs/event/src/lib/guard/identity-check-guard.ts
> +    ).subscribe();
this guard was removed

2021-11-09 11:04 UTC, phpgeekfr commented on libs/event/src/lib/pages/email/email.component.scss
> +        margin-bottom: 58px;
@Poppe-A can you check ?

2021-11-09 11:07 UTC, phpgeekfr commented on libs/event/src/lib/guard/event-auth.guard.ts
> +            if (org.status === 'pending') {
This is working only when we first enter the guard, but not when user goes from valid to invalid

2021-11-09 14:56 UTC, Poppe-A commented on libs/event/src/lib/pages/login/login.component.ts
> +  private snackbarDuration = 8000;
We have a property here to change the text while waiting for email/password verification, as we do on the shelle component (submit demo request, sending request, ...)

2021-11-09 16:00 UTC, phpgeekfr commented on libs/ui/src/lib/layout/event/event.component.html
> +      <bf-footer></bf-footer>
@GrandSchtroumpf  This is the case for all the layouts (dashboard & marketplace). If you want to move this we should do it for all layouts in a separate issue.

2021-11-10 12:49 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/event/email/email.component.scss
> +  background-image: url("/assets/images/light/stars_wallpaper.svg");
what about dark theme ? You can use `:host-context(body.dark-theme) :host {..}`

2021-11-10 12:49 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/event/identity/identity.component.scss
> +  background-image: url("/assets/images/light/stars_wallpaper.svg");
same as above

2021-11-10 12:49 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/event/event.component.html
> +<layout-event>
I though layout-event was using `router-outlet`

2021-11-10 13:38 UTC, phpgeekfr commented on apps/festival/festival/src/app/event/email/email.component.scss
> +  background-image: url("/assets/images/light/stars_wallpaper.svg");
dark theme cannot be shown on this page (and also login, identity, role)

2021-11-10 15:12 UTC, GrandSchtroumpf requested changes

2021-11-10 15:12 UTC, GrandSchtroumpf commented on apps/backend-functions/src/notification.ts
> +  console.log(`Sending request email to attend an event (${notification.docId}) from ${notification.user.uid} to : ${toAdmin.email}`);
prefer the firebase Logger than console

2021-11-10 15:12 UTC, GrandSchtroumpf commented on apps/backend-functions/src/notification.ts
> +  if (invitation.mode === 'request' || (invitation.mode === 'invitation' && eventData.accessibility === 'private')) {
difficult to read. use a variable with a good name

2021-11-10 15:12 UTC, GrandSchtroumpf commented on libs/event/src/lib/form/edit-details/edit-details.component.ts
> +    if (this.dialogSub) {
you can do `this.dialogSub?.unsubscribe();` directly

2021-11-10 15:12 UTC, GrandSchtroumpf commented on libs/event/src/lib/guard/event-auth.guard.ts
> +            if (!validUser) {
The guard shouldn't be the one responsible to trigger navigation once you are in the page

2021-11-10 15:12 UTC, GrandSchtroumpf commented on libs/event/src/lib/guard/event-auth.guard.ts
> +            if (org.status === 'pending') {
same as above

2021-11-10 15:12 UTC, GrandSchtroumpf commented on libs/ui/src/lib/layout/event/event.component.html
> +      <bf-footer></bf-footer>
ok

2021-11-10 16:09 UTC, phpgeekfr commented on libs/ui/src/lib/layout/event/event.component.html
> +      <bf-footer></bf-footer>
created #7087

2021-11-10 16:24 UTC, GrandSchtroumpf approved these changes

2021-11-11 10:38 UTC, merged