6996 Buyer preferences
blockframes/blockframes pull request #7301
Opened 2021-12-01 15:09 UTC by RemcoSimonides

Fix #6996
Waiting for UI

2021-12-02 09:10 UTC, GrandSchtroumpf requested changes

2021-12-02 09:10 UTC, GrandSchtroumpf commented on libs/user/src/lib/auth/pages/profile-view/profile-view.component.ts
>    }
```suggestion
    const hasPreferences = this.navLinks.some(link => link.path === 'preferences');
    if (hasPreferences) return;
    const org = this.organizationQuery.getActive();
    const app = getCurrentApp(this.routerQuery);
    if (app !== 'catalog' && app !== 'festival') return;
    const { marketplace, dashboard } = org.appAccess[app];
    if (marketplace && !dashboard) {
      this.navLinks.push({ path: 'preferences', label: 'Buyer Preferences' })
    }
  }
```

Would be a good idea to extract the logic of `canHavePreferences` : 
```typescript
function canHavePreferences(org: Organization, app: App) {
    if (app !== 'catalog' && app !== 'festival') return;
    const { marketplace, dashboard } = org.appAccess[app];
    return marketplace && !dashboard;
}
```

2021-12-02 09:10 UTC, GrandSchtroumpf commented on libs/utils/src/lib/mailchimp/mailchimp-model.ts
> +export function getPreferenceTag(type: string, tags: string[] = [], status: MailchimpTagStatus): MailchimpTag[] {
type & tags can be any string ? Or do we want some string literals ?

2021-12-02 09:10 UTC, GrandSchtroumpf commented on libs/user/src/lib/auth/forms/preferences/preferences.form.ts
> +export function createPreferences(params: Partial<Preferences> = {}): Preferences {
This should be in the model file, not in the form file.

2021-12-02 09:10 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/home/home.component.ts
> +          autoFocus: false
why you don't want to autofocus ? If the user is user TAB it'll be very difficult for him to focus the content of the modal.
You can use the `cdkFocusInitial` directive if you want a specific focus.

2021-12-02 09:26 UTC, RemcoSimonides commented on libs/utils/src/lib/mailchimp/mailchimp-model.ts
> +export function getPreferenceTag(type: string, tags: string[] = [], status: MailchimpTagStatus): MailchimpTag[] {
There are too many options. It's all genre | language | media | territory and some more.
And in order to have more clear names, I wanted to have `genre_animation` instead of only `animation` as a tag.
If you know of a smart way to create all these string literals, then I love to hear you suggestion ^^

2021-12-02 13:38 UTC, RemcoSimonides commented on apps/festival/festival/src/app/marketplace/home/home.component.ts
> +      const org = await this.orgService.getValue(this.authQuery.user.orgId)
For this to work there needs to be a subscription on the `active$`. Creating this subscription in this service isn't the best practice, is it?

2021-12-02 13:56 UTC, RemcoSimonides commented on apps/festival/festival/src/app/marketplace/home/home.component.ts
> +          autoFocus: false
The initial focus is set on the close button in the top-right corner of the modal. It has been disabled for most if not all modals. `cdkFocusInitial` doesn't work on any of the elements in the html.

2021-12-02 14:02 UTC, RemcoSimonides commented on libs/user/src/lib/auth/forms/preferences/preferences.component.html
> +    <chips-autocomplete [form]="form.get('languages')" scope="languages">
Not supported on `chips-autocomplete`. Do you want me to add support? Looking at `static-group` how its done, it might be fun :)

2021-12-03 13:35 UTC, GrandSchtroumpf approved these changes

2021-12-03 16:14 UTC, merged