7242 search with a space
blockframes/blockframes pull request #7302
Opened 2021-12-02 08:42 UTC by RemcoSimonides

Fix #7242

2021-12-03 09:49 UTC, GrandSchtroumpf requested changes

2021-12-03 09:49 UTC, GrandSchtroumpf commented on libs/utils/src/lib/form/form-state-url-encoder.ts
> +  if (dateKeys.includes(key) && typeof value === 'string') {
A much cleaner way would be to use the same format for replacing Date in stringify & parse : 
- Stringify: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#the_replacer_parameter
- parse: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#using_the_reviver_parameter

2021-12-06 11:02 UTC, RemcoSimonides commented
After doing some more tests, I found out the `dateReviver` function still returned the date as a string and all the filters do get their pre-filled data and everything is working.

`dateReviver` function caused some bugs if it recognised a string as a date even if it wasn't a date (e.g. 'movie 1')

2021-12-07 11:50 UTC, GrandSchtroumpf approved these changes

2021-12-07 12:08 UTC, merged