Implement unit-tests described in issue 4833
blockframes/blockframes pull request #7316
Opened 2021-12-03 07:30 UTC by xmano

Closes #4833

2021-12-03 09:54 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +        status: 'accepted',
is some tests :
- User with admin role
- With User not belonging to any org

movies MI-0d7 is  described as a draftMovie (`draftMovieId`) please rename this var that can be confusing

2021-12-03 11:19 UTC, xmano commented on apps/rules/src/tests/firestore/movies.spec.ts
> +        let movies = [];
done

2021-12-03 11:19 UTC, xmano commented on apps/rules/src/tests/firestore/movies.spec.ts
> +        let movies = [];
done

2021-12-03 11:20 UTC, xmano commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +        status: 'accepted',
Will rethink this and see if it conflicts the other tests. Get back to you on this.

2021-12-03 11:21 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +        status: 'accepted',
From what I saw, it only needs to be renamed in 

-    User with admin role
-   With User not belonging to any org

2021-12-03 11:33 UTC, phpgeekfr requested changes

2021-12-03 11:33 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/movies.spec.ts
> +      test('should be able to fetch movie collection for current org', async () => {
add a new test that should fail if we are asking for movies of a given org if current user is not orgMember

2021-12-03 11:33 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/movies.spec.ts
> +      test('should be able to fetch movie collection for query condition', async () => {
add a new test without specifying `.where('app.financiers.status', '==', 'accepted')` that should fail

2021-12-03 11:33 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/movies.spec.ts
> +      test('should be able to fetch movie collection for query condition', async () => {
you are testing a query where connected user org is  'O001 .. so any query should work .. change the user you are connected with for this test for an user that does not belong to   'O001 ..

2021-12-03 11:39 UTC, xmano commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +        status: 'accepted',
ok will rename

2021-12-07 06:44 UTC, xmano commented on apps/rules/src/tests/firestore/movies.spec.ts
> +      test('should be able to fetch movie collection for current org', async () => {
This is covered in the scenario:
`test('should be able to fetch movie collection for current org)'

Here the movie from org 'O003' is not present in the list. So I think it covers the case you mentioned.

Also we have positive confirmation that movies only belonging to the org will be listed here.

2021-12-07 08:49 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/movies.spec.ts
> +      test('should be able to fetch movie collection for current org', async () => {
This does not cover it at all.
The query  `const movieRef = db.collection('movies').where('orgIds', 'array-contains', orgId);`  is asking form movies of orgId O001 how can movies from org 'O003' can be present here ? 

The goal of this test is to check if orgMembers of a given org can fetch movies they own ( despite of the movie status) and that members of others orgs can not

2021-12-07 08:50 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/movies.spec.ts
> +      test('should be able to fetch movie collection for current org', async () => {
so add a new test that should fail if we are asking for movies of a given org if current user is not orgMember

2021-12-07 08:51 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/movies.spec.ts
> +      test('should be able to fetch movie collection for query condition', async () => {
I just tried to remove `.where('app.financiers.status', '==', 'accepted')` from query and this still work. So this test is not testing what we want: we want users to be able to fetch only accepted movies of an org they are not member of

2021-12-07 08:59 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/movies.spec.ts
> +        expect(movies).not.toEqual(expect.arrayContaining(unexpectedMovie));
remove this. as this is not testing what we want and may be confusing

2021-12-07 08:59 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/movies.spec.ts
> +        expect(movies).toEqual(expect.arrayContaining(expectedMovie));
remove this. as this is not testing what we want and may be confusing

2021-12-07 13:04 UTC, xmano commented on apps/rules/src/tests/firestore/movies.spec.ts
> +      test('should be able to fetch movie collection for query condition', async () => {
Created new test for addressing this and merged your code in right place.

2021-12-07 13:16 UTC, phpgeekfr commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +  },
this is not used

2021-12-07 13:30 UTC, xmano commented on apps/rules/src/tests/firestore/fixtures/data.ts
> +  },
removed

2021-12-07 13:59 UTC, merged