[💣 DO NOT MERGE] Avails big Refactoring
blockframes/blockframes pull request #7359
Opened 2021-12-07 13:49 UTC by pldespaigne

This is a feature branch, do not merge

2022-01-04 13:35 UTC, GrandSchtroumpf requested changes

2022-01-04 14:11 UTC, pldespaigne commented on apps/catalog/catalog/src/app/dashboard/avails/map/map.component.ts
> +    if (!decodedData.medias) decodedData.medias = [];
There is no territories in the form and so in the url, because we are on the Map

2022-01-04 14:17 UTC, pldespaigne commented on libs/contract/src/lib/avails/filter/filter.component.html
> +<mat-form-field appearance="outline" *ngIf="safeGet('territories') as territories">
I didn't had the time or the energy to dig further

`libs/contract/src/lib/avails/filter/filter.component.ts`, line 20
```TypeScript
public safeGet(key: keyof AvailsFilter) {
  // if we don't cast the type, we get a type error
  // this is probably caused by the way the FormEntity is typed
  return (this.form as AvailsForm).get(key);
}
```

2022-01-05 15:35 UTC, GrandSchtroumpf approved these changes

2022-01-05 15:35 UTC, GrandSchtroumpf commented on libs/contract/src/lib/avails/filter/filter.component.html
> +<mat-form-field appearance="outline" *ngIf="safeGet('territories') as territories">
Ok, then create an issue for Springfield.

2022-01-05 15:37 UTC, merged

2022-01-05 15:48 UTC, pldespaigne commented on libs/contract/src/lib/avails/filter/filter.component.html
> +<mat-form-field appearance="outline" *ngIf="safeGet('territories') as territories">
Done 👉 #7508

2022-01-05 15:49 UTC, pldespaigne commented
Done 👉 #7508