Crm contract list
blockframes/blockframes pull request #7755
Opened 2022-02-14 14:24 UTC by yspringfield

Fixed: #7226

2022-02-15 15:41 UTC, yspringfield commented
here's how the sale-list component looks like both in the crm and catalog.
<img width="1440" alt="Bildschirmfoto 2022-02-15 um 4 29 21 PM" src="https://user-images.githubusercontent.com/22674720/154096254-86759695-48da-457d-80c8-4c4ac7d4f89f.png">
<img width="1440" alt="Bildschirmfoto 2022-02-15 um 4 29 31 PM" src="https://user-images.githubusercontent.com/22674720/154096270-6d0cc23f-c3f1-4e8a-b389-ef3eb406d8be.png">
<img width="1440" alt="Bildschirmfoto 2022-02-15 um 4 31 07 PM" src="https://user-images.githubusercontent.com/22674720/154096278-b57fd58f-21f0-4090-83e7-1c1d25140d80.png">

2022-02-17 15:00 UTC, GrandSchtroumpf requested changes

2022-02-17 15:00 UTC, GrandSchtroumpf commented on libs/contract/src/lib/contract/list/list.component.ts
> +    return sale.stakeholders.find(
same as above

2022-02-18 11:41 UTC, GrandSchtroumpf commented on apps/crm/crm/src/app/crm/pages/external-sales/view/view.component.ts
> +      })
I think you can inline it.
```suggestion
      tap(contract => this.statusForm.setValue(contract.status))
```

2022-02-18 11:41 UTC, GrandSchtroumpf commented on libs/contract/src/lib/contract/list/external-sales/external-sales.component.html
> +<ng-container *ngIf="sales as externalSales">
You can gt rid of this line and on the second line do:
```html
<ng-container *ngIf="externalSales?.length; else empty">
  ...
</ng-container>
```

2022-02-18 11:41 UTC, GrandSchtroumpf commented on libs/contract/src/lib/contract/list/external-sales/external-sales.component.scss
> +  display: flex;
I don't see the benefit of a flex here. A simple `display: block` would do the trick I think

2022-02-18 11:41 UTC, GrandSchtroumpf commented on libs/contract/src/lib/contract/list/external-sales/external-sales.component.html
> +  <ng-content select="[empty]"></ng-content>
If you've bot only one `ng-content` you don't need to use a select.

2022-02-18 11:41 UTC, GrandSchtroumpf commented on libs/contract/src/lib/contract/list/internal-sales/internal-sales.component.html
> +      <bf-table *ngIf="internalSales.length" [source]="internalSales | filterBy: filterBySalesStatus: filter.value"
wrong tab

2022-02-18 11:41 UTC, GrandSchtroumpf commented on libs/contract/src/lib/contract/list/internal-sales/internal-sales.component.html
> +  <ng-content select="[empty]"></ng-content>
same as above

2022-02-18 11:41 UTC, GrandSchtroumpf commented on libs/contract/src/lib/contract/list/internal-sales/internal-sales.component.scss
> +  display: flex;
same as above

2022-02-18 11:41 UTC, GrandSchtroumpf commented on libs/contract/src/lib/contract/list/internal-sales/internal-sales.component.ts
> +  filterBySalesStatus(sale: Sale, index: number, status: ContractStatus): boolean {
This method doesn't rely on the context (`this`), so it can be outside of the class.

2022-02-18 11:41 UTC, GrandSchtroumpf approved these changes

2022-02-21 07:40 UTC, yspringfield commented on libs/contract/src/lib/contract/list/internal-sales/internal-sales.component.ts
> +  filterBySalesStatus(sale: Sale, index: number, status: ContractStatus): boolean {
It is used within the template, so it needs to be declared in the class to be accessible there.

2022-02-21 08:31 UTC, merged