[E2E] SIGNUP : WIP - for advice
blockframes/blockframes pull request #7773
Opened 2022-02-15 10:45 UTC by n-germain-work

2022-02-15 10:53 UTC, phpgeekfr commented on apps/festival/festival-e2e/src/integration/login/signup.spec.ts
> +//TODO : move functions inside a library
Take the habit to always bind a TODO with a issue number:
`// TODO #xxx : move functions inside a library`

2022-02-15 10:53 UTC, phpgeekfr commented on apps/backend-functions/src/templates/mail.ts
> +  if (e2eMode) return supportEmails.mailosaur
missing `:` ;)

2022-02-15 10:53 UTC, phpgeekfr commented on env/env.blockframes-nicolas.ts
> +  mailosaur: 'support@fteeksuu.mailosaur.net'
I'm not sure this one is supposed to be here, please find a better location as this is only intended for e2e tests

2022-03-10 10:13 UTC, george43g requested changes

2022-03-10 10:13 UTC, george43g commented on apps/festival/festival-e2e/src/integration/login/signup.spec.ts
> +    cy.task('getRandomOrg', { application: 'festival', access: 'dashboard' }).then(
we will eventually improve these to either generate data or do a more precise search

2022-03-10 10:13 UTC, george43g commented on apps/festival/festival-e2e/src/integration/login/signup.spec.ts
> +        interceptEmail({ sentTo: user.email })
really nicely done!

2022-03-10 10:13 UTC, george43g commented on libs/e2e/src/lib/utils/functions.ts
> +export function interceptEmail(option: InterceptOption) {
use the new libs as the location for these helper funcs. You're welcome to move/refactor any pure TS funcs you need into this lib as well

2022-03-10 10:13 UTC, george43g commented on libs/organization/src/lib/organization/forms/organization-lite-form/organization-lite-form.component.html
> +        <mat-option *ngIf="activity.key !== 'other'" [value]="activity.key" [attr.test-id]="'activity_' + i">
great initiative

2022-03-10 10:13 UTC, george43g commented on libs/user/src/lib/auth/components/data-validation/data-validation.component.ts
>      window.location.reload();
this would refresh everything including the cypress test runner no?

2022-03-10 12:13 UTC, phpgeekfr reviewed
a lot of missing `;` please add them

2022-03-10 12:13 UTC, phpgeekfr commented on libs/testing/cypress/src/lib/plugins/auth.ts
> +  return await auth.updateUser(user.uid, {emailVerified: true})
missing spaces

2022-03-10 12:13 UTC, phpgeekfr commented on libs/testing/cypress/src/lib/plugins/db.ts
> +  console.log(email);
remove console.log

2022-03-10 12:13 UTC, phpgeekfr commented on libs/testing/cypress/src/lib/plugins/db.ts
> +export async function getRandomUser() {
you will be able to close #7701

2022-03-10 12:13 UTC, phpgeekfr commented on libs/testing/cypress/src/lib/plugins/db.ts
> +  const randomUser = users[Math.floor(Math.random() * users.length)];
do `return users[Math.floor(Math.random() * users.length)];` directly

2022-03-10 12:13 UTC, phpgeekfr commented on libs/testing/cypress/src/lib/plugins/db.ts
> +  const randomOrg = orgs[Math.floor(Math.random() * orgs.length)];
`return orgs[Math.floor(Math.random() * orgs.length)];`

2022-03-10 12:13 UTC, phpgeekfr commented on libs/testing/cypress/src/lib/plugins/db.ts
> +export async function getRandomOrg(data: { application: string; access: 'marketplace' | 'dashboard' }) {
for `access` use existing type `Module`

2022-03-10 12:13 UTC, phpgeekfr commented on libs/testing/cypress/src/lib/plugins/db.ts
> +export async function getRandomOrg(data: { application: string; access: 'marketplace' | 'dashboard' }) {
`application` can be typed to `App`

2022-03-10 12:13 UTC, phpgeekfr commented on libs/testing/cypress/src/lib/plugins/db.ts
> +  const randomUser = users[Math.floor(Math.random() * users.length)];
You don't need to do `data()` for each documents. 
you can do :

```
return userQuery.docs[Math.floor(Math.random() * users.length)].data();
```

2022-03-10 12:13 UTC, phpgeekfr commented on libs/testing/cypress/src/lib/plugins/db.ts
> +export async function getRandomUser() {
add return type `User`

2022-03-10 12:13 UTC, phpgeekfr commented on libs/testing/cypress/src/lib/plugins/db.ts
> +export async function getRandomOrg(data: { application: string; access: 'marketplace' | 'dashboard' }) {
add return type `Organization`

2022-03-10 12:13 UTC, phpgeekfr commented on libs/testing/cypress/src/lib/plugins/db.ts
> +export async function getRandomOrg(data: { application: string; access: 'marketplace' | 'dashboard' }) {
in fact, instead of `getRandomOrg(data: { application: string; access: 'marketplace' | 'dashboard' })
you should use  `getRandomOrg(data: { app: App; access: ModuleAccess })`

(see OrgAppAccess)

2022-03-10 12:13 UTC, phpgeekfr commented on libs/testing/cypress/src/lib/plugins/db.ts
> +    .where(`appAccess.${application}.dashboard`, '==', access === 'dashboard')
this looks weird but should look cleaner after my suggestion above

2022-03-10 12:13 UTC, phpgeekfr commented on libs/testing/cypress/src/lib/plugins/db.ts
> +  console.log(invitation);
remove console.Log

2022-03-10 12:13 UTC, phpgeekfr commented on libs/ui/src/lib/algolia/autocomplete/algolia-autocomplete.component.html
> +    <mat-option [value]="result | deepKey: keyToDisplay" (onSelectionChange)="selected(result) " [attr.test-id]="'org_' + i">
you should be able to remove `ng-container` and put `*ngFor="let result of (algoliaSearchResults$ | async); let i = index"` directly into `mat-option'

2022-03-10 12:13 UTC, phpgeekfr commented on libs/ui/src/lib/static-autocomplete/select/static-select.component.html
> +      <mat-option [value]="value" [attr.test-id]="'country_' + i">
same

```
<mat-option *ngFor="let value of staticValue; let i = index" [value]="value" [attr.test-id]="'country_' + i">
```

2022-03-10 12:17 UTC, phpgeekfr commented on libs/e2e/src/lib/utils/functions.ts
> +  return cy.mailosaurGetMessage(serverId, option, {receivedAfter: now})
will this really prevent mail overlap if two tests from 2 PR are running at same time ?

2022-03-10 13:38 UTC, n-germain-work commented on libs/user/src/lib/auth/components/data-validation/data-validation.component.ts
>      window.location.reload();
Bruce's code here ^^
I tested it, and it only reloads the emulated window, not the tests 👌

2022-03-10 13:55 UTC, n-germain-work commented on libs/e2e/src/lib/utils/functions.ts
> +  return cy.mailosaurGetMessage(serverId, option, {receivedAfter: now})
combined with random names & emails I believe yes 👌

2022-03-10 13:58 UTC, n-germain-work commented on apps/festival/festival-e2e/cypress.json
> +  "viewportHeight": 1080
I've discussed with Camille, and the first definition we should focus on is a lambda hd one. By writting the resolution in this options file, I force Cypress to render it, and not to adapt depending of my window size.
This way, if I make my Cypress window smaller or bigger, the test window will just shrink or get bigger, but always behaving in HD.

2022-03-10 14:02 UTC, phpgeekfr commented on libs/organization/src/lib/organization/forms/organization-lite-form/organization-lite-form.component.html
> +        <mat-option *ngIf="activity.key !== 'other'" [value]="activity.key" [attr.test-id]="'activity_' + i">
I think that you don't need ng-container

2022-03-10 14:12 UTC, n-germain-work commented on apps/catalog/catalog-e2e/src/support/pages/landing/LandingPage.ts
> +    cy.get('button[test-id="cookies"]', {timeout: 3 * SEC})
I wanted to shorten it, still keeping the sense. I can put it back if you want ^^

2022-03-10 14:13 UTC, phpgeekfr commented on apps/catalog/catalog-e2e/src/support/pages/landing/LandingPage.ts
> +    cy.get('button[test-id="cookies"]', {timeout: 3 * SEC})
as you want

2022-03-10 14:14 UTC, n-germain-work commented on libs/testing/cypress/src/lib/plugins/auth.ts
>  }
All the `createUserToken` function ?
I haven't touched it, propably a mistake. I'm erasing it 👌

2022-03-10 14:18 UTC, n-germain-work commented on libs/ui/src/lib/algolia/autocomplete/algolia-autocomplete.component.html
> +    <mat-option [value]="result | deepKey: keyToDisplay" (onSelectionChange)="selected(result) " [attr.test-id]="'org_' + i">
If you don't mind, I prefer having the loop logic separated from the values, functions and test attributes. Its easier to read. Do you mind keeping it this way ? ^^

2022-03-10 14:18 UTC, n-germain-work commented on libs/ui/src/lib/static-autocomplete/select/static-select.component.html
> +      <mat-option [value]="value" [attr.test-id]="'country_' + i">
Same ^^

2022-03-10 14:20 UTC, phpgeekfr commented on libs/ui/src/lib/algolia/autocomplete/algolia-autocomplete.component.html
> +    <mat-option [value]="result | deepKey: keyToDisplay" (onSelectionChange)="selected(result) " [attr.test-id]="'org_' + i">
I think @GrandSchtroumpf would prefere my solution, but your argument is also good

2022-03-11 08:19 UTC, GrandSchtroumpf commented on libs/ui/src/lib/algolia/autocomplete/algolia-autocomplete.component.html
> +    <mat-option [value]="result | deepKey: keyToDisplay" (onSelectionChange)="selected(result) " [attr.test-id]="'org_' + i">
Usually I put on the element directly except when it makes the line to long and difficult to read. Then I use a `ng-container`
Here I think the `ng-container` makes sense

2022-03-11 08:48 UTC, n-germain-work commented on apps/festival/festival-e2e/src/integration/login/signup.spec.ts
> +    indexedDB.deleteDatabase('firebaseLocalStorageDb');
Like this ?
`beforeEach(() => {
    cy.visit('home');
    auth.clearBrowserAuth();
    cy.visit('auth/identity');
  });`

2022-03-11 14:48 UTC, n-germain-work commented on apps/backend-functions/src/templates/mail.ts
> +import { supportMailosaur } from '@blockframes/e2e/utils';
I'm moving all my code into the library George prepared, and as I'll eventually redo all the existing tests with a better structure, only the `supportMailsaur` will be kept.

2022-03-11 14:51 UTC, n-germain-work commented on libs/e2e/src/lib/utils/commands.ts
> +  app.auth().useEmulator('http://localhost:9099')
not anymore indeed, as we'll use George library 👌

2022-03-11 14:51 UTC, n-germain-work commented on libs/e2e/src/lib/utils/env.ts
> +export const supportMailosaur = `support@${serverId}.mailosaur.net`;
I've moved mine to the new library 👌

2022-03-15 15:31 UTC, phpgeekfr commented on libs/testing/cypress/src/lib/plugins/db.ts
> +import { User, Organization } from '../../../../e2e/src'
don't do imports like this , use `@blockframes/e2e`

2022-03-15 15:31 UTC, phpgeekfr commented on libs/testing/e2e/src/lib/type.ts
> +}
this is a duplicate of `libs/testing/e2e/src/lib/type.ts`

And why not using existing models ?

2022-03-15 15:31 UTC, phpgeekfr commented on libs/testing/cypress/src/lib/plugins/db.ts
> +export async function getRandomUser() {
`getRandomUser` is used only in this file, no need to export it.

2022-03-15 15:31 UTC, phpgeekfr commented on libs/testing/cypress/src/lib/plugins/db.ts
> +export async function getRandomUser() {
instead of casting `as User` use existing `createUser()`
same for `as Organization` use `createOrganization()`
and get rid of models in `libs/testing/e2e/src/lib/type.ts`

2022-03-15 15:31 UTC, phpgeekfr commented on libs/testing/e2e/src/lib/support.ts
> +export function getAllStartingWith(selector: string) {
you can remove export

2022-03-15 15:31 UTC, phpgeekfr commented on libs/testing/cypress/src/lib/plugins/db.ts
> +  return userQuery.docs[Math.floor(Math.random() * userQuery.docs.length)].data() as Organization;
```
  const { app, access } = data;
  const { docs } = access.dashboard ? await getDashboardOrgs(app) : await getMarketplaceOrgs(app);
  const randomIndex = Math.floor(Math.random() * docs.length);
  return createOrganization(docs[randomIndex].data());
```

2022-03-15 15:31 UTC, phpgeekfr commented on libs/testing/cypress/src/lib/plugins/db.ts
> +  return docRef.update({ status: 'accepted' });
I think this is more elegant
```
  const [org] = userQuery.docs;
  const { id: orgId } = org.data();
  const docRef = db.collection('orgs').doc(orgId);
```

2022-03-15 15:31 UTC, phpgeekfr commented on libs/testing/cypress/src/lib/plugins/db.ts
> +  return db.collection('invitations').doc(invitation.id).update({ status: 'accepted' });
You should be able to query invitation with userEmail directly :
```
  const userQuery = await db.collection('invitations').where('fromUser.email', '==', userEmail).get();
  const [invitation] = userQuery.docs;
  const { id: invitationId } = invitation.data();
  return db.collection('invitations').doc(invitationId).update({ status: 'accepted' });
```

2022-03-15 15:31 UTC, phpgeekfr commented on libs/testing/e2e/src/lib/support.ts
> +import { InterceptOption } from "./type";
use  single quotes

2022-03-18 03:21 UTC, george43g commented on apps/catalog/catalog-e2e/src/integration/marketplace/create-bucket.spec.ts
> +import { assertUrlIncludes } from 'libs/testing/e2e/src';
+1

2022-03-18 03:23 UTC, george43g commented on libs/testing/e2e/src/lib/type.ts
> +}
yeah +1 - we are trying not to duplicate interfaces and have them all in models lib

2022-03-22 22:37 UTC, n-germain-work commented on apps/catalog/catalog-e2e/src/integration/marketplace/create-bucket.spec.ts
> +import { assertUrlIncludes } from 'libs/testing/e2e/src';
This one is an old test, I've just modified it because of my `assertUrlInclues()` function replacing the `assertMoveTo()` ones. The rest will be remodeled entirely in the future.

2022-03-23 09:06 UTC, phpgeekfr commented on apps/catalog/catalog-e2e/src/integration/dashboard/import.spec.ts
> +// eslint-disable-next-line @nrwl/nx/enforce-module-boundaries
// eslint-disable-next-line @nrwl/nx/enforce-module-boundaries TODO #xxxx

2022-03-23 09:36 UTC, phpgeekfr commented on apps/catalog/catalog-e2e/src/integration/landing/account-creation.spec.ts
> +    const newOrgUSer = {...USER, ...{email: supportMailosaur}};
bad formatting

2022-03-23 09:36 UTC, phpgeekfr commented on apps/backend-functions/src/internals/users.ts
> +  const mailRequest = await userFirstConnexion(user);
remove async

2022-03-23 09:36 UTC, phpgeekfr commented on apps/backend-functions/src/templates/mail.ts
> +  const supportEmail = e2eMode ? supportMailosaur : getSupportEmail(user._meta.createdFrom);
this method is not async.
remove `e2eMode ? supportMailosaur`

2022-03-23 09:36 UTC, phpgeekfr commented on apps/catalog/catalog-e2e/src/integration/landing/account-creation.spec.ts
> +﻿/* eslint-disable @nrwl/nx/enforce-module-boundaries */
same

2022-03-23 09:36 UTC, phpgeekfr commented on apps/catalog/catalog-e2e/src/integration/marketplace/create-bucket.spec.ts
> +﻿/* eslint-disable @nrwl/nx/enforce-module-boundaries */
same

2022-03-23 09:36 UTC, phpgeekfr commented on libs/e2e/src/lib/utils/commands.ts
>    return app.auth().signInWithEmailAndPassword(email, password);
duplicate code with apps/catalog/catalog-e2e/src/support/commands.ts

2022-03-23 09:36 UTC, phpgeekfr commented on apps/catalog/catalog-e2e/src/integration/landing/account-creation.spec.ts
>    "A new organization has been created",
use single quotes

2022-03-23 09:36 UTC, phpgeekfr commented on apps/festival/festival-e2e/src/integration/dashboard/screening-invitations-2688.spec.ts
> +// eslint-disable-next-line @nrwl/nx/enforce-module-boundaries
same

2022-03-23 09:36 UTC, phpgeekfr commented on apps/festival/festival-e2e/src/integration/landing/demo-request.spec.ts
> +/* eslint-disable @nrwl/nx/enforce-module-boundaries */
same

2022-03-23 09:36 UTC, phpgeekfr commented on apps/festival/festival-e2e/src/plugins/index.ts
> +import { testingCypress } from '@blockframes/testing/cypress/server'
missing `;`

2022-03-23 09:36 UTC, phpgeekfr commented on apps/festival/festival-e2e/src/support/index.ts
> +// eslint-disable-next-line @nrwl/nx/enforce-module-boundaries
same

2022-03-23 09:36 UTC, phpgeekfr commented on apps/financiers/financiers-e2e/src/integration/marketplace/investment-email.spec.ts
> +// eslint-disable-next-line @nrwl/nx/enforce-module-boundaries
same

2022-03-23 09:36 UTC, phpgeekfr commented on libs/e2e/src/lib/utils/functions.ts
> +// eslint-disable-next-line @nrwl/nx/enforce-module-boundaries
same

2022-03-23 09:36 UTC, phpgeekfr commented on libs/landing/src/lib/shell/shell.component.ts
> +// eslint-disable-next-line @nrwl/nx/enforce-module-boundaries
same

2022-03-23 09:36 UTC, phpgeekfr commented on libs/testing/cypress/src/lib/client/auth.ts
> +    await w['LoginService'].signOut().then(res => console.log('signout res : ', res));
remove console.log

2022-03-23 09:36 UTC, phpgeekfr commented on libs/testing/cypress/src/lib/client/index.ts
> +export { events };
missing `;`

2022-03-23 10:16 UTC, phpgeekfr approved these changes

2022-03-23 10:31 UTC, george43g approved these changes

2022-03-23 11:05 UTC, merged