Reviewing emails and notifications
blockframes/blockframes pull request #7946
Opened 2022-03-10 08:13 UTC by Poppe-A

#7742
Some code about non used emails is commented. But we keep it in case we use package deal again in the future.

2022-03-10 09:34 UTC, RemcoSimonides commented on apps/backend-functions/src/notification.ts
> +  await Promise.all([
use `return` instead of `await` here. To keep it as it was and also maybe we don't need to wait for the emails to be sent ;)

2022-03-10 09:34 UTC, RemcoSimonides commented on apps/backend-functions/src/notification.ts
> +    movie,
Change to `movie: title`

2022-03-10 09:34 UTC, RemcoSimonides commented on apps/backend-functions/src/notification.ts
> +  let adminTemplateId = null;
No need to initiate with null
`let adminTemplateId;` does suffice

2022-03-10 09:34 UTC, RemcoSimonides commented on apps/backend-functions/src/notification.ts
> +      adminTemplateId = templateIds.negotiation.toAdminContractDeclined;
Are you sure it should be within this if statement? `if (options.didRecipientAcceptOrDecline) {`
It makes sense to me if it's next to `templateId = templateIds.negotiation.myContractWasDeclined;`

2022-03-10 09:34 UTC, RemcoSimonides commented on apps/backend-functions/src/notification.ts
> +  await Promise.all(mailToSend);
```
if (adminTemplateId) {
  const adminTemplate = { to: supportEmails.catalog, templateId: adminTemplateId, data };
  return Promise.all([
    sendMailFromTemplate(template, app, groupIds.unsubscribeAll),
    sendMailFromTemplate(adminTemplate, app, groupIds.unsubscribeAll)
  ])
} else {
  return sendMailFromTemplate(template, app, groupIds.unsubscribeAll),
}
```

2022-03-10 09:34 UTC, RemcoSimonides commented on apps/backend-functions/src/templates/mail.ts
> +    movie
`movie: title`

2022-03-10 09:42 UTC, RemcoSimonides commented on libs/utils/src/lib/emails/ids.ts
> +    // underSignature: 'd-38ee6949f4724b1c8796b8df9229f21d'//To remove
You can remove the `// To remove` comments

2022-03-10 09:42 UTC, RemcoSimonides commented on libs/user/src/lib/auth/pages/identity/identity.component.html
> +              </a>.
Why is this? I don't see it in the issue?

2022-03-10 09:45 UTC, Poppe-A commented on apps/backend-functions/src/notification.ts
> +      adminTemplateId = templateIds.negotiation.toAdminContractDeclined;
If I understood correctly, we only want to send the email when the org declined the contract, not when the buyer do it

2022-03-10 09:48 UTC, Poppe-A commented on libs/user/src/lib/auth/pages/identity/identity.component.html
> +              </a>.
It's from another issue, but since it's very fast to do, I wanted to put it here. But I will remove it

2022-03-10 13:21 UTC, phpgeekfr requested changes

2022-03-10 13:21 UTC, phpgeekfr commented on apps/backend-functions/src/notification.ts
>        case "userRequestAppAccess":
replace to singlequotes please

2022-03-10 13:21 UTC, phpgeekfr commented on apps/backend-functions/src/notification.ts
> +    movie: title,
doing this will break emails templates that where using `title`

2022-03-10 13:21 UTC, phpgeekfr commented on apps/backend-functions/src/templates/mail.ts
> +    movie: title,
same

2022-03-10 13:21 UTC, phpgeekfr commented on apps/backend-functions/src/templates/mail.ts
> +    offer,
do we really need the whole offer object ? If only id is used, use only id, else, create something like `orgEmailData`

2022-03-10 13:21 UTC, phpgeekfr commented on apps/backend-functions/src/templates/mail.ts
> +    movie: title,
same as above, and maybe created something like `orgEmailData`

2022-03-10 13:21 UTC, phpgeekfr commented on apps/backend-functions/src/templates/mail.ts
> +    movie: title
same

2022-03-10 13:21 UTC, phpgeekfr commented on apps/backend-functions/src/templates/mail.ts
> +    movie: title
same

2022-03-10 13:21 UTC, phpgeekfr commented on libs/utils/src/lib/emails/utils.ts
> +    contractId?: string,
I think you are missing : app,  movieTitle, MovieUrl, orgNames, negotiation, date, offer, offerId

We have both `pageUrl` and `pageURL`

2022-03-10 13:21 UTC, phpgeekfr commented on libs/utils/src/lib/emails/utils.ts
> +    contractId?: string,
doing `buyer?: PublicUser | string,` also shows that we are doing not pretty stuffs.

Can you add this to #7491 ?

2022-03-10 13:21 UTC, phpgeekfr commented on apps/backend-functions/src/notification.ts
> +    movie: title,
and this we can have movie & tv contentType, title is more appropriate

2022-03-10 13:48 UTC, phpgeekfr commented on libs/utils/src/lib/emails/utils.ts
>      bucket?: MailBucket,
for a better consistency, `MailBucket` should be renammed to `BucketEmailData`

2022-03-11 08:11 UTC, RemcoSimonides commented on apps/backend-functions/src/offer.ts
> +
```suggestion
```

2022-03-11 08:32 UTC, RemcoSimonides approved these changes

2022-03-11 08:32 UTC, RemcoSimonides commented on apps/backend-functions/src/notification.ts
> +  if(adminTemplateId) {
```suggestion
  if (adminTemplateId) {
```

2022-03-11 08:32 UTC, RemcoSimonides commented on apps/backend-functions/src/notification.ts
> +    movie: title,
Shouldn't this also use `getMovieEmailData()`?

2022-03-11 08:32 UTC, RemcoSimonides commented on libs/notification/src/lib/+state/notification.service.ts
> +import { filter, map, switchMap, take, tap } from 'rxjs/operators';
```suggestion
import { filter, map, switchMap, take } from 'rxjs/operators';
```

2022-03-11 08:32 UTC, RemcoSimonides commented on libs/notification/src/lib/+state/notification.service.ts
> +      const org = await this.orgService.valueChanges(contract.sellerId).pipe(take(1)).toPromise() as Organization;
How come it doesn't know the type?

notification doesn't already contain either the org or user data?

2022-03-11 08:32 UTC, RemcoSimonides commented on libs/notification/src/lib/+state/notification.service.ts
> +  // The goal of this method is to return a user name or an org name depending on who is receiving a counter offer
```
/**
* @returns A username or org name depending on who is receiving a counter offer
*/
```
☝️ this way, the text will show up when you hover the function name

2022-03-11 08:32 UTC, RemcoSimonides commented on libs/utils/src/lib/emails/utils.ts
> +    movie?: MovieEmailData | MovieDocument,
Would be nice if we can have only `MovieEmailData`. Could you add that as to do for issue https://github.com/blockframes/blockframes/issues/7624 perhaps?

2022-03-11 08:32 UTC, RemcoSimonides commented on libs/utils/src/lib/emails/utils.ts
> +    buyer?: PublicUser | string,
Would be nice if we can have only `PublicUser`. Could you add that as to do for issue https://github.com/blockframes/blockframes/issues/7624 perhaps?

2022-03-11 08:40 UTC, Poppe-A commented on libs/notification/src/lib/+state/notification.service.ts
> +  // The goal of this method is to return a user name or an org name depending on who is receiving a counter offer
Thx !

2022-03-11 08:46 UTC, Poppe-A commented on libs/notification/src/lib/+state/notification.service.ts
> +      const org = await this.orgService.valueChanges(contract.sellerId).pipe(take(1)).toPromise() as Organization;
This is what the notifications look like :

```
app: {isRead: false}
docId: "FNBIAvyBVAuYFsR4Ms6R"
docPath: "contracts/FNBIAvyBVAuYFsR4Ms6R/negotiations/bdSuxDWVZfdJnntvaa0e"
email: {isSent: true}
id: "QKXRBpvHofIkWTXwZ3Xk"
offerId: "ROB-464544"
toUserId: "g04XYIOQ2AQ2a6rZ7xC5cNofpo33"
type: "createdCounterOffer"
_meta: {createdBy: 'internal', createdAt: t, createdFrom: 'catalog'}
```

2022-03-11 14:04 UTC, RemcoSimonides commented on libs/notification/src/lib/+state/notification.service.ts
> +      const org = await this.orgService.valueChanges(contract.sellerId).pipe(take(1)).toPromise() as Organization;
Alright. Asked because the `Notification` interface does have org / user in there

But how come it doesn't know the type? It should know the type already. Is `contract.sellerId` not known as a string?

2022-03-11 14:05 UTC, phpgeekfr commented on libs/notification/src/lib/+state/notification.service.ts
> +      return org.denomination.public;
use `orgName`

2022-03-11 14:16 UTC, Poppe-A commented on libs/notification/src/lib/+state/notification.service.ts
> +      const org = await this.orgService.valueChanges(contract.sellerId).pipe(take(1)).toPromise() as Organization;
My mistake. `as Organization` is removed

2022-03-11 16:26 UTC, merged