4.1 Event fixes
blockframes/blockframes pull request #8043
Opened 2022-03-18 14:25 UTC by Poppe-A

#7980

2022-03-21 09:08 UTC, RemcoSimonides requested changes

2022-03-21 09:08 UTC, RemcoSimonides commented on libs/invitation/src/lib/form/user/user.component.ts
> +        this.snackBar.open('Something went wrong ...', 'close', { duration: 5000 });
I think it's important to know what caused the 'internal' error and fix that instead.

2022-03-21 09:08 UTC, RemcoSimonides commented on libs/movie/src/lib/movie/components/request-asking-price/request-asking-price.component.ts
> +  public disableSendButton: boolean;
`disableSendButton = false;`

☝️ I also don't specify `public` because it's default by public and I see that the other variable in this class (form) also doesn't specify it. So I'd keep it consistent

2022-03-22 08:31 UTC, Poppe-A commented on libs/event/src/lib/guard/event-access.guard.ts
> +          this.snackBar.open('Sorry, it seems that you were not invited to this event', 'Try with other mail', { duration: 6000 })
It was a request from Anastasiia

2022-03-22 08:54 UTC, Poppe-A commented on libs/invitation/src/lib/form/user/user.component.ts
> +        this.snackBar.open('Something went wrong ...', 'close', { duration: 5000 });
That was also a request from Anastasiia, and I couldn't reproduce the error

2022-03-22 11:02 UTC, RemcoSimonides approved these changes

2022-03-22 14:08 UTC, merged