slate event view component
blockframes/blockframes pull request #8105
Opened 2022-03-25 09:05 UTC by Poppe-A

#6844

2022-03-28 13:23 UTC, RemcoSimonides requested changes

2022-03-28 13:23 UTC, RemcoSimonides commented on apps/festival/festival/src/app/event/view/view.component.html
> +            <p *ngIf="event.type === 'screening'" class="mat-body-2">{{ event.meta.description }}</p>
Meeting also has `event.meta.description`? I think it shouldn't be hidden for meeting
Maybe you should ask design team if it's okay to show the description here too for Slate. Saying this because if the designs for each event type start to differentiate too much, then it's better to create separate components for each.

2022-03-28 13:23 UTC, RemcoSimonides commented on apps/festival/festival/src/app/event/view/view.component.html
> +            <p *ngIf="event.type === 'screening'" class="mat-body-2">{{ event.meta.description }}</p>
Same as above

2022-03-28 13:23 UTC, RemcoSimonides commented on apps/festival/festival/src/app/event/view/view.component.html
> +                  <span>{{ user | displayName }}{{ user | displayPosition }}</span>
It would be nice to have some space between username and position.
Also fix for meeting since this code is a duplicate of that.

2022-03-28 13:23 UTC, RemcoSimonides commented on apps/festival/festival/src/app/event/view/view.component.html
> +            <bf-carousel flex [min]="4">
`[min]="4"` doens't look good on small screen. Isn't it possible to make it responsive?

2022-03-28 13:23 UTC, RemcoSimonides commented on apps/festival/festival/src/app/event/view/view.component.scss
> +    width: calc(25% - 24px);
Make it responsive

2022-03-28 13:23 UTC, RemcoSimonides commented on apps/festival/festival/src/app/event/view/view.component.scss
> +@import '~@angular/flex-layout/mq';
Is this needed?

2022-03-28 13:23 UTC, RemcoSimonides commented on apps/festival/festival/src/app/event/view/view.component.ts
> +      map(event => event as Event<Slate>),
This event can be any type of event. Use a Pipe instead to get the titles. In the html you know already it's of type Slate, here you don't. `event.meta.titles | getTitle | async`

Sorry for not noting this last time, but can you change the interface to
```
export interface Slate {
  description: string;
  organizerUid: string;
  titleIds: string[];
  video: string;
}
```
☝️ Note the `string[]`, the `;` at the end and `titleIds` instead of `titles` since it's only the ids, not the titles themselves.

Also, next time you should do `switchMap((event: Event<Slate>) => ...` instead of this map

2022-03-29 07:41 UTC, Poppe-A commented on apps/festival/festival/src/app/event/view/view.component.ts
> +      map(event => event as Event<Slate>),
I also changed `video` for `videoId` since its not the whole `videoStorage` object, but just the id

2022-03-29 08:29 UTC, Poppe-A commented on apps/festival/festival/src/app/event/view/view.component.html
> +            <p *ngIf="event.type === 'screening'" class="mat-body-2">{{ event.meta.description }}</p>
Ok. I'll correct it with the second choice (discussed with Ana:. We put the event description in the header. Then UX/UI team will possibly do a rework on the header

2022-03-29 09:58 UTC, Poppe-A commented on apps/festival/festival/src/app/event/view/view.component.scss
> +@import '~@angular/flex-layout/mq';
It is now for the media query

2022-03-29 12:08 UTC, RemcoSimonides approved these changes

2022-03-29 12:30 UTC, merged