7689 add back no titles ui for dashboard
blockframes/blockframes pull request #8158
Opened 2022-03-30 14:36 UTC by RemcoSimonides

The states of dashboard where an organization doesn't have any (accepted) movie yet was accidentally removed. This PR adds it back.
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/27687382/160860582-d3910b78-9f6b-4ff4-96f9-c384346b671d.png">

2022-03-30 14:54 UTC, GrandSchtroumpf requested changes

2022-03-30 14:54 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/dashboard/home/home.component.html
> +<ng-container *ngIf="titles$ | async as titles; else loading">
you're not using titles in the template. You can remove it

2022-03-30 14:54 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/dashboard/home/home.component.html
> +    <header>
I think the correct html would be : 
```html
<h1></h1>
<nav>
  <a>...</a>
  <a>...</a>
  <a>...</a>
</nav>
```

2022-03-30 14:54 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/dashboard/home/home.component.scss
> +    width: 330px;
why do you hardcode width & height ?

2022-03-31 07:47 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/home/home.component.html
> +    <header>
The header has css making it a row. Putting the buttons next to the h1 instead of on a new line.

2022-03-31 07:51 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/home/home.component.scss
> +    width: 330px;
width is needed in order not to make it too wide, especially on smaller screens where they're arranged as a column.
Height could be removed indeed.
<img width="827" alt="image" src="https://user-images.githubusercontent.com/27687382/161005123-c365e309-c230-4c44-bd9d-edc24d1a80bf.png">

2022-03-31 07:52 UTC, RemcoSimonides commented
FYI, I've also updated the changes in `libs/ui/src/lib/dashboard/pages/home/home.component.ts` of which this is mostly a copy

2022-03-31 10:21 UTC, GrandSchtroumpf approved these changes
change the array in `hasAppStatus:['accepted']` to a single string `hasAppStatus:'accepted'`

2022-03-31 10:55 UTC, merged