Adapt LP for mobile
blockframes/blockframes pull request #8201
Opened 2022-04-06 12:32 UTC by Poppe-A

#7194

2022-04-07 06:24 UTC, RemcoSimonides requested changes
Just curious; did you check the impact of your changes on catalog and financiers too? as some of the files touch multiple apps

2022-04-07 06:24 UTC, RemcoSimonides commented on apps/festival/festival/src/app/landing/landing.component.scss
> +    #headerToScroll {
Change casing type to be just as all the other classes.
I don't think you need this id btw. `landing-header` has only one header anyway so you can do
```
landing-header {
  header {
    ...
  }
}
```

2022-04-07 06:24 UTC, RemcoSimonides commented on apps/festival/festival/src/app/landing/landing.component.scss
> +    #landing-partners {
No need to change this to an `id=""` I think

2022-04-07 06:24 UTC, RemcoSimonides commented on apps/festival/festival/src/app/landing/landing.component.scss
> +      .opinions > div {
This targets only the direct `div` children of `opinions`? Why not just give that `div` a class of "opinion" instead? It's easier to understand for me

2022-04-07 06:24 UTC, RemcoSimonides commented on libs/landing/src/lib/shell/shell.component.html
>        <span>First invitation</span>
It's getting difficult to maintain with all these `fxHide`s on these button
Check with Stephanie if it's okay to have only 'Join us' button on `sm` devices too and then you can refactor this all to a 
```
<ng-container *ngIf="ltMd$ | async; else gtSm">
  Join us
</ng-container>
<ng-template #gtSm>
  Schedule demo, login, sign up, first invitation
</ng-template>
```

2022-04-07 06:24 UTC, RemcoSimonides commented on libs/landing/src/lib/shell/shell.component.html
> +          <div fxLayout fxFlex fxLayoutAlign.lt-sm="center">
`fxLayoutAlign.xs`

2022-04-07 06:24 UTC, RemcoSimonides commented on libs/landing/src/lib/shell/shell.component.html
> +          <form fxFlex fxLayout.lt-sm="column" fxLayoutAlign.lt-sm="center" [formGroup]="newslettersForm" (ngSubmit)="subscribe(newslettersForm)">
Same as above

2022-04-07 06:24 UTC, RemcoSimonides commented on libs/landing/src/lib/shell/shell.component.scss
> +      }
It doesn't say anything about a scroll bar in the issue?
Maybe this should be done on a global level. And check if the screen has touch capabilities?

2022-04-07 06:24 UTC, RemcoSimonides commented on libs/landing/src/lib/shell/shell.component.scss
> +        width: 90%;
I don't think this is what Stephanie wants as it wont align properly with other elements on the page.
Why not use `padding-inline`?

2022-04-07 07:11 UTC, Poppe-A commented on apps/festival/festival/src/app/landing/landing.component.scss
> +    #headerToScroll {
I had to use the `id` because some general styling (in the shell.component) were overriding this
```
landing-header {
  header {
    ...
  }
}
```
(ID has more priority)

2022-04-07 07:45 UTC, Poppe-A commented on libs/landing/src/lib/shell/shell.component.scss
> +        width: 90%;
No need, it's already `width: 80%;`
It was a bit small on my opinion

2022-04-07 08:32 UTC, Poppe-A commented
> Just curious; did you check the impact of your changes on catalog and financiers too? as some of the files touch multiple apps

Yep, catalog and financiers desktop LP are ok.
I also worked on catalog LP for mobile, and I asked Camille if we need to rework financiers LP.

2022-04-07 13:45 UTC, RemcoSimonides commented on apps/festival/festival/src/app/landing/landing.component.scss
> +    #headerToScroll {
how come?

Anyway the naming is bad now. It's not being used to scroll to

2022-04-11 07:08 UTC, RemcoSimonides commented on apps/catalog/catalog/src/app/landing/landing.component.html
> +  <app-bridge-banner fxHide.lt-sm></app-bridge-banner>
`fxHide.xs`

2022-04-11 07:08 UTC, RemcoSimonides commented on apps/festival/festival/src/app/landing/landing.component.html
> +  <app-bridge-banner fxHide.lt-sm></app-bridge-banner>
`fxHide.xs`

2022-04-11 07:08 UTC, RemcoSimonides commented on apps/festival/festival/src/app/landing/landing.component.html
> +        <div fxLayout="row wrap" fxLayoutAlign.lt-sm="space-around center" fxLayoutGap="32px" fxLayoutGap.lt-sm="16px">
`fXlayoutAlign.xs=""` && `fxLayoutGap.xs`

2022-04-11 07:08 UTC, RemcoSimonides commented on apps/festival/festival/src/app/landing/landing.component.scss
> +      }
The guy in the video that Francois sent, he mentioned that it's usually better to have extra css for large screen instead of small screen.

Higher in this css file we add padding for these component, and now we have to remove it again for small screen. What if you only add padding for bigger screen so you don't have to 'undo' that here.

2022-04-11 07:48 UTC, Poppe-A commented on apps/festival/festival/src/app/landing/landing.component.scss
> +      }
Not easy to change it, we have to define padding for large, medium, and small screen

2022-04-11 07:50 UTC, Poppe-A commented on apps/festival/festival/src/app/landing/landing.component.scss
> +    #headerToScroll {
Yes it's used to scroll to, on the app-bridge-banner component

2022-04-11 07:52 UTC, Poppe-A commented on apps/festival/festival/src/app/landing/landing.component.scss
> +    #headerToScroll {
Shell component override it line 125 :
```
 landing-shell-page main landing-header header {
    padding: 60px 80px;
}
```

2022-04-12 13:41 UTC, GrandSchtroumpf commented on apps/catalog/catalog/src/app/landing/landing.component.html
> +    <header id="header-to-scroll" class="max-width" fxLayout="column" fxLayoutAlign="start start" fxLayoutAlign.xs="center center" fxLayoutGap="32px">
As I mentioned to @RemcoSimonides, consider using more CSS and less `fxLayout` to manage the responsivness

2022-04-12 13:41 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/landing/landing.component.html
> +    <header id="header-to-scroll" class="max-width" fxLayout="column" fxLayoutAlign="start start" fxLayoutAlign.xs="start center" fxLayoutGap="32px">
same as above and below.

2022-04-12 13:41 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/landing/landing.component.html
> +              <h2 fxHide.xs>{{ tabTitle[0].title }}</h2>
There is an issue with the hierarchy of heading here. You already have a h2 above. This should be fixed.
Also using CSS would be more efficient here than fxHide : 
```
header h2 { // <- should not be h2
  display: none;
}
```

2022-04-12 13:41 UTC, GrandSchtroumpf commented on libs/landing/src/lib/shell/shell.component.html
> +    <ng-container *ngIf="ltMd$ | async; else gtSm">
use CSS instead of Breakpoint.

2022-04-14 14:20 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/landing/landing.component.scss
> +      gap: 0;
```suggestion
```

2022-04-14 14:23 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/landing/landing.component.scss
> +        div {
If it's not a flex it doesn't do anything

2022-04-14 14:25 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/landing/landing.component.scss
>  @include layout-bp(lt-sm) {
This is the same as `@include layout-bp(xs)`

2022-04-14 14:25 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/marketplace.component.scss
> +@import "~@angular/flex-layout/mq";
remove `~`

2022-04-14 14:27 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/title/view/view.component.scss
> +@import "~@angular/flex-layout/mq";
remove `~`

2022-04-14 14:27 UTC, GrandSchtroumpf commented on apps/financiers/financiers/src/app/marketplace/title/view/view.component.scss
> +@import "~@angular/flex-layout/mq";
same as above and below

2022-04-14 14:28 UTC, GrandSchtroumpf commented on libs/event/src/lib/components/slide/slide.component.html
> +      <a fclass="title-image" [routerLink]="['/event', event.id, 'r', 'i']">
```suggestion
      <a class="title-image" [routerLink]="['/event', event.id, 'r', 'i']">
```

2022-04-14 14:31 UTC, GrandSchtroumpf commented on libs/landing/src/lib/shell/shell.component.html
> +    <div class="desktop-navbar">
remove this div and use `a:not(.mobile-navbar) { display: none; }`

2022-04-19 08:28 UTC, RemcoSimonides approved these changes

2022-04-19 08:56 UTC, merged