7961 responsive movie banner
blockframes/blockframes pull request #8202
Opened 2022-04-07 07:56 UTC by RemcoSimonides

Fix #7961

2022-04-07 07:57 UTC, RemcoSimonides commented on apps/festival/festival/src/app/marketplace/title/view/view.component.html
> +            <button mat-button class="translucent" [disabled]="requestSent" (click)="requestAskingPrice(movie.id)">
I didn't commit the changes properly in my previous PR to change `translucent-button` to `translucent`.

2022-04-07 10:29 UTC, GrandSchtroumpf requested changes

2022-04-07 10:29 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/title/view/view.component.html
> +              <span *ngIf="gtSm$ | async" class="linear-wipe">Request Asking Price</span>
why not using `fxHide.gtsm` ?

2022-04-07 10:29 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/title/view/view.component.scss
> +    @include layout-bp(xs) {
I prefer to put the media queries at the root of the css file

2022-04-07 10:29 UTC, GrandSchtroumpf commented on apps/festival/festival/src/app/marketplace/title/view/view.component.ts
> +    private breakpointsService: BreakpointsService
I don't think you need it

2022-04-07 10:29 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/components/header/header.component.scss
> +          height: 400px;
It's usually better to use properties like `min()`, `max()` or `clamp()` for sizing than media queries with fixed value

2022-04-07 10:29 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/components/promotional-links/promotional-links.component.html
> +  <ng-container *ngIf="xs$ | async; else gtxs">
This should be managed by CSS. HTML is not CSS. Use the right tool for the right task.
You can use properties like `display: none` to remove element from the layout.

2022-04-07 12:42 UTC, RemcoSimonides commented on libs/movie/src/lib/movie/components/header/header.component.scss
> +          height: 400px;
The layout changes from row to column. I'm not able to make these functions work with that structure change.
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/27687382/162200554-e8870394-469a-4561-a2ae-88cf1c508918.png">

<img width="341" alt="image" src="https://user-images.githubusercontent.com/27687382/162200685-3e4a2b2e-29f3-42b4-aaf2-16377b11a5d3.png">

2022-04-07 13:01 UTC, GrandSchtroumpf commented on libs/movie/src/lib/movie/components/promotional-links/promotional-links.component.html
> +  <ng-container *ngIf="xs$ | async; else gtxs">
Either separate component or using `display: none` as I mention earlier

2022-04-08 10:05 UTC, GrandSchtroumpf approved these changes

2022-04-08 10:47 UTC, merged