UI for mobile - first step
blockframes/blockframes pull request #8207
Opened 2022-04-07 12:54 UTC by Poppe-A

#6860

2022-04-08 07:28 UTC, RemcoSimonides requested changes

2022-04-08 07:28 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/home/home.component.scss
> +}
This seems overly complex to me btw for only wrapping the buttons to the next line.
Currently on desktop it's using flexbox and on mobile you overwrite it to be a grid? It's probably possible to only use one of them

2022-04-08 07:28 UTC, RemcoSimonides commented on apps/festival/festival/src/app/marketplace/marketplace.component.html
> +      <a fxHide.lt-sm mat-button class="link-to-app" color="primary" [href]="applicationUrl.catalog" target="_blank">
`fxHide.xs`

2022-04-08 07:28 UTC, RemcoSimonides commented on libs/movie/src/lib/movie/marketplace/shell/shell.component.scss
> +}
Same in this file. On desktop you're using grid and on mobile, you use flexbox. It should be possible to achieve what you want with only one of them.

I assume you're changing this comment:
- [x] Can't put the video in fullscreen ? --> Make it bigger on mobile and include option to see it in fullscreen
![File (1)](https://user-images.githubusercontent.com/85220905/131829910-29b39106-684d-4023-842c-a2338c5accec.jpg)

It's not very specific so you have a lot of freedom on how to solve this issue. Btw, I don't see any changes regarding "Can't put the video in fullscreen?"

2022-04-08 07:28 UTC, RemcoSimonides commented on libs/movie/src/lib/movie/marketplace/shell/shell.component.scss
> +@include layout-bp(lt-sm) {
`xs`

2022-04-08 07:28 UTC, RemcoSimonides commented on libs/ui/src/lib/confirm/confirm.component.scss
> +@include layout-bp(lt-sm) {
`xs`

2022-04-08 07:28 UTC, RemcoSimonides commented on libs/ui/src/lib/list/page/list-page.component.ts
> +import { BreakpointsService } from '@blockframes/utils/breakpoint/breakpoints.service';
Move 👇  into `// blockframes` section of imports

2022-04-08 07:28 UTC, RemcoSimonides commented on styles/components/mat-dialog.scss
> +  }
Did you try to solve this one with `clamp` too? Seems to be a good application for it.

2022-04-08 08:59 UTC, Poppe-A commented on styles/components/mat-dialog.scss
> +  }
It's finally not useful, since default padding is already 24px.
But we have to check every modal because we sometime add padding on the sections inside

2022-04-08 11:19 UTC, RemcoSimonides commented on styles/components/mat-dialog.scss
> +  }
Did you do it or create an issue for it?

2022-04-08 12:16 UTC, Poppe-A commented on libs/movie/src/lib/movie/marketplace/shell/shell.component.scss
> +}
![fullscreen](https://user-images.githubusercontent.com/35397614/162433772-53e93dd8-2165-432a-88b3-e072ed4515d3.png)
I can have it fullscreen, and I tried with landscape orientation, it's fine

2022-04-11 06:56 UTC, RemcoSimonides approved these changes

2022-04-11 06:56 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/home/home.component.html
> +      <div fxLayoutAlign.xs="column" fxLayoutGap="24px">
`fxLayoutAlign.xs="column"` isn't correct and can be removed

2022-04-11 06:56 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/home/home.component.scss
>    }
This is putting the space-between h1 and the buttons. As you do it with flexbox now, you can remove this.

2022-04-11 06:56 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/home/home.component.scss
> +    }
You can remove this too if you do what I said above ☝️

2022-04-11 06:56 UTC, RemcoSimonides commented on libs/ui/src/lib/list/page/list-page.component.ts
> +    private breakpointsService: BreakpointsService) { }
put `) { }` on new line

2022-04-11 06:56 UTC, RemcoSimonides commented on styles/components/mat-dialog.scss
> +@import "~@angular/flex-layout/mq";
Did this import fix something? Otherwise remove it

2022-04-11 08:27 UTC, merged