updated terms and conditions and privacy policy
blockframes/blockframes pull request #8235
Opened 2022-04-12 14:10 UTC by yspringfield

Fixed:  #7969

2022-04-12 14:16 UTC, RemcoSimonides commented on libs/user/src/lib/auth/components/privacy-policy/privacy-policy.component.html
> +      <mat-card-content>
Use `class="surface"` instead of `mat-card`

2022-04-12 14:16 UTC, RemcoSimonides commented on libs/user/src/lib/auth/components/privacy-policy/privacy-policy.component.html
> +<ng-container>
Remove

2022-04-13 07:46 UTC, RemcoSimonides commented on libs/user/src/lib/auth/components/terms-conditions/terms-conditions.component.html
> +              <a href="www.archipelmarket.com">www.archipelmarket.com</a>
I don't see why you'd make it static instead of using the appUrl
Please change it back

2022-04-13 07:46 UTC, RemcoSimonides commented on libs/user/src/lib/auth/components/terms-conditions/terms-conditions.component.html
>              </ul>
Items in an `<ul>` should already have a prefix icon... No need to add. Otherwise change the icon if it's not the good one

2022-04-13 09:13 UTC, RemcoSimonides approved these changes

2022-04-13 09:13 UTC, RemcoSimonides commented on libs/user/src/lib/auth/components/privacy-policy/privacy-policy.component.html
> +<section fxLayout="row" fxLayoutAlign="center">
I don't think this should be row as everything is aligned in column style

2022-04-13 09:13 UTC, RemcoSimonides commented on libs/user/src/lib/auth/components/privacy-policy/privacy-policy.component.scss
> +
The table is indeed horrible on mobile, but so is all the other text. Could you perhaps do an attempt to fix the text for mobile?

2022-04-13 09:38 UTC, RemcoSimonides commented
I just switched back to develop and it looks a lot better there on small screen so I'm afraid you broke something. There is also padding around
<img width="633" alt="image" src="https://user-images.githubusercontent.com/27687382/163147500-3f7978da-5413-4bc9-a97c-b229f481eb12.png">

2022-04-13 09:39 UTC, RemcoSimonides requested changes
.

2022-04-14 07:01 UTC, yspringfield commented on libs/user/src/lib/auth/components/privacy-policy/privacy-policy.component.html
> +<section fxLayout="row" fxLayoutAlign="center">
It's row. To keep it's child `.surface` horizontally centered.

2022-04-14 08:12 UTC, RemcoSimonides approved these changes

2022-04-14 08:12 UTC, RemcoSimonides commented on libs/user/src/lib/auth/components/privacy-policy/privacy-policy.component.scss
> +}
Why not directly target the `table` element? Does it not work like that?

Anyway, remove one of the underscores if you need this wrapper. `table_wrapper` instead of `table__wrapper`

2022-04-14 09:10 UTC, merged