Display currency symbol / format price number
blockframes/blockframes pull request #8269
Opened 2022-04-20 13:22 UTC by Poppe-A

#7624

2022-04-20 13:58 UTC, RemcoSimonides requested changes

2022-04-20 13:58 UTC, RemcoSimonides commented on libs/utils/src/lib/emails/utils.ts
> +  const currencyKey = Object.keys(movieCurrencies).find(key => movieCurrencies[key] === bucket.currency);
Use `getKeyIfExists` instead

2022-04-20 13:58 UTC, RemcoSimonides commented on apps/backend-functions/src/templates/mail.ts
> +  const currency = staticModel['movieCurrenciesSymbols'][negotiation.currency];
```suggestion
  const currency = staticModel.movieCurrenciesSymbols[negotiation.currency];
```

2022-04-20 13:58 UTC, RemcoSimonides commented on apps/backend-functions/src/templates/mail.ts
> +  const currency = staticModel['movieCurrenciesSymbols'][negotiation.currency];
```suggestion
  const currency = staticModel.movieCurrenciesSymbols[negotiation.currency];
```

2022-04-20 13:58 UTC, RemcoSimonides commented on libs/utils/src/lib/emails/utils.ts
> +  }
missing `;`

2022-04-20 13:58 UTC, RemcoSimonides commented on libs/model/src/lib/static/static-model.ts
> +} as const
missing `;`

2022-04-20 13:58 UTC, RemcoSimonides commented on libs/model/src/lib/contract.ts
> +  const updatedContract = {...contract} as any;
This kinda ruins every type safety there is I think
Instead create an interface which combines Contract, Terms and the extra price field.

2022-04-20 13:58 UTC, RemcoSimonides commented on libs/utils/src/lib/emails/utils.ts
> +  const currencyKey = Object.keys(movieCurrencies).find(key => movieCurrencies[key] === bucket.currency);
What was the reason the bucket.currency contains the value instead of the key? That's something that should be fixed too since it's incorrect now and will cause unexpected bugs in the future

2022-04-20 14:04 UTC, Poppe-A commented on libs/utils/src/lib/emails/utils.ts
> +  const currencyKey = Object.keys(movieCurrencies).find(key => movieCurrencies[key] === bucket.currency);
Not a bug. Here we get the bucket from a notification. But when creating a notification, we "override" the currency value (offer.ts l.27)

2022-04-21 08:32 UTC, RemcoSimonides commented on apps/backend-functions/src/templates/mail.ts
> +    negotiation: {...negotiation, currency},
This data object should reflect the `EmailTemplateRequest` in `libs/utils/src/lib/emails/utils.ts`. I don't see a negotiation property in there. Also, type safety seems to be gone here but you're magically changing a value from USD to $ which again might cause unexpected behaviour later. Better would be to have a `MailNegotation` type too, just like all the other types

2022-04-21 08:32 UTC, RemcoSimonides commented on apps/backend-functions/src/templates/mail.ts
> +    negotiation: {...negotiation, currency},
Also add spacing `{ ...negotiation, currency }`

2022-04-21 08:32 UTC, RemcoSimonides commented on apps/backend-functions/src/templates/mail.ts
> +  const data = { org, bucket: { ...mailBucket }, user: toUser, baseUrl: appUrl.content, date };
`{ ...mailBucket }` === `mailBucket`

2022-04-21 08:32 UTC, RemcoSimonides commented on apps/backend-functions/src/templates/mail.ts
> +    bucket: { ...mailBucket },
`{ ...mailBucket }` === `mailBucket`

2022-04-21 08:32 UTC, RemcoSimonides commented on libs/model/src/lib/contract.ts
> +  const formattedPrice = formatter.format(contract.price);
Rename to `price`

2022-04-21 08:32 UTC, RemcoSimonides commented on libs/model/src/lib/contract.ts
> +    price: formattedPrice,
After rename you can do just `price` instead

2022-04-21 08:32 UTC, RemcoSimonides commented on libs/model/src/lib/contract.ts
> +export type EmailContract = ReturnType<typeof createMailContract>;
Change the name back

2022-04-21 08:32 UTC, RemcoSimonides commented on libs/utils/src/lib/emails/utils.ts
> +// }
Remove
Please don't forget to check your changes before asking me to check your PR.

2022-04-21 08:32 UTC, RemcoSimonides commented on libs/utils/src/lib/emails/utils.ts
> +  const contracts = bucket.contracts.map(contract => createMailContract(contract));
✔️

2022-04-21 09:25 UTC, RemcoSimonides approved these changes

2022-04-21 09:25 UTC, RemcoSimonides commented on libs/model/src/lib/static/static-model.ts
> +} as const;
Let's also add the symbols for the other currencies available in `movieCurrencies`.

2022-04-21 10:15 UTC, merged