Buyers insights map
blockframes/blockframes pull request #8458
Opened 2022-05-12 13:56 UTC by yspringfield

Fixed: #7843

2022-05-12 13:57 UTC, yspringfield commented
<img width="1438" alt="Bildschirmfoto 2022-05-12 um 2 57 33 PM" src="https://user-images.githubusercontent.com/22674720/168092277-e43ad8ef-783b-4eb7-bafd-313f1a15cbda.png">

2022-05-12 13:58 UTC, yspringfield commented
We're targeting fix-for-release-4-2 only for reviewing sake. Once fix-for-release-4-2 is merged into develop, we'll change the target branch to develop.

2022-05-13 07:37 UTC, RemcoSimonides requested changes

2022-05-13 07:37 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/home/home.component.scss
> +  flex: 1 1 350px;
I don't know what this `350px` is doing, but there should probably be a way to do it without

2022-05-13 07:37 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/home/home.component.scss
> +}
There is really little space between the text and the lines in your legend

<img width="387" alt="image" src="https://user-images.githubusercontent.com/27687382/168230626-6968a0c3-a625-43c4-b374-cfd6ead2f640.png">

👇 UI Design
<img width="154" alt="image" src="https://user-images.githubusercontent.com/27687382/168230750-93c16f26-0a48-4a1f-9557-59e835b60914.png">

UI Design doesn't have bold numbers and the header should be `h5` instead of `h4` according to design

Try to use mat-divider instead of `li { border-bottom: ... }` maybe that will give you some extra space already

2022-05-13 07:37 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/home/home.component.scss
> +  flex: 0 0 270px;
Should be fixed height either

2022-05-13 07:37 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/home/home.component.ts
> +  activeCountries$ = this.titleAnalytics$.pipe(
You don't need all the changes in this file if you use the `analytics-map` component

what you need for the map
```
  buyersPerTerritory$ = this.titleAnalytics$.pipe(
    filter(analytics => analytics.length > 0),
    map(analytics => {
      // get 1 analytic per buyer
    }),
    map(analytics => counter(analytics, 'org.addresses.main.country', 'territories')),
  )
```

titleAnalytics$ already has the org of each title

2022-05-13 11:35 UTC, yspringfield commented on apps/festival/festival/src/app/dashboard/home/home.component.scss
> +}
<img width="367" alt="Bildschirmfoto 2022-05-13 um 12 34 36 PM" src="https://user-images.githubusercontent.com/22674720/168275077-3c20ef9e-1c73-4e00-b472-578a3153c8d5.png">
The figma design does.

2022-05-16 08:14 UTC, RemcoSimonides requested changes

2022-05-16 08:14 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/home/home.component.ts
> +function getTerritoryAndCount({ orgs, analytics }: TerritoryAndCountOption): AnalyticData[] {
Use `counter` function instead

2022-05-16 08:14 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/home/home.component.ts
> +    map(getTerritoryAndCount),
```suggestion
    map(analytics => counter(analytics, 'org.addresses.main.country', 'territories')),
```

2022-05-16 08:14 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/home/home.component.ts
> +    map(stats => stats.sort(({ count: countA }, { count: countB }) => countA - countB))
You're making it more complicated than need be
```suggestion
    map(stats => stats.sort((a, b) => a.count - b.count))
```

2022-05-16 08:14 UTC, RemcoSimonides commented on libs/analytics/src/lib/components/map/map.component.html
> +<header *ngIf="!noHeader">
Either move the header outside of this component or do it like the other analytics components
```
<header>
  <ng-content></ng-content>
</header>
```
And then just put nothing in this header. At least then it works the same as all other other components

2022-05-16 08:14 UTC, RemcoSimonides commented on libs/analytics/src/lib/components/map/map.component.ts
> +  @Input() topCountriesTemplate: TemplateRef<HTMLElement>;
This is not how we pass templates into a component. Use @ContentChild for this.

2022-05-16 11:33 UTC, closed without merging