Analytics last screening
blockframes/blockframes pull request #8526
Opened 2022-05-25 09:51 UTC by yspringfield

Fixed: #7840

2022-05-25 12:32 UTC, RemcoSimonides requested changes

2022-05-25 12:32 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/home/home.component.html
> +            </bf-table>
Missing watch time column

2022-05-25 12:32 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/home/home.component.ts
> +    );
Why can't it be just
```
return this.invitationService.allInvitations$.pipe(
  joinWith({
    event: invitation => this.eventService.queryDocs<Screening>(invitation.eventId),
    org: invitation => {
      // 👇 function from libs/invitation/src/lib/pipes/guest.pipe.ts
      const orgId = getGuest(invitation);
      return this.orgService.valueChanges(orgId);
    }
  }, { shouldAwait: true })
);
```

2022-05-25 12:32 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/home/home.component.ts
> +    }));
add Watch time

2022-05-27 09:19 UTC, yspringfield commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts
> +    };
no, don't think I understand but the fields are empty as a result of two things.
1. The permission denied error I was having and is now resolved.
2. The user is an external user to the platform.

2022-05-27 09:24 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts
> +    };
What does it mean "an external user to the platform"? All our users are logged in, some of them just might not have an orgId associated with them

2022-05-30 07:53 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html
> +    <a ongoing-event-button href="/c/o/dashboard/event/{{events[0].id}}/statistics">Ongoing
Use `routerLink` instead of `href`

2022-05-30 07:53 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html
> +  <span>"O" meaning the user left the screening right away.</span>
Should be a `<p>`

2022-05-30 07:53 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html
> +
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/27687382/170939087-d00e2328-e48d-466c-ae73-c6a247c8b0ef.png">
Too much space

2022-05-30 07:53 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html
> +    </ng-template>
There is never no user. It's either `invitation.fromUser` or `invitation.toUser`. Use the getGuest pipe again

2022-05-30 07:53 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html
> +    </ng-template>
Same as above

2022-05-30 07:53 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html
> +      <span>{{ country ?? '--' }}</span>
Give it a `| toLabel:'territories` and add filter for static model values

2022-05-30 07:53 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html
> +      <span>{{ activity ?? '--' }}</span>
Is activity also part of the static model? Then do the same as comment below

2022-05-30 07:53 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.scss
> +}
Still think these classes can be combined without affecting the UI since both headings have a title and a button on the other side
```
.heading {
  display flex:
  align-items: center;
  justify-content: space-between;
  
  h3 {
    display: flex;
    align-items: center;
  }
}
```

Shouldn't need `margin-bottom: 16px;` as <h12345> tags already have margin themselves

2022-05-30 07:53 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.scss
> +}
You should move all your html code inside the other section on the page. Then you don't need this and more.

2022-05-30 07:53 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.scss
> +}
Is this for the `ongoing-event-button`? I don't see a mat-stroked-button in your html otherwise

2022-05-30 07:53 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts
> +    if (!invitation.eventId) return EMPTY as Observable<Event<Screening>>;
If an invitation doesn't have an `eventId`, then you already know it's not an invitation for a Screening (or any other event actually). So invitations without eventId should be filtered out before already.

2022-05-30 07:53 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts
> +    return this.eventService.queryDocs<Screening>(invitation.eventId)
You're not querying only screening invitations. You're querying all events. So you can't give it a type yet

2022-05-30 07:53 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts
> +    return of({} as Organization);
`{}` is not of type Organization.
Do you even need to return an empty object? Can't it just be undefined?

2022-05-30 07:53 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts
> +    const titleAnalytics = await firstValueFrom(this.titleAnalytics$);
`firstValueFrom()` shouldn't be needed. This causes the table not to update in realtime when new data arrives. All other graphs/tables we created do update when new analytics data comes in so this table should too

2022-05-30 07:53 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts
> +          const eventIsOfTitle = event.meta.titleId === titleId;
```suggestion
          const eventIsOfTitle = event.meta?.titleId === titleId;
```

2022-05-30 11:30 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html
> +        <b *ngIf="invitation| guest:'user' as user">{{ user.firstName }} {{ user.lastName }}</b>
Use `displayName` instead

2022-05-30 11:30 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html
> +      </ng-template>
Same issue applies here as it did to territories. The default filter on the bf-table won't work now for these columns. You'll have to create a custom one.

2022-05-30 11:30 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html
> +        <span>{{ name ?? '--' }}</span>
```suggestion
        <span>{{ name ?? '-' }}</span>
```

2022-05-30 11:30 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html
> +        <ng-template #noActivity>--</ng-template>
```suggestion
        <ng-template #noActivity>-</ng-template>
```

2022-05-30 11:30 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts
> +}
Use `isScreening` from `libs/model/src/lib/event.ts` instead

2022-05-30 11:30 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts
> +    filter(events => !!events.length),
```suggestion
    map(invitations => invitations.filter(({ event }) => eventTime(event) === 'onTime')),
    filter(invitations => !!invitations.length),
```

2022-05-30 11:30 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts
> +    })
```suggestion
    map(([requests, invitations]) => toScreenerCards(requests, invitations))
```

2022-05-30 11:30 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts
> +  aggregatedScreeningCards$: Observable<MetricCard[]> = combineLatest([
```suggestion
  aggregatedScreeningCards$ = combineLatest([
```
It knows because `toScreenerCards` return value is typed

2022-05-30 11:30 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts
> +    return of(undefined);
```suggestion
  return orgId ? this.orgService.valueChanges(orgId) : of(undefined);
```

2022-05-30 11:30 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts
> +  }
No need to have this as a separate function anymore

2022-05-31 05:28 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts
> +  const averageWatchTime = sum(attendees, inv => inv.watchTime) / invitations.length || 0
<img width="283" alt="image" src="https://user-images.githubusercontent.com/27687382/171096212-4901bb81-b03f-4966-adfc-d95dd4846a85.png">
Round number to 0 decimals

2022-05-31 05:28 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts
> +        'Email': invitation.toUser.email,
Again: invitation can have either `toUser` and `fromUser`. Use getGuest()

2022-05-31 05:28 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts
> +  const caseInsensitive = new RegExp(input, 'i');
Avoid using RegExp as it's usually hard to read/understand what it does exactly. Use `toLowerCase()` and `includes()` instead

2022-05-31 05:28 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts
> +  return names.some(name => name.match(caseInsensitive)?.length);
Same as above

2022-05-31 05:28 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts
> +    return orgId ? from(this.orgService.getValue(orgId)) : of(undefined);
Why do you use `from(this.orgService.getValue(orgId))` instead of `this.orgService.valueChanges(orgId)`?

2022-05-31 05:28 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.ts
> +      icon: 'hand'
Most but not all icons come from https://fonts.google.com/icons
We try to keep the names the same if the icon does come from there. This hand for example, should be called `front_hand` instead for example.

2022-05-31 07:34 UTC, RemcoSimonides approved these changes

2022-05-31 07:34 UTC, RemcoSimonides commented on libs/ui/src/lib/icon.service.ts
> +  { name: 'stop_watch', url: 'assets/icons/stop_watch.svg' },
https://fonts.google.com/icons?icon.query=timer
Should be "timer"

2022-05-31 07:34 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html
> +    <h3 class="last_screenings">
Why did you add a class instead of using `h3` like you did before last commit?

2022-05-31 07:34 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html
> +  <header class="heading">
You could now remove `heading` class and target `header` directly inside `section` in css
```
section {
  ...
  header {
    ...
  }
}
```

2022-05-31 07:34 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html
> +          <b *ngIf="invitation| guest:'user' as user">{{ user | displayName }}</b>
```suggestion
          <b>{{ invitation | guest:'user' | displayName }}</b>
```

2022-05-31 08:13 UTC, yspringfield commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html
> +    <h3 class="last_screenings">
felt like it'll be very all encompassing knowing that subsequent headers within the section risk having h3s too.

2022-05-31 08:45 UTC, RemcoSimonides approved these changes

2022-05-31 10:53 UTC, merged