#7555 Screening stat improvements
blockframes/blockframes pull request #8749
Opened 2022-07-04 14:46 UTC by phpgeekfr

2022-07-05 05:28 UTC, RemcoSimonides requested changes

2022-07-05 05:28 UTC, RemcoSimonides commented on libs/event/src/lib/pages/analytics/analytics.component.html
> +<ng-container *ngIf="isEventStarted(event$ | async) as event">
I think you should user the `eventTime` pipe instead
libs/event/src/lib/pipes/event-time.pipe.ts

2022-07-05 05:28 UTC, RemcoSimonides commented on libs/event/src/lib/pages/analytics/analytics.component.html
> +    <ng-container *ngIf="ongoingScreening(event)">
I think you should user the `eventTime` pipe instead
libs/event/src/lib/pipes/event-time.pipe.ts

2022-07-05 05:28 UTC, RemcoSimonides commented on libs/event/src/lib/pages/analytics/analytics.component.html
> +      <a ongoing-event-button routerLink="/event/{{event.id}}/r/i">
I think you should use the `eventLink` pipe instead
libs/event/src/lib/pipes/event-link.pipe.ts

2022-07-05 05:28 UTC, RemcoSimonides commented on libs/event/src/lib/pages/analytics/analytics.component.html
> +        <article fxLayout="row" fxLayoutAlign="space-between start" flex>
Use css instead of fxLayout
Also, the `flex` directive doesn't exist anymore so it's probably not doing anything here

2022-07-05 05:28 UTC, RemcoSimonides commented on libs/event/src/lib/pages/analytics/analytics.component.html
> +          <ng-template colRef="orgActivity" label="Company Activity" let-orgActivity>{{ orgActivity ? (orgActivity | toLabel: 'orgActivity') : dataMissing }}</ng-template>
```suggestion
          <ng-template colRef="orgActivity" label="Company Activity" let-orgActivity [filter]="filters.orgActivity">{{ orgActivity ? (orgActivity | toLabel: 'orgActivity') : dataMissing }}</ng-template>
```
If the displayed values are different than the one in the source data, then sometimes the filters and sorting doesn't working as expected. So we have to add a special filter function for this

You can check for example in this bf-table how it's implemented apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html

2022-07-05 05:28 UTC, RemcoSimonides commented on libs/event/src/lib/pages/analytics/analytics.component.html
> +          <ng-template colRef="orgCountry" label="Country" let-orgCountry>{{ orgCountry ? (orgCountry | toLabel: 'territories') : dataMissing }}</ng-template>
```suggestion
          <ng-template colRef="orgCountry" label="Country" let-orgCountry [filter]="filters.territories">{{ orgCountry ? (orgCountry | toLabel: 'territories') : dataMissing }}</ng-template>
```

2022-07-05 05:28 UTC, RemcoSimonides commented on libs/event/src/lib/pages/analytics/analytics.component.html
> +          <ng-template colRef="watchInfos.date" label="Watching Status" let-date sort>
Does the sorting work ass expected on this column?

2022-07-05 05:28 UTC, RemcoSimonides commented on libs/analytics/src/lib/utils.ts
> +export function toScreenerCards(screeningRequests: Invitation[] | Analytics<'title'>[], invitations: Invitation[] | InvitationWithAnalytics[]): MetricCard[] {
`Invitation[]` and `Analytics<'title'>[]` are totally different from each other.
Screening Requests is an analytics event triggered when a user is really requesting a screening - like a request to the seller to create an event and invite them. It's not a user asking for access to participate in one.

2022-07-05 05:28 UTC, RemcoSimonides commented on libs/event/src/lib/pages/analytics/analytics.component.ts
> +        this.aggregatedScreeningCards = toScreenerCards(this.eventInvitations.filter(i => i.mode === 'request'), this.eventInvitations);
See comment at `toScreenerCards` function

2022-07-05 08:43 UTC, phpgeekfr commented on libs/event/src/lib/pages/analytics/analytics.component.html
> +    <ng-container *ngIf="ongoingScreening(event)">
This pipe is not really good to use here because I want the link to redirect to `event/eventId` but if I use this pipe, it will redirect on `c/o/dashboard/eventId` and I'm already on that page.

2022-07-05 08:43 UTC, phpgeekfr commented on libs/event/src/lib/pages/analytics/analytics.component.html
> +      <a ongoing-event-button routerLink="/event/{{event.id}}/r/i">
This pipe is not really good to use here because I want the link to redirect to `event/eventId` but if I use this pipe, it will redirect on `c/o/dashboard/eventId` and I'm already on that page.

2022-07-05 11:24 UTC, phpgeekfr commented on libs/event/src/lib/pages/analytics/analytics.component.html
> +          <ng-template colRef="watchInfos.date" label="Watching Status" let-date sort>
yest

2022-07-05 14:48 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.html
> +        <div>
Let's use article instead of `div`. Francois like to avoid div as much as possible

2022-07-05 14:48 UTC, RemcoSimonides commented on apps/festival/festival/src/app/dashboard/analytics/title/title-analytics.component.html
> +        <ng-template colRef="status" label="Invitation" let-status sort defaultSort >
Each bf-table should have max 1 column with `defaultSort`. I see all the other columns also have it so please only add it to the one which needs to be sorted by default

2022-07-05 14:48 UTC, RemcoSimonides commented on apps/festival/festival/src/app/event/session/session.component.ts
> +            }
What if I play and pause? Then the timer is reset to 0? It should only be set to 0 when watchInfos is empty

2022-07-05 14:48 UTC, RemcoSimonides commented on libs/event/src/lib/pages/analytics/analytics.component.ts
> +        const titleIds = event.type === 'screening' ? [(this.event.meta as Screening).titleId] : (this.event.meta as Slate).titleIds;
```suggestion
        const titleIds = isScreening(event) 
          ? [event.meta.titleId]
          : isSlate(event)
            ? event.meta.titleIds
            : [];
```

2022-07-05 14:48 UTC, RemcoSimonides commented on libs/event/src/lib/pages/analytics/analytics.component.ts
> +          .filter(analytic => analytic.name === 'screeningRequested');
`getTitleAnalytics` function doesn't support this yet, but maybe we can pass the name 'screeningRequested' to this function and add this parameter to the query. Probably saves quite some doc reads

2022-07-05 14:48 UTC, RemcoSimonides commented on libs/event/src/lib/pages/analytics/analytics.component.ts
> +          .filter(({ org }) => !org.appAccess.festival.dashboard)
During my holidays, Springfield chose to query only buyers analytics data differently than I would have done it. I would have liked to see it done already by the getTitleAnalytics() function. This would have saved you to join org on this page, and this filter here... Also it would have been cleaner everywhere else getTitleAnalytics is used. But maybe I'll do that later this month if there is time left.

2022-07-05 15:07 UTC, phpgeekfr commented on apps/festival/festival/src/app/dashboard/analytics/buyer/buyer-analytics.component.html
> +        <div>
yes but it also want section and articles to have a heading ;) https://www.notion.so/cascade8/Code-conventions-0dc3a5db4f1045f68f1587f9a88bcce2

but ok lets go with `article`

2022-07-05 15:26 UTC, phpgeekfr commented on apps/festival/festival/src/app/event/session/session.component.ts
> +            }
This is only triggered when hitting the main button : 
![image](https://user-images.githubusercontent.com/1194344/177363093-3e373e60-2533-46f2-ba2f-23ed120bac16.png)

So to see it again, user will have to refresh page and if he already have some `watchInfos.duration` we will continue to increment time from this value

2022-07-05 15:36 UTC, phpgeekfr commented on libs/event/src/lib/pages/analytics/analytics.component.ts
> +          .filter(({ org }) => !org.appAccess.festival.dashboard)
> But maybe I'll do that later this month if there is time left.

Like this because I don't know all possible edge cases

2022-07-06 05:16 UTC, RemcoSimonides approved these changes

2022-07-06 07:42 UTC, merged