accept TC to access events
blockframes/blockframes pull request #8756
Opened 2022-07-06 08:23 UTC by Poppe-A

#8743

2022-07-06 10:19 UTC, RemcoSimonides requested changes
It's not working very well yet.

Elements are overlapping, there is too much space between the fields, no space between the buttons, a horizontal scroll on mobile screen size.
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/27687382/177528450-16504292-3c2f-4f33-8267-edd058b35f67.png">

I wonder why the code or functionality is not the same as on the sign up page. Is it really needed that the surface disappears on small screen and such?

2022-07-06 12:26 UTC, Poppe-A commented on apps/festival/festival/src/app/event/email/email.component.html
> +          <span class="mat-caption">I hereby accept Archipel Market&nbsp;
Why ? Here we are working with event so it will be 'Archipel Market' every time. I think it's way less optimized to use the app injection and a pipe if we don't really need it

2022-07-07 05:32 UTC, RemcoSimonides commented on apps/festival/festival/src/app/event/email/email.component.html
> +          <span class="mat-caption">I hereby accept Archipel Market&nbsp;
Sorry, I meant using the static model. But never mind about that, searching the code; "Archipel Market" just written like that has been used many times so its ok.

2022-07-07 06:04 UTC, RemcoSimonides commented on apps/festival/festival/src/app/event/email/email.component.html
> +      <div>
I don't think these checkboxes need to be inside a `footer` and inside a `div`. Can you move them outside of the footer?

2022-07-07 08:48 UTC, merged